/-
Copyright (c) 2026 Brian Nugent. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Brian Nugent

The empty-relations presentation is adapted from current Mathlib
Algebra/Category/ModuleCat/Sheaf/LocallyFree.lean at commit
633b366493a76df88a2bff099ed0cbf711a59ec9, lines 117-137.
The finite-presentation consequence uses the project's actual rank-one bases.
-/
import KltDP.Compatibility.InvertibleModuleSheaf
import Mathlib.Algebra.Category.ModuleCat.Sheaf.Quasicoherent
import Mathlib.Algebra.Category.ModuleCat.Sheaf.Limits

/-!
# Quasi-coherent and finite presentations from actual local bases

On each original trivializing chart, the local free presentation map is
an isomorphism. Its actual categorical kernel is therefore zero and is
generated by the empty family. Keeping the original cover and generators
gives a quasi-coherent presentation. For an invertible sheaf the singleton
basis and empty relations are finite, giving finite presentation as well.

These are properties of the original sheaf of modules over its original
ring sheaf. No replacement by a module of global sections is made.
-/

noncomputable section

open CategoryTheory CategoryTheory.Limits

universe u v u₁

namespace KltDP.SheafOfModules

variable {C : Type u₁} [Category.{v} C] {J : GrothendieckTopology C}
    {R : Sheaf J RingCat.{u}}
    [∀ U : C, HasWeakSheafify (J.over U) AddCommGrp.{u}]
    [∀ U : C, (J.over U).WEqualsLocallyBijective AddCommGrp.{u}]
    [∀ U : C, (J.over U).HasSheafCompose (forget₂ RingCat.{u} AddCommGrp.{u})]
    {M : _root_.SheafOfModules.{u} R}

-- The pinned limit construction supplies terminal objects; the existing
-- zero morphisms make those terminal objects actual zero objects.
local instance overHasZeroObject (U : C) :
    HasZeroObject (_root_.SheafOfModules.{u} (R.over U)) :=
  hasZeroObject_of_hasTerminal_object

/-- The original local basis gives a presentation with its actual zero kernel
generated by the empty family. -/
def localBasisQuasicoherentData (q : M.LocalGeneratorsData)
    (hq : q.IsLocallyFreeData) : M.QuasicoherentData where
  I := q.I
  X := q.X
  coversTop := q.coversTop
  presentation i := by
    letI := hq.isIso i
    exact {
      generators := q.generators i
      relations := {
        I := ULift.{u} Empty
        s j := Empty.elim j.down
        epi := IsZero.epi
          (IsZero.of_iso (isZero_zero _) (kernel.ofMono (q.generators i).π)) _ } }

/-- The local generator data are retained literally. -/
@[simp]
theorem localBasisQuasicoherentData_localGeneratorsData (q : M.LocalGeneratorsData)
    (hq : q.IsLocallyFreeData) :
    (localBasisQuasicoherentData q hq).localGeneratorsData = q := rfl

/-- Every actual locally free sheaf is quasi-coherent. -/
instance (priority := 100) locallyFree_isQuasicoherent
    (M : _root_.SheafOfModules.{u} R) [h : M.IsLocallyFree] : M.IsQuasicoherent := by
  obtain ⟨q, hq⟩ := h.exists_isLocallyFreeData
  exact ⟨⟨localBasisQuasicoherentData q hq⟩⟩

/-- Rank-one local bases give finite presentations of the original invertible sheaf. -/
instance invertible_isFinitePresentation
    (M : _root_.SheafOfModules.{u} R) [h : IsInvertible M] : M.IsFinitePresentation := by
  obtain ⟨q, hq⟩ := h.exists_isInvertible
  refine ⟨localBasisQuasicoherentData q hq.isLocallyFreeData, fun i => ⟨?_, ?_⟩⟩
  · change Finite (q.generators i).I
    letI := hq.basisSubsingleton i
    infer_instance
  · change Finite (ULift.{u} Empty)
    infer_instance

end KltDP.SheafOfModules
