/-
Copyright (c) 2025 Andrew Yang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Andrew Yang
-/
import KltDP.Compatibility.MinpolyScalar
import KltDP.Compatibility.IntegralIdealPolynomial
import Mathlib.RingTheory.Ideal.GoingDown

/-!
# Going down over an actual integrally closed domain

Bounded port of official Mathlib
`RingTheory/IntegralClosure/GoingDown.lean` at
`5aedf732b6987e8c26ab3c9ebc855314f82b045f`, whole-file SHA-256
`906958977dfd39a61416945f59bc18cd817252640e691aaed27b3cf09cd84999`.

The proof constructs actual primes lying over smaller primes. It reuses
integrality over the actual extended ideal and the root-scaling formula
for minimal polynomials. The localization membership step is written
against the exact pinned fraction presentation. Domain hypotheses and
the injectivity of the original algebra map are explicit; no going-down
or chain-lifting conclusion is assumed.
-/

noncomputable section

namespace KltDP.Compatibility

open Polynomial

variable {R S : Type*} [CommRing R] [CommRing S] [Algebra R S]

/-- Divisibility of monic polynomials forces the nonleading coefficients
of the divisor into the radical generated by those of the dividend. -/
theorem coeff_mem_radical_span_coeff_of_dvd
    (p : R[X]) (q : R[X]) (hp : p.Monic) (hq : q.Monic)
    (H : q ∣ p) (i : ℕ) (hi : i ≠ q.natDegree) :
    q.coeff i ∈ (Ideal.span { p.coeff j | j < p.natDegree }).radical := by
  rw [Ideal.radical_eq_sInf, Ideal.mem_sInf]
  rintro P ⟨hPJ, hP⟩
  letI : P.IsPrime := hP
  have heval : p.map (Ideal.Quotient.mk P) = X ^ p.natDegree := by
    ext j
    obtain hj | rfl | hj := lt_trichotomy j p.natDegree
    · simpa [hj.ne, Ideal.Quotient.eq_zero_iff_mem] using
        hPJ (Ideal.subset_span ⟨_, hj, rfl⟩)
    · simp [hp]
    · simp [coeff_eq_zero_of_natDegree_lt hj, hj.ne']
  obtain ⟨j, hj, a, ha⟩ :=
    (dvd_prime_pow (prime_X (R := R ⧸ P)) _).mp
      (heval ▸ map_dvd (Ideal.Quotient.mk P) H)
  obtain ⟨r, hr, e⟩ := Polynomial.isUnit_iff.mp a⁻¹.isUnit
  rw [← Units.eq_mul_inv_iff_mul_eq, ← e] at ha
  obtain rfl : j = q.natDegree := by
    simpa [hq.natDegree_map, hr.ne_zero] using
      (congrArg Polynomial.natDegree ha).symm
  simpa [hi, Ideal.Quotient.eq_zero_iff_mem] using
    congrArg (fun f => f.coeff i) ha

/-- Integral extensions of domains over an integrally closed base satisfy
the actual pinned going-down property. -/
theorem normal_hasGoingDown [IsDomain R] [IsDomain S] [FaithfulSMul R S]
    [Algebra.IsIntegral R S] [IsIntegrallyClosed R] : Algebra.HasGoingDown R S := by
  letI : NoZeroSMulDivisors R S := NoZeroSMulDivisors.iff_faithfulSMul.mpr inferInstance
  constructor
  intro p _ Q _ hpQ
  let SQ := Localization.AtPrime Q
  suffices (p.map (algebraMap R SQ)).comap (algebraMap R SQ) ≤ p by
    obtain ⟨P, hP, e⟩ :=
      (Ideal.comap_map_eq_self_iff_of_isPrime p).mp
        (this.antisymm Ideal.le_comap_map)
    letI : P.IsPrime := hP
    refine ⟨P.under S, ?_, inferInstance, ⟨by rw [Ideal.under_under, ← e]⟩⟩
    exact (Ideal.comap_mono (IsLocalRing.le_maximalIdeal hP.ne_top)).trans_eq
      (IsLocalization.AtPrime.comap_maximalIdeal SQ Q)
  intro x hx
  obtain ⟨a, ha, haQ⟩ :
      ∃ a : S, x • a ∈ Ideal.map (algebraMap R S) p ∧ a ∉ Q := by
    have hx' : algebraMap S SQ (algebraMap R S x) ∈
        (p.map (algebraMap R S)).map (algebraMap S SQ) := by
      rw [Ideal.map_map, ← IsScalarTower.algebraMap_eq R S SQ]
      exact hx
    obtain ⟨⟨b, a⟩, hab⟩ := (IsLocalization.mem_map_algebraMap_iff Q.primeCompl SQ).mp hx'
    have heq : algebraMap R S x * (a : S) = (b : S) :=
      IsLocalization.injective SQ Q.primeCompl_le_nonZeroDivisors
        ((map_mul (algebraMap S SQ) _ _).trans hab)
    refine ⟨a, ?_, a.2⟩
    rw [Algebra.smul_def, heq]
    exact b.2
  obtain ⟨f, hfm, hfa, hf⟩ :=
    IntegralIdealPolynomial.exists_monic_aeval_eq_zero_forall_mem_of_mem_map ha
  obtain ⟨i, hi, hip⟩ :
      ∃ i ≠ (minpoly R a).natDegree, (minpoly R a).coeff i ∉ p := by
    set g := minpoly R a
    by_contra! H
    have heval : g.map (Ideal.Quotient.mk p) = X ^ g.natDegree := by
      ext i
      obtain hi | rfl | hi := lt_trichotomy i g.natDegree
      · simpa [hi.ne, Ideal.Quotient.eq_zero_iff_mem] using H _ hi.ne
      · simp [g, minpoly.monic (Algebra.IsIntegral.isIntegral _)]
      · simp [coeff_eq_zero_of_natDegree_lt hi, hi.ne']
    have hazero : Ideal.Quotient.mk (Ideal.map (algebraMap R S) p)
        (a ^ (minpoly R a).natDegree) = 0 := by
      simpa [← Ideal.Quotient.algebraMap_eq, aeval_algebraMap_apply, g] using
        (congrArg (aeval (Ideal.Quotient.mk (Ideal.map (algebraMap R S) p) a)) heval).symm
    exact haQ (‹Q.IsPrime›.mem_of_pow_mem _
      (Ideal.map_le_iff_le_comap.mpr hpQ.le (Ideal.Quotient.eq_zero_iff_mem.mp hazero)))
  by_cases hx0 : x = 0
  · simp [hx0]
  have hcoeff := coeff_mem_radical_span_coeff_of_dvd _ _ hfm
    (minpoly.monic (Algebra.IsIntegral.isIntegral _))
    (minpoly.isIntegrallyClosed_dvd (Algebra.IsIntegral.isIntegral _) hfa)
  simp only [minpoly_smul hx0 (Algebra.IsIntegral.isIntegral _),
    natDegree_scaleRoots, coeff_scaleRoots, Ideal.radical_eq_sInf, Submodule.mem_sInf,
    Set.mem_setOf_eq, and_imp] at hcoeff
  refine ‹p.IsPrime›.mem_of_pow_mem _ ((‹p.IsPrime›.mem_or_mem
    (hcoeff i hi p ?_ inferInstance)).resolve_left hip)
  simp +contextual [Ideal.span_le, Set.subset_def, LT.lt.ne, hf]

end KltDP.Compatibility
