import Mathlib.RingTheory.MvPolynomial.Homogeneous
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.RingTheory.Ideal.BigOperators
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Data.Finsupp.Order
import Mathlib.Data.Finsupp.Weight

/-!
# Powers of the variable ideal, and order of vanishing at the origin

BRIEF38 task 1, first half. For `MvPolynomial σ R` and the ideal `varIdeal` generated by **all** the
variables, this identifies the `n`-th power with the polynomials all of whose monomials have total
degree at least `n`:

  `varIdeal ^ n = degreeGE n`.

This is the statement that makes "order of vanishing at the origin" computable, and it is the input the
associated graded ring of the polynomial plane needs. It is stated for an arbitrary index type and an
arbitrary commutative ring, with no geometry and no Frobenius content.

## Why it is not in Mathlib

Checked at this pin. `MvPolynomial.mem_ideal_span_X_image` characterises membership in the ideal
generated by a *set* of variables — the `n = 1` case — and `mem_ideal_span_monomial_image` characterises
monomial ideals, but nothing characterises **powers** of the variable ideal, and there is no
order-of-vanishing notion for `MvPolynomial` at all.

## The two inclusions

* `varIdeal_pow_le_degreeGE`: degrees add, so a product of `n` elements of `varIdeal` has every monomial
  of degree at least `n`. Proved by induction through `degreeGE_mul`.
* `degreeGE_le_varIdeal_pow`: a monomial of degree at least `n + 1` has some exponent `dᵢ ≠ 0`, so it
  factors as `Xᵢ · (monomial of degree at least n)` via `monomial_single_add`. Induction on `n`, then
  expand an arbitrary polynomial as the finite sum of its monomials.

Both closure proofs go through the coefficient formula `coeff_mul` rather than `support_mul`, which
avoids pointwise `Finset` arithmetic entirely.

## Consequences used downstream

`homogeneousComponent_eq_zero_of_mem_pow` and `mem_pow_of_homogeneousComponent_eq_zero` restate the
equality in terms of homogeneous components: lying in `varIdeal ^ n` is exactly having no homogeneous
component below degree `n`. That is the form the initial-form map consumes.
-/

noncomputable section

open MvPolynomial

universe u v

namespace KltDP.RingTheory.MvPolynomialVarOrder

variable {σ : Type u} {R : Type v} [CommRing R]

/-! ## The two ideals -/

/-- The ideal generated by all the variables — the origin of affine space. -/
def varIdeal (σ : Type u) (R : Type v) [CommRing R] : Ideal (MvPolynomial σ R) :=
  Ideal.span (Set.range (X : σ → MvPolynomial σ R))

theorem X_mem_varIdeal (i : σ) : (X i : MvPolynomial σ R) ∈ varIdeal σ R :=
  Ideal.subset_span ⟨i, rfl⟩

/-- The polynomials every one of whose monomials has total degree at least `n`. -/
def degreeGE (σ : Type u) (R : Type v) [CommRing R] (n : ℕ) : Ideal (MvPolynomial σ R) where
  carrier := {f | ∀ d ∈ f.support, n ≤ d.degree}
  zero_mem' := by
    intro d hd
    simp only [MvPolynomial.support_zero, Finset.not_mem_empty] at hd
  add_mem' := by
    classical
    intro a b ha hb d hd
    rcases Finset.mem_union.mp (MvPolynomial.support_add hd) with h | h
    · exact ha d h
    · exact hb d h
  smul_mem' := by
    classical
    intro c f hf d hd
    rw [MvPolynomial.mem_support_iff, smul_eq_mul, coeff_mul] at hd
    obtain ⟨x, hx, hxne⟩ := Finset.exists_ne_zero_of_sum_ne_zero hd
    have hsum : x.1 + x.2 = d := Finset.mem_antidiagonal.mp hx
    have hx2 : x.2 ∈ f.support := MvPolynomial.mem_support_iff.mpr (right_ne_zero_of_mul hxne)
    have hge : n ≤ x.2.degree := hf x.2 hx2
    have hdeg : d.degree = x.1.degree + x.2.degree := by rw [← hsum, Finsupp.degree_add]
    omega

theorem mem_degreeGE_iff {n : ℕ} {f : MvPolynomial σ R} :
    f ∈ degreeGE σ R n ↔ ∀ d ∈ f.support, n ≤ d.degree := Iff.rfl

/-! ## Powers land in the degree filtration -/

/-- Degrees add, so the filtration is multiplicative. -/
theorem degreeGE_mul (a b : ℕ) :
    degreeGE σ R a * degreeGE σ R b ≤ degreeGE σ R (a + b) := by
  classical
  refine Ideal.mul_le.mpr fun p hp q hq d hd => ?_
  rw [MvPolynomial.mem_support_iff, coeff_mul] at hd
  obtain ⟨x, hx, hxne⟩ := Finset.exists_ne_zero_of_sum_ne_zero hd
  have hsum : x.1 + x.2 = d := Finset.mem_antidiagonal.mp hx
  have h1 : a ≤ x.1.degree := hp x.1 (MvPolynomial.mem_support_iff.mpr (left_ne_zero_of_mul hxne))
  have h2 : b ≤ x.2.degree := hq x.2 (MvPolynomial.mem_support_iff.mpr (right_ne_zero_of_mul hxne))
  have hdeg : d.degree = x.1.degree + x.2.degree := by rw [← hsum, Finsupp.degree_add]
  omega

theorem varIdeal_le_degreeGE_one : varIdeal σ R ≤ degreeGE σ R 1 := by
  classical
  refine Ideal.span_le.mpr ?_
  rintro _ ⟨i, rfl⟩ d hd
  rw [MvPolynomial.mem_support_iff, coeff_X'] at hd
  by_cases hcase : Finsupp.single i 1 = d
  · rw [← hcase, Finsupp.degree_single]
  · rw [if_neg hcase] at hd
    exact absurd rfl hd

theorem varIdeal_pow_le_degreeGE (n : ℕ) : varIdeal σ R ^ n ≤ degreeGE σ R n := by
  induction n with
  | zero =>
      intro f _ d _
      exact Nat.zero_le _
  | succ n ih =>
      rw [pow_succ]
      exact le_trans (Ideal.mul_mono ih varIdeal_le_degreeGE_one) (degreeGE_mul n 1)

/-! ## The degree filtration lands in the powers -/

/-- A monomial of degree at least `n` lies in the `n`-th power of the variable ideal. -/
theorem monomial_mem_varIdeal_pow :
    ∀ (n : ℕ) (d : σ →₀ ℕ) (c : R), n ≤ d.degree →
      (monomial d c : MvPolynomial σ R) ∈ varIdeal σ R ^ n
  | 0, _, _, _ => by
      rw [pow_zero, Ideal.one_eq_top]
      trivial
  | n + 1, d, c, h => by
      have hd : d ≠ 0 := by
        intro h0
        rw [h0, Finsupp.degree_zero] at h
        omega
      obtain ⟨i, hi⟩ : ∃ i, d i ≠ 0 := by
        by_contra hc
        push_neg at hc
        exact hd (by ext j; simp [hc j])
      have hle : Finsupp.single i 1 ≤ d :=
        Finsupp.single_le_iff.mpr (Nat.one_le_iff_ne_zero.mpr hi)
      obtain ⟨d', hd'⟩ := exists_add_of_le hle
      have hdeg : n ≤ d'.degree := by
        have hsplit : d.degree = 1 + d'.degree := by
          rw [hd', Finsupp.degree_add, Finsupp.degree_single]
        omega
      have hfac : (monomial d c : MvPolynomial σ R) = X i * monomial d' c := by
        rw [hd', monomial_single_add, pow_one]
      have hpow : varIdeal σ R ^ (n + 1) = varIdeal σ R * varIdeal σ R ^ n := by
        rw [pow_succ, mul_comm]
      rw [hfac, hpow]
      exact Ideal.mul_mem_mul (X_mem_varIdeal i) (monomial_mem_varIdeal_pow n d' c hdeg)

theorem degreeGE_le_varIdeal_pow (n : ℕ) : degreeGE σ R n ≤ varIdeal σ R ^ n := by
  classical
  intro f hf
  have hsum : (∑ d ∈ f.support, (monomial d (coeff d f) : MvPolynomial σ R))
      ∈ varIdeal σ R ^ n :=
    Ideal.sum_mem _ fun d hd => monomial_mem_varIdeal_pow n d _ (hf d hd)
  rwa [support_sum_monomial_coeff] at hsum

/-- **Powers of the variable ideal are the degree filtration.** -/
theorem varIdeal_pow_eq_degreeGE (n : ℕ) : varIdeal σ R ^ n = degreeGE σ R n :=
  le_antisymm (varIdeal_pow_le_degreeGE n) (degreeGE_le_varIdeal_pow n)

/-! ## In terms of homogeneous components -/

/-- Lying in `varIdeal ^ n` kills every homogeneous component below degree `n`. -/
theorem homogeneousComponent_eq_zero_of_mem_pow {n m : ℕ} {f : MvPolynomial σ R}
    (hf : f ∈ varIdeal σ R ^ n) (hm : m < n) :
    homogeneousComponent m f = 0 := by
  apply homogeneousComponent_eq_zero'
  intro d hd
  have hge : n ≤ d.degree := varIdeal_pow_le_degreeGE n hf d hd
  omega

/-- Conversely, no homogeneous component below degree `n` puts `f` in `varIdeal ^ n`. -/
theorem mem_pow_of_homogeneousComponent_eq_zero {n : ℕ} {f : MvPolynomial σ R}
    (h : ∀ m, m < n → homogeneousComponent m f = 0) :
    f ∈ varIdeal σ R ^ n := by
  refine degreeGE_le_varIdeal_pow n fun d hd => ?_
  by_contra hlt
  push_neg at hlt
  have h0 := h d.degree hlt
  have hc : coeff d f = 0 := by
    have hcc := congrArg (coeff d) h0
    rwa [coeff_homogeneousComponent, if_pos rfl, coeff_zero] at hcc
  exact (MvPolynomial.mem_support_iff.mp hd) hc

end KltDP.RingTheory.MvPolynomialVarOrder
