import KltDP.CommutativeAlgebra.FiniteAlgebraOneFiber
import Mathlib.RingTheory.LocalProperties.Exactness
import Mathlib.RingTheory.LocalRing.ResidueField.Ideal
import Mathlib.RingTheory.Localization.BaseChange

/-!
# Finite algebras with one-dimensional original residue fibers

The residue fiber at a prime is the actual tensor algebra over the original
base ring. Tensor cancellation identifies it with the residue fiber of the
localized algebra. The local Nakayama result and locality of surjectivity
then apply to the original algebra map.
-/

set_option autoImplicit false

noncomputable section

open TensorProduct

universe u v

namespace KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers

variable {R : Type u} [CommRing R]
  {A : Type v} [CommRing A] [Algebra R A]

/-- Localizing the original linear algebra map gives the original algebra
map to the tensor base change, with scalars restricted to `R`. -/
theorem localized_algebraMap_eq (p : Ideal R) [p.IsPrime] :
    IsLocalizedModule.map p.primeCompl
        (Algebra.linearMap R (Localization.AtPrime p))
        (TensorProduct.mk R (Localization.AtPrime p) A 1)
        (Algebra.linearMap R A) =
      (Algebra.linearMap (Localization.AtPrime p)
        ((Localization.AtPrime p) ⊗[R] A)).restrictScalars R := by
  apply IsLocalizedModule.linearMap_ext p.primeCompl
    (Algebra.linearMap R (Localization.AtPrime p))
    (TensorProduct.mk R (Localization.AtPrime p) A 1)
  rw [IsLocalizedModule.map_comp]
  apply LinearMap.ext
  intro r
  change (1 : Localization.AtPrime p) ⊗ₜ[R] algebraMap R A r =
    algebraMap R (Localization.AtPrime p) r ⊗ₜ[R] (1 : A)
  exact (Algebra.TensorProduct.tmul_one_eq_one_tmul r).symm

variable [Module.Finite R A]

/-- Dimension one of the original fiber forces the localized original
algebra map to be surjective. -/
theorem localized_algebraMap_surjective (p : Ideal R) [p.IsPrime]
    (hdim : Module.finrank p.ResidueField (p.ResidueField ⊗[R] A) = 1) :
    Function.Surjective (algebraMap (Localization.AtPrime p)
      ((Localization.AtPrime p) ⊗[R] A)) := by
  apply FiniteAlgebraOneFiber.algebraMap_surjective
  exact (Algebra.TensorProduct.cancelBaseChange R (Localization.AtPrime p)
    p.ResidueField p.ResidueField A).toLinearEquiv.finrank_eq.trans hdim

/-- Injectivity of the original map combines with its one-dimensional
original fiber to give the bijective localized algebra map. -/
theorem localized_algebraMap_bijective (p : Ideal R) [p.IsPrime]
    (hdim : Module.finrank p.ResidueField (p.ResidueField ⊗[R] A) = 1)
    (hinjective : Function.Injective (algebraMap R A)) :
    Function.Bijective (algebraMap (Localization.AtPrime p)
      ((Localization.AtPrime p) ⊗[R] A)) := by
  refine ⟨?_, localized_algebraMap_surjective p hdim⟩
  have h := IsLocalizedModule.map_injective p.primeCompl
    (Algebra.linearMap R (Localization.AtPrime p))
    (TensorProduct.mk R (Localization.AtPrime p) A 1)
    (Algebra.linearMap R A) hinjective
  rwa [localized_algebraMap_eq] at h

/-- A finite algebra whose actual residue fiber has dimension one at every
maximal ideal is generated by the image of its original base ring. -/
theorem algebraMap_surjective
    (hdim : ∀ (p : Ideal R) [p.IsMaximal],
      Module.finrank p.ResidueField (p.ResidueField ⊗[R] A) = 1) :
    Function.Surjective (algebraMap R A) := by
  change Function.Surjective (Algebra.linearMap R A)
  apply surjective_of_isLocalized_maximal
    (fun (p : Ideal R) (_ : p.IsMaximal) => Localization.AtPrime p)
    (fun p _ => Algebra.linearMap R (Localization.AtPrime p))
    (fun p _ => (Localization.AtPrime p) ⊗[R] A)
    (fun p _ => TensorProduct.mk R (Localization.AtPrime p) A 1)
    (Algebra.linearMap R A)
  intro p hp
  rw [localized_algebraMap_eq]
  exact localized_algebraMap_surjective p (hdim p)

/-- For an injective original map, the same actual residue-fiber condition
makes that original map bijective. -/
theorem algebraMap_bijective
    (hdim : ∀ (p : Ideal R) [p.IsMaximal],
      Module.finrank p.ResidueField (p.ResidueField ⊗[R] A) = 1)
    (hinjective : Function.Injective (algebraMap R A)) :
    Function.Bijective (algebraMap R A) :=
  ⟨hinjective, algebraMap_surjective hdim⟩

end KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers

#check @KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.localized_algebraMap_eq
#print axioms KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.localized_algebraMap_eq
#check @KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.localized_algebraMap_surjective
#print axioms KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.localized_algebraMap_surjective
#check @KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.localized_algebraMap_bijective
#print axioms KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.localized_algebraMap_bijective
#check @KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.algebraMap_surjective
#print axioms KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.algebraMap_surjective
#check @KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.algebraMap_bijective
#print axioms KltDP.CommutativeAlgebra.FiniteAlgebraResidueFibers.algebraMap_bijective
