import Mathlib.RingTheory.LocalRing.Module
import Mathlib.RingTheory.TensorProduct.Basic
import Mathlib.LinearAlgebra.FiniteDimensional.Basic

/-!
# A finite local algebra whose original residue fiber has dimension one

The original unit is a basis of the one-dimensional residue-field algebra.
Pinned Nakayama lifts this basis to the assertion that the original algebra
is spanned by its original unit. Thus the original algebra map is surjective.
No flatness, normalization, free-rank, or surjectivity premise is used.
-/

set_option autoImplicit false

noncomputable section

open TensorProduct IsLocalRing

universe u v

namespace KltDP.CommutativeAlgebra.FiniteAlgebraOneFiber

variable {R : Type u} [CommRing R] [IsLocalRing R]
  {A : Type v} [CommRing A] [Algebra R A] [Module.Finite R A]

/-- A finite algebra over a local ring is generated by its original unit
when its actual residue fiber has dimension one over the residue field. -/
theorem algebraMap_surjective
    (hdim : Module.finrank (ResidueField R) ((ResidueField R) ⊗[R] A) = 1) :
    Function.Surjective (algebraMap R A) := by
  letI : Nontrivial ((ResidueField R) ⊗[R] A) :=
    Module.nontrivial_of_finrank_eq_succ hdim
  let b : Basis Unit (ResidueField R) ((ResidueField R) ⊗[R] A) :=
    FiniteDimensional.basisSingleton Unit hdim 1 one_ne_zero
  have hb (i : Unit) : (1 : ResidueField R) ⊗ₜ[R] (1 : A) = b i := by
    simp only [b, FiniteDimensional.basisSingleton_apply]
    rfl
  have hspan : Submodule.span R ({1} : Set A) = ⊤ := by
    simpa only [Set.range_const] using
      IsLocalRing.span_eq_top_of_tmul_eq_basis (R := R) (fun _ : Unit => (1 : A)) b hb
  intro a
  obtain ⟨r, hr⟩ := (Submodule.span_singleton_eq_top_iff R (1 : A)).mp hspan a
  exact ⟨r, by simpa only [Algebra.smul_def, mul_one] using hr⟩

/-- If the original algebra map is also injective, the same residue-fiber
dimension hypothesis makes that map bijective. -/
theorem algebraMap_bijective
    (hdim : Module.finrank (ResidueField R) ((ResidueField R) ⊗[R] A) = 1)
    (hinjective : Function.Injective (algebraMap R A)) :
    Function.Bijective (algebraMap R A) :=
  ⟨hinjective, algebraMap_surjective hdim⟩

end KltDP.CommutativeAlgebra.FiniteAlgebraOneFiber

#check @KltDP.CommutativeAlgebra.FiniteAlgebraOneFiber.algebraMap_surjective
#print axioms KltDP.CommutativeAlgebra.FiniteAlgebraOneFiber.algebraMap_surjective
#check @KltDP.CommutativeAlgebra.FiniteAlgebraOneFiber.algebraMap_bijective
#print axioms KltDP.CommutativeAlgebra.FiniteAlgebraOneFiber.algebraMap_bijective
