import Mathlib.LinearAlgebra.Matrix.SchurComplement
import Mathlib.Tactic

/-!
# Bordered intersection matrices and orthogonal correction

The bordered matrix in this file has exceptional block `-A`, contact column
`p`, and final self-intersection `d`. All matrices and vectors are concrete
functions on finite index types, and every theorem is purely algebraic.

For manuscript `lem:projection`, take `d = -1`. The correction vector
`(A⁻¹p, 1)` is orthogonal to all exceptional coordinates and has square
`pᵀA⁻¹p - 1`. The proof that the geometric orthogonal complement is the line
generated by the anticanonical pullback is not supplied here. Consequently,
the equality of this square with `(L·P)²/K_Y²` remains a geometric obligation,
as does the adjunction identity relating the charge to `1 - L·P`.

The determinant formula is useful independently of that geometric adapter.
-/

namespace KltDP.LinearAlgebra

open Matrix

variable {ι 𝕜 : Type*} [Fintype ι] [Field 𝕜]

/-- A Gram matrix with exceptional block `-A`, contact vector `p`, and final
self-intersection `d`. The last coordinate is indexed by `Unit`. -/
def borderedGram (A : Matrix ι ι 𝕜) (p : ι → 𝕜) (d : 𝕜) :
    Matrix (ι ⊕ Unit) (ι ⊕ Unit) 𝕜 :=
  Matrix.fromBlocks (-A) (fun i _ => p i) (fun _ j => p j) (fun _ _ => d)

/-- Block multiplication with the bordered intersection matrix. -/
theorem borderedGram_mulVec (A : Matrix ι ι 𝕜) (p x : ι → 𝕜) (d t : 𝕜) :
    borderedGram A p d *ᵥ Sum.elim x (fun _ => t) =
      Sum.elim (-(A *ᵥ x) + t • p) (fun _ => dotProduct p x + d * t) := by
  ext i
  cases i <;>
    simp [borderedGram, Matrix.fromBlocks_mulVec, Matrix.mulVec, dotProduct,
      Finset.sum_neg_distrib, mul_comm]

/-- The last coordinate is one, and the exceptional coordinates solve the
orthogonality equations. -/
noncomputable def orthogonalCorrection [DecidableEq ι]
    (A : Matrix ι ι 𝕜) (p : ι → 𝕜) :
    (ι ⊕ Unit) → 𝕜 :=
  Sum.elim (A⁻¹ *ᵥ p) (fun _ => 1)

/-- The correction vector has zero pairing with every exceptional coordinate.
Its remaining pairing is the scalar Schur complement. -/
theorem borderedGram_mulVec_orthogonalCorrection [DecidableEq ι]
    {A : Matrix ι ι 𝕜} (hA : IsUnit A) (p : ι → 𝕜) (d : 𝕜) :
    borderedGram A p d *ᵥ orthogonalCorrection A p =
      Sum.elim (0 : ι → 𝕜) (fun (_ : Unit) => d + dotProduct p (A⁻¹ *ᵥ p)) := by
  letI : Invertible A := hA.invertible
  rw [orthogonalCorrection, borderedGram_mulVec, Matrix.mulVec_mulVec,
    Matrix.mul_inv_of_invertible, Matrix.one_mulVec]
  simp [add_comm]

/-- Squaring the corrected vector computes the scalar Schur complement. -/
theorem orthogonalCorrection_square [DecidableEq ι]
    {A : Matrix ι ι 𝕜} (hA : IsUnit A) (p : ι → 𝕜) (d : 𝕜) :
    dotProduct (orthogonalCorrection A p)
      (borderedGram A p d *ᵥ orthogonalCorrection A p) =
      d + dotProduct p (A⁻¹ *ᵥ p) := by
  rw [borderedGram_mulVec_orthogonalCorrection hA]
  simp [orthogonalCorrection, sumElim_dotProduct_sumElim, dotProduct]

/-- An inverse solution recovers the source charge from its row equation.
No relation between that charge and an anticanonical degree is assumed. -/
theorem inverse_charge_of_rowEquation [DecidableEq ι]
    {A : Matrix ι ι 𝕜} (hA : IsUnit A) {q coeff : ι → 𝕜}
    (hrow : A *ᵥ coeff = q) (p : ι → 𝕜) :
    dotProduct p (A⁻¹ *ᵥ q) = dotProduct p coeff := by
  letI : Invertible A := hA.invertible
  rw [← hrow, Matrix.mulVec_mulVec, Matrix.inv_mul_of_invertible,
    Matrix.one_mulVec]

/-- Determinant of the bordered intersection matrix, with its sign expressed
as the determinant of the negative exceptional block. -/
theorem det_borderedGram [DecidableEq ι] {A : Matrix ι ι 𝕜}
    (hA : IsUnit A) (p : ι → 𝕜) (d : 𝕜) :
    (borderedGram A p d).det = (-A).det * (d + dotProduct p (A⁻¹ *ᵥ p)) := by
  letI : Invertible A := hA.invertible
  letI : Invertible (-A) := invertibleNeg A
  rw [borderedGram, Matrix.det_fromBlocks₁₁, invOf_neg,
    Matrix.invOf_eq_nonsing_inv, Matrix.mul_neg, Matrix.neg_mul,
    sub_neg_eq_add, Matrix.det_unique (n := Unit)]
  congr 1
  change d + (Matrix.replicateRow Unit p * A⁻¹ * Matrix.replicateCol Unit p) () () =
    d + dotProduct p (A⁻¹ *ᵥ p)
  rw [Matrix.mul_assoc]
  rfl

/-- The determinant formula with the exceptional-block sign made explicit. -/
theorem det_borderedGram_signed [DecidableEq ι] {A : Matrix ι ι 𝕜}
    (hA : IsUnit A) (p : ι → 𝕜) (d : 𝕜) :
    (borderedGram A p d).det =
      (-1 : 𝕜) ^ Fintype.card ι * A.det * (d + dotProduct p (A⁻¹ *ᵥ p)) := by
  rw [det_borderedGram hA, Matrix.det_neg]

/-- The full Gram determinant for a curve of self-intersection minus one. -/
theorem det_minusOne_borderedGram [DecidableEq ι] {A : Matrix ι ι 𝕜}
    (hA : IsUnit A) (p : ι → 𝕜) :
    (borderedGram A p (-1)).det = (-1 : 𝕜) ^ Fintype.card ι * A.det *
      (dotProduct p (A⁻¹ *ᵥ p) - 1) := by
  simpa only [sub_eq_add_neg, add_comm] using det_borderedGram_signed hA p (-1)

/-- Nondegeneracy is exactly nonvanishing of the scalar Schur complement. -/
theorem det_borderedGram_ne_zero_iff [DecidableEq ι] {A : Matrix ι ι 𝕜}
    (hA : IsUnit A) (p : ι → 𝕜) (d : 𝕜) :
    (borderedGram A p d).det ≠ 0 ↔ d + dotProduct p (A⁻¹ *ᵥ p) ≠ 0 := by
  have hdet : A.det ≠ 0 := ((Matrix.isUnit_iff_isUnit_det A).mp hA).ne_zero
  rw [det_borderedGram_signed hA]
  simp [hdet]

/-- Invertibility, rather than just a determinant condition, is controlled by
the same scalar Schur complement. -/
theorem isUnit_borderedGram_iff [DecidableEq ι] {A : Matrix ι ι 𝕜}
    (hA : IsUnit A) (p : ι → 𝕜) (d : 𝕜) :
    IsUnit (borderedGram A p d) ↔ d + dotProduct p (A⁻¹ *ᵥ p) ≠ 0 := by
  rw [Matrix.isUnit_iff_isUnit_det, isUnit_iff_ne_zero,
    det_borderedGram_ne_zero_iff hA]

section Ordered

variable [LinearOrder 𝕜] [IsStrictOrderedRing 𝕜]

/-- The strict Green inequality is equivalent to positivity of the actual
corrected vector's square when the original curve has square minus one. -/
theorem orthogonalCorrection_square_pos_iff [DecidableEq ι]
    {A : Matrix ι ι 𝕜} (hA : IsUnit A) (p : ι → 𝕜) :
    0 < dotProduct (orthogonalCorrection A p)
      (borderedGram A p (-1) *ᵥ orthogonalCorrection A p) ↔
      1 < dotProduct p (A⁻¹ *ᵥ p) := by
  rw [orthogonalCorrection_square hA]
  constructor <;> intro h <;> linarith

/-- The strict Green inequality implies nondegeneracy of the full Gram matrix.
It is an explicit hypothesis, not inferred from any geometric structure. -/
theorem isUnit_minusOne_borderedGram_of_green [DecidableEq ι]
    {A : Matrix ι ι 𝕜} (hA : IsUnit A) (p : ι → 𝕜)
    (hgreen : 1 < dotProduct p (A⁻¹ *ᵥ p)) :
    IsUnit (borderedGram A p (-1)) := by
  apply (isUnit_borderedGram_iff hA p (-1)).2
  have hpos : 0 < -1 + dotProduct p (A⁻¹ *ᵥ p) := by linarith
  exact ne_of_gt hpos

end Ordered

end KltDP.LinearAlgebra
