import KltDP.Examples.FrobeniusFiberPicard
import KltDP.Examples.FrobeniusGraphPicardClassIntegral
import KltDP.Examples.ProjectiveLinePointAtInfinity
import KltDP.Examples.FrobeniusTowerPicardRelation
import KltDP.Geometry.GluedIdealInvertible

/-!
# The ideal of the fibre `y = 0` of `P¹ × P¹` is invertible: lane A2's `FiberKernelInvertible 0`

Lane A2 proves the Picard chain of the strict fibre of the origin contact tower under the stage-`0`
hypothesis `FiberKernelInvertible 0`: the kernel module of the closed subscheme glued from the ideal
sheaf `I(F_0)` of the strict fibre of stage `0` is invertible. A2 identifies that ideal sheaf with the
kernel of the horizontal fibre `y = 0` of `P¹ × P¹` (`fiberStrictIdeal_zero`). This module discharges
the hypothesis through the accepted criterion `gluedKernel_isInvertible`: the ideal is locally generated
by one regular element (`IdealLocallyPrincipalRegular`) on the four polynomial charts of the product.

* On the charts `(i, 0)` (second coordinate finite) the fibre is the line `v = 0` of the chart: the
  line `fiberCurve : Spec k[t] ⟶ Spec k[u][v]` composed with `productChart i 0` is the horizontal fibre
  restricted to the `i`-th chart of the first factor (`fiberCurve_productChart`), so the kernel of
  `y = 0` is the kernel of that line (`horizontalFiber_ker_eq`, schematic images ignore dense open
  precomposition) and, through the accepted pullback-kernel comparison, its chart ideal is `(v)`
  (`horizontalFiber_chartIdeal_zero`, `horizontalFiber_ideal_chart_zero`); `v ≠ 0` in the domain
  `Γ(chart)` (`P¹ × P¹` is integral), so the generator is regular.
* On the charts `(i, 1)` (second coordinate `≠ [1:0]`) the fibre is absent: the second coordinate of
  every point of the fibre is the rational point `[1:0]`, which is not on the second chart of `P¹`
  (`horizontalFiber_snd_not_mem_chartOpen_one`), so the chart ideal is the unit ideal, generated by `1`.

Result: `fiberKernel_zero_isInvertible : FiberKernelInvertible 0`, hence A2's invertibility on every
stage (`fiberKernel_isInvertible'`) and the unconditional tower relation
`f29_tower_fiber_picard_relation'` (`π^*F_0 = F̃ + Σ_{j<N} (j+1)·C_j + (N+1)·P` on stage `N+1`).
-/

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits TopologicalSpace

universe u

namespace KltDP.Examples.FrobeniusFiberZeroInvertible

open KltDP.Geometry ProjectiveLineComparison
open FrobeniusProjectivePoints FrobeniusBlowupContact FrobeniusBlowupChartIteration
  FrobeniusProductPlaneChart FrobeniusGraphPicardClassCharts FrobeniusGraphPicardClassIntegral
  FrobeniusGraphPicardClassZeroFiber FrobeniusGraphPicardClassPowerCharts
  FrobeniusGraphPicardClassMixedOverlap FrobeniusFiberClosure FrobeniusFiberTranslation
  FrobeniusTranslatedCharts FrobeniusGlobalBlowupStages FrobeniusFiberPicard
  FrobeniusGraphContact FrobeniusGraphStalkContact ProjectiveLinePointAtInfinity
  FrobeniusGraphClosed

variable {k : Type u} [Field k]

/-! ## Quasi-compactness of morphisms out of the polynomial line -/

/-- The polynomial line is a Noetherian space. -/
instance parameterLine_noetherianSpace :
    NoetherianSpace (Spec (CommRingCat.of (Polynomial k))) :=
  inferInstanceAs (NoetherianSpace (PrimeSpectrum (Polynomial k)))

/-- Every morphism out of a Noetherian scheme is quasi-compact. -/
theorem quasiCompact_of_noetherianSpace {X Y : Scheme.{u}} [NoetherianSpace X] (f : X ⟶ Y) :
    QuasiCompact f :=
  ⟨fun U _ _ => NoetherianSpace.isCompact (f.base ⁻¹' U)⟩

instance fiberLine_chart_quasiCompact (i j : Fin 2) :
    QuasiCompact (fiberCurve (k := k) ≫ productChart i j) :=
  quasiCompact_of_noetherianSpace _

/-! ## The fibre line on the charts `(i, 0)` -/

/-- `fiberCurve` is the fibre line at height `0`. -/
theorem fiberCurve_eq_fiberCurveAt_zero : fiberCurve (k := k) = fiberCurveAt 0 := by
  unfold fiberCurve fiberCurveAt
  rw [Polynomial.C_0]

/-- The line `v = 0` of the chart `(i, 0)` is the horizontal fibre `y = 0` over the `i`-th chart of the
first factor. -/
@[reassoc] theorem fiberCurve_productChart (i : Fin 2) :
    fiberCurve (k := k) ≫ productChart i 0 =
      polynomialChartMap k i ≫ horizontalFiberMorphism 0 := by
  rw [fiberCurve_eq_fiberCurveAt_zero]
  apply pullback.hom_ext
  · simp only [Category.assoc, horizontalFiberMorphism, pullback.lift_fst, Category.comp_id]
    rw [productChart_fst, ← Category.assoc, fiberCurveAt_firstCoordinate, Category.id_comp]
  · simp only [Category.assoc, horizontalFiberMorphism, pullback.lift_snd]
    rw [productChart_snd, ← Category.assoc, fiberCurveAt_secondCoordinate, ← Category.assoc,
      polynomialChartMap_structureMap, CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc,
      polynomialChartMap_evaluation]

/-- The kernel of the horizontal fibre `y = 0` is the kernel of the line `v = 0` of any chart `(i, 0)`. -/
theorem horizontalFiber_ker_eq (i : Fin 2) :
    (horizontalFiberMorphism (0 : k)).ker = (fiberCurve ≫ productChart i 0).ker := by
  letI : IsIntegral (projectiveSpace k 1) := projectiveSpace_isIntegral k 1
  rw [fiberCurve_productChart]
  exact (SchematicImageOpenImmersion.ker_precompose_openImmersion (polynomialChartMap k i)
    (horizontalFiberMorphism 0)).symm

/-- The affine open of the chart `(i, j)` of the product. -/
def fiberChartAffineOpen (i j : Fin 2) : (projectiveProduct k).affineOpens :=
  ⟨productChart i j ''ᵁ ⊤,
    (isAffineOpen_top (Spec (CommRingCat.of (planeRing k)))).image_of_isOpenImmersion
      (productChart i j)⟩

theorem mem_fiberChartAffineOpen_of_mem_range (i j : Fin 2) (x : projectiveProduct k)
    (hx : x ∈ Set.range (productChart (k := k) i j).base) :
    x ∈ (fiberChartAffineOpen (k := k) i j).1 := by
  show x ∈ productChart (k := k) i j ''ᵁ ⊤
  rw [Scheme.Hom.image_top_eq_opensRange]
  exact hx

/-- The fibre line and the chart `(i, 0)` form a pullback square with the identity. -/
theorem fiberCurve_productChart_isPullback (i : Fin 2) :
    IsPullback (fiberCurve (k := k)) (𝟙 _) (productChart i 0) (fiberCurve ≫ productChart i 0) := by
  have hr : Set.range (fiberCurve (k := k) ≫ productChart i 0).base ⊆
      Set.range (productChart (k := k) i 0).base := by
    rintro _ ⟨t, rfl⟩
    exact ⟨(fiberCurve (k := k)).base t,
      (Scheme.comp_base_apply fiberCurve (productChart i 0) t).symm⟩
  have hLift : IsOpenImmersion.lift (productChart (k := k) i 0) (fiberCurve ≫ productChart i 0) hr =
      fiberCurve :=
    (IsOpenImmersion.lift_uniq _ _ hr fiberCurve rfl).symm
  simpa only [hLift] using
    IsOpenImmersion.isPullback_lift_id (fiberCurve (k := k) ≫ productChart i 0) (productChart i 0) hr

/-- The kernel of the fibre line, read in the coordinates `k[u][v]` of the plane, is `(v)`. -/
theorem fiberCurve_coordinateKernel :
    RingHom.ker (((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv ≫
        (fiberCurve (k := k)).appTop).hom) =
      Ideal.span {vCoord} := by
  have hΓ : Function.Injective
      ((Scheme.ΓSpecIso (CommRingCat.of (Polynomial k))).inv.hom) :=
    (Scheme.ΓSpecIso (CommRingCat.of (Polynomial k))).symm.commRingCatIsoToRingEquiv.injective
  rw [fiberCurve, ← Scheme.ΓSpecIso_inv_naturality, CommRingCat.hom_comp,
    RingHom.ker_comp_of_injective _ hΓ, CommRingCat.hom_ofHom, Polynomial.ker_evalRingHom]
  simp only [vCoord, Polynomial.C_0, sub_zero]

/-- On the chart `(i, 0)` the ideal of the fibre `y = 0`, in the chart coordinates, is `(v)`. -/
theorem horizontalFiber_chartIdeal_zero (i : Fin 2) :
    Ideal.comap (Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv.hom
      (Ideal.comap ((productChart (k := k) i 0).appIso ⊤).inv.hom
        ((horizontalFiberMorphism (0 : k)).ker.ideal (fiberChartAffineOpen i 0))) =
      Ideal.span {vCoord} := by
  unfold fiberChartAffineOpen
  rw [horizontalFiber_ker_eq i, ← Scheme.ker_ideal_of_isPullback_of_isOpenImmersion
    (fiberCurve ≫ productChart i 0) fiberCurve (𝟙 _) (productChart i 0)
    (fiberCurve_productChart_isPullback i) ⟨⊤, isAffineOpen_top (plane k)⟩, Scheme.Hom.ker_apply]
  change RingHom.ker (((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv ≫
    (fiberCurve (k := k)).appTop).hom) = _
  exact fiberCurve_coordinateKernel

/-- The local equation `v` of the fibre `y = 0` on the chart `(i, 0)`, as a section of the product. -/
def fiberZeroChartEquation (i : Fin 2) :
    Γ(projectiveProduct k, (fiberChartAffineOpen (k := k) i 0).1) :=
  ((productChart (k := k) i 0).appIso ⊤).inv.hom
    ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv.hom vCoord)

/-- On the chart `(i, 0)` the ideal of the fibre `y = 0` is generated by its local equation. -/
theorem horizontalFiber_ideal_chart_zero (i : Fin 2) :
    (horizontalFiberMorphism (0 : k)).ker.ideal (fiberChartAffineOpen i 0) =
      Ideal.span {fiberZeroChartEquation i} := by
  have e1 : Function.Surjective ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv.hom) :=
    (Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).symm.commRingCatIsoToRingEquiv.surjective
  have e2 : Function.Surjective (((productChart (k := k) i 0).appIso ⊤).inv.hom) :=
    ((productChart (k := k) i 0).appIso ⊤).symm.commRingCatIsoToRingEquiv.surjective
  calc (horizontalFiberMorphism (0 : k)).ker.ideal (fiberChartAffineOpen i 0)
      = Ideal.map (((productChart (k := k) i 0).appIso ⊤).inv.hom)
          (Ideal.map ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv.hom)
            (Ideal.comap ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv.hom)
              (Ideal.comap (((productChart (k := k) i 0).appIso ⊤).inv.hom)
                ((horizontalFiberMorphism (0 : k)).ker.ideal (fiberChartAffineOpen i 0))))) := by
        rw [Ideal.map_comap_of_surjective _ e1, Ideal.map_comap_of_surjective _ e2]
    _ = Ideal.span {fiberZeroChartEquation i} := by
        rw [horizontalFiber_chartIdeal_zero, Ideal.map_span, Set.image_singleton, Ideal.map_span,
          Set.image_singleton]
        rfl

theorem fiberZeroChartEquation_ne_zero (i : Fin 2) : fiberZeroChartEquation (k := k) i ≠ 0 := by
  intro h0
  have h1 : Function.Injective (((productChart (k := k) i 0).appIso ⊤).inv.hom) :=
    ((productChart (k := k) i 0).appIso ⊤).symm.commRingCatIsoToRingEquiv.injective
  have h2 : Function.Injective ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv.hom) :=
    (Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).symm.commRingCatIsoToRingEquiv.injective
  have hv : (vCoord : planeRing k) = 0 := by
    apply h2
    rw [map_zero]
    apply h1
    rw [map_zero]
    exact h0
  exact Polynomial.X_ne_zero hv

/-- The local equation is a nonzero element of a domain, hence a nonzerodivisor. -/
theorem fiberZeroChartEquation_mem_nonZeroDivisors (i : Fin 2) :
    fiberZeroChartEquation (k := k) i ∈
      nonZeroDivisors Γ(projectiveProduct k, (fiberChartAffineOpen (k := k) i 0).1) := by
  letI : IsIntegral (projectiveProduct k) := projectiveProduct_isIntegral
  haveI : Nonempty (fiberChartAffineOpen (k := k) i 0).1 :=
    ⟨⟨(productChart (k := k) i 0).base (Nonempty.some inferInstance),
      mem_fiberChartAffineOpen_of_mem_range i 0 _ ⟨_, rfl⟩⟩⟩
  haveI : IsDomain Γ(projectiveProduct k, (fiberChartAffineOpen (k := k) i 0).1) :=
    IsIntegral.component_integral _
  exact mem_nonZeroDivisors_of_ne_zero (fiberZeroChartEquation_ne_zero i)

/-! ## The fibre is absent from the charts `(i, 1)` -/

theorem otherIndex_zero : otherIndex (0 : Fin 2) = 1 := rfl

/-- The second coordinate of every point of the fibre `y = 0` is the rational point `[1:0]`. -/
theorem horizontalFiber_snd_eq_point (z : projectiveSpace k 1) :
    (pullback.snd (projectiveSpaceToSpec k 1) (projectiveSpaceToSpec k 1)).base
        ((horizontalFiberMorphism (0 : k)).base z) = FrobeniusProjectivePoints.point 0 := by
  rw [← Scheme.comp_base_apply]
  change (horizontalFiberMorphism (0 : k) ≫ secondProjection).base z = _
  rw [horizontalFiberMorphism_snd, Scheme.comp_base_apply]
  unfold FrobeniusProjectivePoints.point fieldMorphismPoint
  exact congrArg (pointMorphism (0 : k)).base (Subsingleton.elim _ _)

/-- `[1:0]` is not on the second chart of `P¹`, so the fibre misses the charts `(i, 1)`. -/
theorem horizontalFiber_snd_not_mem_chartOpen_one (z : projectiveSpace k 1) :
    (pullback.snd (projectiveSpaceToSpec k 1) (projectiveSpaceToSpec k 1)).base
        ((horizontalFiberMorphism (0 : k)).base z) ∉
      (chartOpen k 1 : Set (projectiveSpace k 1)) := by
  rw [horizontalFiber_snd_eq_point, point_eq_chart]
  intro h
  have h' := (polynomialChart_mem_other_iff (k := k) 0 (parameterSchemePoint 0)).mp
    (by rw [otherIndex_zero]; exact h)
  exact h' X_mem_parameterPointIdeal_zero

/-- The fibre line does not meet the chart `(i, 1)`. -/
theorem fiberLine_preimage_chart_one (i : Fin 2) :
    (fiberCurve (k := k) ≫ productChart 0 0) ⁻¹ᵁ (fiberChartAffineOpen (k := k) i 1).1 = ⊥ := by
  rw [eq_bot_iff]
  intro t ht
  have h1 : (fiberCurve (k := k) ≫ productChart 0 0).base t ∈
      Set.range (productChart (k := k) i 1).base := by
    have : (fiberCurve (k := k) ≫ productChart 0 0).base t ∈ productChart (k := k) i 1 ''ᵁ ⊤ := ht
    rw [Scheme.Hom.image_top_eq_opensRange] at this
    exact this
  rw [productChart_range] at h1
  have h2 := h1.2
  rw [fiberCurve_productChart 0, Scheme.comp_base_apply] at h2
  exact absurd h2 (horizontalFiber_snd_not_mem_chartOpen_one _)

/-- On the chart `(i, 1)` the ideal of the fibre `y = 0` is the unit ideal. -/
theorem horizontalFiber_ideal_chart_one (i : Fin 2) :
    (horizontalFiberMorphism (0 : k)).ker.ideal (fiberChartAffineOpen i 1) = Ideal.span {1} := by
  rw [Ideal.span_singleton_one, horizontalFiber_ker_eq 0, Scheme.Hom.ker_apply,
    Ideal.eq_top_iff_one, RingHom.mem_ker]
  haveI : Subsingleton Γ(Spec (CommRingCat.of (Polynomial k)),
      (fiberCurve (k := k) ≫ productChart 0 0) ⁻¹ᵁ (fiberChartAffineOpen (k := k) i 1).1) :=
    CommRingCat.subsingleton_of_isTerminal
      ((Spec (CommRingCat.of (Polynomial k))).sheaf.isTerminalOfEqEmpty
        (fiberLine_preimage_chart_one i))
  exact Subsingleton.elim _ _

/-! ## Local regular equations on the four charts -/

/-- The ideal sheaf of the fibre `y = 0` has a regular local equation on an affine neighbourhood of
every point of `P¹ × P¹`. -/
theorem horizontalFiber_ker_locallyPrincipalRegular :
    IdealLocallyPrincipalRegular ((horizontalFiberMorphism (0 : k)).ker) := by
  intro x
  obtain ⟨i, j, hx⟩ := productCharts_cover x
  have hx' : x ∈ (fiberChartAffineOpen (k := k) i j).1 :=
    mem_fiberChartAffineOpen_of_mem_range i j x hx
  fin_cases j
  · exact ⟨fiberChartAffineOpen i 0, hx', fiberZeroChartEquation i,
      horizontalFiber_ideal_chart_zero i, fiberZeroChartEquation_mem_nonZeroDivisors i⟩
  · exact ⟨fiberChartAffineOpen i 1, hx', 1, horizontalFiber_ideal_chart_one i,
      Submonoid.one_mem _⟩

/-- **Lane A2's stage-`0` hypothesis holds**: the kernel module of the strict fibre of stage `0` of the
origin contact tower is invertible. -/
theorem fiberKernel_zero_isInvertible : FiberKernelInvertible (k := k) 0 := by
  have hI : IdealLocallyPrincipalRegular
      (liftedFiberClosureIdeal (projectiveProductInitial (k := k)) 0) := by
    rw [fiberStrictIdeal_zero]
    exact horizontalFiber_ker_locallyPrincipalRegular
  exact gluedKernel_isInvertible _ hI

/-- The strict-fibre ideal is invertible on every stage of the origin tower (A2's propagation, now
unconditional). -/
theorem fiberKernel_isInvertible' (n : ℕ) : FiberKernelInvertible (k := k) n :=
  fiberKernel_isInvertible fiberKernel_zero_isInvertible n

end KltDP.Examples.FrobeniusFiberZeroInvertible

namespace KltDP.Examples

open FrobeniusStrictTransformClassesTower FrobeniusOldExceptionalLaterStages FrobeniusFiberPicard
  FrobeniusFiberZeroInvertible

/-- Bundle: the ideal of the stage-`0` strict fibre (`y = 0` on `P¹ × P¹`) is invertible. -/
theorem f29_fiber_zero_invertible (k : Type u) [Field k] : FiberKernelInvertible (k := k) 0 :=
  fiberKernel_zero_isInvertible

/-- Bundle (unconditional): on every stage `N + 1` of the origin contact tower,
`π^*F_0 = F̃ + Σ_{j<N} (j+1)·C_j + (N+1)·P` in `Additive Pic`. -/
theorem f29_tower_fiber_picard_relation' (k : Type u) [Field k] :
    ∀ N : ℕ, fiberTotalClass (fiberKernel_zero_isInvertible (k := k)) (N + 1) =
      fiberPicardClass (fiberKernel_zero_isInvertible (k := k)) (N + 1) +
        ∑ j : Fin N, (j.val + 1) • oldExceptionalStrictClass (k := k) (N + 1) j.val (by omega) +
          (N + 1) • totalExceptionalClass (N + 1) (Fin.last N) :=
  f29_tower_fiber_picard_relation k fiberKernel_zero_isInvertible

/-- The bundles have exactly one universe parameter. -/
theorem f29_tower_fiber_picard_relation'_universe_check (k : Type u) [Field k] : True := by
  have _ := f29_fiber_zero_invertible.{u} k
  have _ := f29_tower_fiber_picard_relation'.{u} k
  trivial

end KltDP.Examples
