import KltDP.Examples.FrobeniusOldExceptionalSecondChartFrame
import KltDP.Examples.FrobeniusStrictTransformFirstChartComparison

/-!
# The older exceptional curve on the first Rees open: frames and the product comparison

On the first affine open of stage `j+2` the strict transform of the exceptional curve `E_j`
(the accepted `previousStrictι (A.stage j)`, written `oldExceptionalStrictι j`) is absent
(`oldStrict_firstChart_isEmpty`), so its kernel ideal restricted to this open is the whole
structure sheaf, framed by the equation `1`. The newest exceptional curve `E_{j+1}` has the
regular equation `u` there, and the first-chart blowdown `(u, w) ↦ (u, u w)` fixes the exceptional
coordinate `u` of stage `j+1`. Transporting the frame of `E_j` on the first affine open of stage
`j+1` through this blowdown therefore gives the pulled equation `u = u * 1`, so on this open

  `π^* I(E_j) ≅ I(E_{j+1}) ⊗ I(strict transform of E_j)`

with both original ambient inclusions preserved (`oldTotalProductFirstOpenIso_inclusion`), for the
same product morphism `exceptionalOldProduct j` as on the second Rees open. Together with
`FrobeniusOldExceptionalSecondChartFrame` this covers the two Rees charts over the blowup centre;
the centre-complement member is `FrobeniusOldExceptionalPuncture`, and the three members are glued
in `FrobeniusOldExceptionalTotalProduct`.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory MonoidalCategory

universe u

namespace KltDP.Examples.FrobeniusOldExceptionalFirstChartFrame

open KltDP.Geometry KltDP.Geometry.AffineBlowup
open FrobeniusBlowupContact FrobeniusBlowupSmooth FrobeniusBlowupChartIteration
open FrobeniusGlobalBlowupStages FrobeniusExceptionalSuccessorChart
open FrobeniusGlobalExceptionalSuccessor
open FrobeniusStrictTransformInvertible FrobeniusStrictTransformProductKernel
open FrobeniusStrictTransformFirstChartTensorFrame FrobeniusStrictTransformFirstChartComparison
open FrobeniusOldExceptionalChartIdeals FrobeniusOldExceptionalSecondChartFrame

attribute [local instance] Types.instFunLike Types.instConcreteCategory

local instance oldFirstTensorModules (X : Scheme.{u}) : MonoidalCategory X.Modules :=
  Scheme.Modules.monoidalCategory X

variable {k : Type u} [Field k]

local instance oldFirstOriginIdealMaximal : (originPoint (k := k)).asIdeal.IsMaximal :=
  FrobeniusBlowupChartIteration.centerIdeal_isMaximal

/-- Generic form of the tensor-frame inclusion: two normalized kernel frames on an actual open
tensor to a frame whose inclusion multiplies by the product of the two equations. -/
private theorem tensorFrame_inclusion_generic {Y Z : Scheme.{u}} (i : Z ⟶ Y) {M N : Y.Modules}
    (g : M ⟶ _root_.SheafOfModules.unit Y.ringCatSheaf)
    (h : N ⟶ _root_.SheafOfModules.unit Y.ringCatSheaf)
    (Fe : _root_.SheafOfModules.unit Z.ringCatSheaf ≅ (schemeModulePullback i).obj M)
    (Fs : _root_.SheafOfModules.unit Z.ringCatSheaf ≅ (schemeModulePullback i).obj N)
    (d₁ d₂ : Γ(Z, ⊤))
    (he : Fe.hom ≫ (schemeModulePullback i).map g ≫ (schemeModulePullbackUnitIso i).hom =
      schemeScalarEnd d₁)
    (hs : Fs.hom ≫ (schemeModulePullback i).map h ≫ (schemeModulePullbackUnitIso i).hom =
      schemeScalarEnd d₂) :
    ((schemeStructureTensorRightIso (_root_.SheafOfModules.unit Z.ringCatSheaf)).symm ≪≫
        tensorIso Fe Fs ≪≫ (schemeModulePullbackTensorIso i M N).symm).hom ≫
      (schemeModulePullback i).map ((g ⊗ h) ≫
        (schemeStructureTensorRightIso (_root_.SheafOfModules.unit Y.ringCatSheaf)).hom) ≫
      (schemeModulePullbackUnitIso i).hom =
    schemeScalarEnd (d₁ * d₂) := by
  rw [← schemeModulePullbackTensorIso_product, Iso.trans_hom, Iso.trans_hom, Iso.symm_hom,
    Iso.symm_hom, tensorIso_hom, Category.assoc, Category.assoc, Iso.inv_hom_id_assoc,
    ← tensor_comp_assoc, he, hs, schemeStructureTensor_scalar_mul]

/-- The strict transform of `E_j` misses the first Rees chart of stage `j+2`, so there its kernel
ideal is generated by `1`. -/
theorem oldStrictIdeal_firstAffineOpen (j : ℕ) :
    (oldExceptionalStrictι (k := k) j).ker.ideal (firstAffineOpen (j + 1 + 1)) =
      Ideal.span
        {(1 : Γ(projectiveContactStage (k := k) (j + 1 + 1), (firstAffineOpen (j + 1 + 1)).1))} := by
  have hbot :
      (oldExceptionalStrictι (k := k) j) ⁻¹ᵁ (firstAffineOpen (k := k) (j + 1 + 1)).1 = ⊥ := by
    apply TopologicalSpace.Opens.ext
    rw [TopologicalSpace.Opens.coe_bot]
    exact Set.eq_empty_iff_forall_not_mem.mpr fun x hx =>
      (oldStrict_firstChart_isEmpty (k := k) j).false ⟨x, hx⟩
  haveI : Subsingleton
      Γ(previousStrictTransform (previousStage (k := k) j),
        (oldExceptionalStrictι (k := k) j) ⁻¹ᵁ (firstAffineOpen (k := k) (j + 1 + 1)).1) := by
    rw [hbot]
    infer_instance
  rw [Ideal.span_singleton_one, Scheme.Hom.ker_apply, Ideal.eq_top_iff_one, RingHom.mem_ker]
  exact Subsingleton.elim _ _

/-- The equation `1` of the absent strict transform in the first affine open's own section ring. -/
def oldStrictFirstOpenEquation (j : ℕ) :
    Γ((firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme, ⊤) :=
  gluedAffineEquation (firstAffineOpen (j + 1 + 1)) 1

theorem oldStrictFirstOpenEquation_eq_one (j : ℕ) :
    oldStrictFirstOpenEquation (k := k) j = 1 := by
  simp only [oldStrictFirstOpenEquation, gluedAffineEquation, map_one]

/-- The absent strict transform has the unit frame on the first affine open. -/
def oldStrictFirstOpenFrame (j : ℕ) :
    _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ≅
      (schemeModulePullback (firstAffineOpen (k := k) (j + 1 + 1)).1.ι).obj
        (schemeKernelIdeal (oldExceptionalStrictι j)) :=
  schemeKernelAffineOpenFrame (oldExceptionalStrictι j) (firstAffineOpen (j + 1 + 1)) 1
    (oldStrictIdeal_firstAffineOpen j) (Submonoid.one_mem _)

theorem oldStrictFirstOpenFrame_inclusion (j : ℕ) :
    (oldStrictFirstOpenFrame (k := k) j).hom ≫
        pulledKernelInclusion (oldExceptionalStrictι j) (firstAffineOpen (j + 1 + 1)).1.ι =
      (schemeScalarEnd (Y := (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme)
          (oldStrictFirstOpenEquation j) :
        _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ⟶
          _root_.SheafOfModules.unit
            (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf) :=
  schemeKernelAffineOpenFrame_inclusion (oldExceptionalStrictι j) (firstAffineOpen (j + 1 + 1)) 1
    (oldStrictIdeal_firstAffineOpen j) (Submonoid.one_mem _)

/-- The frame of `E_{j+1}` on the first affine open, for the second-chart-module form of its
inclusion (the same closed immersion `stepExceptionalInclusion (j+1)`). -/
def exceptionalNewFirstOpenFrame (j : ℕ) :
    _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ≅
      (schemeModulePullback (firstAffineOpen (k := k) (j + 1 + 1)).1.ι).obj
        (schemeKernelIdeal
          (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc
            (k := k) (j + 1))) :=
  schemeKernelAffineOpenFrame
    (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc (j + 1))
    (firstAffineOpen (j + 1 + 1)) (firstExceptionalAmbientEquation (j + 1))
    (stepExceptionalIdeal_firstAffineOpen (j + 1)) (firstExceptionalAmbientEquation_regular (j + 1))

theorem exceptionalNewFirstOpenFrame_inclusion (j : ℕ) :
    (exceptionalNewFirstOpenFrame (k := k) j).hom ≫
        pulledKernelInclusion
          (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc (j + 1))
          (firstAffineOpen (j + 1 + 1)).1.ι =
      (schemeScalarEnd (Y := (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme)
          (firstExceptionalOpenEquation (j + 1)) :
        _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ⟶
          _root_.SheafOfModules.unit
            (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf) :=
  schemeKernelAffineOpenFrame_inclusion
    (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc (j + 1))
    (firstAffineOpen (j + 1 + 1)) (firstExceptionalAmbientEquation (j + 1))
    (stepExceptionalIdeal_firstAffineOpen (j + 1)) (firstExceptionalAmbientEquation_regular (j + 1))

/-- The first-chart blowdown fixes the previous exceptional coordinate `u`. -/
theorem firstStepExceptional_section :
    (coordinateBlowdown (k := k)).appTop
        ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord) =
      (Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord := by
  have h := ConcreteCategory.congr_hom
    (Scheme.ΓSpecIso_inv_naturality (CommRingCat.ofHom (chartSubstitution (k := k))))
    (uCoord (k := k))
  change (Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv (chartSubstitution uCoord) =
    (Spec.map (CommRingCat.ofHom (chartSubstitution (k := k)))).appTop
      ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord) at h
  rw [chartSubstitution_u] at h
  rw [coordinateBlowdown_eq]
  exact h.symm

/-- The first-chart blowdown pulls the first-open equation of `E_j` to that of `E_{j+1}`. -/
theorem firstOpenStepProjection_exceptionalEquation (j : ℕ) :
    (firstOpenStepProjection (k := k) (j + 1)).appTop (firstExceptionalOpenEquation j) =
      firstExceptionalOpenEquation (j + 1) := by
  have h := schemeOpenChartMap_section
    (((projectiveProductInitial (k := k)).stage (j + 1 + 1)).chart)
    (((projectiveProductInitial (k := k)).stage (j + 1)).chart) (coordinateBlowdown (k := k))
    ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord)
  rw [firstStepExceptional_section] at h
  exact h

/-- The frame of `E_j` on the first open of stage `j+1`, transported to the pulled kernel on the
first open of stage `j+2`. -/
def oldTotalFirstOpenFrame (j : ℕ) :
    _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ≅
      (schemeModulePullback (firstAffineOpen (k := k) (j + 1 + 1)).1.ι).obj
        ((schemeModulePullback ((projectiveProductInitial (k := k)).stepProjection (j + 1))).obj
          (schemeKernelIdeal (stepExceptionalInclusionSucc j))) :=
  schemeKernelFrameOnSquare (stepExceptionalInclusionSucc j) (firstAffineOpen (j + 1)).1.ι
    (firstOpenStepProjection (j + 1)) (firstAffineOpen (j + 1 + 1)).1.ι
    ((projectiveProductInitial (k := k)).stepProjection (j + 1))
    (firstOpenStepProjection_square (j + 1)) (stepExceptionalFirstOpenFrame j)

/-- The transported frame's inclusion multiplies by the exceptional coordinate of stage `j+2`. -/
theorem oldTotalFirstOpenFrame_inclusion (j : ℕ) :
    (oldTotalFirstOpenFrame (k := k) j).hom ≫
      (schemeModulePullback (firstAffineOpen (j + 1 + 1)).1.ι).map
        (pulledKernelInclusion (stepExceptionalInclusionSucc j)
          ((projectiveProductInitial (k := k)).stepProjection (j + 1))) ≫
      (schemeModulePullbackUnitIso (firstAffineOpen (j + 1 + 1)).1.ι).hom =
        (schemeScalarEnd (Y := (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme)
            (firstExceptionalOpenEquation (j + 1)) :
          _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ⟶
            _root_.SheafOfModules.unit
              (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf) := by
  have h := schemeKernelFrameOnSquare_inclusion (stepExceptionalInclusionSucc (k := k) j)
    (firstAffineOpen (j + 1)).1.ι (firstOpenStepProjection (j + 1))
    (firstAffineOpen (j + 1 + 1)).1.ι ((projectiveProductInitial (k := k)).stepProjection (j + 1))
    (firstOpenStepProjection_square (j + 1)) (stepExceptionalFirstOpenFrame j)
    (firstExceptionalOpenEquation j) (stepExceptionalFirstOpenFrame_inclusion j)
  rw [firstOpenStepProjection_exceptionalEquation] at h
  -- `exact h` unfolds the frame through the sheaf-of-modules composition and times out;
  -- the congruence closure only has to see that the frame is literally the transported one.
  convert h using 3

/-- The tensor of the two kernel frames on the first affine open. -/
def exceptionalOldFirstOpenFrame (j : ℕ) :
    _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ≅
      (schemeModulePullback (firstAffineOpen (k := k) (j + 1 + 1)).1.ι).obj
        (schemeKernelIdeal
            (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc
              (k := k) (j + 1)) ⊗
          schemeKernelIdeal (oldExceptionalStrictι (k := k) j)) :=
  (schemeStructureTensorRightIso
      (_root_.SheafOfModules.unit (firstAffineOpen (j + 1 + 1)).1.toScheme.ringCatSheaf)).symm ≪≫
    tensorIso (exceptionalNewFirstOpenFrame j) (oldStrictFirstOpenFrame j) ≪≫
    (schemeModulePullbackTensorIso (firstAffineOpen (j + 1 + 1)).1.ι
      (schemeKernelIdeal
        (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc (j + 1)))
      (schemeKernelIdeal (oldExceptionalStrictι j))).symm

/-- The product inclusion multiplies by the exceptional coordinate of stage `j+2` (times `1`). -/
theorem exceptionalOldFirstOpenFrame_inclusion (j : ℕ) :
    (exceptionalOldFirstOpenFrame (k := k) j).hom ≫
      (schemeModulePullback (firstAffineOpen (j + 1 + 1)).1.ι).map (exceptionalOldProduct j) ≫
      (schemeModulePullbackUnitIso (firstAffineOpen (j + 1 + 1)).1.ι).hom =
        (schemeScalarEnd (Y := (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme)
            (firstExceptionalOpenEquation (j + 1)) :
          _root_.SheafOfModules.unit (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf ⟶
            _root_.SheafOfModules.unit
              (firstAffineOpen (k := k) (j + 1 + 1)).1.toScheme.ringCatSheaf) := by
  have h := tensorFrame_inclusion_generic (firstAffineOpen (k := k) (j + 1 + 1)).1.ι
    (schemeKernelIdealι
      (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc (j + 1)))
    (schemeKernelIdealι (oldExceptionalStrictι j))
    (exceptionalNewFirstOpenFrame j) (oldStrictFirstOpenFrame j)
    (firstExceptionalOpenEquation (j + 1)) (oldStrictFirstOpenEquation j)
    (exceptionalNewFirstOpenFrame_inclusion j) (oldStrictFirstOpenFrame_inclusion j)
  rw [oldStrictFirstOpenEquation_eq_one, mul_one] at h
  exact h

/-- On the first affine open, the pulled ideal of `E_j` is the tensor of the ideals of `E_{j+1}`
and of the (absent) strict transform of `E_j`. -/
def oldTotalProductFirstOpenIso (j : ℕ) :
    (schemeModulePullback (firstAffineOpen (k := k) (j + 1 + 1)).1.ι).obj
        ((schemeModulePullback ((projectiveProductInitial (k := k)).stepProjection (j + 1))).obj
          (schemeKernelIdeal (stepExceptionalInclusionSucc j))) ≅
      (schemeModulePullback (firstAffineOpen (k := k) (j + 1 + 1)).1.ι).obj
        (schemeKernelIdeal
            (FrobeniusStrictTransformSecondChartTensorFrame.stepExceptionalInclusionSucc
              (k := k) (j + 1)) ⊗
          schemeKernelIdeal (oldExceptionalStrictι (k := k) j)) :=
  (oldTotalFirstOpenFrame j).symm ≪≫ exceptionalOldFirstOpenFrame j

/-- This isomorphism preserves both original ambient ideal maps. -/
theorem oldTotalProductFirstOpenIso_inclusion (j : ℕ) :
    (oldTotalProductFirstOpenIso (k := k) j).hom ≫
      (schemeModulePullback (firstAffineOpen (j + 1 + 1)).1.ι).map (exceptionalOldProduct j) ≫
      (schemeModulePullbackUnitIso (firstAffineOpen (j + 1 + 1)).1.ι).hom =
    (schemeModulePullback (firstAffineOpen (j + 1 + 1)).1.ι).map
      (pulledKernelInclusion (stepExceptionalInclusionSucc j)
        ((projectiveProductInitial (k := k)).stepProjection (j + 1))) ≫
      (schemeModulePullbackUnitIso (firstAffineOpen (j + 1 + 1)).1.ι).hom := by
  have h1 := exceptionalOldFirstOpenFrame_inclusion (k := k) j
  have h2 := oldTotalFirstOpenFrame_inclusion (k := k) j
  unfold oldTotalProductFirstOpenIso
  rw [Iso.trans_hom, Iso.symm_hom, Category.assoc, h1, ← h2, Iso.inv_hom_id_assoc]

end KltDP.Examples.FrobeniusOldExceptionalFirstChartFrame
