import KltDP.Examples.FrobeniusOldExceptionalChartIdeals
import KltDP.Examples.FrobeniusStrictTransformFirstChartTensorFrame
import KltDP.Examples.FrobeniusStrictTransformSecondChartComparison

/-!
# The older exceptional curve on the second Rees open: frames and the product comparison

On the second affine open of stage `j+2`, the strict transform of the exceptional curve `E_j`
(the accepted `previousStrictι (A.stage j)`, written as `oldExceptionalStrictι j`) has the regular
equation `u/v`. Its normalized kernel frame tensors with the frame of the newest exceptional curve
`E_{j+1}` (equation `v`), and the product inclusion multiplies by the pulled-back exceptional
coordinate `u` of the previous stage, because `v * (u/v) = u` in the second Rees chart. Transporting
the frame of `E_j` on the first affine open of stage `j+1` through the second-chart blowdown gives
the same pulled equation, so on this open

  `π^* I(E_j) ≅ I(E_{j+1}) ⊗ I(strict transform of E_j)`

with both original ambient inclusions preserved (`oldTotalProductSecondOpenIso_inclusion`).
This is the second-chart member of the three-open comparison behind the manuscript's
`C_j = E_j - E_{j+1}`; the first-chart member is `FrobeniusOldExceptionalFirstChartFrame`, the
centre-complement member is `FrobeniusOldExceptionalPuncture`, and the three members are glued in
`FrobeniusOldExceptionalTotalProduct`.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory MonoidalCategory

universe u

namespace KltDP.Examples.FrobeniusOldExceptionalSecondChartFrame

open KltDP.Geometry KltDP.Geometry.AffineBlowup
open FrobeniusBlowupContact FrobeniusBlowupSmooth FrobeniusBlowupChartIteration
open FrobeniusGlobalBlowupStages FrobeniusExceptionalSuccessorChart
open FrobeniusGlobalExceptionalSuccessor
open FrobeniusStrictTransformInvertible FrobeniusStrictTransformProductKernel
open FrobeniusStrictTransformSecondChart FrobeniusStrictTransformSecondChartFrame
open FrobeniusStrictTransformSecondChartTensorFrame FrobeniusStrictTransformSecondChartComparison
open FrobeniusOldExceptionalChartIdeals

attribute [local instance] Types.instFunLike Types.instConcreteCategory

local instance oldSecondTensorModules (X : Scheme.{u}) : MonoidalCategory X.Modules :=
  Scheme.Modules.monoidalCategory X

variable {k : Type u} [Field k]

local instance oldSecondOriginIdealMaximal : (originPoint (k := k)).asIdeal.IsMaximal :=
  FrobeniusBlowupChartIteration.centerIdeal_isMaximal

/-- Generic form of the tensor-frame inclusion: two normalized kernel frames on an actual open
tensor to a frame whose inclusion multiplies by the product of the two equations. -/
private theorem tensorFrame_inclusion_generic {Y Z : Scheme.{u}} (i : Z ⟶ Y) {M N : Y.Modules}
    (g : M ⟶ _root_.SheafOfModules.unit Y.ringCatSheaf)
    (h : N ⟶ _root_.SheafOfModules.unit Y.ringCatSheaf)
    (Fe : _root_.SheafOfModules.unit Z.ringCatSheaf ≅ (schemeModulePullback i).obj M)
    (Fs : _root_.SheafOfModules.unit Z.ringCatSheaf ≅ (schemeModulePullback i).obj N)
    (d₁ d₂ : Γ(Z, ⊤))
    (he : Fe.hom ≫ (schemeModulePullback i).map g ≫ (schemeModulePullbackUnitIso i).hom =
      schemeScalarEnd d₁)
    (hs : Fs.hom ≫ (schemeModulePullback i).map h ≫ (schemeModulePullbackUnitIso i).hom =
      schemeScalarEnd d₂) :
    ((schemeStructureTensorRightIso (_root_.SheafOfModules.unit Z.ringCatSheaf)).symm ≪≫
        tensorIso Fe Fs ≪≫ (schemeModulePullbackTensorIso i M N).symm).hom ≫
      (schemeModulePullback i).map ((g ⊗ h) ≫
        (schemeStructureTensorRightIso (_root_.SheafOfModules.unit Y.ringCatSheaf)).hom) ≫
      (schemeModulePullbackUnitIso i).hom =
    schemeScalarEnd (d₁ * d₂) := by
  rw [← schemeModulePullbackTensorIso_product, Iso.trans_hom, Iso.trans_hom, Iso.symm_hom,
    Iso.symm_hom, tensorIso_hom, Category.assoc, Category.assoc, Iso.inv_hom_id_assoc,
    ← tensor_comp_assoc, he, hs, schemeStructureTensor_scalar_mul]

/-- The strict-transform equation `u/v` in the ambient section ring of the second affine open. -/
def oldStrictSecondAmbientEquation (j : ℕ) :
    Γ(projectiveContactStage (k := k) (j + 1 + 1), (secondAffineOpen (j + 1)).1) :=
  secondSectionsEquiv (j + 1) oldRatio

/-- The strict transform's kernel ideal on the second affine open is generated by that equation. -/
theorem oldStrictIdeal_secondAffineOpen (j : ℕ) :
    (oldExceptionalStrictι (k := k) j).ker.ideal (secondAffineOpen (j + 1)) =
      Ideal.span {oldStrictSecondAmbientEquation j} := by
  let e := secondSectionsEquiv (k := k) (j + 1)
  have h : ((oldExceptionalStrictι (k := k) j).ker.ideal
      (secondAffineOpen (j + 1))).comap e.toRingHom = Ideal.span {oldRatio} := by
    change oldStrictSecondChartIdeal (k := k) j = _
    exact oldStrictSecondChartIdeal_eq_span j
  change (oldExceptionalStrictι (k := k) j).ker.ideal (secondAffineOpen (j + 1)) =
    Ideal.span {e oldRatio}
  calc
    _ = (((oldExceptionalStrictι (k := k) j).ker.ideal
        (secondAffineOpen (j + 1))).comap e.toRingHom).map e.toRingHom :=
      (Ideal.map_comap_of_surjective e.toRingHom e.surjective _).symm
    _ = (Ideal.span {oldRatio}).map e.toRingHom := by rw [h]
    _ = _ := by
      rw [Ideal.map_span, Set.image_singleton]
      rfl

/-- The actual ratio `u/v` is a regular element of the second Rees chart ring. -/
theorem oldRatio_regular : oldRatio (k := k) ∈ nonZeroDivisors (reesVChartRing k) := by
  apply mem_nonZeroDivisors_of_injective (f := vChartPolynomialEquiv (k := k))
    (vChartPolynomialEquiv (k := k)).injective
  rw [mem_nonZeroDivisors_iff_ne_zero]
  change vChartPolynomialEquiv (chartFraction centerIdeal (centerV (k := k)) centerU) ≠ 0
  rw [FrobeniusExceptionalCharts.vChartPolynomialEquiv_coordinate]
  exact Polynomial.X_ne_zero

theorem oldStrictSecondAmbientEquation_regular (j : ℕ) :
    oldStrictSecondAmbientEquation (k := k) j ∈
      nonZeroDivisors Γ(projectiveContactStage (k := k) (j + 1 + 1), (secondAffineOpen (j + 1)).1) := by
  let e := secondSectionsEquiv (k := k) (j + 1)
  apply mem_nonZeroDivisors_of_injective (f := e.symm) e.symm.injective
  change e.symm (e oldRatio) ∈ nonZeroDivisors (reesVChartRing k)
  simpa only [e.symm_apply_apply] using oldRatio_regular (k := k)

/-- The strict-transform equation in the second open scheme's own global sections. -/
def oldStrictSecondOpenEquation (j : ℕ) : Γ((secondAffineOpen (k := k) (j + 1)).1.toScheme, ⊤) :=
  gluedAffineEquation (secondAffineOpen (j + 1)) (oldStrictSecondAmbientEquation j)

/-- The normalized kernel frame of the strict transform of `E_j` on the second affine open. -/
def oldStrictSecondOpenFrame (j : ℕ) :
    _root_.SheafOfModules.unit (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf ≅
      (schemeModulePullback (secondAffineOpen (k := k) (j + 1)).1.ι).obj
        (schemeKernelIdeal (oldExceptionalStrictι j)) :=
  schemeKernelAffineOpenFrame (oldExceptionalStrictι j) (secondAffineOpen (j + 1))
    (oldStrictSecondAmbientEquation j) (oldStrictIdeal_secondAffineOpen j)
    (oldStrictSecondAmbientEquation_regular j)

theorem oldStrictSecondOpenFrame_inclusion (j : ℕ) :
    (oldStrictSecondOpenFrame (k := k) j).hom ≫
        pulledKernelInclusion (oldExceptionalStrictι j) (secondAffineOpen (j + 1)).1.ι =
      (schemeScalarEnd (Y := (secondAffineOpen (k := k) (j + 1)).1.toScheme)
          (oldStrictSecondOpenEquation j) :
        _root_.SheafOfModules.unit (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf ⟶
          _root_.SheafOfModules.unit (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf) :=
  schemeKernelAffineOpenFrame_inclusion (oldExceptionalStrictι j) (secondAffineOpen (j + 1))
    (oldStrictSecondAmbientEquation j) (oldStrictIdeal_secondAffineOpen j)
    (oldStrictSecondAmbientEquation_regular j)

/-- The second-chart blowdown sends the previous exceptional coordinate to `v * (u/v)`. -/
theorem secondStepExceptional_section_factorization :
    (secondCoordinateBlowdown (k := k)).appTop
        ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord) =
      (Scheme.ΓSpecIso (CommRingCat.of (reesVChartRing k))).inv vEquation *
        (Scheme.ΓSpecIso (CommRingCat.of (reesVChartRing k))).inv oldRatio := by
  have h := ConcreteCategory.congr_hom
    (Scheme.ΓSpecIso_inv_naturality
      (CommRingCat.ofHom (chartBaseMap (centerIdeal (k := k)) centerV))) (uCoord (k := k))
  change (Scheme.ΓSpecIso (CommRingCat.of (reesVChartRing k))).inv
      (chartBaseMap centerIdeal centerV uCoord) =
    (secondCoordinateBlowdown (k := k)).appTop
      ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord) at h
  rw [← vEquation_mul_oldRatio, map_mul] at h
  exact h.symm

/-- The pulled previous exceptional coordinate on the second open, through both original
section comparisons. -/
def oldTotalOpenEquation (j : ℕ) : Γ((secondAffineOpen (k := k) (j + 1)).1.toScheme, ⊤) :=
  (secondAffineOpen (j + 1)).1.topIso.inv
    (((secondStageChart (j + 1)).appIso ⊤).inv
      ((secondCoordinateBlowdown (k := k)).appTop
        ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord)))

theorem oldTotalOpenEquation_factorization (j : ℕ) :
    oldTotalOpenEquation (k := k) j =
      secondExceptionalOpenEquation (j + 1) * oldStrictSecondOpenEquation j := by
  change (secondAffineOpen (j + 1)).1.topIso.inv
      (((secondStageChart (j + 1)).appIso ⊤).inv
        ((secondCoordinateBlowdown (k := k)).appTop
          ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord))) =
    (secondAffineOpen (j + 1)).1.topIso.inv (((secondStageChart (j + 1)).appIso ⊤).inv
        ((Scheme.ΓSpecIso (CommRingCat.of (reesVChartRing k))).inv vEquation)) *
      (secondAffineOpen (j + 1)).1.topIso.inv (((secondStageChart (j + 1)).appIso ⊤).inv
        ((Scheme.ΓSpecIso (CommRingCat.of (reesVChartRing k))).inv oldRatio))
  rw [secondStepExceptional_section_factorization, map_mul, map_mul]

/-- The second-chart blowdown pulls the first-open equation of `E_j` to the total equation. -/
theorem secondOpenStepProjection_exceptionalEquation (j : ℕ) :
    (secondOpenStepProjection (k := k) (j + 1)).appTop
        (FrobeniusStrictTransformFirstChartTensorFrame.firstExceptionalOpenEquation j) =
      oldTotalOpenEquation j :=
  schemeOpenChartMap_section (secondStageChart (j + 1))
    (((projectiveProductInitial (k := k)).stage (j + 1)).chart) (secondCoordinateBlowdown (k := k))
    ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv uCoord)

/-- The multiplication of the two ideal inclusions of `E_{j+1}` and of the strict transform of
`E_j`, through the original structure-sheaf unit. -/
def exceptionalOldProduct (j : ℕ) :
    schemeKernelIdeal (stepExceptionalInclusionSucc (k := k) (j + 1)) ⊗
        schemeKernelIdeal (oldExceptionalStrictι (k := k) j) ⟶
      _root_.SheafOfModules.unit (projectiveContactStage (k := k) (j + 1 + 1)).ringCatSheaf :=
  (schemeKernelIdealι (stepExceptionalInclusionSucc (j + 1)) ⊗
    schemeKernelIdealι (oldExceptionalStrictι j)) ≫
    (schemeStructureTensorRightIso
      (_root_.SheafOfModules.unit (projectiveContactStage (k := k) (j + 1 + 1)).ringCatSheaf)).hom

/-- The tensor of the two kernel frames on the second affine open. -/
def exceptionalOldSecondOpenFrame (j : ℕ) :
    _root_.SheafOfModules.unit (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf ≅
      (schemeModulePullback (secondAffineOpen (k := k) (j + 1)).1.ι).obj
        (schemeKernelIdeal (stepExceptionalInclusionSucc (k := k) (j + 1)) ⊗
          schemeKernelIdeal (oldExceptionalStrictι (k := k) j)) :=
  (schemeStructureTensorRightIso
      (_root_.SheafOfModules.unit (secondAffineOpen (j + 1)).1.toScheme.ringCatSheaf)).symm ≪≫
    tensorIso (stepExceptionalSecondOpenFrame (j + 1)) (oldStrictSecondOpenFrame j) ≪≫
    (schemeModulePullbackTensorIso (secondAffineOpen (j + 1)).1.ι
      (schemeKernelIdeal (stepExceptionalInclusionSucc (j + 1)))
      (schemeKernelIdeal (oldExceptionalStrictι j))).symm

/-- The product inclusion multiplies by the pulled previous exceptional coordinate. -/
theorem exceptionalOldSecondOpenFrame_inclusion (j : ℕ) :
    (exceptionalOldSecondOpenFrame (k := k) j).hom ≫
      (schemeModulePullback (secondAffineOpen (j + 1)).1.ι).map (exceptionalOldProduct j) ≫
      (schemeModulePullbackUnitIso (secondAffineOpen (j + 1)).1.ι).hom =
        (schemeScalarEnd (Y := (secondAffineOpen (k := k) (j + 1)).1.toScheme)
            (oldTotalOpenEquation j) :
          _root_.SheafOfModules.unit (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf ⟶
            _root_.SheafOfModules.unit
              (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf) := by
  rw [oldTotalOpenEquation_factorization]
  exact tensorFrame_inclusion_generic (secondAffineOpen (k := k) (j + 1)).1.ι
    (schemeKernelIdealι (stepExceptionalInclusionSucc (j + 1)))
    (schemeKernelIdealι (oldExceptionalStrictι j))
    (stepExceptionalSecondOpenFrame (j + 1)) (oldStrictSecondOpenFrame j)
    (secondExceptionalOpenEquation (j + 1)) (oldStrictSecondOpenEquation j)
    (stepExceptionalSecondOpenFrame_inclusion (j + 1)) (oldStrictSecondOpenFrame_inclusion j)

/-- The frame of `E_j` on the first open of stage `j+1`, transported to the pulled kernel on the
second open of stage `j+2`. -/
def oldTotalSecondOpenFrame (j : ℕ) :
    _root_.SheafOfModules.unit (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf ≅
      (schemeModulePullback (secondAffineOpen (k := k) (j + 1)).1.ι).obj
        ((schemeModulePullback ((projectiveProductInitial (k := k)).stepProjection (j + 1))).obj
          (schemeKernelIdeal
            (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalInclusionSucc j))) :=
  schemeKernelFrameOnSquare
    (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalInclusionSucc j)
    (firstAffineOpen (j + 1)).1.ι (secondOpenStepProjection (j + 1)) (secondAffineOpen (j + 1)).1.ι
    ((projectiveProductInitial (k := k)).stepProjection (j + 1))
    (secondOpenStepProjection_square (j + 1))
    (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalFirstOpenFrame j)

/-- The transported frame's inclusion multiplies by the pulled previous exceptional coordinate. -/
theorem oldTotalSecondOpenFrame_inclusion (j : ℕ) :
    (oldTotalSecondOpenFrame (k := k) j).hom ≫
      (schemeModulePullback (secondAffineOpen (j + 1)).1.ι).map
        (pulledKernelInclusion
          (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalInclusionSucc j)
          ((projectiveProductInitial (k := k)).stepProjection (j + 1))) ≫
      (schemeModulePullbackUnitIso (secondAffineOpen (j + 1)).1.ι).hom =
        (schemeScalarEnd (Y := (secondAffineOpen (k := k) (j + 1)).1.toScheme)
            (oldTotalOpenEquation j) :
          _root_.SheafOfModules.unit (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf ⟶
            _root_.SheafOfModules.unit
              (secondAffineOpen (k := k) (j + 1)).1.toScheme.ringCatSheaf) := by
  have h := schemeKernelFrameOnSquare_inclusion
    (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalInclusionSucc (k := k) j)
    (firstAffineOpen (j + 1)).1.ι (secondOpenStepProjection (j + 1)) (secondAffineOpen (j + 1)).1.ι
    ((projectiveProductInitial (k := k)).stepProjection (j + 1))
    (secondOpenStepProjection_square (j + 1))
    (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalFirstOpenFrame j)
    (FrobeniusStrictTransformFirstChartTensorFrame.firstExceptionalOpenEquation j)
    (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalFirstOpenFrame_inclusion j)
  rw [secondOpenStepProjection_exceptionalEquation] at h
  -- `exact h` unfolds the frame through the sheaf-of-modules composition and times out;
  -- the congruence closure only has to see that the frame is literally the transported one.
  convert h using 3

/-- On the second affine open, the pulled ideal of `E_j` is the tensor of the ideals of `E_{j+1}`
and of the strict transform of `E_j`. -/
def oldTotalProductSecondOpenIso (j : ℕ) :
    (schemeModulePullback (secondAffineOpen (k := k) (j + 1)).1.ι).obj
        ((schemeModulePullback ((projectiveProductInitial (k := k)).stepProjection (j + 1))).obj
          (schemeKernelIdeal
            (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalInclusionSucc j))) ≅
      (schemeModulePullback (secondAffineOpen (k := k) (j + 1)).1.ι).obj
        (schemeKernelIdeal (stepExceptionalInclusionSucc (k := k) (j + 1)) ⊗
          schemeKernelIdeal (oldExceptionalStrictι (k := k) j)) :=
  (oldTotalSecondOpenFrame j).symm ≪≫ exceptionalOldSecondOpenFrame j

/-- This isomorphism preserves both original ambient ideal maps. -/
theorem oldTotalProductSecondOpenIso_inclusion (j : ℕ) :
    (oldTotalProductSecondOpenIso (k := k) j).hom ≫
      (schemeModulePullback (secondAffineOpen (j + 1)).1.ι).map (exceptionalOldProduct j) ≫
      (schemeModulePullbackUnitIso (secondAffineOpen (j + 1)).1.ι).hom =
    (schemeModulePullback (secondAffineOpen (j + 1)).1.ι).map
      (pulledKernelInclusion
        (FrobeniusStrictTransformFirstChartTensorFrame.stepExceptionalInclusionSucc j)
        ((projectiveProductInitial (k := k)).stepProjection (j + 1))) ≫
      (schemeModulePullbackUnitIso (secondAffineOpen (j + 1)).1.ι).hom := by
  have h1 := exceptionalOldSecondOpenFrame_inclusion (k := k) j
  have h2 := oldTotalSecondOpenFrame_inclusion (k := k) j
  unfold oldTotalProductSecondOpenIso
  rw [Iso.trans_hom, Iso.symm_hom, Category.assoc, h1, ← h2, Iso.inv_hom_id_assoc]

end KltDP.Examples.FrobeniusOldExceptionalSecondChartFrame
