import KltDP.Examples.FrobeniusFiberZeroInvertible
import KltDP.Examples.FrobeniusTowerFunctionField
import KltDP.Geometry.EffectiveCartierOfInvertibleIdeal

/-!
# The strict fibre of the origin contact tower as an effective Cartier divisor

On every stage `n` of the origin contact tower (`projectiveContactStage k n`), the ideal sheaf
`fiberStrictIdeal n = liftedFiberClosureIdeal (projectiveProductInitial k) n` of the strict transform
`F̃_n` of the fibre `y = 0` is locally principal with regular generators
(`fiberStrictIdeal_locallyPrincipalRegular`), by induction over the tower:

* stage `0`: BRIEF17's `horizontalFiber_ker_locallyPrincipalRegular` through lane A2's
  `fiberStrictIdeal_zero`;
* stage `n+1`: on the selected chart open the ideal is generated by the fibre coordinate
  (lane A2's `fiberStrictIdeal_firstAffineOpen`, regular by `fiberFirstAmbientEquation_regular`),
  on the second Rees open it is the unit ideal (`fiberStrictIdeal_secondAffineOpen`), and over the
  centre complement it is the transport of the stage-`n` ideal along the restricted blowdown
  (lane A2's pullback square `fiberStepOnPuncture_isPullback` together with the pinned
  `ker_ideal_of_isPullback_of_isOpenImmersion` and `ker_morphismRestrict_ideal`:
  `fiberStrictIdeal_puncture_transport`); the three opens cover the stage
  (accepted `strictProductStage_cover`).

Hence `fiberStrictDivisor n : CartierDivisor (projectiveContactStage k n)` (the generic
`cartierDivisorOfIdeal`) is an effective Cartier divisor with regular equations whose ideal-sheaf
data is `fiberStrictIdeal n` (so its zero scheme is the strict fibre `liftedFiberClosure`), and
`cartierPicardHom (fiberStrictDivisor n) = fiberPicardClass h n`, lane A2's class of `F̃_n`.
Bundle: `f29_fiber_strict_cartier`, with a universe check.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Opposite TopologicalSpace

universe u

namespace KltDP.Examples.FrobeniusFiberStrictCartier

open KltDP.Geometry
open FrobeniusGlobalBlowupStages FrobeniusFiberClosure FrobeniusFiberPicard FrobeniusFiberPuncture
  FrobeniusFiberTotalProduct FrobeniusStrictTransformProductCover
  FrobeniusStrictTransformStepPuncture FrobeniusStrictTransformInvertible
  FrobeniusStrictTransformSecondChartFrame FrobeniusFiberZeroInvertible
  FrobeniusTowerFunctionField FrobeniusGraphPicardClassIntegral

variable {k : Type u} [Field k]

local instance initialIntegral : IsIntegral (projectiveProductInitial (k := k)).carrier :=
  projectiveProduct_isIntegral

/-! ## Two ring-isomorphism transports -/

/-- Pulling a principal ideal back along the inverse of a ring isomorphism is the principal ideal
of the image of the generator. -/
theorem comap_inv_span {R S : CommRingCat.{u}} (i : R ≅ S) (g : R) :
    (Ideal.span {g}).comap i.inv.hom = Ideal.span {i.hom g} := by
  let σ := i.commRingCatIsoToRingEquiv
  change (Ideal.span {g}).comap (σ.symm : S →+* R) = Ideal.span {σ g}
  rw [Ideal.comap_coe, ← Ideal.map_symm, RingEquiv.symm_symm, Ideal.map_span, Set.image_singleton]

/-- Nonzerodivisors are preserved by ring isomorphisms. -/
theorem regular_of_iso {R S : CommRingCat.{u}} (i : R ≅ S) (g : R) (hg : g ∈ nonZeroDivisors R) :
    i.hom g ∈ nonZeroDivisors S := by
  let σ := i.commRingCatIsoToRingEquiv
  apply mem_nonZeroDivisors_of_injective (f := σ.symm) σ.symm.injective
  change σ.symm (σ g) ∈ nonZeroDivisors R
  simpa only [σ.symm_apply_apply] using hg

/-! ## The strict-fibre ideal sheaf and its charts -/

/-- The ideal sheaf of the strict fibre `F̃_n` on stage `n`. -/
abbrev fiberStrictIdeal (n : ℕ) : (projectiveContactStage (k := k) n).IdealSheafData :=
  liftedFiberClosureIdeal (projectiveProductInitial (k := k)) n

theorem fiberClosureInclusion_ker (n : ℕ) :
    (fiberClosureInclusion (projectiveProductInitial (k := k)) n).ker = fiberStrictIdeal n :=
  Scheme.IdealSheafData.ker_gluedTo _

/-- On the selected chart open of stage `n` the strict fibre is cut out by the fibre coordinate. -/
theorem fiberStrictIdeal_firstOpen (n : ℕ) :
    (fiberStrictIdeal (k := k) n).ideal (firstAffineOpen n) =
      Ideal.span {fiberFirstAmbientEquation n} := by
  rw [← fiberClosureInclusion_ker]
  exact fiberStrictIdeal_firstAffineOpen n

/-- On the second Rees open of the last blowup the strict fibre is absent. -/
theorem fiberStrictIdeal_secondOpen (n : ℕ) :
    (fiberStrictIdeal (k := k) (n + 1)).ideal (secondAffineOpen n) =
      Ideal.span {(1 : Γ(projectiveContactStage (k := k) (n + 1), (secondAffineOpen n).1))} := by
  rw [← fiberClosureInclusion_ker]
  exact fiberStrictIdeal_secondAffineOpen n

/-- The blowdown restricted over the centre complement (an isomorphism). -/
abbrev punctureIso (n : ℕ) :
    (nextPuncture (k := k) n).toScheme ⟶ (currentPuncture (k := k) n).toScheme :=
  (projectiveProductInitial (k := k)).stepProjection n ∣_ currentPuncture n

/-- Over the centre complement the strict-fibre ideal of stage `n+1` is the transport of the
strict-fibre ideal of stage `n` along the restricted blowdown. -/
theorem fiberStrictIdeal_puncture_transport (n : ℕ)
    (W : (nextPuncture (k := k) n).toScheme.affineOpens) :
    (fiberStrictIdeal (k := k) (n + 1)).ideal
        ⟨(nextPuncture n).ι ''ᵁ W.1, W.2.image_of_isOpenImmersion _⟩ =
      ((fiberStrictIdeal (k := k) n).ideal
          ⟨(currentPuncture n).ι ''ᵁ (punctureIso n ''ᵁ W.1),
            (W.2.image_of_isOpenImmersion (punctureIso n)).image_of_isOpenImmersion _⟩).comap
        ((punctureIso n).appIso W.1).inv.hom := by
  rw [← fiberClosureInclusion_ker, ← fiberClosureInclusion_ker,
    ← Scheme.ker_morphismRestrict_ideal _ (nextPuncture n) W,
    ← Scheme.ker_morphismRestrict_ideal _ (currentPuncture n)
      ⟨punctureIso n ''ᵁ W.1, W.2.image_of_isOpenImmersion _⟩]
  exact Scheme.ker_ideal_of_isPullback_of_isOpenImmersion _ _ _ _
    (fiberStepOnPuncture_isPullback n) W

/-- Over the centre complement, a principal regular chart of the stage-`n` ideal containing the
image of an affine open `W` gives a principal regular generator of the stage-`n+1` ideal on the
image of `W`. -/
theorem fiberStrictIdeal_puncture_chart (n : ℕ)
    (W : (nextPuncture (k := k) n).toScheme.affineOpens) [Nonempty W.1]
    (c : PrincipalRegularChart (projectiveContactStage (k := k) n) (fiberStrictIdeal n))
    (hle : (currentPuncture n).ι ''ᵁ (punctureIso n ''ᵁ W.1) ≤ c.openSet.1) :
    (fiberStrictIdeal (k := k) (n + 1)).ideal
        ⟨(nextPuncture n).ι ''ᵁ W.1, W.2.image_of_isOpenImmersion _⟩ =
      Ideal.span {((punctureIso n).appIso W.1).hom
        ((projectiveContactStage (k := k) n).presheaf.map (homOfLE hle).op c.generator)} ∧
    ((punctureIso n).appIso W.1).hom
        ((projectiveContactStage (k := k) n).presheaf.map (homOfLE hle).op c.generator) ∈
      nonZeroDivisors Γ(projectiveContactStage (k := k) (n + 1), (nextPuncture n).ι ''ᵁ W.1) := by
  haveI : Nonempty ((currentPuncture (k := k) n).ι ''ᵁ (punctureIso n ''ᵁ W.1) :
      (projectiveContactStage (k := k) n).Opens) := by
    obtain ⟨w⟩ := (inferInstance : Nonempty W.1)
    exact ⟨⟨(currentPuncture n).ι.base ((punctureIso n).base w.1),
      ⟨_, ⟨w.1, w.2, rfl⟩, rfl⟩⟩⟩
  have hspan := c.restrict_span_eq
    ⟨(currentPuncture n).ι ''ᵁ (punctureIso n ''ᵁ W.1),
      (W.2.image_of_isOpenImmersion (punctureIso n)).image_of_isOpenImmersion _⟩ hle
  have hreg := (c.restrict
    ⟨(currentPuncture n).ι ''ᵁ (punctureIso n ''ᵁ W.1),
      (W.2.image_of_isOpenImmersion (punctureIso n)).image_of_isOpenImmersion _⟩ hle).regular
  refine ⟨?_, regular_of_iso _ _ hreg⟩
  rw [fiberStrictIdeal_puncture_transport n W, hspan]
  exact comap_inv_span ((punctureIso n).appIso W.1) _

/-! ## Local principal regular generators on every stage -/

/-- The strict-fibre ideal sheaf is locally principal with regular generators on every stage. -/
theorem fiberStrictIdeal_locallyPrincipalRegular :
    ∀ n : ℕ, IdealLocallyPrincipalRegular (fiberStrictIdeal (k := k) n)
  | 0 => by
    change IdealLocallyPrincipalRegular (liftedFiberClosureIdeal (projectiveProductInitial (k := k)) 0)
    rw [fiberStrictIdeal_zero]
    exact horizontalFiber_ker_locallyPrincipalRegular
  | n + 1 => by
    intro x
    rcases strictProductStage_cover n x with hx | hx | hx
    · exact ⟨firstAffineOpen (n + 1), hx, fiberFirstAmbientEquation (n + 1),
        fiberStrictIdeal_firstOpen (n + 1), fiberFirstAmbientEquation_regular (n + 1)⟩
    · exact ⟨secondAffineOpen n, hx, 1, fiberStrictIdeal_secondOpen n, Submonoid.one_mem _⟩
    · obtain ⟨x', hx'⟩ : ∃ x' : (nextPuncture (k := k) n).toScheme, (nextPuncture n).ι.base x' = x := by
        have hr : x ∈ Set.range (nextPuncture (k := k) n).ι.base := by
          rw [Scheme.Opens.range_ι]
          exact hx
        exact hr
      obtain ⟨U', hxU', d, hd, hdr⟩ := fiberStrictIdeal_locallyPrincipalRegular n
        (((projectiveProductInitial (k := k)).stepProjection n).base x)
      have hmem : x' ∈ punctureIso n ⁻¹ᵁ ((currentPuncture (k := k) n).ι ⁻¹ᵁ U'.1) := by
        change (currentPuncture (k := k) n).ι.base ((punctureIso n).base x') ∈ U'.1
        rw [← Scheme.comp_base_apply, morphismRestrict_ι, Scheme.comp_base_apply]
        change ((projectiveProductInitial (k := k)).stepProjection n).base
          ((nextPuncture n).ι.base x') ∈ U'.1
        rw [hx']
        exact hxU'
      obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ :=
        (isBasis_affine_open (nextPuncture (k := k) n).toScheme).exists_subset_of_mem_open hmem
          (punctureIso n ⁻¹ᵁ ((currentPuncture (k := k) n).ι ⁻¹ᵁ U'.1)).2
      haveI : Nonempty W := ⟨⟨x', hxW⟩⟩
      have hle : (currentPuncture (k := k) n).ι ''ᵁ (punctureIso n ''ᵁ W) ≤ U'.1 := by
        rintro _ ⟨_, ⟨z, hz, rfl⟩, rfl⟩
        exact hWle hz
      obtain ⟨hspan, hreg⟩ := fiberStrictIdeal_puncture_chart n ⟨W, hW⟩
        ⟨U', ⟨⟨_, hxU'⟩⟩, d, hd, hdr⟩ hle
      exact ⟨⟨(nextPuncture n).ι ''ᵁ W, hW.image_of_isOpenImmersion _⟩, ⟨x', hxW, hx'⟩, _, hspan, hreg⟩

/-! ## The effective Cartier divisor -/

/-- The strict fibre `F̃_n` as an effective Cartier divisor on stage `n`. -/
def fiberStrictDivisor (n : ℕ) : CartierDivisor (projectiveContactStage (k := k) n) :=
  cartierDivisorOfIdeal _ (fiberStrictIdeal n) (fiberStrictIdeal_locallyPrincipalRegular n)

theorem fiberStrictDivisor_hasRegularEquations (n : ℕ) :
    HasRegularCartierEquations (projectiveContactStage (k := k) n) (fiberStrictDivisor n) :=
  cartierDivisorOfIdeal_hasRegularEquations _ _ _

/-- The zero scheme of the divisor is the strict fibre: its ideal-sheaf data is `fiberStrictIdeal n`. -/
theorem fiberStrictDivisor_idealData (n : ℕ) :
    effectiveCartierIdealDataOfRegularEquations (projectiveContactStage (k := k) n)
        (fiberStrictDivisor n) (fiberStrictDivisor_hasRegularEquations n) =
      fiberStrictIdeal n :=
  cartierDivisorOfIdeal_idealData _ _ _

/-- On the selected chart open of stage `n` the divisor is the class of the fibre coordinate. -/
theorem fiberStrictDivisor_restrict_firstOpen (n : ℕ) [hne : Nonempty (firstAffineOpen (k := k) n).1] :
    (cartierDivisorSheaf (projectiveContactStage (k := k) n)).val.map
        (homOfLE (show (firstAffineOpen (k := k) n).1 ≤ ⊤ from le_top)).op (fiberStrictDivisor n) =
      cartierEquationClassHom (projectiveContactStage (k := k) n) (firstAffineOpen n).1
        (Additive.ofMul (PrincipalRegularChart.equation (X := projectiveContactStage (k := k) n)
          (I := fiberStrictIdeal n) ⟨firstAffineOpen n, hne, fiberFirstAmbientEquation n,
            fiberStrictIdeal_firstOpen n, fiberFirstAmbientEquation_regular n⟩)) :=
  cartierDivisorOfIdeal_restrict_affine _ _ _ (firstAffineOpen n) _ _ _

/-- **`[F̃_n] = cartierPicardHom (fiberStrictDivisor n)`**: the Cartier class of the strict-fibre
divisor is lane A2's Picard class of `F̃_n`. -/
theorem fiberStrictDivisor_picard (n : ℕ) :
    cartierPicardHom (projectiveContactStage (k := k) n) (fiberStrictDivisor n) =
      fiberPicardClass (fiberKernel_zero_isInvertible (k := k)) n := by
  rw [fiberStrictDivisor, cartierDivisorOfIdeal_picard]
  rfl

end KltDP.Examples.FrobeniusFiberStrictCartier

namespace KltDP.Examples

open KltDP.Geometry FrobeniusGlobalBlowupStages FrobeniusFiberPicard FrobeniusFiberZeroInvertible
  FrobeniusFiberStrictCartier FrobeniusTowerFunctionField FrobeniusGraphPicardClassIntegral
  FrobeniusFiberClosure

local instance fiberStrictInitialIntegral' {k : Type u} [Field k] :
    IsIntegral (projectiveProductInitial (k := k)).carrier :=
  projectiveProduct_isIntegral

/-- Bundle: on every stage `n` of the origin contact tower the strict fibre `F̃_n` is an effective
Cartier divisor with regular equations, its zero scheme is the strict fibre (ideal-sheaf data
`liftedFiberClosureIdeal`), and its Cartier class is lane A2's Picard class of `F̃_n`. -/
theorem f29_fiber_strict_cartier (k : Type u) [Field k] :
    ∀ n : ℕ,
      HasRegularCartierEquations (projectiveContactStage (k := k) n) (fiberStrictDivisor n) ∧
      effectiveCartierIdealDataOfRegularEquations (projectiveContactStage (k := k) n)
          (fiberStrictDivisor n) (fiberStrictDivisor_hasRegularEquations n) =
        liftedFiberClosureIdeal (projectiveProductInitial (k := k)) n ∧
      cartierPicardHom (projectiveContactStage (k := k) n) (fiberStrictDivisor n) =
        fiberPicardClass (fiberKernel_zero_isInvertible (k := k)) n :=
  fun n => ⟨fiberStrictDivisor_hasRegularEquations n, fiberStrictDivisor_idealData n,
    fiberStrictDivisor_picard n⟩

/-- The bundle has exactly one universe parameter. -/
theorem f29_fiber_strict_cartier_universe_check (k : Type u) [Field k] : True := by
  have _ := f29_fiber_strict_cartier.{u} k
  trivial

end KltDP.Examples
