import KltDP.Examples.FrobeniusExceptionalSuccessorChart
import KltDP.Geometry.AffineBlowupExceptionalOverlap
import Mathlib.RingTheory.Localization.Ideal
import Mathlib.RingTheory.Coprime.Lemmas

/-!
# The residual curve on the original second Rees chart

The original first-chart parameter map extends to the actual homogeneous
overlap after inverting the parameter. Its composite with the original
second-chart restriction has kernel generated by `1-u^m*(u/v)`.

The proof uses the already established first-chart kernel, the two actual
overlap localizations, and the explicit coprimeness identity. It includes
`m=0`: the dense parameter still computes the entire schematic kernel.
The final factorization uses the actual base ring map and center ideal.
-/

noncomputable section

universe u

namespace KltDP.Examples.FrobeniusStrictTransformSecondChartAlgebra

open KltDP.Geometry.AffineBlowup
open FrobeniusBlowupContact FrobeniusBlowupSmooth
open FrobeniusExceptionalSuccessorChart

variable {k : Type u} [Field k]

/-- The original parameter ring with its parameter inverted. -/
abbrev puncturedParameterRing (k : Type u) [Field k] :=
  Localization.Away (Polynomial.X : Polynomial k)

/-- The original polynomial-to-localization map. -/
def puncturedParameterMap : Polynomial k →+* puncturedParameterRing k :=
  algebraMap (Polynomial k) (puncturedParameterRing k)

theorem puncturedParameterMap_injective :
    Function.Injective (puncturedParameterMap (k := k)) :=
  IsLocalization.injective (puncturedParameterRing k)
    (powers_le_nonZeroDivisors_of_noZeroDivisors Polynomial.X_ne_zero)

private theorem puncturedResidualMap_chartW_isUnit (m : ℕ) :
    IsUnit (((puncturedParameterMap (k := k)).comp (residualCurveMap m)) chartW) := by
  change IsUnit (algebraMap (Polynomial k) (puncturedParameterRing k)
    (residualCurveMap m chartW))
  rw [residualCurveMap_w, map_pow]
  exact (IsLocalization.Away.algebraMap_isUnit
    (S := puncturedParameterRing k) (Polynomial.X : Polynomial k)).pow m

/-- The original residual map extended through the actual first overlap restriction. -/
def residualOverlapMap (m : ℕ) :
    conormalOverlapRing (centerIdeal (k := k)) centerU centerV →+*
      puncturedParameterRing k := by
  letI := (conormalOverlapLeft (centerIdeal (k := k)) centerU centerV).toAlgebra
  letI : IsLocalization.Away (chartW (k := k))
      (conormalOverlapRing (centerIdeal (k := k)) centerU centerV) :=
    conormalOverlapLeft_isLocalization centerIdeal centerU centerV
  exact IsLocalization.Away.lift chartW (puncturedResidualMap_chartW_isUnit m)

/-- The extension agrees with the entire original first-chart map. -/
theorem residualOverlapMap_comp_left (m : ℕ) :
    (residualOverlapMap (k := k) m).comp
        (conormalOverlapLeft centerIdeal centerU centerV) =
      puncturedParameterMap.comp (residualCurveMap m) := by
  letI := (conormalOverlapLeft (centerIdeal (k := k)) centerU centerV).toAlgebra
  letI : IsLocalization.Away (chartW (k := k))
      (conormalOverlapRing (centerIdeal (k := k)) centerU centerV) :=
    conormalOverlapLeft_isLocalization centerIdeal centerU centerV
  exact IsLocalization.Away.lift_comp chartW (puncturedResidualMap_chartW_isUnit m)

/-- The original residual equation on the actual second chart. -/
def secondResidualEquation (m : ℕ) : reesVChartRing k :=
  1 - chartBaseMap (centerIdeal (k := k)) centerV uCoord ^ m * oldRatio (k := k)

/-- In the original coordinates `v,u/v`, this is `1-v^m*(u/v)^(m+1)`. -/
theorem secondResidualEquation_eq (m : ℕ) :
    secondResidualEquation (k := k) m =
      1 - vEquation (k := k) ^ m * oldRatio (k := k) ^ (m + 1) := by
  rw [secondResidualEquation, ← vEquation_mul_oldRatio]
  ring

/-- The original second-chart map is obtained by the actual overlap restriction. -/
def secondResidualMap (m : ℕ) : reesVChartRing k →+* puncturedParameterRing k :=
  (residualOverlapMap m).comp (conormalOverlapRight centerIdeal centerU centerV)

/-- On the actual overlap the second equation is `(u/v)` times the first equation. -/
theorem secondResidualEquation_overlap (m : ℕ) :
    conormalOverlapRight (centerIdeal (k := k)) centerU centerV
        (secondResidualEquation (k := k) m) =
      conormalOverlapRight (centerIdeal (k := k)) centerU centerV (oldRatio (k := k)) *
        conormalOverlapLeft (centerIdeal (k := k)) centerU centerV (residualEquation m) := by
  have hu : conormalOverlapRight (centerIdeal (k := k)) centerU centerV
      (chartBaseMap (centerIdeal (k := k)) centerV (uCoord (k := k))) =
        conormalOverlapLeft (centerIdeal (k := k)) centerU centerV (chartU (k := k)) :=
    (conormalOverlapRight_baseMap centerIdeal centerU centerV uCoord).trans
      (conormalOverlapLeft_baseMap centerIdeal centerU centerV uCoord).symm
  have hr : conormalOverlapLeft (centerIdeal (k := k)) centerU centerV (chartW (k := k)) *
      conormalOverlapRight (centerIdeal (k := k)) centerU centerV (oldRatio (k := k)) = 1 :=
    conormalOverlap_chartFractions_mul centerIdeal centerU centerV
  rw [secondResidualEquation, map_sub, map_one, map_mul, map_pow, hu,
    residualEquation, map_sub, map_pow, ← hr]
  ring

/-- The localization kernel is the extension of the already proved first-chart kernel. -/
theorem residualOverlapMap_ker (m : ℕ) :
    RingHom.ker (residualOverlapMap (k := k) m) =
      Ideal.span {conormalOverlapLeft (centerIdeal (k := k)) centerU centerV
        (residualEquation m)} := by
  letI := (conormalOverlapLeft (centerIdeal (k := k)) centerU centerV).toAlgebra
  letI : IsLocalization.Away (chartW (k := k))
      (conormalOverlapRing (centerIdeal (k := k)) centerU centerV) :=
    conormalOverlapLeft_isLocalization centerIdeal centerU centerV
  have hc : Ideal.comap (conormalOverlapLeft (centerIdeal (k := k)) centerU centerV)
      (RingHom.ker (residualOverlapMap (k := k) m)) =
        Ideal.span {residualEquation m} := by
    rw [RingHom.comap_ker, residualOverlapMap_comp_left,
      RingHom.ker_comp_of_injective _ puncturedParameterMap_injective, residualCurveMap_ker]
  have h := IsLocalization.map_comap (Submonoid.powers (chartW (k := k)))
    (conormalOverlapRing (centerIdeal (k := k)) centerU centerV)
    (RingHom.ker (residualOverlapMap (k := k) m))
  change Ideal.map (conormalOverlapLeft (centerIdeal (k := k)) centerU centerV)
      (Ideal.comap (conormalOverlapLeft (centerIdeal (k := k)) centerU centerV)
        (RingHom.ker (residualOverlapMap (k := k) m))) = _ at h
  rw [hc, Ideal.map_span, Set.image_singleton] at h
  exact h.symm

/-- No component is lost on contraction from the actual second-chart overlap. -/
theorem secondResidualEquation_isCoprime (m : ℕ) :
    IsCoprime (secondResidualEquation (k := k) m) (oldRatio (k := k)) := by
  refine ⟨1, chartBaseMap (centerIdeal (k := k)) centerV uCoord ^ m, ?_⟩
  rw [secondResidualEquation]
  ring

private theorem secondResidualEquation_contract (m : ℕ) :
    Ideal.comap (conormalOverlapRight (centerIdeal (k := k)) centerU centerV)
        (Ideal.map (conormalOverlapRight (centerIdeal (k := k)) centerU centerV)
          (Ideal.span {secondResidualEquation (k := k) m})) =
      Ideal.span {secondResidualEquation m} := by
  letI := (conormalOverlapRight (centerIdeal (k := k)) centerU centerV).toAlgebra
  letI : IsLocalization.Away (oldRatio (k := k))
      (conormalOverlapRing (centerIdeal (k := k)) centerU centerV) :=
    conormalOverlapRight_isLocalization centerIdeal centerU centerV
  refine le_antisymm ?_ Ideal.le_comap_map
  intro x hx
  change algebraMap (reesVChartRing k)
      (conormalOverlapRing (centerIdeal (k := k)) centerU centerV) x ∈
    Ideal.map (algebraMap (reesVChartRing k)
      (conormalOverlapRing (centerIdeal (k := k)) centerU centerV))
      (Ideal.span {secondResidualEquation m}) at hx
  obtain ⟨s, hs, hx⟩ := (IsLocalization.algebraMap_mem_map_algebraMap_iff
    (Submonoid.powers (oldRatio (k := k)))
    (conormalOverlapRing (centerIdeal (k := k)) centerU centerV)
    (Ideal.span {secondResidualEquation m}) x).mp hx
  obtain ⟨j, hj⟩ := hs
  rw [← hj] at hx
  exact Ideal.mem_span_singleton.mpr
    ((secondResidualEquation_isCoprime m).pow_right.dvd_of_dvd_mul_left
      (Ideal.mem_span_singleton.mp hx))

/-- The exact kernel of the original dense residual parameter map on the second chart. -/
theorem secondResidualMap_ker (m : ℕ) :
    RingHom.ker (secondResidualMap (k := k) m) =
      Ideal.span {secondResidualEquation m} := by
  have hr : IsUnit
      (conormalOverlapRight (centerIdeal (k := k)) centerU centerV (oldRatio (k := k))) := by
    letI := (conormalOverlapRight (centerIdeal (k := k)) centerU centerV).toAlgebra
    letI : IsLocalization.Away (oldRatio (k := k))
        (conormalOverlapRing (centerIdeal (k := k)) centerU centerV) :=
      conormalOverlapRight_isLocalization centerIdeal centerU centerV
    exact IsLocalization.Away.algebraMap_isUnit (oldRatio (k := k))
  have he : Ideal.map (conormalOverlapRight (centerIdeal (k := k)) centerU centerV)
      (Ideal.span {secondResidualEquation (k := k) m}) =
        Ideal.span {conormalOverlapLeft (centerIdeal (k := k)) centerU centerV
          (residualEquation m)} := by
    rw [Ideal.map_span, Set.image_singleton, secondResidualEquation_overlap,
      Ideal.span_singleton_mul_left_unit hr]
  rw [secondResidualMap, ← RingHom.comap_ker, residualOverlapMap_ker, ← he]
  exact secondResidualEquation_contract m

/-- The actual pullback of the original equation factors by the actual exceptional equation. -/
theorem secondTotalEquation_factorization (m : ℕ) :
    chartBaseMap (centerIdeal (k := k)) centerV (vCoord (k := k) - uCoord (k := k) ^ (m + 1)) =
      vEquation (k := k) * secondResidualEquation (k := k) m := by
  rw [map_sub, map_pow, secondResidualEquation, pow_succ,
    ← vEquation_mul_oldRatio]
  change vEquation (k := k) - (vEquation (k := k) * oldRatio (k := k)) ^ m *
    (vEquation (k := k) * oldRatio (k := k)) = _
  ring

/-- The factorization is an equality of the original second-chart ideals. -/
theorem secondTotalIdeal_factorization (m : ℕ) :
    Ideal.map (chartBaseMap (centerIdeal (k := k)) centerV)
        (Ideal.span {vCoord (k := k) - uCoord (k := k) ^ (m + 1)}) =
      chartCenterIdeal (centerIdeal (k := k)) centerV *
        RingHom.ker (secondResidualMap (k := k) m) := by
  rw [chartCenterIdeal, map_chartBaseMap_ideal, secondResidualMap_ker,
    Ideal.map_span, Set.image_singleton, Ideal.span_singleton_mul_span_singleton]
  exact congrArg (fun z : reesVChartRing k => Ideal.span {z})
    (secondTotalEquation_factorization m)

end KltDP.Examples.FrobeniusStrictTransformSecondChartAlgebra
