import KltDP.Examples.FrobeniusDiscrepancyStalkParameters
import KltDP.Geometry.PrimeCurveClosedOrGeneric

/-!
# Original candidate-support parameters at every point

The closed and generic cases are exhaustive on the actual prime-curve
scheme. Their original inclusion kernels are generated by a regular
parameter; the parameter itself, or it together with one companion,
generates the actual ambient maximal ideal. The ambient stalk is regular.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory IsLocalRing

universe u

namespace KltDP.Examples.FrobeniusDiscrepancyBounds

open KltDP.Geometry KltDP.Geometry.NormalProjectiveSurface
open FrobeniusMultiCentreSurface FrobeniusMultiCentreCanonicalWeilRepresentatives
open FrobeniusMultiCentreGraphExceptionalPairing

variable {k : Type u} [Field k] [IsAlgClosed k]
    (q n : ℕ) [Fact (q + 1).Prime] [CharP k (q + 1)]
    (a : Fin n → k) (ha : Function.Injective a)
    (hproj : IsProjectiveOverField (multiStructure (q + 1) n a))

/-- All-point local geometric parameter clause for the original candidate support. -/
theorem candidate_support_all_stalk_parameters
    (C : (sourceSurface q n a ha hproj).PrimeCurve)
    (hC : C ∈ (candidate q n a ha hproj).support) (y : C.toScheme) :
    RegularPoint (sourceSurface q n a ha hproj).toScheme (C.inclusion.base y) ∧
    ∃ f : (sourceSurface q n a ha hproj).toScheme.presheaf.stalk (C.inclusion.base y),
      RingHom.ker (C.inclusion.stalkMap y).hom = Ideal.span {f} ∧
      f ∉ (maximalIdeal
        ((sourceSurface q n a ha hproj).toScheme.presheaf.stalk (C.inclusion.base y))) ^ 2 ∧
      (Ideal.span {f} = maximalIdeal
          ((sourceSurface q n a ha hproj).toScheme.presheaf.stalk (C.inclusion.base y)) ∨
        ∃ g, Ideal.span {f, g} = maximalIdeal
          ((sourceSurface q n a ha hproj).toScheme.presheaf.stalk (C.inclusion.base y))) := by
  refine ⟨multiSurfaceSurface_regularPoints (q + 1) n a ha hproj (C.inclusion.base y), ?_⟩
  rcases C.isClosed_or_eq_genericPoint y with hy | rfl
  · obtain ⟨f, g, hspan, hker, hf⟩ :=
      candidate_support_stalk_parameters q n a ha hproj C hC y hy
    exact ⟨f, hker, hf, Or.inr ⟨g, hspan⟩⟩
  · obtain ⟨f, hspan, hker, hf⟩ := C.exists_generic_stalk_parameter
    exact ⟨f, hker, hf, Or.inl hspan⟩

end KltDP.Examples.FrobeniusDiscrepancyBounds
