import KltDP.Examples.FrobeniusTowerSecondChart

/-!
# The two Rees charts and the puncture cover the last stage

The centre ideal is generated by `u`, `v` (`centerGenerators_span`), so the accepted
`iSup_chartOpen_generators` covers the affine blowup by the two Rees chart opens, which are the ranges of the
chart immersions (`Proj.opensRange_awayι`). With the accepted `pieces_cover` of the point-blowup gluing this
covers the stage-`n+1` tower by the selected chart, the second chart `secondChart A n` and the step puncture
(`stage_succ_cover`) — the atlas on which the BRIEF8 constructor `cartierDivisorOfEquations` would build the
Cartier divisors of the last blowup.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Opposite TopologicalSpace

universe u

namespace KltDP.Examples.FrobeniusTowerChartCover

open KltDP.Geometry KltDP.Geometry.AffineBlowup FrobeniusBlowupContact FrobeniusBlowupChartIteration
  FrobeniusGlobalBlowupStages FrobeniusStageComplement FrobeniusStageComplement.PlaneChartedScheme
  FrobeniusTowerFunctionField.PlaneChartedScheme FrobeniusTowerSecondChart
  FrobeniusTowerSecondChart.PlaneChartedScheme

variable {k : Type u} [Field k]

/-- The two generators `u`, `v` of the centre ideal. -/
def centerGenerators : Fin 2 → centerIdeal (k := k) := ![centerU, centerV]

theorem range_centerGenerators :
    Set.range (fun i => (centerGenerators (k := k) i : planeRing k)) = {uCoord, vCoord} := by
  ext r
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i
    · exact Or.inl rfl
    · exact Or.inr rfl
  · rintro (rfl | rfl)
    · exact ⟨0, rfl⟩
    · exact ⟨1, rfl⟩

theorem centerGenerators_span :
    Ideal.span (Set.range (fun i => (centerGenerators (k := k) i : planeRing k))) = centerIdeal := by
  rw [range_centerGenerators]
  rfl

/-- Ranges of equal open immersions agree. -/
theorem opensRange_congr {X Y : Scheme.{u}} {f g : X ⟶ Y} [IsOpenImmersion f] [IsOpenImmersion g]
    (hfg : f = g) : f.opensRange = g.opensRange := by
  subst hfg
  rfl

/-- The range of a Rees chart immersion is its chart open. -/
theorem chartι_opensRange (a : centerIdeal (k := k)) :
    (chartι centerIdeal a).opensRange = chartOpen centerIdeal a :=
  Proj.opensRange_awayι _ _ _ _

/-- Every point of the affine blowup of the centre lies on one of the two Rees charts. -/
theorem affineBlowup_cover (x : AffineBlowup.scheme (centerIdeal (k := k))) :
    x ∈ (chartι centerIdeal centerU).opensRange ∨ x ∈ (chartι centerIdeal centerV).opensRange := by
  have hx : x ∈ ⨆ i, chartOpen centerIdeal (centerGenerators (k := k) i) := by
    rw [iSup_chartOpen_generators centerIdeal centerGenerators centerGenerators_span]
    trivial
  obtain ⟨i, hi⟩ := Opens.mem_iSup.mp hx
  fin_cases i
  · left
    rw [chartι_opensRange]
    exact hi
  · right
    rw [chartι_opensRange]
    exact hi

namespace PlaneChartedScheme

variable (A : PlaneChartedScheme k) [IsIntegral A.carrier] (n : ℕ)

omit [IsIntegral A.carrier] in
theorem selectedChart_opensRange :
    (A.stage (n + 1)).chart.opensRange =
      (chartι centerIdeal centerU ≫ (A.stage n).nextAffineBlowup).opensRange := by
  calc (A.stage (n + 1)).chart.opensRange
      = (coordinateChartIso.hom ≫ (chartι centerIdeal centerU ≫ (A.stage n).nextAffineBlowup)).opensRange :=
        opensRange_congr (Category.assoc _ _ _)
    _ = _ := Scheme.Hom.opensRange_comp_of_isIso _ _

omit [IsIntegral A.carrier] in
theorem secondChart_opensRange :
    (secondChart A n).opensRange =
      (chartι centerIdeal centerV ≫ (A.stage n).nextAffineBlowup).opensRange := by
  calc (secondChart A n).opensRange
      = (vChartIso.hom ≫ (chartι centerIdeal centerV ≫ (A.stage n).nextAffineBlowup)).opensRange :=
        opensRange_congr rfl
    _ = _ := Scheme.Hom.opensRange_comp_of_isIso _ _

omit [IsIntegral A.carrier] in
/-- The stage-`n+1` tower is covered by the two Rees charts of the last blowup and the step puncture. -/
theorem stage_succ_cover (x : (A.stage (n + 1)).carrier) :
    x ∈ (A.stage (n + 1)).chart.opensRange ∨ x ∈ (secondChart A n).opensRange ∨
      x ∈ (A.stage n).nextProjection ⁻¹ᵁ initialPuncture (A.stage n) := by
  letI : (originPoint (k := k)).asIdeal.IsMaximal :=
    FrobeniusBlowupChartIteration.centerIdeal_isMaximal
  rcases PointBlowupGluing.pieces_cover (A.stage n).chart (originPoint (k := k))
    (A.stage n).center_closed x with ⟨a, rfl⟩ | ⟨b, rfl⟩
  · rcases affineBlowup_cover a with h | h
    · obtain ⟨y, rfl⟩ : ∃ y, (chartι centerIdeal centerU).base y = a := h
      left
      rw [selectedChart_opensRange]
      show ∃ z, (chartι centerIdeal centerU ≫ (A.stage n).nextAffineBlowup).base z = _
      exact ⟨y, rfl⟩
    · obtain ⟨y, rfl⟩ : ∃ y, (chartι centerIdeal centerV).base y = a := h
      right
      left
      rw [secondChart_opensRange]
      show ∃ z, (chartι centerIdeal centerV ≫ (A.stage n).nextAffineBlowup).base z = _
      exact ⟨y, rfl⟩
  · right
    right
    have hb : (PointBlowupGluing.complementι (A.stage n).chart (originPoint (k := k))
        (A.stage n).center_closed).base b ∈
          Set.range (PointBlowupGluing.complementι (A.stage n).chart (originPoint (k := k))
            (A.stage n).center_closed).base := ⟨b, rfl⟩
    rw [PointBlowupGluing.range_complementι] at hb
    exact hb

end PlaneChartedScheme

end KltDP.Examples.FrobeniusTowerChartCover

namespace KltDP.Examples

open FrobeniusGlobalBlowupStages FrobeniusStageComplement.PlaneChartedScheme
  FrobeniusTowerSecondChart.PlaneChartedScheme FrobeniusTowerChartCover.PlaneChartedScheme

/-- Bundle: the atlas of the last blowup covers the stage-`n+1` tower. -/
theorem f29_tower_last_blowup_cover {k : Type u} [Field k] (A : PlaneChartedScheme k) (n : ℕ) :
    ∀ x : (A.stage (n + 1)).carrier,
      x ∈ (A.stage (n + 1)).chart.opensRange ∨ x ∈ (secondChart A n).opensRange ∨
        x ∈ (A.stage n).nextProjection ⁻¹ᵁ initialPuncture (A.stage n) :=
  stage_succ_cover A n

/-- The bundle has exactly one universe parameter. -/
theorem f29_tower_last_blowup_cover_universe_check {k : Type u} [Field k]
    (A : PlaneChartedScheme k) : True := by
  have _ := f29_tower_last_blowup_cover.{u} A 0
  trivial

end KltDP.Examples
