import KltDP.Examples.FrobeniusGraphZeroCartier
import KltDP.Examples.FrobeniusTowerFiberPullback

/-!
# The total transform `π_N^*Γ` of the graph on the origin contact tower

Item 2 of BRIEF38, and the direct analogue of the accepted `totalFiberDivisor` for the graph.

The composite blowdown `π_N = between (Nat.zero_le N)` sends the generic point to the generic point
(accepted instance `between_genericPointPreserving`), and BRIEF37's `graphZeroDivisor p` is an
effective Cartier divisor of the graph `v = u^p` on `P¹ × P¹` **with regular equations**
(`graphZeroDivisor_hasRegularEquations`) — the input that did not exist before BRIEF37 and that the
generic `pullbackDivisor` consumes. Hence

  `totalGraphDivisor N p = π_N^*Γ`,

with regular equations and ideal-sheaf data `totalGraphIdeal N p`, generated on an affine open inside
the preimage of a regular chart by the pulled-back coefficient (`totalGraphIdeal_ideal`).

Stage `0` of the tower is the projective product itself (`stage 0 = A` by definition), so
`graphZeroDivisor p` is already a divisor on `projectiveContactStage 0`.

The two chart computations of the pulled-back generator are BRIEF37's `between_appLE_graph_first'`
and `between_appLE_graph_second'`; combining them with this module and the stage divisors of
`FrobeniusGraphStrictCartier` is the remaining step (`π^*Γ = B̃ + Σ_j E_j^tot`), which needs the
three-case induction and is not performed here.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits Opposite TopologicalSpace

universe u

namespace KltDP.Examples.FrobeniusTowerGraphPullback

open KltDP.Geometry
open FrobeniusProjectivePoints
open FrobeniusGlobalBlowupStages FrobeniusExceptionalFinalConfiguration
open FrobeniusGraphPicardClassIntegral
open FrobeniusGraphZeroCartier
open FrobeniusTowerFiberPullback

variable {k : Type u} [Field k]

local instance graphPullbackInitialIntegral :
    IsIntegral (projectiveProductInitial (k := k)).carrier :=
  projectiveProduct_isIntegral

/-- **The total transform `π_N^*Γ` of the graph on stage `N`, as an effective Cartier divisor.** -/
def totalGraphDivisor (N p : ℕ) : CartierDivisor (projectiveContactStage (k := k) N) :=
  pullbackDivisor (between (projectiveProductInitial (k := k)) (Nat.zero_le N))
    (graphZeroDivisor p) (graphZeroDivisor_hasRegularEquations p)

theorem totalGraphDivisor_hasRegularEquations (N p : ℕ) :
    HasRegularCartierEquations _ (totalGraphDivisor (k := k) N p) :=
  pullbackDivisor_hasRegularEquations _ _ _

/-- The ideal-sheaf data of the total transform of the graph. -/
def totalGraphIdeal (N p : ℕ) : (projectiveContactStage (k := k) N).IdealSheafData :=
  pullbackIdealData (between (projectiveProductInitial (k := k)) (Nat.zero_le N))
    (graphZeroDivisor p) (graphZeroDivisor_hasRegularEquations p)

theorem totalGraphIdeal_eq_idealData (N p : ℕ) :
    totalGraphIdeal (k := k) N p =
      effectiveCartierIdealDataOfRegularEquations _ (totalGraphDivisor N p)
        (totalGraphDivisor_hasRegularEquations N p) := rfl

/-- On an affine open inside the preimage of a regular chart `c` of the graph, the ideal of the
total transform is generated by the pulled-back coefficient. -/
theorem totalGraphIdeal_ideal (N p : ℕ)
    (c : RegularCartierEquationChart (projectiveContactStage (k := k) 0) (graphZeroDivisor p))
    (W : (projectiveContactStage (k := k) N).affineOpens) [Nonempty W.1]
    (hW : W.1 ≤ between (projectiveProductInitial (k := k)) (Nat.zero_le N) ⁻¹ᵁ c.chart.openSet) :
    (totalGraphIdeal N p).ideal W =
      Ideal.span {(between (projectiveProductInitial (k := k)) (Nat.zero_le N)).appLE
        c.chart.openSet W.1 hW c.coefficient} :=
  pullbackIdealData_ideal _ _ _ c W hW

end KltDP.Examples.FrobeniusTowerGraphPullback
