import KltDP.Examples.FrobeniusStrictTransformFirstChartTensorFrame
import KltDP.Examples.FrobeniusStrictTransformSecondChartTensorFrame
import KltDP.Examples.FrobeniusStrictTransformProductCover
import KltDP.Examples.FrobeniusTowerFunctionField
import KltDP.Geometry.EffectiveCartierOfInvertibleIdeal

/-!
# The newest exceptional curve of the origin contact tower as an effective Cartier divisor

On stage `n+1` of the origin contact tower the ideal sheaf `stepExceptionalIdeal n` of the newest
exceptional curve `P = E_n` (the kernel of the accepted centre-fibre inclusion
`stepExceptionalInclusion n`) is locally principal with regular generators
(`stepExceptionalIdeal_locallyPrincipalRegular`): on the selected chart open it is generated by the
exceptional coordinate (accepted `stepExceptionalIdeal_firstAffineOpen`), on the second Rees open by
the second exceptional equation (accepted `stepExceptionalIdeal_secondAffineOpen`), and on every
affine open inside the centre complement it is the unit ideal, because every point of `P` lies
over the centre (accepted `range_globalCenterFiberι`) and the centre is not in the puncture
(`stepExceptionalIdeal_puncture`); the three opens cover the stage (`strictProductStage_cover`).

Hence `stepExceptionalDivisor n : CartierDivisor (projectiveContactStage k (n+1))` (generic
`cartierDivisorOfIdeal`) is an effective Cartier divisor with regular equations, its ideal-sheaf
data is `stepExceptionalIdeal n` (zero scheme: the glued closed subscheme of the kernel of `P`), and
`cartierPicardHom (stepExceptionalDivisor n) = −[gluedKernelLine (stepExceptionalIdeal n)]`.

Not proved here: the identification of this class with the accepted `stepExceptionalPicardClass n`
(`−[stepExceptionalIdealLine n]`), which needs the comparison
`schemeKernelIdeal f ≅ schemeKernelIdeal f.ker.gluedTo` for the closed immersion
`f = stepExceptionalInclusion n` (available only as a private construction in the accepted
`FrobeniusStrictTransformProductKernel`/`…ClassesTower`).
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Opposite TopologicalSpace

universe u

namespace KltDP.Examples.FrobeniusExceptionalCartier

open KltDP.Geometry
open FrobeniusGlobalBlowupStages FrobeniusStrictTransformProductKernel
  FrobeniusStrictTransformFirstChartTensorFrame FrobeniusStrictTransformSecondChartTensorFrame
  FrobeniusStrictTransformProductCover FrobeniusStrictTransformStepPuncture
  FrobeniusStrictTransformInvertible FrobeniusStrictTransformSecondChartFrame
  FrobeniusTowerFunctionField FrobeniusGraphPicardClassIntegral FrobeniusStageComplement
  FrobeniusBlowupChartIteration

variable {k : Type u} [Field k]

local instance initialIntegral : IsIntegral (projectiveProductInitial (k := k)).carrier :=
  projectiveProduct_isIntegral

local instance originMaximal : (originPoint (k := k)).asIdeal.IsMaximal :=
  FrobeniusBlowupChartIteration.centerIdeal_isMaximal

/-- The ideal sheaf of the newest exceptional curve `P = E_n` on stage `n+1`. -/
abbrev stepExceptionalIdeal (n : ℕ) : (projectiveContactStage (k := k) (n + 1)).IdealSheafData :=
  (stepExceptionalInclusion (k := k) n).ker

/-- On the selected chart open, `P` is cut out by the exceptional coordinate. -/
theorem stepExceptionalIdeal_firstOpen (n : ℕ) :
    (stepExceptionalIdeal (k := k) n).ideal (firstAffineOpen (n + 1)) =
      Ideal.span {firstExceptionalAmbientEquation n} :=
  stepExceptionalIdeal_firstAffineOpen n

/-- On the second Rees open, `P` is cut out by the second exceptional equation. -/
theorem stepExceptionalIdeal_secondOpen (n : ℕ) :
    (stepExceptionalIdeal (k := k) n).ideal (secondAffineOpen n) =
      Ideal.span {secondExceptionalAmbientEquation n} :=
  stepExceptionalIdeal_secondAffineOpen n

/-- Every point of `P` lies over the centre of the last blowup. -/
theorem stepExceptional_over_center (n : ℕ) (x : projectiveContactStage (k := k) (n + 1))
    (hx : x ∈ Set.range (stepExceptionalInclusion (k := k) n).base) :
    ((projectiveProductInitial (k := k)).stepProjection n).base x =
      ((projectiveProductInitial (k := k)).stage n).chart.base (originPoint (k := k)) := by
  rw [PointBlowupGluing.range_globalCenterFiberι] at hx
  exact hx

/-- The centre is not in the centre complement. -/
theorem center_not_mem_currentPuncture (n : ℕ) :
    ((projectiveProductInitial (k := k)).stage n).chart.base (originPoint (k := k)) ∉
      currentPuncture (k := k) n := by
  intro h
  exact h (Set.mem_singleton _)

/-- `P` misses every open inside the centre complement. -/
theorem stepExceptional_preimage_puncture (n : ℕ)
    (W : (projectiveContactStage (k := k) (n + 1)).Opens) (hW : W ≤ nextPuncture n) :
    stepExceptionalInclusion (k := k) n ⁻¹ᵁ W = ⊥ := by
  apply Opens.ext
  rw [Opens.coe_bot]
  refine Set.eq_empty_iff_forall_not_mem.mpr fun y hy => ?_
  have hx : (stepExceptionalInclusion (k := k) n).base y ∈ nextPuncture n := hW hy
  have hc := stepExceptional_over_center n _ ⟨y, rfl⟩
  apply center_not_mem_currentPuncture (k := k) n
  rw [← hc]
  exact hx

/-- (generic) A quasi-compact morphism with empty preimage of an affine open has the unit kernel
ideal there. -/
theorem ker_ideal_eq_top_of_preimage_eq_bot {S T : Scheme.{u}} (f : S ⟶ T) [QuasiCompact f]
    (W : T.affineOpens) (h : f ⁻¹ᵁ W.1 = ⊥) :
    f.ker.ideal W = Ideal.span {(1 : Γ(T, W.1))} := by
  rw [Ideal.span_singleton_one, Scheme.Hom.ker_apply, Ideal.eq_top_iff_one, RingHom.mem_ker]
  haveI : Subsingleton Γ(S, f ⁻¹ᵁ W.1) :=
    CommRingCat.subsingleton_of_isTerminal (S.sheaf.isTerminalOfEqEmpty h)
  exact Subsingleton.elim _ _

/-- On every affine open inside the centre complement the ideal of `P` is the unit ideal. -/
theorem stepExceptionalIdeal_puncture (n : ℕ)
    (W : (projectiveContactStage (k := k) (n + 1)).affineOpens) (hW : W.1 ≤ nextPuncture n) :
    (stepExceptionalIdeal (k := k) n).ideal W =
      Ideal.span {(1 : Γ(projectiveContactStage (k := k) (n + 1), W.1))} :=
  ker_ideal_eq_top_of_preimage_eq_bot (stepExceptionalInclusion (k := k) n) W
    (stepExceptional_preimage_puncture n W.1 hW)

/-- The ideal sheaf of `P` is locally principal with regular generators. -/
theorem stepExceptionalIdeal_locallyPrincipalRegular (n : ℕ) :
    IdealLocallyPrincipalRegular (stepExceptionalIdeal (k := k) n) := by
  intro x
  rcases strictProductStage_cover n x with hx | hx | hx
  · exact ⟨firstAffineOpen (n + 1), hx, _, stepExceptionalIdeal_firstOpen n,
      firstExceptionalAmbientEquation_regular n⟩
  · exact ⟨secondAffineOpen n, hx, _, stepExceptionalIdeal_secondOpen n,
      secondExceptionalAmbientEquation_regular n⟩
  · obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ :=
      (isBasis_affine_open (projectiveContactStage (k := k) (n + 1))).exists_subset_of_mem_open hx
        (nextPuncture (k := k) n).2
    exact ⟨⟨W, hW⟩, hxW, 1, stepExceptionalIdeal_puncture n ⟨W, hW⟩ hWle, Submonoid.one_mem _⟩

/-- The newest exceptional curve `P` as an effective Cartier divisor on stage `n+1`. -/
def stepExceptionalDivisor (n : ℕ) : CartierDivisor (projectiveContactStage (k := k) (n + 1)) :=
  cartierDivisorOfIdeal _ (stepExceptionalIdeal n) (stepExceptionalIdeal_locallyPrincipalRegular n)

theorem stepExceptionalDivisor_hasRegularEquations (n : ℕ) :
    HasRegularCartierEquations (projectiveContactStage (k := k) (n + 1))
      (stepExceptionalDivisor n) :=
  cartierDivisorOfIdeal_hasRegularEquations _ _ _

/-- The ideal-sheaf data of the divisor is the kernel of the centre-fibre inclusion. -/
theorem stepExceptionalDivisor_idealData (n : ℕ) :
    effectiveCartierIdealDataOfRegularEquations (projectiveContactStage (k := k) (n + 1))
        (stepExceptionalDivisor n) (stepExceptionalDivisor_hasRegularEquations n) =
      stepExceptionalIdeal n :=
  cartierDivisorOfIdeal_idealData _ _ _

/-- The Cartier class of `P` is minus the class of the ideal line of its kernel. -/
theorem stepExceptionalDivisor_picard (n : ℕ) :
    cartierPicardHom (projectiveContactStage (k := k) (n + 1)) (stepExceptionalDivisor n) =
      -Additive.ofMul (gluedKernelLine (stepExceptionalIdeal n)
        (stepExceptionalIdeal_locallyPrincipalRegular n)).toPic :=
  cartierDivisorOfIdeal_picard _ _ _

end KltDP.Examples.FrobeniusExceptionalCartier

namespace KltDP.Examples

open KltDP.Geometry FrobeniusGlobalBlowupStages FrobeniusStrictTransformProductKernel
  FrobeniusExceptionalCartier FrobeniusTowerFunctionField FrobeniusGraphPicardClassIntegral

local instance exceptionalInitialIntegral' {k : Type u} [Field k] :
    IsIntegral (projectiveProductInitial (k := k)).carrier :=
  projectiveProduct_isIntegral

local instance exceptionalOriginMaximal' {k : Type u} [Field k] :
    (FrobeniusBlowupChartIteration.originPoint (k := k)).asIdeal.IsMaximal :=
  FrobeniusBlowupChartIteration.centerIdeal_isMaximal

/-- Bundle: on every stage `n+1` of the origin contact tower the newest exceptional curve `P` is an
effective Cartier divisor with regular equations whose ideal-sheaf data is the kernel of the
centre-fibre inclusion, and whose Cartier class is minus the class of that kernel's ideal line. -/
theorem f29_exceptional_cartier (k : Type u) [Field k] :
    ∀ n : ℕ,
      HasRegularCartierEquations (projectiveContactStage (k := k) (n + 1))
          (stepExceptionalDivisor n) ∧
      effectiveCartierIdealDataOfRegularEquations (projectiveContactStage (k := k) (n + 1))
          (stepExceptionalDivisor n) (stepExceptionalDivisor_hasRegularEquations n) =
        (stepExceptionalInclusion (k := k) n).ker ∧
      cartierPicardHom (projectiveContactStage (k := k) (n + 1)) (stepExceptionalDivisor n) =
        -Additive.ofMul (gluedKernelLine (stepExceptionalIdeal n)
          (stepExceptionalIdeal_locallyPrincipalRegular n)).toPic :=
  fun n => ⟨stepExceptionalDivisor_hasRegularEquations n, stepExceptionalDivisor_idealData n,
    stepExceptionalDivisor_picard n⟩

/-- The bundle has exactly one universe parameter. -/
theorem f29_exceptional_cartier_universe_check (k : Type u) [Field k] : True := by
  have _ := f29_exceptional_cartier.{u} k
  trivial

end KltDP.Examples
