import KltDP.Examples.FrobeniusDiscrepancySmoothSupport
import KltDP.Geometry.SmoothPrimeCurveStalkParameters

/-!
# Actual local parameters along the candidate discrepancy support

Every nonzero-coefficient prime of the original candidate is smooth, and
its original inclusion kernel is generated by a regular parameter at every
closed point. Distinct support primes are globally disjoint. These are
ordinary local geometric conclusions, with no SNC or parameter hypothesis.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory IsLocalRing

universe u

namespace KltDP.Examples.FrobeniusDiscrepancyBounds

open KltDP.Geometry KltDP.Geometry.NormalProjectiveSurface
open FrobeniusMultiCentreSurface FrobeniusMultiCentreCanonicalWeilRepresentatives

variable {k : Type u} [Field k] [IsAlgClosed k]
    (q n : ℕ) [Fact (q + 1).Prime] [CharP k (q + 1)]
    (a : Fin n → k) (ha : Function.Injective a)
    (hproj : IsProjectiveOverField (multiStructure (q + 1) n a))

/-- The original curve equation extends to actual ambient regular parameters
at every closed point of every nonzero-coefficient candidate prime. -/
theorem candidate_support_stalk_parameters
    (C : (sourceSurface q n a ha hproj).PrimeCurve)
    (hC : C ∈ (candidate q n a ha hproj).support)
    (y : C.toScheme) (hy : IsClosed ({y} : Set C.toScheme)) :
    ∃ f g : (sourceSurface q n a ha hproj).toScheme.presheaf.stalk (C.inclusion.base y),
      Ideal.span {f, g} = maximalIdeal
        ((sourceSurface q n a ha hproj).toScheme.presheaf.stalk (C.inclusion.base y)) ∧
      RingHom.ker (C.inclusion.stalkMap y).hom = Ideal.span {f} ∧
      f ∉ (maximalIdeal
        ((sourceSurface q n a ha hproj).toScheme.presheaf.stalk (C.inclusion.base y))) ^ 2 := by
  letI := multiStructure_smoothTwo (q + 1) n a ha
  letI : IsSmooth (sourceSurface q n a ha hproj).structureMorphism :=
    IsSmoothOfRelativeDimension.isSmooth 2 (multiStructure (q + 1) n a)
  letI := candidate_support_isSmooth q n a ha hproj C hC
  exact PrimeCurve.exists_stalk_parameters (sourceSurface q n a ha hproj) C y hy

end KltDP.Examples.FrobeniusDiscrepancyBounds
