import KltDP.Examples.FrobeniusProjectivePoints
import KltDP.Geometry.DivisorOrderLength
import Mathlib.Algebra.MvPolynomial.Equiv
import Mathlib.Algebra.Polynomial.RingDivision
import Mathlib.RingTheory.AdjoinRoot
import Mathlib.RingTheory.DedekindDomain.Dvr
import Mathlib.RingTheory.Length

/-!
# The actual affine Frobenius fiber equation and its contact algebra

The second projection of the existing affine graph is the actual scheme
morphism induced by `parameterMap p`. Pulling back the chart equation
`y-a^p` by that ring map gives `(t-a)^p` in characteristic `p`.

The fiber algebra below is the quotient by the ideal generated by this
actual pullback section. An actual polynomial-coordinate algebra equivalence
identifies it with `k[t]/((t-a)^p)`. The pinned `AdjoinRoot.powerBasis'`
and `Polynomial.rootMultiplicity_X_sub_C_pow` give its dimension and
root multiplicity. No numerical contact assertion is placed in a structure.

The explicit local ring `k[t]_(t-a)` is proved to be a DVR, and the image of
`t-a` is proved to be a uniformizer. The actual local quotient therefore
has module length `p` over that local ring as well. Identification with the
scheme stalk and the successive blowups remain separate adapters.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Limits

universe u

namespace KltDP.Examples.FrobeniusGraphContact

open KltDP.Geometry ProjectiveChart FrobeniusProjectivePoints

variable {k : Type u} [Field k]

attribute [local instance] MvPolynomial.gradedAlgebra

/-- The second projection of the actual affine graph uses exactly this chart ring map. -/
theorem affineGraph_secondProjection (p : ℕ) :
    affineGraphMorphism (k := k) p ≫
        pullback.snd (projectiveSpaceToSpec k 1) (projectiveSpaceToSpec k 1) =
      Spec.map (CommRingCat.ofHom (parameterMap p)) ≫ chartMorphism k 1 :=
  pullback.lift_snd _ _ _

/-- The equation of the fiber at chart coordinate `b`. -/
def fiberEquation (b : k) : chartRing k 1 :=
  ratio k 1 0 - constants k 1 b

/-- Its actual pullback along the graph's second coordinate. -/
def pulledFiberEquation (p : ℕ) (a : k) : affineRing k 1 :=
  parameterMap p (fiberEquation (a ^ p))

theorem parameterMap_ratio (p : ℕ) :
    parameterMap (k := k) p (ratio k 1 0) = MvPolynomial.X 0 ^ p := by
  simp [parameterMap]

theorem pulledFiberEquation_eq (p : ℕ) (a : k) :
    pulledFiberEquation p a = MvPolynomial.X 0 ^ p - MvPolynomial.C (a ^ p) := by
  simp only [pulledFiberEquation, fiberEquation, map_sub,
    parameterMap_ratio, parameterMap_constants]

/-- The actual ideal generated by the pulled-back fiber equation. -/
def contactIdeal (p : ℕ) (a : k) : Ideal (affineRing k 1) :=
  Ideal.span {pulledFiberEquation p a}

/-- The actual affine fiber algebra, retaining the pulled-back defining equation. -/
abbrev contactAlgebra (p : ℕ) (a : k) :=
  affineRing k 1 ⧸ contactIdeal p a

/-- The standard identification of the existing one-variable affine ring with `k[t]`. -/
def parameterPolynomialEquiv : affineRing k 1 ≃ₐ[k] Polynomial k :=
  (MvPolynomial.renameEquiv k finOneEquiv).trans (MvPolynomial.pUnitAlgEquiv k)

@[simp] theorem parameterPolynomialEquiv_C (a : k) :
    parameterPolynomialEquiv (MvPolynomial.C a) = Polynomial.C a :=
  parameterPolynomialEquiv.commutes a

@[simp] theorem parameterPolynomialEquiv_X :
    parameterPolynomialEquiv (k := k) (MvPolynomial.X 0) = Polynomial.X := by
  simp [parameterPolynomialEquiv, MvPolynomial.renameEquiv_apply,
    MvPolynomial.pUnitAlgEquiv_apply]

/-- The actual polynomial prime ideal of the selected affine parameter. -/
def parameterPointIdeal (a : k) : Ideal (Polynomial k) :=
  Ideal.span {Polynomial.X - Polynomial.C a}

instance parameterPointIdeal_isPrime (a : k) : (parameterPointIdeal a).IsPrime :=
  (Ideal.span_singleton_prime (Polynomial.monic_X_sub_C a).ne_zero).mpr
    (Polynomial.prime_X_sub_C a)

theorem parameterPointIdeal_ne_bot (a : k) : parameterPointIdeal a ≠ ⊥ := by
  intro h
  have hm : Polynomial.X - Polynomial.C a ∈ parameterPointIdeal a :=
    Ideal.subset_span (Set.mem_singleton _)
  rw [h, Ideal.mem_bot] at hm
  exact (Polynomial.monic_X_sub_C a).ne_zero hm

/-- The specified localization of the actual polynomial coordinate ring at the selected point. -/
abbrev parameterLocalRing (a : k) := Localization.AtPrime (parameterPointIdeal a)

instance parameterLocalRing_isDVR (a : k) : IsDiscreteValuationRing (parameterLocalRing a) :=
  IsLocalization.AtPrime.isDiscreteValuationRing_of_dedekind_domain (Polynomial k)
    (parameterPointIdeal_ne_bot a) (parameterLocalRing a)

/-- The actual local image of the translated affine coordinate. -/
def localParameter (a : k) : parameterLocalRing a :=
  algebraMap (Polynomial k) (parameterLocalRing a) (Polynomial.X - Polynomial.C a)

/-- This explicit local coordinate generates the actual maximal ideal. -/
theorem localParameter_uniformizer (a : k) : Irreducible (localParameter a) := by
  apply (IsDiscreteValuationRing.irreducible_iff_uniformizer (localParameter a)).mpr
  have h := (Localization.AtPrime.map_eq_maximalIdeal (I := parameterPointIdeal a)).symm
  simpa only [parameterPointIdeal, Ideal.map_span, Set.image_singleton, localParameter] using h

/-- The actual pullback section, now mapped into the specified local coordinate ring. -/
def localPulledFiberEquation (p : ℕ) (a : k) : parameterLocalRing a :=
  algebraMap (Polynomial k) (parameterLocalRing a)
    (parameterPolynomialEquiv (pulledFiberEquation p a))

section PositiveCharacteristic

variable (p : ℕ) [Fact p.Prime] [CharP k p]

/-- In characteristic `p`, the actual pulled-back fiber equation is a pure `p`th power. -/
theorem pulledFiberEquation_eq_pow (a : k) :
    pulledFiberEquation p a = (MvPolynomial.X 0 - MvPolynomial.C a) ^ p := by
  rw [pulledFiberEquation_eq, sub_pow_char, ← map_pow]

theorem contactIdeal_eq_span_pow (a : k) :
    contactIdeal p a = Ideal.span {(MvPolynomial.X 0 - MvPolynomial.C a) ^ p} := by
  rw [contactIdeal, pulledFiberEquation_eq_pow]

/-- The pulled section vanishes at exactly the selected affine parameter. -/
theorem pulledFiberEquation_eval_eq_zero_iff (a b : k) :
    parameterEvaluation b (pulledFiberEquation p a) = 0 ↔ b = a := by
  rw [pulledFiberEquation_eq_pow]
  simp only [map_pow, map_sub, parameterEvaluation, MvPolynomial.eval₂Hom_X',
    MvPolynomial.eval₂Hom_C, RingHom.id_apply]
  rw [pow_eq_zero_iff (Fact.out : p.Prime).ne_zero, sub_eq_zero]

/-- Polynomial coordinates preserve the actual pulled section. -/
theorem parameterPolynomialEquiv_pulledFiberEquation (a : k) :
    parameterPolynomialEquiv (pulledFiberEquation p a) =
      (Polynomial.X - Polynomial.C a) ^ p := by
  rw [pulledFiberEquation_eq_pow, map_pow, map_sub,
    parameterPolynomialEquiv_X, parameterPolynomialEquiv_C]

/-- The actual fiber quotient is the standard quotient by `(t-a)^p`. -/
def contactQuotientEquiv (a : k) :
    contactAlgebra p a ≃ₐ[k] AdjoinRoot ((Polynomial.X - Polynomial.C a) ^ p) := by
  refine Ideal.quotientEquivAlg (contactIdeal p a)
    (Ideal.span {(Polynomial.X - Polynomial.C a) ^ p}) parameterPolynomialEquiv ?_
  rw [contactIdeal, Ideal.map_span, Set.image_singleton]
  change Ideal.span {(Polynomial.X - Polynomial.C a) ^ p} =
    Ideal.span {parameterPolynomialEquiv (pulledFiberEquation p a)}
  rw [parameterPolynomialEquiv_pulledFiberEquation]

/-- The fiber quotient is an actual finite-dimensional algebra over the base field. -/
instance contactAlgebra_finite (a : k) : Module.Finite k (contactAlgebra p a) := by
  letI : Module.Finite k (AdjoinRoot ((Polynomial.X - Polynomial.C a) ^ p)) :=
    ((Polynomial.monic_X_sub_C a).pow p).finite_adjoinRoot
  exact FiniteDimensional.of_injective (contactQuotientEquiv p a).toLinearEquiv.toLinearMap
    (contactQuotientEquiv p a).injective

/-- The actual contact algebra has dimension `p` over `k`. -/
theorem contactAlgebra_finrank (a : k) :
    Module.finrank k (contactAlgebra p a) = p := by
  rw [(contactQuotientEquiv p a).toLinearEquiv.finrank_eq]
  have h := (AdjoinRoot.powerBasis' ((Polynomial.monic_X_sub_C a).pow p)).finrank
  change Module.finrank k (AdjoinRoot ((Polynomial.X - Polynomial.C a) ^ p)) =
    ((Polynomial.X - Polynomial.C a) ^ p).natDegree at h
  simpa only [Polynomial.natDegree_pow, Polynomial.natDegree_X_sub_C, mul_one] using h

/-- Length over the base field equals `p`; no stalk-length convention is hidden here. -/
theorem contactAlgebra_length_over_field (a : k) :
    Module.length k (contactAlgebra p a) = p := by
  rw [Module.length_eq_finrank, contactAlgebra_finrank]

/-- The actual pulled polynomial has root multiplicity exactly `p` at the selected point. -/
theorem pulledFiberEquation_rootMultiplicity (a : k) :
    Polynomial.rootMultiplicity a (parameterPolynomialEquiv (pulledFiberEquation p a)) = p := by
  rw [parameterPolynomialEquiv_pulledFiberEquation]
  exact Polynomial.rootMultiplicity_X_sub_C_pow a p

theorem localPulledFiberEquation_eq_pow (a : k) :
    localPulledFiberEquation p a = localParameter a ^ p := by
  simp only [localPulledFiberEquation, parameterPolynomialEquiv_pulledFiberEquation,
    map_pow, localParameter]

/-- The actual local fiber quotient has module length `p` over `k[t]_(t-a)`.
The DVR property and the uniformizer calculation are conclusions above. -/
theorem localContactAlgebra_length (a : k) :
    Module.length (parameterLocalRing a)
      (parameterLocalRing a ⧸ Ideal.span {localPulledFiberEquation p a}) = p := by
  rw [localPulledFiberEquation_eq_pow]
  exact KltDP.RingTheory.dvr_length_quotient_uniformizer_pow
    (parameterLocalRing a) (localParameter a) (localParameter_uniformizer a) p

end PositiveCharacteristic

end KltDP.Examples.FrobeniusGraphContact
