import KltDP.Examples.FrobeniusStageDimension
import KltDP.Examples.FrobeniusProductPlaneChart
import KltDP.Geometry.SurfaceRegularCharts
import KltDP.Geometry.RegularLocalDimensionTwo
import KltDP.Geometry.RegularLocalEquiv

/-!
# The stalk of `P¹ × P¹` at the origin is regular of dimension two

BRIEF21, task 1. The origin `productOrigin` of `P¹ × P¹` is the image of the origin `(u, v) = 0`
of the polynomial plane chart `planeChart : Spec k[u][v] ⟶ P¹ × P¹`. Along this open immersion the
stalk is the localisation `k[u][v]_{(u,v)}` (accepted `openImmersionStalkLocalizationEquiv`;
`originStalkEquiv`). That local ring is a Noetherian domain whose maximal ideal is generated by the
images of `u` and `v` (Mathlib `IsLocalization.AtPrime.map_eq_maximalIdeal`), of Krull dimension
exactly two: at most two because the stalk of `P¹ × P¹` has dimension at most the topological
dimension two of the product (accepted `ringKrullDim_stalk_le_topologicalKrullDim`,
`projectiveProduct_topologicalKrullDim`), at least two because of the chain of primes
`⊥ < (v) < (u, v)`, transported into the localisation (`originPrimeChain`). Hence it is regular in
the project's sense (`RegularLocal`, accepted `regularLocal_of_generators_of_dimension_le_two`:
a local domain of dimension `≤ 2` whose maximal ideal has as many generators as its dimension), and
so is the stalk (`originStalk_regularLocal`, `originStalk_ringKrullDim`). The two local equations
`originU`, `originV` of the fibres `x = 0`, `y = 0` generate the maximal ideal of the stalk
(`span_originU_originV`). No smoothness input is used.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing

universe u

namespace KltDP.Examples.ProjectiveProductOriginStalkRegular

open KltDP.Geometry
open FrobeniusBlowupContact FrobeniusBlowupChartIteration FrobeniusProjectivePoints
  FrobeniusProductPlaneChart FrobeniusStageDimension

variable {k : Type u} [Field k]

local instance centerIdeal_isMaximal' : (centerIdeal (k := k)).IsMaximal := centerIdeal_isMaximal

local instance centerIdeal_isPrime' : (centerIdeal (k := k)).IsPrime := centerIdeal_isMaximal'.isPrime

/-! ## The local ring `k[u][v]_{(u,v)}` -/

/-- The localisation of the polynomial plane at the origin `(u, v)`. -/
abbrev originLocalRing : Type u := Localization.AtPrime (centerIdeal (k := k))

theorem originLocalRing_isNoetherianRing : IsNoetherianRing (originLocalRing (k := k)) :=
  IsLocalization.isNoetherianRing (centerIdeal (k := k)).primeCompl (originLocalRing (k := k))
    inferInstance

/-- The maximal ideal of `k[u][v]_{(u,v)}` is generated by `u` and `v`. -/
theorem span_uv_eq_maximalIdeal :
    Ideal.span {algebraMap (planeRing k) (originLocalRing (k := k)) uCoord,
      algebraMap (planeRing k) (originLocalRing (k := k)) vCoord} =
      maximalIdeal (originLocalRing (k := k)) := by
  have h : Ideal.map (algebraMap (planeRing k) (originLocalRing (k := k)))
      (Ideal.span {uCoord, vCoord}) = maximalIdeal (originLocalRing (k := k)) :=
    Localization.AtPrime.map_eq_maximalIdeal (I := centerIdeal (k := k))
  rw [Ideal.map_span, Set.image_insert_eq, Set.image_singleton] at h
  exact h

theorem uCoord_mem_maximalIdeal :
    algebraMap (planeRing k) (originLocalRing (k := k)) uCoord ∈
      maximalIdeal (originLocalRing (k := k)) := by
  rw [← span_uv_eq_maximalIdeal]
  exact Ideal.subset_span (Set.mem_insert _ _)

theorem vCoord_mem_maximalIdeal :
    algebraMap (planeRing k) (originLocalRing (k := k)) vCoord ∈
      maximalIdeal (originLocalRing (k := k)) := by
  rw [← span_uv_eq_maximalIdeal]
  exact Ideal.subset_span (Set.mem_insert_of_mem _ (Set.mem_singleton _))

/-! ## The chain of primes `⊥ < (v) < (u, v)` -/

theorem vCoord_prime : Prime (vCoord (k := k)) := Polynomial.prime_X

theorem vCoord_ne_zero : vCoord (k := k) ≠ 0 := Polynomial.X_ne_zero

theorem uCoord_not_mem_span_vCoord : uCoord (k := k) ∉ Ideal.span {vCoord (k := k)} := by
  rw [Ideal.mem_span_singleton]
  show ¬ (Polynomial.X ∣ Polynomial.C Polynomial.X)
  rw [Polynomial.X_dvd_iff, Polynomial.coeff_C_zero]
  exact Polynomial.X_ne_zero

theorem span_vCoord_le_centerIdeal : Ideal.span {vCoord (k := k)} ≤ centerIdeal (k := k) :=
  Ideal.span_mono (Set.singleton_subset_iff.mpr (Set.mem_insert_of_mem _ (Set.mem_singleton _)))

theorem span_vCoord_lt_centerIdeal : Ideal.span {vCoord (k := k)} < centerIdeal (k := k) := by
  refine lt_of_le_of_ne span_vCoord_le_centerIdeal fun h => uCoord_not_mem_span_vCoord (k := k) ?_
  rw [h]
  exact Ideal.subset_span (Set.mem_insert _ _)

theorem bot_lt_span_vCoord : (⊥ : Ideal (planeRing k)) < Ideal.span {vCoord (k := k)} :=
  bot_lt_iff_ne_bot.mpr fun h => vCoord_ne_zero (Ideal.span_singleton_eq_bot.mp h)

theorem disjoint_primeCompl_of_le {P : Ideal (planeRing k)} (h : P ≤ centerIdeal (k := k)) :
    Disjoint ((centerIdeal (k := k)).primeCompl : Set (planeRing k)) (P : Set (planeRing k)) :=
  Set.disjoint_left.mpr fun _ hx hxP => hx (h hxP)

/-- A prime of the plane contained in `(u, v)`, as a prime of the localisation. -/
def locPrime (P : Ideal (planeRing k)) [hP : P.IsPrime] (hle : P ≤ centerIdeal (k := k)) :
    PrimeSpectrum (originLocalRing (k := k)) :=
  ⟨Ideal.map (algebraMap (planeRing k) (originLocalRing (k := k))) P,
    IsLocalization.isPrime_of_isPrime_disjoint (centerIdeal (k := k)).primeCompl
      (originLocalRing (k := k)) P hP (disjoint_primeCompl_of_le hle)⟩

theorem locPrime_lt {P Q : Ideal (planeRing k)} [hP : P.IsPrime] [hQ : Q.IsPrime]
    (hPle : P ≤ centerIdeal (k := k)) (hQle : Q ≤ centerIdeal (k := k)) (h : P < Q) :
    locPrime P hPle < locPrime Q hQle := by
  rw [← PrimeSpectrum.asIdeal_lt_asIdeal]
  show Ideal.map (algebraMap (planeRing k) (originLocalRing (k := k))) P <
    Ideal.map (algebraMap (planeRing k) (originLocalRing (k := k))) Q
  refine lt_of_le_of_ne (Ideal.map_mono h.le) fun heq => h.ne ?_
  have hc := congrArg (Ideal.comap (algebraMap (planeRing k) (originLocalRing (k := k)))) heq
  rwa [IsLocalization.comap_map_of_isPrime_disjoint _ _ P hP (disjoint_primeCompl_of_le hPle),
    IsLocalization.comap_map_of_isPrime_disjoint _ _ Q hQ (disjoint_primeCompl_of_le hQle)] at hc

/-- The chain `⊥ < (v) < (u, v)` of primes of `k[u][v]_{(u,v)}`. -/
def originPrimeChain : LTSeries (PrimeSpectrum (originLocalRing (k := k))) :=
  haveI hbot : (⊥ : Ideal (planeRing k)).IsPrime := Ideal.bot_prime
  haveI hv : (Ideal.span {vCoord (k := k)}).IsPrime :=
    (Ideal.span_singleton_prime vCoord_ne_zero).mpr vCoord_prime
  ⟨2, ![locPrime ⊥ bot_le, locPrime (Ideal.span {vCoord}) span_vCoord_le_centerIdeal,
      locPrime (centerIdeal (k := k)) le_rfl], fun i => by
    fin_cases i
    · exact locPrime_lt bot_le span_vCoord_le_centerIdeal bot_lt_span_vCoord
    · exact locPrime_lt span_vCoord_le_centerIdeal le_rfl span_vCoord_lt_centerIdeal⟩

theorem two_le_ringKrullDim_originLocalRing :
    (2 : WithBot ℕ∞) ≤ ringKrullDim (originLocalRing (k := k)) := by
  have h := Order.LTSeries.length_le_krullDim (originPrimeChain (k := k))
  exact h

/-! ## The stalk at the origin -/

/-- The origin of `P¹ × P¹`: the image of the origin of the polynomial plane chart. -/
def productOrigin : projectiveProduct k := (planeChart (k := k)).base (originPoint (k := k))

/-- The stalk of `P¹ × P¹` at the origin is `k[u][v]_{(u,v)}`. -/
def originStalkEquiv :
    (projectiveProduct k).presheaf.stalk (productOrigin (k := k)) ≃+* originLocalRing (k := k) :=
  openImmersionStalkLocalizationEquiv (planeChart (k := k)) (originPoint (k := k))

theorem originStalk_ringKrullDim_le_two :
    ringKrullDim ((projectiveProduct k).presheaf.stalk (productOrigin (k := k))) ≤ 2 := by
  have h := ringKrullDim_stalk_le_topologicalKrullDim (projectiveProduct k) (productOrigin (k := k))
  rwa [projectiveProduct_topologicalKrullDim] at h

/-- `k[u][v]_{(u,v)}` has Krull dimension two. -/
theorem ringKrullDim_originLocalRing : ringKrullDim (originLocalRing (k := k)) = 2 := by
  apply le_antisymm
  · rw [← ringKrullDim_eq_of_ringEquiv (originStalkEquiv (k := k))]
    exact originStalk_ringKrullDim_le_two
  · exact two_le_ringKrullDim_originLocalRing

/-- The generators `u`, `v` of the maximal ideal, as a family. -/
def originGenerators : Fin 2 → maximalIdeal (originLocalRing (k := k)) :=
  ![⟨_, uCoord_mem_maximalIdeal⟩, ⟨_, vCoord_mem_maximalIdeal⟩]

theorem range_originGenerators :
    Set.range (fun i => (originGenerators (k := k) i : originLocalRing (k := k))) =
      {algebraMap (planeRing k) (originLocalRing (k := k)) uCoord,
        algebraMap (planeRing k) (originLocalRing (k := k)) vCoord} := by
  ext x
  simp only [Set.mem_range, Set.mem_insert_iff, Set.mem_singleton_iff]
  constructor
  · rintro ⟨i, rfl⟩
    fin_cases i
    · exact Or.inl rfl
    · exact Or.inr rfl
  · rintro (rfl | rfl)
    · exact ⟨0, rfl⟩
    · exact ⟨1, rfl⟩

theorem span_originGenerators :
    Ideal.span (Set.range (fun i => (originGenerators (k := k) i : originLocalRing (k := k)))) =
      maximalIdeal (originLocalRing (k := k)) := by
  rw [range_originGenerators]
  exact span_uv_eq_maximalIdeal

/-- `k[u][v]_{(u,v)}` is a regular local ring (generators `u`, `v`, dimension two). -/
theorem originLocalRing_regularLocal : RegularLocal (originLocalRing (k := k)) := by
  haveI := originLocalRing_isNoetherianRing (k := k)
  exact regularLocal_of_generators_of_dimension_le_two ringKrullDim_originLocalRing.le
    ⟨inferInstance, 2, originGenerators, ringKrullDim_originLocalRing, span_originGenerators⟩

/-- **The stalk of `P¹ × P¹` at the origin is regular.** -/
theorem originStalk_regularLocal :
    RegularLocal ((projectiveProduct k).presheaf.stalk (productOrigin (k := k))) :=
  regularLocal_of_ringEquiv (originStalkEquiv (k := k)).symm originLocalRing_regularLocal

/-- **The stalk of `P¹ × P¹` at the origin has Krull dimension two.** -/
theorem originStalk_ringKrullDim :
    ringKrullDim ((projectiveProduct k).presheaf.stalk (productOrigin (k := k))) = 2 :=
  (ringKrullDim_eq_of_ringEquiv (originStalkEquiv (k := k))).trans ringKrullDim_originLocalRing

/-! ## The local equations `u`, `v` in the stalk -/

/-- The germ of `u` at the origin. -/
def originU : (projectiveProduct k).presheaf.stalk (productOrigin (k := k)) :=
  (originStalkEquiv (k := k)).symm (algebraMap (planeRing k) (originLocalRing (k := k)) uCoord)

/-- The germ of `v` at the origin. -/
def originV : (projectiveProduct k).presheaf.stalk (productOrigin (k := k)) :=
  (originStalkEquiv (k := k)).symm (algebraMap (planeRing k) (originLocalRing (k := k)) vCoord)

/-- The image of the maximal ideal under the inverse stalk equivalence is the maximal ideal. -/
theorem map_symm_maximalIdeal :
    Ideal.map (originStalkEquiv (k := k)).symm (maximalIdeal (originLocalRing (k := k))) =
      maximalIdeal ((projectiveProduct k).presheaf.stalk (productOrigin (k := k))) := by
  apply IsLocalRing.eq_maximalIdeal
  rw [← Ideal.comap_symm, RingEquiv.symm_symm]
  exact Ideal.comap_isMaximal_of_surjective (f := originStalkEquiv (k := k))
    (originStalkEquiv (k := k)).surjective

/-- **`u`, `v` generate the maximal ideal of the stalk at the origin.** -/
theorem span_originU_originV :
    Ideal.span {originU (k := k), originV (k := k)} =
      maximalIdeal ((projectiveProduct k).presheaf.stalk (productOrigin (k := k))) := by
  rw [← map_symm_maximalIdeal, ← span_uv_eq_maximalIdeal, Ideal.map_span, Set.image_insert_eq,
    Set.image_singleton]
  rfl

/-- Universe check at universe `0`. -/
example (k₀ : Type) [Field k₀] :
    RegularLocal ((projectiveProduct k₀).presheaf.stalk (productOrigin (k := k₀))) ∧
      ringKrullDim ((projectiveProduct k₀).presheaf.stalk (productOrigin (k := k₀))) = 2 :=
  ⟨originStalk_regularLocal, originStalk_ringKrullDim⟩

end KltDP.Examples.ProjectiveProductOriginStalkRegular
