import KltDP.Examples.RationalTreePicardWitnessTwoFibresNode

/-!
# Witness (b), concluded: the crossing of the two fibres at the node is transversal

BRIEF21, task 2 (conclusion). On the polynomial plane chart `planeChart : Spec k[u][v] ⟶ P¹ × P¹`
the horizontal fibre `y = 0` is the line `v = 0` and the vertical fibre `x = 0` is the line `u = 0`
(`horizontalLine_planeChart`, `verticalLine_planeChart`, by `pullback.hom_ext`), so a point
`planeChart p` lies on `y = 0` iff `v ∈ p` and on `x = 0` iff `u ∈ p`
(`base_planeChart_mem_range_horizontal_iff`, `base_planeChart_mem_range_vertical_iff`; the
converse directions use `PrimeSpectrum.range_comap_of_surjective`). Hence on the affine open
`planeChartOpen = planeChart(Spec k[u][v])`, whose section ring is `k[u][v]` (`chartSectionEquiv`),
the union of the two fibres is the zero locus of `u v` and the vanishing ideal of the union is
`(u v)` — the radical of `(u v) = (u) ∩ (v)` is itself (`twoFibresIdeal_ideal_planeChartOpen`).

The kernel of the stalk map of a glued closed subscheme at `z` is the ideal generated by the germs
of `I(U)` for any affine `U ∋ ι z` (`ker_stalkMap_gluedTo_eq_map_germ`: the germ description of
the accepted `stalkMap_gluedTo_ker_eq_span`, shrinking to a basic open of `U` where
`map_ideal_basicOpen` applies). With the identification of the germs of `u`, `v` under the
accepted stalk-localisation equivalence (`stalkEquiv_germ_chartSection`, `originU_eq_germ`), the
kernel at the node is `(germ u · germ v)` (`ker_stalkMap_node`), and the germs of `u`, `v` restricted
to the union lie in the chart ideals of the components `x = 0`, `y = 0`
(`stalkMap_germU_mem`, `stalkMap_germV_mem`: a point of a component pulled back to the chart is
a point where the equation vanishes). Therefore the crossing is transversal
(`twoFibresCrossing : TwoFibresCrossing`) and, for `k` algebraically closed,
**`Pic(x = 0 ∪ y = 0) ≃* ℤ²`** with the degree-zero clause, unconditionally
(`twoFibresPicardEquiv'`, `twoFibres_trivial_of_degree_zero'`, `twoFibres_rationalTreePicard'`).
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing CategoryTheory.Limits Opposite

universe u

namespace KltDP.Examples.RationalTreePicardWitnessTwoFibres

open KltDP.Geometry KltDP.Geometry.RationalTreePicard
open FrobeniusProjectivePoints FrobeniusGraphClosed FrobeniusGraphPicardClassZeroFiber
  FrobeniusUnaffectedFibers FrobeniusBlowupContact FrobeniusBlowupChartIteration
  FrobeniusProductPlaneChart FrobeniusTranslatedCharts ProjectiveProductOriginStalkRegular
  ProjectiveLineComparison

variable {k : Type u} [Field k]

/-! ## The two coordinate lines of the plane and the two fibres -/

/-- Killing `u`: `k[u][v] → k[v]`. -/
def killU : planeRing k →+* Polynomial k := Polynomial.mapRingHom (Polynomial.evalRingHom 0)

theorem evalV_comp_firstCoordinateMap :
    (Polynomial.evalRingHom (0 : Polynomial k)).comp firstCoordinateMap = RingHom.id _ := by
  apply RingHom.ext
  intro p
  simp [firstCoordinateMap]

theorem evalV_comp_secondCoordinateMap :
    (Polynomial.evalRingHom (0 : Polynomial k)).comp secondCoordinateMap =
      (Polynomial.C : k →+* Polynomial k).comp (Polynomial.evalRingHom 0) := by
  apply Polynomial.ringHom_ext
  · intro r
    simp [secondCoordinateMap]
  · simp [secondCoordinateMap]

theorem killU_comp_firstCoordinateMap :
    (killU (k := k)).comp firstCoordinateMap =
      (Polynomial.C : k →+* Polynomial k).comp (Polynomial.evalRingHom 0) := by
  apply Polynomial.ringHom_ext
  · intro r
    simp [killU, firstCoordinateMap]
  · simp [killU, firstCoordinateMap]

theorem killU_comp_secondCoordinateMap :
    (killU (k := k)).comp secondCoordinateMap = RingHom.id _ := by
  apply Polynomial.ringHom_ext
  · intro r
    simp [killU, secondCoordinateMap]
  · simp [killU, secondCoordinateMap]

theorem ker_evalV :
    RingHom.ker (Polynomial.evalRingHom (0 : Polynomial k)) = Ideal.span {vCoord (k := k)} := by
  rw [Polynomial.ker_evalRingHom, Polynomial.C_0, sub_zero]
  rfl

theorem ker_killU : RingHom.ker (killU (k := k)) = Ideal.span {uCoord (k := k)} := by
  rw [killU, Polynomial.ker_mapRingHom, Polynomial.ker_evalRingHom, Ideal.map_span,
    Set.image_singleton, Polynomial.C_0, sub_zero]
  rfl

theorem evalV_surjective : Function.Surjective (Polynomial.evalRingHom (0 : Polynomial k)) :=
  fun r => ⟨firstCoordinateMap r, RingHom.congr_fun evalV_comp_firstCoordinateMap r⟩

theorem killU_surjective : Function.Surjective (killU (k := k)) :=
  fun r => ⟨secondCoordinateMap r, RingHom.congr_fun killU_comp_secondCoordinateMap r⟩

/-- The line `v = 0` of the plane. -/
def horizontalLine : Spec (CommRingCat.of (Polynomial k)) ⟶ plane k :=
  Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : Polynomial k)))

/-- The line `u = 0` of the plane. -/
def verticalLine : Spec (CommRingCat.of (Polynomial k)) ⟶ plane k :=
  Spec.map (CommRingCat.ofHom (killU (k := k)))

/-- On the plane chart the line `v = 0` is the fibre `y = 0`. -/
theorem horizontalLine_planeChart :
    horizontalLine ≫ planeChart (k := k) = polynomialChartMap k 0 ≫ horizontalFiberMorphism 0 := by
  apply pullback.hom_ext
  · rw [Category.assoc, Category.assoc, planeChart_fst, horizontalFiberMorphism_fst,
      Category.comp_id, ← Category.assoc horizontalLine, horizontalLine, ← Spec.map_comp,
      ← CommRingCat.ofHom_comp, evalV_comp_firstCoordinateMap, CommRingCat.ofHom_id, Spec.map_id,
      Category.id_comp]
  · rw [Category.assoc, Category.assoc, planeChart_snd, horizontalFiberMorphism_snd,
      ← Category.assoc (polynomialChartMap k 0), polynomialChartMap_structureMap,
      ← Category.assoc horizontalLine, horizontalLine, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
      evalV_comp_secondCoordinateMap, CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc,
      polynomialChartMap_evaluation]

/-- On the plane chart the line `u = 0` is the fibre `x = 0`. -/
theorem verticalLine_planeChart :
    verticalLine ≫ planeChart (k := k) = polynomialChartMap k 0 ≫ verticalFiberMorphismAt 0 := by
  apply pullback.hom_ext
  · rw [Category.assoc, Category.assoc, planeChart_fst, verticalFiberMorphismAt_fst,
      ← Category.assoc (polynomialChartMap k 0), polynomialChartMap_structureMap,
      ← Category.assoc verticalLine, verticalLine, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
      killU_comp_firstCoordinateMap, CommRingCat.ofHom_comp, Spec.map_comp, Category.assoc,
      polynomialChartMap_evaluation]
  · rw [Category.assoc, Category.assoc, planeChart_snd, verticalFiberMorphismAt_snd,
      Category.comp_id, ← Category.assoc verticalLine, verticalLine, ← Spec.map_comp,
      ← CommRingCat.ofHom_comp, killU_comp_secondCoordinateMap, CommRingCat.ofHom_id, Spec.map_id,
      Category.id_comp]

/-- A point of the plane chart lies on the fibre `y = 0` iff `v` vanishes at it. -/
theorem base_planeChart_mem_range_horizontal_iff (p : plane k) :
    (planeChart (k := k)).base p ∈ Set.range (horizontalFiberMorphism (0 : k)).base ↔
      vCoord ∈ p.asIdeal := by
  constructor
  · rintro ⟨q, hq⟩
    have h1 : (secondProjection (k := k)).base ((planeChart (k := k)).base p) =
        (polynomialChartMap k 0).base
          ((Spec.map (CommRingCat.ofHom (secondCoordinateMap (k := k)))).base p) := by
      rw [← Scheme.comp_base_apply, planeChart_snd, Scheme.comp_base_apply]
    have h2 : (secondProjection (k := k)).base ((horizontalFiberMorphism (0 : k)).base q) =
        (polynomialChartMap k 0).base
          ((Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : k)))).base
            ((projectiveSpaceToSpec k 1).base q)) := by
      rw [← Scheme.comp_base_apply, horizontalFiberMorphism_snd, Scheme.comp_base_apply,
        ← polynomialChartMap_evaluation, Scheme.comp_base_apply]
    rw [hq, h1] at h2
    have h3 := (polynomialChartMap k 0).isOpenEmbedding.injective h2
    have h4 : (Polynomial.X : Polynomial k) ∈
        ((Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : k)))).base
          ((projectiveSpaceToSpec k 1).base q)).asIdeal := by
      rw [Spec.map_base_apply, PrimeSpectrum.comap_asIdeal, Ideal.mem_comap]
      simp
    rw [← h3, Spec.map_base_apply, PrimeSpectrum.comap_asIdeal, Ideal.mem_comap] at h4
    simpa using h4
  · intro hv
    have hp : p ∈ PrimeSpectrum.zeroLocus
        (RingHom.ker (Polynomial.evalRingHom (0 : Polynomial k)) : Set (planeRing k)) := by
      rw [ker_evalV, PrimeSpectrum.mem_zeroLocus, SetLike.coe_subset_coe,
        Ideal.span_singleton_le_iff_mem]
      exact hv
    rw [← PrimeSpectrum.range_comap_of_surjective _ _ evalV_surjective] at hp
    obtain ⟨t, ht⟩ := hp
    refine ⟨(polynomialChartMap k 0).base t, ?_⟩
    rw [← Scheme.comp_base_apply, ← horizontalLine_planeChart, Scheme.comp_base_apply]
    exact congrArg (planeChart (k := k)).base ht

/-- A point of the plane chart lies on the fibre `x = 0` iff `u` vanishes at it. -/
theorem base_planeChart_mem_range_vertical_iff (p : plane k) :
    (planeChart (k := k)).base p ∈ Set.range (verticalFiberMorphismAt (0 : k)).base ↔
      uCoord ∈ p.asIdeal := by
  constructor
  · rintro ⟨q, hq⟩
    have h1 : (firstProjection (k := k)).base ((planeChart (k := k)).base p) =
        (polynomialChartMap k 0).base
          ((Spec.map (CommRingCat.ofHom (firstCoordinateMap (k := k)))).base p) := by
      rw [← Scheme.comp_base_apply, planeChart_fst, Scheme.comp_base_apply]
    have h2 : (firstProjection (k := k)).base ((verticalFiberMorphismAt (0 : k)).base q) =
        (polynomialChartMap k 0).base
          ((Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : k)))).base
            ((projectiveSpaceToSpec k 1).base q)) := by
      rw [← Scheme.comp_base_apply, verticalFiberMorphismAt_fst, Scheme.comp_base_apply,
        ← polynomialChartMap_evaluation, Scheme.comp_base_apply]
    rw [hq, h1] at h2
    have h3 := (polynomialChartMap k 0).isOpenEmbedding.injective h2
    have h4 : (Polynomial.X : Polynomial k) ∈
        ((Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : k)))).base
          ((projectiveSpaceToSpec k 1).base q)).asIdeal := by
      rw [Spec.map_base_apply, PrimeSpectrum.comap_asIdeal, Ideal.mem_comap]
      simp
    rw [← h3, Spec.map_base_apply, PrimeSpectrum.comap_asIdeal, Ideal.mem_comap] at h4
    simpa using h4
  · intro hu
    have hp : p ∈ PrimeSpectrum.zeroLocus (RingHom.ker (killU (k := k)) : Set (planeRing k)) := by
      rw [ker_killU, PrimeSpectrum.mem_zeroLocus, SetLike.coe_subset_coe,
        Ideal.span_singleton_le_iff_mem]
      exact hu
    rw [← PrimeSpectrum.range_comap_of_surjective _ _ killU_surjective] at hp
    obtain ⟨t, ht⟩ := hp
    refine ⟨(polynomialChartMap k 0).base t, ?_⟩
    rw [← Scheme.comp_base_apply, ← verticalLine_planeChart, Scheme.comp_base_apply]
    exact congrArg (planeChart (k := k)).base ht

/-! ## The plane chart as an affine open and its sections -/

/-- The plane chart as an affine open of `P¹ × P¹`. -/
abbrev planeChartOpen : (projectiveProduct k).affineOpens :=
  ⟨planeChart ''ᵁ ⊤, (isAffineOpen_top (plane k)).image_of_isOpenImmersion planeChart⟩

theorem base_mem_planeChartOpen (p : plane k) :
    (planeChart (k := k)).base p ∈ (planeChartOpen (k := k)).1 := by
  show (planeChart (k := k)).base p ∈ planeChart ''ᵁ ⊤
  rw [Scheme.Hom.image_top_eq_opensRange]
  exact ⟨p, rfl⟩

theorem exists_of_mem_planeChartOpen (x : projectiveProduct k) (hx : x ∈ (planeChartOpen (k := k)).1) :
    ∃ p : plane k, (planeChart (k := k)).base p = x := by
  change x ∈ planeChart ''ᵁ ⊤ at hx
  rw [Scheme.Hom.image_top_eq_opensRange] at hx
  exact hx

theorem productOrigin_mem_planeChartOpen : productOrigin (k := k) ∈ (planeChartOpen (k := k)).1 :=
  base_mem_planeChartOpen originPoint

theorem mem_planeChartOpen_of_eq {y : projectiveProduct k} (hy : y = productOrigin) :
    y ∈ (planeChartOpen (k := k)).1 :=
  hy ▸ productOrigin_mem_planeChartOpen

/-- The section ring of the plane chart is `k[u][v]`. -/
def chartSectionEquiv : planeRing k ≃+* Γ(projectiveProduct k, (planeChartOpen (k := k)).1) :=
  (Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).symm.commRingCatIsoToRingEquiv.trans
    ((planeChart (k := k)).appIso ⊤).symm.commRingCatIsoToRingEquiv

/-- A polynomial as a section of `P¹ × P¹` on the plane chart. -/
def chartSection (r : planeRing k) : Γ(projectiveProduct k, (planeChartOpen (k := k)).1) :=
  chartSectionEquiv r

theorem chartSection_mul (a b : planeRing k) :
    chartSection (k := k) (a * b) = chartSection a * chartSection b :=
  map_mul chartSectionEquiv a b

/-- A point of the plane chart lies in the basic open of a polynomial iff the polynomial does not
vanish at it. -/
theorem base_mem_basicOpen_chartSection_iff (p : plane k) (r : planeRing k) :
    (planeChart (k := k)).base p ∈ (projectiveProduct k).basicOpen (chartSection r) ↔
      r ∉ p.asIdeal := by
  change p ∈ planeChart ⁻¹ᵁ (projectiveProduct k).basicOpen (chartSection r) ↔ _
  rw [Scheme.preimage_basicOpen]
  change p ∈ (plane k).basicOpen ((planeChart (k := k)).app (planeChart ''ᵁ ⊤)
    (((planeChart (k := k)).appIso ⊤).inv
      ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv r))) ↔ _
  rw [Scheme.Hom.appIso_inv_app_apply, Scheme.basicOpen_res_eq, basicOpen_eq_of_affine,
    PrimeSpectrum.mem_basicOpen]

theorem base_mem_zeroLocus_chartSection_iff (p : plane k) (r : planeRing k) :
    (planeChart (k := k)).base p ∈ (projectiveProduct k).zeroLocus {chartSection r} ↔
      r ∈ p.asIdeal := by
  rw [Scheme.mem_zeroLocus_iff]
  simp only [Set.mem_singleton_iff, forall_eq]
  rw [base_mem_basicOpen_chartSection_iff, not_not]

/-! ## The vanishing ideal of the union on the plane chart -/

/-- A point of the plane chart lies on the union of the two fibres iff `u v` vanishes at it. -/
theorem base_planeChart_mem_twoFibresLocus_iff (p : plane k) :
    (planeChart (k := k)).base p ∈ twoFibresLocus (k := k) ↔ uCoord * vCoord ∈ p.asIdeal := by
  rw [Ideal.IsPrime.mul_mem_iff_mem_or_mem p.isPrime]
  constructor
  · intro h
    obtain ⟨i, hi⟩ := Set.mem_iUnion.mp h
    fin_cases i
    · exact Or.inr ((base_planeChart_mem_range_horizontal_iff p).mp hi)
    · exact Or.inl ((base_planeChart_mem_range_vertical_iff p).mp hi)
  · rintro (hu | hv)
    · exact Set.mem_iUnion.mpr ⟨1, (base_planeChart_mem_range_vertical_iff p).mpr hu⟩
    · exact Set.mem_iUnion.mpr ⟨0, (base_planeChart_mem_range_horizontal_iff p).mpr hv⟩

theorem fromSpec_preimage_twoFibresLocus :
    (planeChartOpen (k := k)).2.fromSpec.base ⁻¹' twoFibresLocus (k := k) =
      PrimeSpectrum.zeroLocus {chartSection (uCoord * vCoord)} := by
  rw [← IsAffineOpen.fromSpec_preimage_zeroLocus]
  ext q
  simp only [Set.mem_preimage]
  have hqU : (planeChartOpen (k := k)).2.fromSpec.base q ∈
      ((planeChartOpen (k := k)).1 : Set (projectiveProduct k)) := by
    rw [← IsAffineOpen.range_fromSpec (planeChartOpen (k := k)).2]
    exact ⟨q, rfl⟩
  obtain ⟨p, hp⟩ := exists_of_mem_planeChartOpen ((planeChartOpen (k := k)).2.fromSpec.base q) hqU
  rw [← hp, base_planeChart_mem_twoFibresLocus_iff, base_mem_zeroLocus_chartSection_iff]

theorem uCoord_prime : Prime (uCoord (k := k)) := Polynomial.prime_C_iff.mpr Polynomial.prime_X

theorem uCoord_ne_zero : uCoord (k := k) ≠ 0 := Polynomial.C_ne_zero.mpr Polynomial.X_ne_zero

theorem span_uCoord_isPrime : (Ideal.span {uCoord (k := k)}).IsPrime :=
  (Ideal.span_singleton_prime uCoord_ne_zero).mpr uCoord_prime

theorem span_vCoord_isPrime : (Ideal.span {vCoord (k := k)}).IsPrime :=
  (Ideal.span_singleton_prime vCoord_ne_zero).mpr vCoord_prime

/-- `(u v) = (u) ∩ (v)` is a radical ideal of `k[u][v]`. -/
theorem span_uv_isRadical : (Ideal.span {uCoord (k := k) * vCoord}).IsRadical := by
  rw [← span_u_inf_span_v]
  exact span_uCoord_isPrime.isRadical.inf span_vCoord_isPrime.isRadical

theorem span_chartSection_uv_isRadical :
    (Ideal.span {chartSection (k := k) (uCoord * vCoord)}).IsRadical := by
  have h : Ideal.span {chartSection (k := k) (uCoord * vCoord)} =
      Ideal.map (chartSectionEquiv (k := k)) (Ideal.span {uCoord * vCoord}) := by
    rw [Ideal.map_span, Set.image_singleton]
    rfl
  rw [h, ← Ideal.comap_symm]
  exact span_uv_isRadical.comap _

/-- **The vanishing ideal of `x = 0 ∪ y = 0` on the plane chart is `(u v)`.** -/
theorem twoFibresIdeal_ideal_planeChartOpen :
    (twoFibresIdeal (k := k)).ideal planeChartOpen = Ideal.span {chartSection (uCoord * vCoord)} := by
  change PrimeSpectrum.vanishingIdeal
    ((planeChartOpen (k := k)).2.fromSpec.base ⁻¹' twoFibresLocus (k := k)) = _
  rw [fromSpec_preimage_twoFibresLocus, ← PrimeSpectrum.zeroLocus_span,
    PrimeSpectrum.vanishingIdeal_zeroLocus_eq_radical]
  exact Ideal.radical_eq_iff.mpr span_chartSection_uv_isRadical

/-! ## The germs of `u`, `v` -/

/-- Under the accepted stalk-localisation equivalence, the germ of a polynomial section is its
image in the localisation. -/
theorem stalkEquiv_germ_chartSection (p : plane k) (r : planeRing k) :
    openImmersionStalkLocalizationEquiv (planeChart (k := k)) p
      ((projectiveProduct k).presheaf.germ (planeChartOpen (k := k)).1 (planeChart.base p)
        (base_mem_planeChartOpen p) (chartSection r)) =
      algebraMap (planeRing k) (Localization.AtPrime p.asIdeal) r := by
  change specStalkLocalizationEquiv (planeRing k) p
    ((planeChart (k := k)).stalkMap p ((projectiveProduct k).presheaf.germ
      (planeChartOpen (k := k)).1 (planeChart.base p) (base_mem_planeChartOpen p)
        (chartSection r))) = _
  rw [Scheme.stalkMap_germ_apply]
  change specStalkLocalizationEquiv (planeRing k) p ((plane k).presheaf.germ
    (planeChart ⁻¹ᵁ (planeChart ''ᵁ ⊤)) p (base_mem_planeChartOpen p)
      ((planeChart (k := k)).app (planeChart ''ᵁ ⊤) (((planeChart (k := k)).appIso ⊤).inv
        ((Scheme.ΓSpecIso (CommRingCat.of (planeRing k))).inv r)))) = _
  rw [Scheme.Hom.appIso_inv_app_apply, TopCat.Presheaf.germ_res_apply']
  change StructureSheaf.stalkToFiberRingHom (planeRing k) p
    (StructureSheaf.toStalk (planeRing k) p r) = _
  exact StructureSheaf.stalkToFiberRingHom_toStalk _ p r

theorem originU_eq_germ :
    originU (k := k) = (projectiveProduct k).presheaf.germ (planeChartOpen (k := k)).1 productOrigin
      productOrigin_mem_planeChartOpen (chartSection uCoord) := by
  apply (originStalkEquiv (k := k)).injective
  rw [originU, RingEquiv.apply_symm_apply]
  exact (stalkEquiv_germ_chartSection originPoint uCoord).symm

theorem originV_eq_germ :
    originV (k := k) = (projectiveProduct k).presheaf.germ (planeChartOpen (k := k)).1 productOrigin
      productOrigin_mem_planeChartOpen (chartSection vCoord) := by
  apply (originStalkEquiv (k := k)).injective
  rw [originV, RingEquiv.apply_symm_apply]
  exact (stalkEquiv_germ_chartSection originPoint vCoord).symm

/-- The germ of `u` at a point equal to the origin. -/
def germU {y : projectiveProduct k} (hy : y = productOrigin) :
    (projectiveProduct k).presheaf.stalk y :=
  (projectiveProduct k).presheaf.germ (planeChartOpen (k := k)).1 y (mem_planeChartOpen_of_eq hy)
    (chartSection uCoord)

/-- The germ of `v` at a point equal to the origin. -/
def germV {y : projectiveProduct k} (hy : y = productOrigin) :
    (projectiveProduct k).presheaf.stalk y :=
  (projectiveProduct k).presheaf.germ (planeChartOpen (k := k)).1 y (mem_planeChartOpen_of_eq hy)
    (chartSection vCoord)

/-- The germs of `u`, `v` generate the maximal ideal at any point equal to the origin. -/
theorem span_germU_germV {y : projectiveProduct k} (hy : y = productOrigin) :
    Ideal.span {germU hy, germV hy} = maximalIdeal ((projectiveProduct k).presheaf.stalk y) := by
  subst hy
  rw [← span_originU_originV, originU_eq_germ, originV_eq_germ]
  rfl

/-! ## The kernel of the stalk map of a glued closed subscheme -/

/-- The kernel of the stalk map of the glued closed subscheme at `z` is generated by the germs of
`I(U)`, for any affine `U` containing `ι z` (germ description; the accepted
`stalkMap_gluedTo_ker_eq_span` needs generators on every smaller affine open, this form needs
only `map_ideal_basicOpen`). -/
theorem ker_stalkMap_gluedTo_eq_map_germ {Y : Scheme.{u}} (I : Y.IdealSheafData)
    {z : I.glueData.glued} (U : Y.affineOpens) (hy : I.gluedTo.base z ∈ U.1) :
    RingHom.ker (I.gluedTo.stalkMap z).hom =
      (I.ideal U).map (Y.presheaf.germ U.1 (I.gluedTo.base z) hy).hom := by
  apply le_antisymm
  · intro a ha
    obtain ⟨W, hzW, s, rfl⟩ := Y.presheaf.germ_exist (I.gluedTo.base z) a
    have ha' : I.gluedTo.stalkMap z (Y.presheaf.germ W (I.gluedTo.base z) hzW s) = 0 := ha
    rw [Scheme.stalkMap_germ_apply] at ha'
    have h0 : I.glueData.glued.presheaf.germ (I.gluedTo ⁻¹ᵁ W) z hzW (I.gluedTo.app W s) =
        I.glueData.glued.presheaf.germ ⊤ z trivial 0 := by
      rw [ha', map_zero]
    obtain ⟨W', hzW', iU, iV, hW'⟩ :=
      TopCat.Presheaf.germ_eq (V := ⊤) I.glueData.glued.presheaf z hzW trivial _ _ h0
    obtain ⟨V', hV'open, hV'⟩ :=
      (IsClosedImmersion.base_closed (f := I.gluedTo)).toIsEmbedding.toIsInducing.isOpen_iff.mp
        W'.isOpen
    let V'op : Y.Opens := ⟨V', hV'open⟩
    have hyV' : I.gluedTo.base z ∈ V'op := by
      have : z ∈ I.gluedTo.base ⁻¹' V' := by rw [hV']; exact hzW'
      exact this
    have hyU' : I.gluedTo.base z ∈ (U.1 ⊓ W ⊓ V'op : Y.Opens) := ⟨⟨hy, hzW⟩, hyV'⟩
    obtain ⟨f, hfle, hyf⟩ := U.2.exists_basicOpen_le ⟨I.gluedTo.base z, hyU'⟩ hy
    have hVU : Y.basicOpen f ≤ U.1 := Y.basicOpen_le f
    have hVW : Y.basicOpen f ≤ W := fun x hx => (hfle hx).1.2
    have hVV' : Y.basicOpen f ≤ V'op := fun x hx => (hfle hx).2
    have hyV : I.gluedTo.base z ∈ Y.basicOpen f := hyf
    have hj₁ : I.gluedTo ⁻¹ᵁ Y.basicOpen f ≤ W' := by
      intro w hw
      have : w ∈ I.gluedTo.base ⁻¹' V' := hVV' hw
      show w ∈ (W' : Set I.glueData.glued)
      rw [← hV']
      exact this
    have hmem : Y.presheaf.map (homOfLE hVW).op s ∈
        RingHom.ker (I.gluedTo.app (Y.basicOpen f)).hom := by
      rw [RingHom.mem_ker]
      have hnat : I.gluedTo.app (Y.basicOpen f) (Y.presheaf.map (homOfLE hVW).op s) =
          I.glueData.glued.presheaf.map ((Opens.map I.gluedTo.base).map (homOfLE hVW)).op
            (I.gluedTo.app W s) :=
        ConcreteCategory.congr_hom (I.gluedTo.naturality ((homOfLE hVW).op : op W ⟶ op _)) s
      have hfac : (Opens.map I.gluedTo.base).map (homOfLE hVW) =
          (homOfLE hj₁ : I.gluedTo ⁻¹ᵁ Y.basicOpen f ⟶ W') ≫ iU := Subsingleton.elim _ _
      change I.gluedTo.app (Y.basicOpen f) (Y.presheaf.map (homOfLE hVW).op s) = 0
      rw [hnat, hfac, op_comp, Functor.map_comp]
      erw [CommRingCat.comp_apply]
      rw [hW', map_zero, map_zero]
    have hker := I.ker_gluedTo_app (Y.affineBasicOpen f)
    change RingHom.ker (I.gluedTo.app (Y.basicOpen f)).hom = I.ideal (Y.affineBasicOpen f) at hker
    rw [hker, ← I.map_ideal_basicOpen U f] at hmem
    have hcomp : (Y.presheaf.germ (Y.basicOpen f) (I.gluedTo.base z) hyV).hom.comp
        (Y.presheaf.map (homOfLE (Y.basicOpen_le f)).op).hom =
          (Y.presheaf.germ U.1 (I.gluedTo.base z) hy).hom := by
      rw [← CommRingCat.hom_comp, Y.presheaf.germ_res]
    have := Ideal.mem_map_of_mem (Y.presheaf.germ (Y.basicOpen f) (I.gluedTo.base z) hyV).hom hmem
    rw [Ideal.map_map, hcomp] at this
    rw [← Y.presheaf.germ_res_apply (homOfLE hVW) (I.gluedTo.base z) hyV s]
    exact this
  · rw [Ideal.map_le_iff_le_comap]
    intro s hs
    rw [Ideal.mem_comap, RingHom.mem_ker]
    have happ : I.gluedTo.app U.1 s = 0 := by
      have h := I.ker_gluedTo_app U
      have : s ∈ RingHom.ker (I.gluedTo.app U.1).hom := by rw [h]; exact hs
      exact this
    show I.gluedTo.stalkMap z (Y.presheaf.germ U.1 (I.gluedTo.base z) hy s) = 0
    rw [Scheme.stalkMap_germ_apply, happ, map_zero]

/-! ## The crossing at the node -/

/-- **The kernel of the stalk map of the union at the node is `(u v)`.** -/
theorem ker_stalkMap_node :
    RingHom.ker ((twoFibresInclusion (k := k)).stalkMap twoFibresNode).hom =
      Ideal.span {germU node_eq_productOrigin * germV node_eq_productOrigin} := by
  refine (ker_stalkMap_gluedTo_eq_map_germ (twoFibresIdeal (k := k)) planeChartOpen
    (mem_planeChartOpen_of_eq node_eq_productOrigin)).trans ?_
  have hmul : (projectiveProduct k).presheaf.germ (planeChartOpen (k := k)).1 _
      (mem_planeChartOpen_of_eq node_eq_productOrigin) (chartSection (uCoord * vCoord)) =
      germU node_eq_productOrigin * germV node_eq_productOrigin := by
    unfold germU germV
    rw [chartSection_mul, map_mul]
  rw [twoFibresIdeal_ideal_planeChartOpen, Ideal.map_span, Set.image_singleton]
  exact congrArg (fun a => Ideal.span {a}) hmul

/-- The affine chart of the union through the node: the preimage of the plane chart. -/
def nodeChart : (twoFibresScheme (k := k)).affineOpens :=
  ⟨twoFibresInclusion ⁻¹ᵁ (planeChartOpen (k := k)).1, by
    haveI : IsAffine (planeChartOpen (k := k)).1.toScheme := (planeChartOpen (k := k)).2
    haveI : IsClosedImmersion (twoFibresInclusion (k := k) ∣_ (planeChartOpen (k := k)).1) :=
      IsLocalAtTarget.restrict (P := @IsClosedImmersion) inferInstance _
    exact (IsClosedImmersion.isAffine_surjective_of_isAffine
      (twoFibresInclusion (k := k) ∣_ (planeChartOpen (k := k)).1)).1⟩

theorem node_mem_nodeChart : twoFibresNode (k := k) ∈ (nodeChart (k := k)).1 :=
  mem_planeChartOpen_of_eq node_eq_productOrigin

/-- A polynomial vanishing on the chart points of the `i`-th fibre restricts into the chart ideal
of the `i`-th component of the union. -/
theorem app_chartSection_mem_componentChartIdeal (i : Fin 2) (r : planeRing k)
    (hr : ∀ p : plane k, (planeChart (k := k)).base p ∈ Set.range (fibre (k := k) i).base →
      r ∈ p.asIdeal) :
    (twoFibresInclusion (k := k)).app (planeChartOpen (k := k)).1 (chartSection r) ∈
      componentChartIdeal (twoFibresScheme (k := k)) {twoFibresComponent i} nodeChart := by
  rw [componentChartIdeal_eq, coe_componentClosedUnion_singleton, PrimeSpectrum.mem_vanishingIdeal]
  intro P hP
  have hxU : (nodeChart (k := k)).2.fromSpec.base P ∈
      ((nodeChart (k := k)).1 : Set (twoFibresScheme (k := k))) := by
    rw [← IsAffineOpen.range_fromSpec (nodeChart (k := k)).2]
    exact ⟨P, rfl⟩
  have hxC : (nodeChart (k := k)).2.fromSpec.base P ∈ (twoFibresComponent (k := k) i).1 := hP
  rw [twoFibresComponent_val, range_twoFibresCurve_eq] at hxC
  obtain ⟨p, hp⟩ := exists_of_mem_planeChartOpen _ hxU
  have hr' : r ∈ p.asIdeal := hr p (by rw [hp]; exact hxC)
  have hz : (twoFibresInclusion (k := k)).base ((nodeChart (k := k)).2.fromSpec.base P) ∈
      (projectiveProduct k).zeroLocus {chartSection r} := by
    rw [← hp]
    exact (base_mem_zeroLocus_chartSection_iff p r).mpr hr'
  have hz' : (nodeChart (k := k)).2.fromSpec.base P ∈ (twoFibresScheme (k := k)).zeroLocus
      {(twoFibresInclusion (k := k)).app (planeChartOpen (k := k)).1 (chartSection r)} := by
    rw [Scheme.mem_zeroLocus_iff] at hz ⊢
    intro f hf
    rw [Set.mem_singleton_iff] at hf
    subst hf
    rw [← Scheme.preimage_basicOpen]
    exact hz _ (Set.mem_singleton _)
  have hP' : P ∈ (nodeChart (k := k)).2.fromSpec.base ⁻¹' (twoFibresScheme (k := k)).zeroLocus
      {(twoFibresInclusion (k := k)).app (planeChartOpen (k := k)).1 (chartSection r)} := hz'
  rw [IsAffineOpen.fromSpec_preimage_zeroLocus, PrimeSpectrum.mem_zeroLocus,
    Set.singleton_subset_iff] at hP'
  exact hP'

/-- The germ of `u` restricts into the stalk ideal of the component `x = 0`. -/
theorem stalkMap_germU_mem :
    ((twoFibresInclusion (k := k)).stalkMap twoFibresNode).hom (germU node_eq_productOrigin) ∈
      (componentChartIdeal (twoFibresScheme (k := k)) {twoFibresComponent 1} nodeChart).map
        ((twoFibresScheme (k := k)).presheaf.germ nodeChart.1 twoFibresNode node_mem_nodeChart).hom := by
  unfold germU
  rw [Scheme.stalkMap_germ_apply]
  exact Ideal.mem_map_of_mem _ (app_chartSection_mem_componentChartIdeal 1 uCoord
    fun p hp => (base_planeChart_mem_range_vertical_iff p).mp hp)

/-- The germ of `v` restricts into the stalk ideal of the component `y = 0`. -/
theorem stalkMap_germV_mem :
    ((twoFibresInclusion (k := k)).stalkMap twoFibresNode).hom (germV node_eq_productOrigin) ∈
      (componentChartIdeal (twoFibresScheme (k := k)) {twoFibresComponent 0} nodeChart).map
        ((twoFibresScheme (k := k)).presheaf.germ nodeChart.1 twoFibresNode node_mem_nodeChart).hom := by
  unfold germV
  rw [Scheme.stalkMap_germ_apply]
  exact Ideal.mem_map_of_mem _ (app_chartSection_mem_componentChartIdeal 0 vCoord
    fun p hp => (base_planeChart_mem_range_horizontal_iff p).mp hp)

/-- **The two fibres cross transversally at the node.** -/
theorem twoFibresCrossing : TwoFibresCrossing (k := k) :=
  (TransversalCrossing.ofChart (twoFibresInclusion (k := k)) (twoFibresComponent 1)
    (twoFibresComponent 0) twoFibresNode nodeStalk_regularLocal nodeStalk_ringKrullDim
    (germU node_eq_productOrigin) (germV node_eq_productOrigin)
    (span_germU_germV node_eq_productOrigin) ker_stalkMap_node nodeChart node_mem_nodeChart
    stalkMap_germU_mem stalkMap_germV_mem).symm

/-- The union of the two fibres is a transversal configuration in `P¹ × P¹`. -/
theorem twoFibres_transversalConfiguration' :
    TransversalConfiguration (twoFibresInclusion (k := k)) :=
  twoFibres_transversalConfiguration twoFibresCrossing

/-! ## Witness (b) -/

section Picard

variable [IsAlgClosed k]

/-- **Witness (b)**: the multidegree map of `x = 0 ∪ y = 0` is bijective. -/
theorem twoFibres_rationalTreePicard' :
    Function.Bijective (multidegreeHom k (twoFibresScheme (k := k))
      (lineIdentification (twoFibresScheme (k := k)) twoFibresCurve twoFibresCurve_cover
        twoFibresCurve_distinct)) :=
  twoFibres_rationalTreePicard twoFibresCrossing

/-- **Witness (b)**: `Pic(x = 0 ∪ y = 0) ≃* ℤ²`. -/
def twoFibresPicardEquiv' : (twoFibresScheme (k := k)).Pic ≃* (Fin 2 → Multiplicative ℤ) :=
  twoFibresPicardEquiv twoFibresCrossing

/-- **Witness (b), degree-zero clause**: a line bundle on `x = 0 ∪ y = 0` with exponent zero on
both fibres is trivial. -/
theorem twoFibres_trivial_of_degree_zero' (L : InvertibleSheaf (twoFibresScheme (k := k)))
    (hL : ∀ i : ULift.{u} (Fin 2), componentExponent k (twoFibresScheme (k := k))
      {lineComponent (twoFibresScheme (k := k)) twoFibresCurve twoFibresCurve_cover
        twoFibresCurve_distinct i}
      (lineIdentification (twoFibresScheme (k := k)) twoFibresCurve twoFibresCurve_cover
        twoFibresCurve_distinct
        (lineComponent (twoFibresScheme (k := k)) twoFibresCurve twoFibresCurve_cover
          twoFibresCurve_distinct i)) L = 0) :
    Nonempty (L.obj ≅ _root_.SheafOfModules.unit (twoFibresScheme (k := k)).ringCatSheaf) :=
  twoFibres_trivial_of_degree_zero twoFibresCrossing L hL

/-- Universe check at universe `0`. -/
example (k₀ : Type) [Field k₀] [IsAlgClosed k₀] :
    (twoFibresScheme (k := k₀)).Pic ≃* (Fin 2 → Multiplicative ℤ) :=
  twoFibresPicardEquiv'

end Picard

end KltDP.Examples.RationalTreePicardWitnessTwoFibres
