import KltDP.Examples.RationalTreePicardWitnessTwoFibres
import KltDP.Examples.FrobeniusTranslatedCharts

/-!
# The node of the two fibres: identification with the origin and the local data of the crossing

BRIEF21, task 2 (continued). The node `twoFibresNode` of the union `x = 0 ∪ y = 0` maps to the
origin of the polynomial plane chart (`node_eq_productOrigin`): the rational points
`originMorphism ≫ planeChart` and `pointMorphism 0 ≫ horizontalFiberMorphism 0` of `P¹ × P¹` agree
(`originMorphism_planeChart`, by `pullback.hom_ext`: both projections are `pointMorphism 0`, since
evaluation at the origin composed with either coordinate map `k[t] → k[u][v]` is evaluation at
`0` and the accepted `polynomialChartMap_evaluation` identifies `Spec (eval 0) ≫ polynomialChartMap`
with `pointMorphism 0`). Transporting `ProjectiveProductOriginStalkRegular` along this equality,
the ambient stalk at the node is regular of dimension two and its maximal ideal is generated by
the germs `nodeU`, `nodeV` of `u`, `v` (`nodeStalk_regularLocal`, `nodeStalk_ringKrullDim`,
`span_nodeU_nodeV`). In the polynomial plane `(u) ⊓ (v) = (uv)` (`span_u_inf_span_v`).

`twoFibresCrossing_of_ker_of_mem` packages what is left of the crossing `TwoFibresCrossing`: the
kernel of the stalk map of the inclusion at the node is `(nodeU · nodeV)`, and the germs of `u`,
`v` on an affine chart of the union through the node lie in the chart ideals of the components
`x = 0`, `y = 0` respectively. These two inputs (the stalk kernel of the glued vanishing ideal —
the chart ideal `(u) ∩ (v) = (uv)` of the union on the plane chart, transported to the stalk — and
the component-ideal memberships) are NOT proved here; see `LEMMA22_PROGRESS.md`, Task 21.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing CategoryTheory.Limits

universe u

namespace KltDP.Examples.RationalTreePicardWitnessTwoFibres

open KltDP.Geometry KltDP.Geometry.RationalTreePicard
open FrobeniusProjectivePoints FrobeniusGraphClosed FrobeniusGraphPicardClassZeroFiber
  FrobeniusUnaffectedFibers FrobeniusBlowupContact FrobeniusBlowupChartIteration
  FrobeniusProductPlaneChart FrobeniusTranslatedCharts ProjectiveProductOriginStalkRegular
  ProjectiveLineComparison

variable {k : Type u} [Field k]

/-! ## The node is the origin of the plane chart -/

/-- Evaluation at the origin after the first coordinate map `u` is evaluation at `0`. -/
theorem originEvaluation_comp_firstCoordinateMap :
    (originEvaluation (k := k)).comp firstCoordinateMap = Polynomial.evalRingHom 0 := by
  apply Polynomial.ringHom_ext
  · intro r
    simp [originEvaluation, firstCoordinateMap]
  · simp [originEvaluation, firstCoordinateMap]

/-- Evaluation at the origin after the second coordinate map `v` is evaluation at `0`. -/
theorem originEvaluation_comp_secondCoordinateMap :
    (originEvaluation (k := k)).comp secondCoordinateMap = Polynomial.evalRingHom 0 := by
  apply Polynomial.ringHom_ext
  · intro r
    simp [originEvaluation, secondCoordinateMap]
  · simp [originEvaluation, secondCoordinateMap]

theorem originMorphism_firstCoordinate :
    originMorphism (k := k) ≫ Spec.map (CommRingCat.ofHom firstCoordinateMap) =
      Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : k))) := by
  rw [originMorphism, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
    originEvaluation_comp_firstCoordinateMap]

theorem originMorphism_secondCoordinate :
    originMorphism (k := k) ≫ Spec.map (CommRingCat.ofHom secondCoordinateMap) =
      Spec.map (CommRingCat.ofHom (Polynomial.evalRingHom (0 : k))) := by
  rw [originMorphism, ← Spec.map_comp, ← CommRingCat.ofHom_comp,
    originEvaluation_comp_secondCoordinateMap]

/-- The origin of the plane chart is the rational point `([1:0], [1:0])` of the horizontal
fibre `y = 0`. -/
theorem originMorphism_planeChart :
    originMorphism ≫ planeChart (k := k) = pointMorphism 0 ≫ horizontalFiberMorphism 0 := by
  apply pullback.hom_ext
  · rw [Category.assoc, Category.assoc, planeChart_fst, horizontalFiberMorphism_fst,
      Category.comp_id, ← Category.assoc originMorphism, originMorphism_firstCoordinate,
      polynomialChartMap_evaluation]
  · rw [Category.assoc, Category.assoc, planeChart_snd, horizontalFiberMorphism_snd,
      ← Category.assoc (pointMorphism 0), pointMorphism_over_base, Category.id_comp,
      ← Category.assoc originMorphism, originMorphism_secondCoordinate,
      polynomialChartMap_evaluation]

/-- The origin of the plane chart is the point `([1:0], [1:0])` of the horizontal fibre. -/
theorem productOrigin_eq_horizontal_q₀ :
    productOrigin (k := k) = (horizontalFiberMorphism (0 : k)).base q₀ := by
  have h : (originMorphism ≫ planeChart (k := k)).base (IsLocalRing.closedPoint k) =
      (pointMorphism 0 ≫ horizontalFiberMorphism 0).base (IsLocalRing.closedPoint k) := by
    rw [originMorphism_planeChart]
  rw [Scheme.comp_base_apply, Scheme.comp_base_apply] at h
  unfold productOrigin q₀
  rw [← originMorphism_point]
  unfold fieldMorphismPoint
  rw [h]
  exact congrArg _ (congrArg _ (spec_subsingleton _ _))

/-- The node of the union of the two fibres is the origin of the plane chart. -/
theorem node_eq_productOrigin :
    (twoFibresInclusion (k := k)).base twoFibresNode = productOrigin :=
  twoFibresInclusion_node.trans productOrigin_eq_horizontal_q₀.symm

/-! ## The ambient stalk at the node -/

/-- The stalk equivalence at any point equal to the origin. -/
def originStalkEquivAt (p : projectiveProduct k) (hp : p = productOrigin) :
    (projectiveProduct k).presheaf.stalk p ≃+* originLocalRing (k := k) := by
  subst hp
  exact originStalkEquiv

theorem originStalk_regularLocal_at (p : projectiveProduct k) (hp : p = productOrigin) :
    RegularLocal ((projectiveProduct k).presheaf.stalk p) :=
  regularLocal_of_ringEquiv (originStalkEquivAt p hp).symm originLocalRing_regularLocal

theorem originStalk_ringKrullDim_at (p : projectiveProduct k) (hp : p = productOrigin) :
    ringKrullDim ((projectiveProduct k).presheaf.stalk p) = 2 :=
  (ringKrullDim_eq_of_ringEquiv (originStalkEquivAt p hp)).trans ringKrullDim_originLocalRing

/-- The germ of `u` at a point equal to the origin. -/
def originU_at (p : projectiveProduct k) (hp : p = productOrigin) :
    (projectiveProduct k).presheaf.stalk p :=
  (originStalkEquivAt p hp).symm (algebraMap (planeRing k) (originLocalRing (k := k)) uCoord)

/-- The germ of `v` at a point equal to the origin. -/
def originV_at (p : projectiveProduct k) (hp : p = productOrigin) :
    (projectiveProduct k).presheaf.stalk p :=
  (originStalkEquivAt p hp).symm (algebraMap (planeRing k) (originLocalRing (k := k)) vCoord)

theorem map_symm_maximalIdeal_at (p : projectiveProduct k) (hp : p = productOrigin) :
    Ideal.map (originStalkEquivAt p hp).symm (maximalIdeal (originLocalRing (k := k))) =
      maximalIdeal ((projectiveProduct k).presheaf.stalk p) := by
  apply IsLocalRing.eq_maximalIdeal
  rw [← Ideal.comap_symm, RingEquiv.symm_symm]
  exact Ideal.comap_isMaximal_of_surjective (f := originStalkEquivAt p hp)
    (originStalkEquivAt p hp).surjective

theorem span_originU_originV_at (p : projectiveProduct k) (hp : p = productOrigin) :
    Ideal.span {originU_at p hp, originV_at p hp} =
      maximalIdeal ((projectiveProduct k).presheaf.stalk p) := by
  rw [← map_symm_maximalIdeal_at p hp, ← span_uv_eq_maximalIdeal, Ideal.map_span,
    Set.image_insert_eq, Set.image_singleton]
  rfl

/-- The germ of `u` at the image of the node. -/
def nodeU : (projectiveProduct k).presheaf.stalk ((twoFibresInclusion (k := k)).base twoFibresNode) :=
  originU_at _ node_eq_productOrigin

/-- The germ of `v` at the image of the node. -/
def nodeV : (projectiveProduct k).presheaf.stalk ((twoFibresInclusion (k := k)).base twoFibresNode) :=
  originV_at _ node_eq_productOrigin

theorem nodeStalk_regularLocal :
    RegularLocal ((projectiveProduct k).presheaf.stalk
      ((twoFibresInclusion (k := k)).base twoFibresNode)) :=
  originStalk_regularLocal_at _ node_eq_productOrigin

theorem nodeStalk_ringKrullDim :
    ringKrullDim ((projectiveProduct k).presheaf.stalk
      ((twoFibresInclusion (k := k)).base twoFibresNode)) = 2 :=
  originStalk_ringKrullDim_at _ node_eq_productOrigin

theorem span_nodeU_nodeV :
    Ideal.span {nodeU (k := k), nodeV (k := k)} =
      maximalIdeal ((projectiveProduct k).presheaf.stalk
        ((twoFibresInclusion (k := k)).base twoFibresNode)) :=
  span_originU_originV_at _ node_eq_productOrigin

/-! ## `(u) ∩ (v) = (uv)` in the polynomial plane -/

theorem span_u_inf_span_v :
    Ideal.span {uCoord (k := k)} ⊓ Ideal.span {vCoord (k := k)} =
      Ideal.span {uCoord (k := k) * vCoord (k := k)} := by
  apply le_antisymm
  · intro x hx
    obtain ⟨hu, hv⟩ := Ideal.mem_inf.mp hx
    rw [Ideal.mem_span_singleton] at hu hv ⊢
    obtain ⟨a, rfl⟩ := hu
    rcases vCoord_prime.dvd_or_dvd hv with h | h
    · exact absurd (Ideal.mem_span_singleton.mpr h) uCoord_not_mem_span_vCoord
    · obtain ⟨b, rfl⟩ := h
      exact ⟨b, by ring⟩
  · rw [Ideal.span_le]
    exact Set.singleton_subset_iff.mpr (Ideal.mem_inf.mpr
      ⟨Ideal.mem_span_singleton.mpr (dvd_mul_right _ _),
        Ideal.mem_span_singleton.mpr (dvd_mul_left _ _)⟩)

/-! ## What remains of the crossing -/

/-- **Reduction of the crossing to its two remaining inputs.** Given that the kernel of the
stalk map of the inclusion at the node is `(u v)` and that the germs of `u`, `v` lie in the chart
ideals of the components `x = 0`, `y = 0` on an affine chart of the union through the node, the
crossing is transversal (`TransversalCrossing.ofChart` with the regular two-dimensional stalk of
`ProjectiveProductOriginStalkRegular`). -/
theorem twoFibresCrossing_of_ker_of_mem
    (hker : RingHom.ker ((twoFibresInclusion (k := k)).stalkMap twoFibresNode).hom =
      Ideal.span {nodeU (k := k) * nodeV (k := k)})
    (U : (twoFibresScheme (k := k)).affineOpens) (hq : twoFibresNode ∈ U.1)
    (hf : ((twoFibresInclusion (k := k)).stalkMap twoFibresNode).hom nodeU ∈
      (componentChartIdeal (twoFibresScheme (k := k)) {twoFibresComponent 1} U).map
        ((twoFibresScheme (k := k)).presheaf.germ U.1 twoFibresNode hq).hom)
    (hg : ((twoFibresInclusion (k := k)).stalkMap twoFibresNode).hom nodeV ∈
      (componentChartIdeal (twoFibresScheme (k := k)) {twoFibresComponent 0} U).map
        ((twoFibresScheme (k := k)).presheaf.germ U.1 twoFibresNode hq).hom) :
    TwoFibresCrossing (k := k) :=
  (TransversalCrossing.ofChart (twoFibresInclusion (k := k)) (twoFibresComponent 1)
    (twoFibresComponent 0) twoFibresNode nodeStalk_regularLocal nodeStalk_ringKrullDim nodeU nodeV
    span_nodeU_nodeV hker U hq hf hg).symm

end KltDP.Examples.RationalTreePicardWitnessTwoFibres
