import KltDP.Literature.Tanaka.ContractionTheorem
import KltDP.Geometry.CurveConeExtremal
import KltDP.Geometry.SteinTargetIntegral
import KltDP.Geometry.ProperSteinConnected
import KltDP.Geometry.ActualExceptionalLocus
import KltDP.Geometry.IsomorphismCanonicalNumericalInvariants
import KltDP.Geometry.SurfaceNumericalFinitenessProved
import KltDP.Geometry.RegularPointsOnIsomorphismOpen
import KltDP.Geometry.BirationalAmplePullbackPositiveSquare
import KltDP.Geometry.ActualExceptionalPullback
import KltDP.Geometry.ArithmeticCurveAdjunction
import KltDP.Geometry.GenusZeroCurveProjectiveLineIso
import KltDP.Geometry.RegularSurfaceSmoothLiteralUse
import KltDP.Geometry.FiniteTypeNoetherian
import KltDP.Geometry.ProjectiveProper
import KltDP.Topology.DimensionTwoIrreducibleClosed

/-!
# The contraction input of the nef threshold (manuscript Lemma 3.3, `lem:nef-threshold`)

Manuscript `source/manuscript.tex`, lines 754–823. The proof of Lemma 3.3 starts by applying
Tanaka's Theorem 4.4 (the single literature instance
`KltDP.Literature.Tanaka.contraction_44_instance`) to the regular projective surface `S` with
`Δ = 0`:

> "Every `K_S`-negative extremal ray contracts by a projective morphism `f : S → Y` with
> `f_*O_S = O_Y` and `ρ(Y) = ρ(S) − 1 > 1`. Thus `dim Y = 2`: a projective integral curve has
> Picard number one, and a point has Picard number zero. The morphism is birational and has an
> exceptional curve `E`. Then `E² < 0` and `K_S · E < 0`, so adjunction makes `E` a smooth
> rational `(−1)`-curve generating that ray. [...] Such a ray exists since `K_S · L = −L² < 0`
> makes `K_S` nonnef. Here one uses the standard compact ample slice of the closed curve cone to
> detect nonnefness on an extremal ray. [...] If `N = L + ℓK_S` were nonnef, choose an
> `N`-negative extremal ray. Since `L` is nef, that ray is `K_S`-negative and hence generated by
> an exterior `(−1)`-curve `E`. But `N · E = L · E − ℓ ≥ 0`, a contradiction."

This module proves exactly these three steps for an actual regular normal projective surface
`S` over an algebraically closed field with `N¹(S)_ℚ` finite dimensional and `ρ(S) > 2`:

* `exists_minusOneCurve_of_extremalRay` (C1): every `K_S`-negative extremal ray of `NE(S)‾` is
  generated by an actual `(−1)`-curve.
* `exists_minusOneCurve_of_not_nef` (C3): if `K_S` is not nef, a `(−1)`-curve exists.
* `nef_of_minusOne_nonneg` (C2): for a nef Cartier divisor `L` and `ℓ ≥ 0`, if
  `(L + ℓ K_S) · E ≥ 0` for every `(−1)`-curve `E`, then `L + ℓ K_S` is nef (nonnegative on
  every prime curve). The manuscript's `ℓ = ℓ_ext` and the adjective "exterior" are supplied by
  the consumer: exterior `(−1)`-curves are the only `(−1)`-curves on a minimal resolution, and the
  hypothesis `(L + ℓK_S) · E ≥ 0` for them is `L · E ≥ ℓ`, the definition of the minimum.

## The argument formalised (C1)

From the axiom: `Y`, `g : Y → Spec k` projective, `f : S → Y` over `k` with `f^♯ : O_Y ≅ f_*O_S`,
contracted prime curves are exactly those on the ray, and `ρ(Y) + 1 = ρ(S)`.

1. `f` is proper (`S` is proper over `k`, `Y` separated) and surjective: the complement of its
   closed image is an open `U` with `f⁻¹U = ∅`, so `O_Y(U) ≅ O_S(∅) = 0`, which forces `U = ∅`
   (`surjective_of_isIso_c`). `Y` is integral and normal (`SteinTargetIntegral`).
2. `dim Y = 2`: a closed continuous surjection from a Noetherian space cannot raise the Krull
   dimension (chain lifting through minimal closed subsets mapping onto each member,
   `topologicalKrullDim_le_of_surjective_of_isClosedMap`), so `dim Y ≤ dim S = 2`; and
   `dim Y ≤ 1` would give `ρ(Y) ≤ 1` (`NumericalOneCycles.rhoReal_le_one_of_dim_le_one`),
   contradicting `ρ(Y) = ρ(S) − 1 ≥ 2`. Hence `Y` is an actual `NormalProjectiveSurface`.
3. `f` is birational (`isBirationalScheme_of_isIso_c`): it maps the generic point to the generic
   point (surjectivity), and the stalk map at the generic point is injective (germs on the
   integral `S`) and surjective: a section of `O_S` on `V ∋ η_S` is a section of
   `O_Y ≅ f_*O_S` on the open `Y ∖ f(S ∖ V)`, which contains `η_Y` because `f(S ∖ V)` has
   dimension `≤ dim (S ∖ V) ≤ 1 < 2 = dim Y`.
4. Some prime curve is contracted (`exists_isExceptionalCurve_of_rhoReal`): otherwise, by Zariski
   connectedness of the fibres (`ProperSteinConnected`) and the union's description of the
   non-isomorphism locus as the union of the contracted curves (`ActualExceptionalLocus`), `f` is
   an isomorphism; then `Y` is regular and `ρ(Y) = ρ(S)` (`NumericalOneCycles.rhoReal_eq_picardRank`
   and `IsomorphismSurfaceInvariants.picardRank_eq`), contradicting `ρ(Y) + 1 = ρ(S)`.
5. For a contracted curve `E`: `E² < 0` by Hodge index, since `E · f^*A = 0` and `(f^*A)² > 0`
   for an ample `A` on `Y` (`selfIntersectionNumber_neg_of_isExceptionalCurve`); `K_S · E < 0`
   because `[E] = t v` with `t > 0` on the `K_S`-negative ray; adjunction
   `K_S · E = 2p_a(E) − 2 − E²` forces `p_a(E) = 0`, `E² = K_S · E = −1`, and a proper integral
   curve of arithmetic genus zero is `P¹` (`isMinusOneCurve_of_neg`).
-/

set_option autoImplicit false
set_option linter.unusedSectionVars false

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace
open KltDP.Geometry KltDP.Geometry.NormalProjectiveSurface KltDP.Geometry.CurveCone
open KltDP.Geometry.NefNullCurveNegativeSquare

universe u

namespace KltDP.Manuscript.S03

namespace NefThresholdCore

/-! ### Topology: a closed continuous surjection from a Noetherian space cannot raise the
Krull dimension -/

section Topology

variable {X Y : Type*} [TopologicalSpace X] [TopologicalSpace Y]

/-- A minimal closed subset of `A` mapping onto an irreducible closed `Z ⊆ f(A)` is irreducible
(`X` Noetherian, `f` continuous and closed). -/
theorem exists_irreducibleCloseds_image_eq [NoetherianSpace X] {f : X → Y}
    (hf : Continuous f) (hc : IsClosedMap f) (A : Set X) (hA : IsClosed A)
    (Z : IrreducibleCloseds Y) (hZA : (Z : Set Y) ⊆ f '' A) :
    ∃ W : IrreducibleCloseds X, (W : Set X) ⊆ A ∧ f '' (W : Set X) = Z := by
  classical
  let P : Set (Closeds X) := {W | (W : Set X) ⊆ A ∧ f '' (W : Set X) = Z}
  have hne : P.Nonempty := by
    refine ⟨⟨A ∩ f ⁻¹' (Z : Set Y), hA.inter (Z.isClosed.preimage hf)⟩,
      Set.inter_subset_left, Set.Subset.antisymm ?_ ?_⟩
    · rintro _ ⟨x, ⟨_, hx⟩, rfl⟩
      exact hx
    · intro z hz
      obtain ⟨x, hxA, rfl⟩ := hZA hz
      exact ⟨x, ⟨hxA, hz⟩, rfl⟩
  obtain ⟨W, ⟨hWA, hWZ⟩, hmin⟩ := (wellFounded_lt (α := Closeds X)).has_min P hne
  have hWne : (W : Set X).Nonempty := by
    obtain ⟨z, hz⟩ := Z.isIrreducible.nonempty
    rw [← hWZ] at hz
    obtain ⟨x, hx, -⟩ := hz
    exact ⟨x, hx⟩
  refine ⟨⟨W, ⟨hWne, ?_⟩, W.isClosed⟩, hWA, hWZ⟩
  rw [isPreirreducible_iff_isClosed_union_isClosed]
  intro z₁ z₂ hz₁ hz₂ hsub
  have hunion : f '' ((W : Set X) ∩ z₁) ∪ f '' ((W : Set X) ∩ z₂) = Z := by
    rw [← Set.image_union, ← Set.inter_union_distrib_left,
      Set.inter_eq_self_of_subset_left hsub, hWZ]
  have key : ∀ z : Set X, IsClosed z → (Z : Set Y) ⊆ f '' ((W : Set X) ∩ z) →
      (W : Set X) ⊆ z := by
    intro z hz hZz
    have hmem : (⟨(W : Set X) ∩ z, W.isClosed.inter hz⟩ : Closeds X) ∈ P :=
      ⟨Set.inter_subset_left.trans hWA,
        Set.Subset.antisymm ((Set.image_mono Set.inter_subset_left).trans hWZ.le) hZz⟩
    have hle : (⟨(W : Set X) ∩ z, W.isClosed.inter hz⟩ : Closeds X) ≤ W :=
      Set.inter_subset_left
    have heq : (⟨(W : Set X) ∩ z, W.isClosed.inter hz⟩ : Closeds X) = W := by
      by_contra hne'
      exact hmin _ hmem (lt_of_le_of_ne hle hne')
    have hset : (W : Set X) ∩ z = W := congrArg (fun C : Closeds X => (C : Set X)) heq
    rw [← hset]
    exact Set.inter_subset_right
  rcases (isPreirreducible_iff_isClosed_union_isClosed.mp Z.isIrreducible.2) _ _
      (hc _ (W.isClosed.inter hz₁)) (hc _ (W.isClosed.inter hz₂)) hunion.symm.le with h | h
  · exact Or.inl (key z₁ hz₁ h)
  · exact Or.inr (key z₂ hz₂ h)

/-- Chains of irreducible closed subsets of `Y` ending at `f(W)` lift to chains in `X` ending
at `W`. -/
theorem exists_ltSeries_lift [NoetherianSpace X] {f : X → Y} (hf : Continuous f)
    (hc : IsClosedMap f) :
    ∀ (n : ℕ) (p : LTSeries (IrreducibleCloseds Y)), p.length = n →
      ∀ W : IrreducibleCloseds X, f '' (W : Set X) = p.last →
        ∃ q : LTSeries (IrreducibleCloseds X), q.length = n ∧ q.last = W := by
  intro n
  induction n with
  | zero =>
      intro p _ W _
      exact ⟨RelSeries.singleton _ W, rfl, rfl⟩
  | succ n ih =>
      intro p hp W hW
      have hrel : p.eraseLast.last < p.last := p.eraseLast_last_rel_last (by omega)
      obtain ⟨W', hW'W, hW'⟩ := exists_irreducibleCloseds_image_eq hf hc (W : Set X) W.isClosed
        p.eraseLast.last (by rw [hW]; exact hrel.le)
      have hlt : W' < W := by
        refine lt_of_le_of_ne hW'W ?_
        rintro rfl
        exact hrel.ne (IrreducibleCloseds.ext (hW'.symm.trans hW))
      obtain ⟨q, hq, hqlast⟩ :=
        ih p.eraseLast (by rw [RelSeries.eraseLast_length, hp]; rfl) W' hW'
      refine ⟨q.snoc W (by rw [hqlast]; exact hlt), ?_, RelSeries.last_snoc _ _ _⟩
      rw [RelSeries.snoc_length, hq]

/-- A closed continuous surjection from a Noetherian space cannot raise the topological Krull
dimension. -/
theorem topologicalKrullDim_le_of_surjective_of_isClosedMap [NoetherianSpace X] {f : X → Y}
    (hf : Continuous f) (hc : IsClosedMap f) (hs : Function.Surjective f) :
    topologicalKrullDim Y ≤ topologicalKrullDim X := by
  unfold topologicalKrullDim Order.krullDim
  refine iSup_le fun p => ?_
  obtain ⟨W, -, hW⟩ := exists_irreducibleCloseds_image_eq hf hc Set.univ isClosed_univ p.last
    (by rw [Set.image_univ, hs.range_eq]; exact Set.subset_univ _)
  obtain ⟨q, hq, -⟩ := exists_ltSeries_lift hf hc p.length p rfl W hW
  calc ((p.length : ℕ) : WithBot ℕ∞) = q.length := by rw [hq]
    _ ≤ ⨆ q : LTSeries (IrreducibleCloseds X), ((q.length : ℕ) : WithBot ℕ∞) :=
      le_iSup (fun q : LTSeries (IrreducibleCloseds X) => ((q.length : ℕ) : WithBot ℕ∞)) q

/-- `d ≤ 2` and `¬ d ≤ 1` force `d = 2` in `WithBot ℕ∞`. -/
theorem eq_two_of_le_two_of_not_le_one {d : WithBot ℕ∞} (h2 : d ≤ 2) (h1 : ¬ d ≤ 1) :
    d = 2 := by
  induction d using WithBot.recBotCoe with
  | bot => exact absurd bot_le h1
  | coe n =>
      have h2n : n ≤ 2 := WithBot.coe_le_coe.mp h2
      have h1n : ¬ n ≤ 1 := fun h => h1 (WithBot.coe_le_coe.mpr h)
      induction n using ENat.recTopCoe with
      | top => exact absurd (top_le_iff.mp h2n) (by decide)
      | coe m =>
          have h2' : m ≤ 2 := ENat.coe_le_coe.mp h2n
          have h1' : ¬ m ≤ 1 := fun h => h1n (ENat.coe_le_coe.mpr h)
          have hm : m = 2 := by omega
          subst hm
          rfl

end Topology

/-! ### Scheme-theoretic consequences of `f_*O_X = O_Y` -/

section Scheme

/-- A proper morphism with `O_Y ≅ f_*O_X` is surjective: over the open complement `U` of the
closed image, `O_Y(U) ≅ O_X(f⁻¹U) = O_X(∅) = 0`, but sections over a nonempty open are
nontrivial (they map to a local ring). -/
theorem surjective_of_isIso_c {X Y : Scheme.{u}} (f : X ⟶ Y) [IsProper f] [IsIso f.c] :
    Function.Surjective f.base := by
  intro y
  by_contra hy
  let U : Y.Opens := ⟨(Set.range f.base)ᶜ, f.isClosedMap.isClosed_range.isOpen_compl⟩
  have hyU : y ∈ U := fun h => hy h
  have hpre : f ⁻¹ᵁ U = ⊥ := by
    apply Opens.ext
    rw [Opens.coe_bot]
    exact Set.eq_empty_iff_forall_not_mem.mpr fun x hx => hx ⟨x, rfl⟩
  letI : IsIso (f.app U) := show IsIso (f.c.app (Opposite.op U)) from inferInstance
  haveI hsub : Subsingleton Γ(X, f ⁻¹ᵁ U) := by
    rw [hpre]
    infer_instance
  haveI hsubY : Subsingleton Γ(Y, U) :=
    (asIso (f.app U)).commRingCatIsoToRingEquiv.injective.subsingleton
  have h01 : (0 : Γ(Y, U)) = 1 := Subsingleton.elim _ _
  have h := congrArg (Y.presheaf.germ U y hyU).hom h01
  rw [map_zero, map_one] at h
  exact zero_ne_one h

/-- A surjective morphism of integral schemes maps the generic point to the generic point. -/
theorem base_genericPoint_eq {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y] (f : X ⟶ Y)
    (hs : Function.Surjective f.base) : f.base (genericPoint X) = genericPoint Y := by
  have h1 : f.base (genericPoint X) ⤳ genericPoint Y := by
    obtain ⟨x, hx⟩ := hs (genericPoint Y)
    rw [← hx]
    exact (genericPoint_specializes x).map f.continuous
  have h2 : genericPoint Y ⤳ f.base (genericPoint X) := genericPoint_specializes _
  exact (h1.antisymm h2).eq

/-- A morphism over `k` from a projective surface to a projective `k`-scheme is proper. -/
theorem isProper_of_comp_eq {k : Type u} [Field k] (S : NormalProjectiveSurface k)
    {Y : Scheme.{u}} {g : Y ⟶ Spec (CommRingCat.of k)} (hproj : IsProjectiveOverField g)
    (f : S.toScheme ⟶ Y) (hcomp : f ≫ g = S.structureMorphism) : IsProper f := by
  haveI : IsProper g := hproj.isProper
  haveI : IsProper (f ≫ g) := by
    rw [hcomp]
    exact S.projective.isProper
  exact IsProper.of_comp_of_isSeparated f g

/-- The image of a surface under a proper morphism has dimension at most two. -/
theorem topologicalKrullDim_le_two_of_surjective {k : Type u} [Field k]
    (S : NormalProjectiveSurface k) {Y : Scheme.{u}} (f : S.toScheme ⟶ Y) [IsProper f]
    (hs : Function.Surjective f.base) : topologicalKrullDim Y ≤ 2 := by
  rw [← S.dimension_two]
  exact topologicalKrullDim_le_of_surjective_of_isClosedMap f.continuous f.isClosedMap hs

/-- **Birationality from `f_*O_S = O_Y`.** A proper surjective morphism `f` from a surface `S`
to an integral scheme `Y` of dimension `> 1` with `O_Y ≅ f_*O_S` is birational: the generic
point goes to the generic point, and the stalk map at the generic point is bijective. -/
theorem isBirationalScheme_of_isIso_c {k : Type u} [Field k] (S : NormalProjectiveSurface k)
    {Y : Scheme.{u}} [IsIntegral Y] (f : S.toScheme ⟶ Y) [IsProper f] [IsIso f.c]
    (hs : Function.Surjective f.base) (hdim : ¬ topologicalKrullDim Y ≤ 1) :
    IsBirationalScheme f := by
  have hgen : f.base (genericPoint S.toScheme) = genericPoint Y := base_genericPoint_eq f hs
  refine ⟨hgen, ?_⟩
  rw [ConcreteCategory.isIso_iff_bijective]
  constructor
  · intro a b hab
    obtain ⟨U, hU, s, rfl⟩ := TopCat.Presheaf.germ_exist Y.presheaf _ a
    obtain ⟨V, hV, t, rfl⟩ := TopCat.Presheaf.germ_exist Y.presheaf _ b
    have hsW : Y.presheaf.germ U _ hU s =
        Y.presheaf.germ (U ⊓ V) (f.base (genericPoint S.toScheme)) ⟨hU, hV⟩
          (Y.presheaf.map (homOfLE (inf_le_left : U ⊓ V ≤ U)).op s) :=
      (TopCat.Presheaf.germ_res_apply Y.presheaf (homOfLE inf_le_left) _ ⟨hU, hV⟩ s).symm
    have htW : Y.presheaf.germ V _ hV t =
        Y.presheaf.germ (U ⊓ V) (f.base (genericPoint S.toScheme)) ⟨hU, hV⟩
          (Y.presheaf.map (homOfLE (inf_le_right : U ⊓ V ≤ V)).op t) :=
      (TopCat.Presheaf.germ_res_apply Y.presheaf (homOfLE inf_le_right) _ ⟨hU, hV⟩ t).symm
    rw [hsW, htW] at hab ⊢
    rw [Scheme.stalkMap_germ_apply, Scheme.stalkMap_germ_apply] at hab
    have hst := germ_injective_of_isIntegral (X := S.toScheme) (genericPoint S.toScheme)
      (show genericPoint S.toScheme ∈ f ⁻¹ᵁ (U ⊓ V) from ⟨hU, hV⟩) hab
    letI : IsIso (f.app (U ⊓ V)) :=
      show IsIso (f.c.app (Opposite.op (U ⊓ V))) from inferInstance
    have heq := (asIso (f.app (U ⊓ V))).commRingCatIsoToRingEquiv.injective hst
    rw [heq]
  · intro t
    obtain ⟨V, hV, t₀, rfl⟩ := TopCat.Presheaf.germ_exist S.toScheme.presheaf _ t
    have hT : IsClosed (f.base '' (V : Set S.toScheme)ᶜ) :=
      f.isClosedMap _ V.isOpen.isClosed_compl
    let U : Y.Opens := ⟨(f.base '' (V : Set S.toScheme)ᶜ)ᶜ, hT.isOpen_compl⟩
    have hηU : f.base (genericPoint S.toScheme) ∈ U := by
      intro hmem
      apply hdim
      have hTuniv : f.base '' (V : Set S.toScheme)ᶜ = Set.univ := by
        rw [hgen] at hmem
        exact Set.univ_subset_iff.mp (((genericPoint_spec Y).mem_closed_set_iff hT).mp hmem)
      let Vc : Set S.toScheme := (V : Set S.toScheme)ᶜ
      have hVc : IsClosed Vc := V.isOpen.isClosed_compl
      have hsurj' : Function.Surjective (f.base ∘ (Subtype.val : Vc → S.toScheme)) := by
        intro y
        have hy : y ∈ f.base '' Vc := by
          show y ∈ f.base '' (V : Set S.toScheme)ᶜ
          rw [hTuniv]
          exact Set.mem_univ y
        obtain ⟨x, hx, rfl⟩ := hy
        exact ⟨⟨x, hx⟩, rfl⟩
      calc topologicalKrullDim Y ≤ topologicalKrullDim Vc :=
            topologicalKrullDim_le_of_surjective_of_isClosedMap
              (f.continuous.comp continuous_subtype_val)
              (f.isClosedMap.comp hVc.isClosedMap_subtype_val) hsurj'
        _ ≤ 1 := KltDP.Topology.topologicalKrullDim_le_one_of_isClosed_of_ne_univ
              S.dimension_two.le hVc (by
                intro h
                have hmem' : genericPoint S.toScheme ∈ Vc := by
                  rw [h]
                  exact Set.mem_univ _
                exact hmem' hV)
    have hpre : f ⁻¹ᵁ U ≤ V := by
      intro x hx
      by_cases hxV : x ∈ V
      · exact hxV
      · exact absurd ⟨x, hxV, rfl⟩ hx
    letI : IsIso (f.app U) := show IsIso (f.c.app (Opposite.op U)) from inferInstance
    let e := (asIso (f.app U)).commRingCatIsoToRingEquiv
    refine ⟨Y.presheaf.germ U _ hηU (e.symm (S.toScheme.presheaf.map (homOfLE hpre).op t₀)), ?_⟩
    rw [Scheme.stalkMap_germ_apply]
    have happ : f.app U (e.symm (S.toScheme.presheaf.map (homOfLE hpre).op t₀)) =
        S.toScheme.presheaf.map (homOfLE hpre).op t₀ := e.apply_symm_apply _
    rw [happ, TopCat.Presheaf.germ_res_apply]

end Scheme

/-! ### The surface-level steps -/

section Surface

variable {k : Type u} [Field k] [IsAlgClosed k] (S : NormalProjectiveSurface k)
  [FiniteDimensional ℚ S.NumericalClassGroup]
  (hreg : ∀ x : S.Point, RegularPoint S.toScheme x)

/-- A contracted prime curve has negative self-intersection: it is orthogonal to the pullback
of an ample divisor of the target, which has positive square (Hodge index). -/
theorem selfIntersectionNumber_neg_of_isExceptionalCurve (T : NormalProjectiveSurface k)
    (f : S.toScheme ⟶ T.toScheme) [IsProper f] [GenericPointPreserving f]
    (hbir : IsBirationalScheme f) (hcomp : f ≫ T.structureMorphism = S.structureMorphism)
    (E : S.PrimeCurve) (hE : IsExceptionalCurve f E) : E.selfIntersectionNumber hreg < 0 := by
  obtain ⟨A, hA⟩ := T.exists_isAmple_cartier
  exact NefNullCurveNegativeSquare.selfIntersectionNumber_neg_of_null S hreg
    (DominantCartierPullback.pullbackHom f A)
    (BirationalAmplePullbackPositiveSquare.intersectionPairing_signedPullback_pos f hbir hreg A hA)
    E (hE.intersectionNumber_pullback_eq_zero f hcomp E A)

/-- Adjunction: a prime curve with `E² < 0` and `K_S · E < 0` is a `(−1)`-curve
(`K_S · E = 2p_a(E) − 2 − E²` forces `p_a(E) = 0`, then `E ≅ P¹`). -/
theorem isMinusOneCurve_of_neg (KS : CartierDivisor S.toScheme)
    (eKS : cartierDivisorModule S.toScheme KS ≅
      SmoothCanonicalExteriorComparison.relativeDifferentialExterior S.structureMorphism 2)
    (E : S.PrimeCurve) (hsq : E.selfIntersectionNumber hreg < 0)
    (hK : E.intersectionNumber KS < 0) : IsMinusOneCurve hreg E := by
  letI : IsSmoothOfRelativeDimension 2 S.structureMorphism :=
    S.isSmoothOfRelativeDimension_two_of_regularPoints hreg
  have hadj := S.arithmetic_canonical_degree hreg KS eKS E
  have hgenus : CurveCanonical.genus E.toSpec = 0 := by omega
  refine ⟨?_, by omega⟩
  letI : IsProper E.toSpec := E.toSpec_isProper
  exact GenusZeroCurveProjectiveLineIso.exists_iso E.toSpec E.dimension_one_toScheme hgenus

include hreg in
/-- **Some curve is contracted.** If `f : S → Y` is a morphism over `k` to a projective
`k`-scheme with `O_Y ≅ f_*O_S` and `ρ(Y) + 1 = ρ(S) > 2`, then some prime curve of `S` is
contracted to a point. -/
theorem exists_isExceptionalCurve_of_rhoReal {Y : Scheme.{u}} (g : Y ⟶ Spec (CommRingCat.of k))
    (f : S.toScheme ⟶ Y) (hproj : IsProjectiveOverField g)
    (hcomp : f ≫ g = S.structureMorphism) [IsIso f.c]
    (hrank : NumericalOneCycles.rhoReal Y g + 1 = S.picardRank) (hrho : 2 < S.picardRank) :
    ∃ E : S.PrimeCurve, ∃ y : Y, f.base '' (E : Set S.toScheme) = {y} := by
  haveI : IsProper f := isProper_of_comp_eq S hproj f hcomp
  have hsurj : Function.Surjective f.base := surjective_of_isIso_c f
  obtain ⟨hint, hnormal⟩ := SteinTargetIntegral.integral_and_normal f S.normal hsurj
  haveI : IsIntegral Y := hint
  haveI : IsLocallyNoetherian Y := hproj.isLocallyNoetherian
  have hdim1 : ¬ topologicalKrullDim Y ≤ 1 := fun h => by
    have := NumericalOneCycles.rhoReal_le_one_of_dim_le_one Y g h
    omega
  have hdim : topologicalKrullDim Y = 2 :=
    eq_two_of_le_two_of_not_le_one (topologicalKrullDim_le_two_of_surjective S f hsurj) hdim1
  let T : NormalProjectiveSurface k := ⟨Y, g, hint, hnormal, hproj, hdim⟩
  have hbir : IsBirationalScheme f := isBirationalScheme_of_isIso_c S f hsurj hdim1
  have hconn : ∀ y : Y, IsConnected (f.base ⁻¹' {y}) :=
    ProperSteinConnected.pointFibers_connected f
  by_contra hno
  have hnoE : ∀ E : S.PrimeCurve, ¬ IsExceptionalCurve (S := S) (X := T) f E :=
    fun E hE => hno ⟨E, hE⟩
  have hsupport : ActualExceptionalLocus.primeSupport (S := S) (X := T) f = ∅ := by
    apply Set.eq_empty_iff_forall_not_mem.mpr
    intro x hx
    obtain ⟨C, hC, -⟩ := (ActualExceptionalLocus.mem_primeSupport (S := S) (X := T) f x).mp hx
    exact hnoE C hC
  have himage : ActualExceptionalLocus.imagePoints (S := S) (X := T) f = ∅ := by
    rw [ActualExceptionalLocus.imagePoints, hsupport, Set.image_empty]
  haveI hisoU : IsIso (f ∣_ ActualExceptionalLocus.complementOpen (S := S) (X := T) f hbir) :=
    ActualExceptionalLocus.isIso_complementOpen (S := S) (X := T) f hbir hcomp hconn
  have hU : ActualExceptionalLocus.complementOpen (S := S) (X := T) f hbir = ⊤ := by
    apply Opens.ext
    change (ActualExceptionalLocus.imagePoints (S := S) (X := T) f)ᶜ = ((⊤ : Y.Opens) : Set Y)
    rw [himage, Set.compl_empty, Opens.coe_top]
  haveI hiso : IsIso f := by
    have hP := IsLocalAtTarget.of_iSup_eq_top (P := MorphismProperty.isomorphisms Scheme)
      (f := f) (fun _ : Unit => ActualExceptionalLocus.complementOpen (S := S) (X := T) f hbir)
      (by rw [iSup_const, hU]) (fun _ => (MorphismProperty.isomorphisms.iff _).mpr hisoU)
    exact (MorphismProperty.isomorphisms.iff f).mp hP
  have hTreg : ∀ y : T.Point, RegularPoint T.toScheme y := fun y =>
    RegularPointsOnIsomorphismOpen.regularPoint_of_mem f
      (ActualExceptionalLocus.complementOpen (S := S) (X := T) f hbir) hreg y
      (by rw [hU]; exact Set.mem_univ y)
  haveI : FiniteDimensional ℚ T.NumericalClassGroup :=
    SurfaceNumericalFinitenessProved.numericalClassGroup_finite T hTreg
  have h1 : S.picardRank = T.picardRank :=
    IsomorphismSurfaceInvariants.picardRank_eq (S := S) (T := T) f hcomp hreg hTreg
  have h2 : NumericalOneCycles.rhoReal Y g = T.picardRank :=
    NumericalOneCycles.rhoReal_eq_picardRank T
  omega

end Surface

end NefThresholdCore

/-! ### The three consequences of Tanaka's contraction theorem -/

section Main

variable {k : Type u} [Field k] [IsAlgClosed k] (S : NormalProjectiveSurface k)
  [FiniteDimensional ℚ S.NumericalClassGroup]
  (hreg : ∀ x : S.Point, RegularPoint S.toScheme x)
  (KS : CartierDivisor S.toScheme)
  (eKS : cartierDivisorModule S.toScheme KS ≅
    SmoothCanonicalExteriorComparison.relativeDifferentialExterior S.structureMorphism 2)
  (hrho : 2 < S.picardRank)

include eKS hrho in
/-- **(C1)** Manuscript Lemma 3.3, contraction step (lines 793–802): on a regular projective
surface with `ρ(S) > 2`, every `K_S`-negative extremal ray `ℝ_{≥0} v` of `NE(S)‾` is generated
by an actual `(−1)`-curve `E` (with `[E] ∈ ℝ_{≥0} v`). -/
theorem exists_minusOneCurve_of_extremalRay (v : V S)
    (hv : IsExtremalRay S (closedCurveCone S hreg) v)
    (hneg : pairReal S hreg (cartierClass S KS) v < 0) :
    ∃ E : S.PrimeCurve, IsMinusOneCurve hreg E ∧ curveClassReal S hreg E ∈ ray S v := by
  obtain ⟨Y, g, f, hproj, hcomp, hc, hcontr, hrank⟩ :=
    KltDP.Literature.Tanaka.contraction_44_instance S hreg KS eKS v hv hneg
  haveI : IsIso f.c := hc
  haveI : IsProper f := NefThresholdCore.isProper_of_comp_eq S hproj f hcomp
  have hsurj : Function.Surjective f.base := NefThresholdCore.surjective_of_isIso_c f
  obtain ⟨hint, hnormal⟩ := SteinTargetIntegral.integral_and_normal f S.normal hsurj
  haveI : IsIntegral Y := hint
  have hdim1 : ¬ topologicalKrullDim Y ≤ 1 := fun h => by
    have := NumericalOneCycles.rhoReal_le_one_of_dim_le_one Y g h
    omega
  have hdim : topologicalKrullDim Y = 2 :=
    NefThresholdCore.eq_two_of_le_two_of_not_le_one
      (NefThresholdCore.topologicalKrullDim_le_two_of_surjective S f hsurj) hdim1
  let T : NormalProjectiveSurface k := ⟨Y, g, hint, hnormal, hproj, hdim⟩
  have hbir : IsBirationalScheme f :=
    NefThresholdCore.isBirationalScheme_of_isIso_c S f hsurj hdim1
  haveI : GenericPointPreserving f := ⟨hbir.map_genericPoint⟩
  obtain ⟨E, hE⟩ :=
    NefThresholdCore.exists_isExceptionalCurve_of_rhoReal S hreg g f hproj hcomp hrank hrho
  have hEray : curveClassReal S hreg E ∈ ray S v := (hcontr E).mp hE
  refine ⟨E, ?_, hEray⟩
  apply NefThresholdCore.isMinusOneCurve_of_neg S hreg KS eKS E
  · exact NefThresholdCore.selfIntersectionNumber_neg_of_isExceptionalCurve S hreg T f hbir
      hcomp E hE
  · obtain ⟨t, ht, hEt⟩ := hEray
    have hne : curveClassReal S hreg E ≠ 0 := fun h =>
      NefNullCurveNegativeSquare.curveClass_ne_zero S hreg E
        (toReal_injective S (h.trans (map_zero (toReal S)).symm))
    have ht0 : t ≠ 0 := by
      rintro rfl
      rw [zero_smul] at hEt
      exact hne hEt
    have htpos : 0 < t := lt_of_le_of_ne ht (Ne.symm ht0)
    have hpair := pairReal_cartierClass_curveClassReal S hreg KS E
    rw [hEt, map_smul, smul_eq_mul] at hpair
    have hlt : (E.intersectionNumber KS : ℝ) < 0 := by
      rw [← hpair]
      exact mul_neg_of_pos_of_neg htpos hneg
    exact_mod_cast hlt

include eKS hrho in
/-- **(C3)** Manuscript Lemma 3.3 (lines 802–805): if `K_S` is not nef (negative on some prime
curve), some `K_S`-negative extremal ray exists (compact ample slice, `CurveConeExtremal`) and
hence a `(−1)`-curve exists. -/
theorem exists_minusOneCurve_of_not_nef (hK : ∃ C : S.PrimeCurve, C.intersectionNumber KS < 0) :
    ∃ E : S.PrimeCurve, IsMinusOneCurve hreg E := by
  obtain ⟨v, hv, hneg⟩ := exists_extremalRay_of_intersectionNumber_neg S hreg KS hK
  obtain ⟨E, hE, -⟩ := exists_minusOneCurve_of_extremalRay S hreg KS eKS hrho v hv hneg
  exact ⟨E, hE⟩

include eKS hrho in
/-- **(C2)** Manuscript Lemma 3.3, nefness of `N = L + ℓ K_S` (lines 807–811): if `L` is nef,
`ℓ ≥ 0`, and `N · E ≥ 0` for every `(−1)`-curve `E`, then `N` is nef. Otherwise an `N`-negative
extremal ray exists; it is `K_S`-negative since `L` is nef, hence generated by a `(−1)`-curve
`E` with `N · E < 0`. -/
theorem nef_of_minusOne_nonneg (L : CartierDivisor S.toScheme)
    (hL : ∀ C : S.PrimeCurve, 0 ≤ C.intersectionNumber L) (ℓ : ℚ) (hℓ : 0 ≤ ℓ)
    (hE : ∀ E : S.PrimeCurve, IsMinusOneCurve hreg E →
      0 ≤ S.numericalRestrictionDegree E (cartierClass S L + ℓ • cartierClass S KS)) :
    ∀ C : S.PrimeCurve,
      0 ≤ S.numericalRestrictionDegree C (cartierClass S L + ℓ • cartierClass S KS) := by
  intro C
  by_contra hC
  push_neg at hC
  set N := cartierClass S L + ℓ • cartierClass S KS with hN
  have hz : ∃ z ∈ closedCurveCone S hreg, pairReal S hreg N z < 0 :=
    ⟨curveClassReal S hreg C, curveClassReal_mem_closedCurveCone S hreg C, by
      rw [NumericalOneCycles.pairReal_curveClassReal S hreg]
      exact_mod_cast hC⟩
  obtain ⟨v, hv, hNv⟩ := exists_extremalRay_of_neg S hreg N hz
  have hLv : 0 ≤ pairReal S hreg (cartierClass S L) v :=
    nonneg_on_closedCurveCone S hreg (pairReal S hreg (cartierClass S L)) (fun C => by
      rw [pairReal_cartierClass_curveClassReal]
      exact_mod_cast hL C) v hv.2.1
  have hKv : pairReal S hreg (cartierClass S KS) v < 0 := by
    rw [hN, pairReal_add_left, pairReal_smul_left] at hNv
    rcases hℓ.lt_or_eq with hpos | hzero
    · have hpos' : (0 : ℝ) < ℓ := by exact_mod_cast hpos
      refine lt_of_not_le fun h => ?_
      have := mul_nonneg hpos'.le h
      linarith
    · subst hzero
      simp only [Rat.cast_zero, zero_mul, add_zero] at hNv
      linarith
  obtain ⟨E, hEm1, hEray⟩ := exists_minusOneCurve_of_extremalRay S hreg KS eKS hrho v hv hKv
  have hE' := hE E hEm1
  obtain ⟨t, ht, hEt⟩ := hEray
  have hne : curveClassReal S hreg E ≠ 0 := fun h =>
    NefNullCurveNegativeSquare.curveClass_ne_zero S hreg E
      (toReal_injective S (h.trans (map_zero (toReal S)).symm))
  have ht0 : t ≠ 0 := by
    rintro rfl
    rw [zero_smul] at hEt
    exact hne hEt
  have htpos : 0 < t := lt_of_le_of_ne ht (Ne.symm ht0)
  have hNE : pairReal S hreg N (curveClassReal S hreg E) < 0 := by
    rw [hEt, map_smul, smul_eq_mul]
    exact mul_neg_of_pos_of_neg htpos hNv
  rw [NumericalOneCycles.pairReal_curveClassReal S hreg] at hNE
  have hNE' : S.numericalRestrictionDegree E N < 0 := by exact_mod_cast hNE
  exact absurd hE' (not_le.mpr hNE')

end Main

end KltDP.Manuscript.S03

#check @KltDP.Manuscript.S03.exists_minusOneCurve_of_extremalRay
#check @KltDP.Manuscript.S03.exists_minusOneCurve_of_not_nef
#check @KltDP.Manuscript.S03.nef_of_minusOne_nonneg
#print axioms KltDP.Manuscript.S03.NefThresholdCore.topologicalKrullDim_le_of_surjective_of_isClosedMap
#print axioms KltDP.Manuscript.S03.NefThresholdCore.isBirationalScheme_of_isIso_c
#print axioms KltDP.Manuscript.S03.NefThresholdCore.exists_isExceptionalCurve_of_rhoReal
#print axioms KltDP.Manuscript.S03.exists_minusOneCurve_of_extremalRay
#print axioms KltDP.Manuscript.S03.exists_minusOneCurve_of_not_nef
#print axioms KltDP.Manuscript.S03.nef_of_minusOne_nonneg
