import KltDP.Geometry.AffineQuasicoherentCounit
import KltDP.Geometry.AffineModuleTildePresentation
import KltDP.Geometry.CoherentQuasicoherent
import KltDP.Geometry.AmpleSerre
import KltDP.Geometry.RationalTreePicardMultidegree
import KltDP.Compatibility.SheafModuleSymmetric

/-!
# Global generation and an original ample sheaf on an affine spectrum

The actual tilde counit identifies every original quasicoherent module
with the tilde of its actual global section module. The original free
module projection therefore gives a global free epimorphism. Applied to
literal coherent modules, this proves Serre ampleness of the original
structure line on Spec R, independently of finite-generator descent.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits MonoidalCategory

universe u

namespace KltDP.Geometry.AffineSpectrumGlobalGeneration

attribute [local instance] Types.instFunLike Types.instConcreteCategory

local instance affineSpectrumMonoidal (X : Scheme.{u}) : MonoidalCategory X.Modules :=
  Scheme.Modules.monoidalCategory X

local instance affineSpectrumSymmetric (X : Scheme.{u}) : SymmetricCategory X.Modules :=
  Scheme.Modules.symmetricCategory X

open AffineModuleTilde

variable (R : Type u) [CommRing R]

/-- Every original quasicoherent module on Spec R is generated by an
actual free sheaf indexed by its original global sections. -/
theorem isGloballyGenerated (M : (Spec (.of R)).Modules) [M.IsQuasicoherent] :
    Positivity.IsGloballyGenerated M := by
  letI : IsIso (counit M) := counit_isIso_of_isQuasicoherent M
  refine ⟨sectionModule M ⊤,
    (freeCoproductIso R (sectionModule M ⊤)).inv ≫
      (functor R).map (freeModuleProjection (sectionModule M ⊤)) ≫ counit M, ?_⟩
  infer_instance

/-- The original structure line on Spec R is ample in the existing
Serre sense. Its threshold is zero for every literal coherent module. -/
theorem trivial_isAmple :
    AmpleSerre.IsAmple (InvertibleSheaf.trivial (Spec (.of R))) := by
  intro M hM
  letI : IsCoherentModule M := hM
  letI : M.IsQuasicoherent :=
    CoherentQuasicoherent.isQuasicoherent_of_isCoherentModule M
  have htriv : (InvertibleSheaf.trivial (Spec (.of R))).toPic = 1 :=
    (RationalTreePicard.toPic_eq_one_iff_iso_unit
      (InvertibleSheaf.trivial (Spec (.of R)))).mpr ⟨Iso.refl _⟩
  refine ⟨0, fun n _ => ⟨InvertibleSheaf.trivial (Spec (.of R)), ?_, ?_⟩⟩
  · simp only [htriv, one_pow]
  · exact AmpleSerre.isGloballyGenerated_of_iso
      ((schemeStructureTensorRightIso M).symm ≪≫
        β_ M (InvertibleSheaf.trivial (Spec (.of R))).obj)
      (isGloballyGenerated R M)

end KltDP.Geometry.AffineSpectrumGlobalGeneration
