import KltDP.Geometry.AffineBlowupLiftUniqueness
import Mathlib.AlgebraicGeometry.Gluing

/-!
# Coefficient charts for a principal regular target ideal

If the actual extended center ideal is generated by a nonzerodivisor `d`,
write the image of each center element `b` as `d c_b`. The coefficients
generate the unit ideal, by cancellation of `d`. Consequently their actual
principal open subsets cover the affine test scheme. On each localization,
the image of the corresponding `b` is a regular generator, so the existing
Rees-chart lift applies.

All coefficients, cover maps, and local lifts are constructed from the actual
ring map and ideal equality. No covering or factorization conclusion is an
input. The chosen `d` need not itself be the image of an element of the center.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits

namespace KltDP.Geometry.AffineBlowup

universe u v w

variable {R : Type u} [CommRing R] (I : Ideal R)
    {S : Type v} [CommRing S] (φ : R →+* S) (d : S)
    (hI : Ideal.map φ I = Ideal.span {d})

include hI in
private theorem exists_principalCoefficient (b : I) : ∃ c : S, φ (b : R) = d * c := by
  apply Ideal.mem_span_singleton.mp
  rw [← hI]
  exact Ideal.mem_map_of_mem φ b.property

/-- The actual coefficient of an ideal element relative to the chosen target equation. -/
def principalCoefficient (b : I) : S :=
  Classical.choose (exists_principalCoefficient I φ d hI b)

/-- The chosen coefficient satisfies the actual target-ring equation. -/
theorem principalCoefficient_spec (b : I) :
    φ (b : R) = d * principalCoefficient I φ d hI b :=
  Classical.choose_spec (exists_principalCoefficient I φ d hI b)

/-- Regularity of the target equation derives coverage: the coefficients
generate the unit ideal. This is not an assumed property of the chosen family. -/
theorem span_principalCoefficient_eq_top (hd : d ∈ nonZeroDivisors S) :
    Ideal.span (Set.range (principalCoefficient I φ d hI)) = ⊤ := by
  let J : Ideal S := Ideal.span (Set.range (principalCoefficient I φ d hI))
  have hmap : Ideal.map φ I ≤ Ideal.span {d} * J := by
    apply Ideal.map_le_iff_le_comap.mpr
    intro r hr
    change φ r ∈ Ideal.span {d} * J
    apply Ideal.mem_span_singleton_mul.mpr
    exact ⟨principalCoefficient I φ d hI ⟨r, hr⟩,
      Ideal.subset_span ⟨⟨r, hr⟩, rfl⟩,
      (principalCoefficient_spec I φ d hI ⟨r, hr⟩).symm⟩
  have hdmem : d ∈ Ideal.map φ I := by
    rw [hI]
    exact Ideal.subset_span (Set.mem_singleton d)
  obtain ⟨s, hs, hds⟩ := Ideal.mem_span_singleton_mul.mp (hmap hdmem)
  have hsone : s = 1 :=
    (mul_cancel_left_mem_nonZeroDivisors hd).mp (hds.trans (mul_one d).symm)
  change J = ⊤
  apply J.eq_top_iff_one.mpr
  simpa only [hsone] using hs

section TargetMap

variable {T : Type w} [CommRing T] (ρ : S →+* T) (b : I)

/-- If a coefficient becomes a unit, the corresponding image of the center
generates the actual extended ideal after this ring map. -/
theorem principalTarget_map_le_span
    (hc : IsUnit (ρ (principalCoefficient I φ d hI b))) :
    Ideal.map (ρ.comp φ) I ≤ Ideal.span {(ρ.comp φ) (b : R)} := by
  obtain ⟨t, ht⟩ := isUnit_iff_exists_inv.mp hc
  have hdmem : ρ d ∈ Ideal.span {(ρ.comp φ) (b : R)} := by
    apply Ideal.mem_span_singleton.mpr
    refine ⟨t, ?_⟩
    change ρ d = ρ (φ (b : R)) * t
    rw [principalCoefficient_spec I φ d hI b, map_mul, mul_assoc, ht, mul_one]
  apply Ideal.map_le_iff_le_comap.mpr
  intro r hr
  change ρ (φ r) ∈ Ideal.span {(ρ.comp φ) (b : R)}
  rw [principalCoefficient_spec I φ d hI ⟨r, hr⟩, map_mul]
  exact Ideal.mul_mem_right _ _ hdmem

/-- Regularity survives once the target equation remains regular and the
chosen coefficient becomes a unit. -/
theorem principalTarget_equation_mem_nonZeroDivisors
    (hd : ρ d ∈ nonZeroDivisors T)
    (hc : IsUnit (ρ (principalCoefficient I φ d hI b))) :
    (ρ.comp φ) (b : R) ∈ nonZeroDivisors T := by
  change ρ (φ (b : R)) ∈ nonZeroDivisors T
  rw [principalCoefficient_spec I φ d hI b, map_mul]
  exact mul_mem hd hc.mem_nonZeroDivisors

end TargetMap

/-- The actual localization ring of a coefficient open. -/
abbrev principalCoefficientRing (b : I) :=
  Localization.Away (principalCoefficient I φ d hI b)

/-- The actual test ring map on a coefficient open. -/
def principalCoefficientMap (b : I) : R →+* principalCoefficientRing I φ d hI b :=
  (algebraMap S (principalCoefficientRing I φ d hI b)).comp φ

theorem principalCoefficientMap_ideal_le (b : I) :
    Ideal.map (principalCoefficientMap I φ d hI b) I ≤
      Ideal.span {principalCoefficientMap I φ d hI b (b : R)} :=
  principalTarget_map_le_span I φ d hI
    (algebraMap S (principalCoefficientRing I φ d hI b)) b
    (IsLocalization.Away.algebraMap_isUnit _)

theorem principalCoefficientMap_equation_regular (hd : d ∈ nonZeroDivisors S) (b : I) :
    principalCoefficientMap I φ d hI b (b : R) ∈
      nonZeroDivisors (principalCoefficientRing I φ d hI b) :=
  principalTarget_equation_mem_nonZeroDivisors I φ d hI
    (algebraMap S (principalCoefficientRing I φ d hI b)) b
    (IsLocalization.nonZeroDivisors_le_comap
      (Submonoid.powers (principalCoefficient I φ d hI b))
      (principalCoefficientRing I φ d hI b) hd)
    (IsLocalization.Away.algebraMap_isUnit _)

/-- The actual Rees-chart ring map on each coefficient localization. -/
def principalCoefficientChartLift (hd : d ∈ nonZeroDivisors S) (b : I) :
    chartRing I b →+* principalCoefficientRing I φ d hI b :=
  chartLift I b (principalCoefficientMap I φ d hI b)
    (principalCoefficientMap_equation_regular I φ d hI hd b)
    (principalCoefficientMap_ideal_le I φ d hI b)

theorem principalCoefficientChartLift_comp_baseMap (hd : d ∈ nonZeroDivisors S) (b : I) :
    (principalCoefficientChartLift I φ d hI hd b).comp (chartBaseMap I b) =
      principalCoefficientMap I φ d hI b :=
  chartLift_comp_baseMap I b (principalCoefficientMap I φ d hI b)
    (principalCoefficientMap_equation_regular I φ d hI hd b)
    (principalCoefficientMap_ideal_le I φ d hI b)

/-- The actual ring of the intersection of two coefficient principal opens. -/
abbrev principalOverlapRing (b c : I) :=
  Localization.Away
    (principalCoefficient I φ d hI b * principalCoefficient I φ d hI c)

def principalOverlapLeft (b c : I) :
    principalCoefficientRing I φ d hI b →+* principalOverlapRing I φ d hI b c :=
  IsLocalization.Away.awayToAwayRight
    (principalCoefficient I φ d hI b) (principalCoefficient I φ d hI c)

def principalOverlapRight (b c : I) :
    principalCoefficientRing I φ d hI c →+* principalOverlapRing I φ d hI b c :=
  IsLocalization.Away.awayToAwayLeft
    (principalCoefficient I φ d hI c) (principalCoefficient I φ d hI b)

@[simp]
theorem principalOverlapLeft_algebraMap (b c : I) (s : S) :
    principalOverlapLeft I φ d hI b c
      (algebraMap S (principalCoefficientRing I φ d hI b) s) =
        algebraMap S (principalOverlapRing I φ d hI b c) s :=
  IsLocalization.Away.awayToAwayRight_eq _ _ _

@[simp]
theorem principalOverlapRight_algebraMap (b c : I) (s : S) :
    principalOverlapRight I φ d hI b c
      (algebraMap S (principalCoefficientRing I φ d hI c) s) =
        algebraMap S (principalOverlapRing I φ d hI b c) s :=
  IsLocalization.Away.awayToAwayLeft_eq _ _ _

def principalOverlapMap (b c : I) : R →+* principalOverlapRing I φ d hI b c :=
  (algebraMap S (principalOverlapRing I φ d hI b c)).comp φ

theorem principalOverlapMap_ideal_le (b c : I) :
    Ideal.map (principalOverlapMap I φ d hI b c) I ≤
      Ideal.span {principalOverlapMap I φ d hI b c (b : R)} :=
  principalTarget_map_le_span I φ d hI
    (algebraMap S (principalOverlapRing I φ d hI b c)) b
    (IsLocalization.Away.isUnit_of_dvd
      (principalCoefficient I φ d hI b * principalCoefficient I φ d hI c)
      (dvd_mul_right _ _))

theorem principalOverlapMap_equation_regular (hd : d ∈ nonZeroDivisors S) (b c : I) :
    principalOverlapMap I φ d hI b c (b : R) ∈
      nonZeroDivisors (principalOverlapRing I φ d hI b c) :=
  principalTarget_equation_mem_nonZeroDivisors I φ d hI
    (algebraMap S (principalOverlapRing I φ d hI b c)) b
    (IsLocalization.nonZeroDivisors_le_comap
      (Submonoid.powers (principalCoefficient I φ d hI b * principalCoefficient I φ d hI c))
      (principalOverlapRing I φ d hI b c) hd)
    (IsLocalization.Away.isUnit_of_dvd
      (principalCoefficient I φ d hI b * principalCoefficient I φ d hI c)
      (dvd_mul_right _ _))

theorem principalOverlapLeft_chartLift_comp (hd : d ∈ nonZeroDivisors S) (b c : I) :
    ((principalOverlapLeft I φ d hI b c).comp
      (principalCoefficientChartLift I φ d hI hd b)).comp (chartBaseMap I b) =
        principalOverlapMap I φ d hI b c := by
  ext r
  have h := RingHom.congr_fun (principalCoefficientChartLift_comp_baseMap I φ d hI hd b) r
  change principalCoefficientChartLift I φ d hI hd b (chartBaseMap I b r) =
    algebraMap S (principalCoefficientRing I φ d hI b) (φ r) at h
  change principalOverlapLeft I φ d hI b c
    (principalCoefficientChartLift I φ d hI hd b (chartBaseMap I b r)) =
      algebraMap S (principalOverlapRing I φ d hI b c) (φ r)
  rw [h, principalOverlapLeft_algebraMap]

theorem principalOverlapRight_chartLift_comp (hd : d ∈ nonZeroDivisors S) (b c : I) :
    ((principalOverlapRight I φ d hI b c).comp
      (principalCoefficientChartLift I φ d hI hd c)).comp (chartBaseMap I c) =
        principalOverlapMap I φ d hI b c := by
  ext r
  have h := RingHom.congr_fun (principalCoefficientChartLift_comp_baseMap I φ d hI hd c) r
  change principalCoefficientChartLift I φ d hI hd c (chartBaseMap I c r) =
    algebraMap S (principalCoefficientRing I φ d hI c) (φ r) at h
  change principalOverlapRight I φ d hI b c
    (principalCoefficientChartLift I φ d hI hd c (chartBaseMap I c r)) =
      algebraMap S (principalOverlapRing I φ d hI b c) (φ r)
  rw [h, principalOverlapRight_algebraMap]

section Scheme

variable {A : Type u} [CommRing A] (f : R →+* A) (e : A)
    (hcenter : Ideal.map f I = Ideal.span {e}) (hregular : e ∈ nonZeroDivisors A)

/-- The actual affine open cover derived from the coefficients of the center images. -/
def principalCoefficientCover : (Spec (CommRingCat.of A)).AffineOpenCover :=
  Scheme.affineOpenCoverOfSpanRangeEqTop
    (R := CommRingCat.of A) (principalCoefficient I f e hcenter)
    (span_principalCoefficient_eq_top I f e hcenter hregular)

/-- Cover maps are exactly the canonical localization morphisms. -/
theorem principalCoefficientCover_map (b : I) :
    (principalCoefficientCover I f e hcenter hregular).map b =
      Spec.map (CommRingCat.ofHom
        (algebraMap A (principalCoefficientRing I f e hcenter b))) := rfl

/-- The actual morphism from a coefficient open to the Rees Proj. -/
def principalCoefficientLift (b : I) :
    Spec (CommRingCat.of (principalCoefficientRing I f e hcenter b)) ⟶ scheme I :=
  Spec.map (CommRingCat.ofHom (principalCoefficientChartLift I f e hcenter hregular b)) ≫
    chartι I b

theorem principalCoefficientLift_toSpec (b : I) :
    principalCoefficientLift I f e hcenter hregular b ≫ toSpec I =
      (principalCoefficientCover I f e hcenter hregular).map b ≫
        Spec.map (CommRingCat.ofHom f) := by
  rw [principalCoefficientLift, Category.assoc, chartι_toSpec,
    principalCoefficientCover_map, ← Spec.map_comp, ← Spec.map_comp,
    ← CommRingCat.ofHom_comp, ← CommRingCat.ofHom_comp]
  exact congrArg (fun g : R →+* principalCoefficientRing I f e hcenter b =>
    Spec.map (CommRingCat.ofHom g))
      (principalCoefficientChartLift_comp_baseMap I f e hcenter hregular b)

/-- On the actual product localization, the two local lifts agree as
morphisms to the full Rees Proj. -/
theorem principalCoefficientLift_product_overlap (b c : I) :
    Spec.map (CommRingCat.ofHom (principalOverlapLeft I f e hcenter b c)) ≫
        principalCoefficientLift I f e hcenter hregular b =
      Spec.map (CommRingCat.ofHom (principalOverlapRight I f e hcenter b c)) ≫
        principalCoefficientLift I f e hcenter hregular c := by
  unfold principalCoefficientLift
  rw [← Spec.map_comp_assoc, ← Spec.map_comp_assoc,
    ← CommRingCat.ofHom_comp, ← CommRingCat.ofHom_comp]
  exact chartMap_hom_ext I b (principalOverlapMap I f e hcenter b c)
    (principalOverlapMap_equation_regular I f e hcenter hregular b c)
    (principalOverlapMap_ideal_le I f e hcenter b c) b c
    ((principalOverlapLeft I f e hcenter b c).comp
      (principalCoefficientChartLift I f e hcenter hregular b))
    ((principalOverlapRight I f e hcenter b c).comp
      (principalCoefficientChartLift I f e hcenter hregular c))
    (principalOverlapLeft_chartLift_comp I f e hcenter hregular b c)
    (principalOverlapRight_chartLift_comp I f e hcenter hregular b c)

private theorem principalOverlapLeft_toSpec (b c : I) :
    Spec.map (CommRingCat.ofHom (principalOverlapLeft I f e hcenter b c)) ≫
        (principalCoefficientCover I f e hcenter hregular).map b =
      Spec.map (CommRingCat.ofHom (algebraMap A (principalOverlapRing I f e hcenter b c))) := by
  rw [principalCoefficientCover_map, ← Spec.map_comp, ← CommRingCat.ofHom_comp]
  have h : (principalOverlapLeft I f e hcenter b c).comp
      (algebraMap A (principalCoefficientRing I f e hcenter b)) =
        algebraMap A (principalOverlapRing I f e hcenter b c) := by
    ext r
    exact principalOverlapLeft_algebraMap I f e hcenter b c r
  exact congrArg (fun g : A →+* principalOverlapRing I f e hcenter b c =>
    Spec.map (CommRingCat.ofHom g)) h

private theorem principalOverlapRight_toSpec (b c : I) :
    Spec.map (CommRingCat.ofHom (principalOverlapRight I f e hcenter b c)) ≫
        (principalCoefficientCover I f e hcenter hregular).map c =
      Spec.map (CommRingCat.ofHom (algebraMap A (principalOverlapRing I f e hcenter b c))) := by
  rw [principalCoefficientCover_map, ← Spec.map_comp, ← CommRingCat.ofHom_comp]
  have h : (principalOverlapRight I f e hcenter b c).comp
      (algebraMap A (principalCoefficientRing I f e hcenter c)) =
        algebraMap A (principalOverlapRing I f e hcenter b c) := by
    ext r
    exact principalOverlapRight_algebraMap I f e hcenter b c r
  exact congrArg (fun g : A →+* principalOverlapRing I f e hcenter b c =>
    Spec.map (CommRingCat.ofHom g)) h

private theorem principalOverlap_range (b c : I) :
    Set.range (pullback.fst
      ((principalCoefficientCover I f e hcenter hregular).map b)
      ((principalCoefficientCover I f e hcenter hregular).map c) ≫
        (principalCoefficientCover I f e hcenter hregular).map b).base =
      Set.range (Spec.map (CommRingCat.ofHom
        (algebraMap A (principalOverlapRing I f e hcenter b c)))).base := by
  rw [IsOpenImmersion.range_pullback_to_base_of_left,
    principalCoefficientCover_map, principalCoefficientCover_map]
  change Set.range (PrimeSpectrum.comap
      (algebraMap A (principalCoefficientRing I f e hcenter b))) ∩
    Set.range (PrimeSpectrum.comap
      (algebraMap A (principalCoefficientRing I f e hcenter c))) =
    Set.range (PrimeSpectrum.comap (algebraMap A (principalOverlapRing I f e hcenter b c)))
  rw [PrimeSpectrum.localization_away_comap_range
      (principalCoefficientRing I f e hcenter b) (principalCoefficient I f e hcenter b),
    PrimeSpectrum.localization_away_comap_range
      (principalCoefficientRing I f e hcenter c) (principalCoefficient I f e hcenter c),
    PrimeSpectrum.localization_away_comap_range (principalOverlapRing I f e hcenter b c)
      (principalCoefficient I f e hcenter b * principalCoefficient I f e hcenter c)]
  exact congrArg (fun U : TopologicalSpace.Opens (PrimeSpectrum A) => (U : Set (PrimeSpectrum A)))
    (PrimeSpectrum.basicOpen_mul
      (principalCoefficient I f e hcenter b) (principalCoefficient I f e hcenter c)).symm

/-- The actual categorical overlap is the spectrum of the product localization. -/
def principalOverlapIso (b c : I) :
    pullback ((principalCoefficientCover I f e hcenter hregular).map b)
      ((principalCoefficientCover I f e hcenter hregular).map c) ≅
        Spec (CommRingCat.of (principalOverlapRing I f e hcenter b c)) :=
  IsOpenImmersion.isoOfRangeEq _ _ (principalOverlap_range I f e hcenter hregular b c)

private theorem principalOverlapIso_inv_toSpec (b c : I) :
    (principalOverlapIso I f e hcenter hregular b c).inv ≫
      (pullback.fst ((principalCoefficientCover I f e hcenter hregular).map b)
        ((principalCoefficientCover I f e hcenter hregular).map c) ≫
          (principalCoefficientCover I f e hcenter hregular).map b) =
      Spec.map (CommRingCat.ofHom (algebraMap A (principalOverlapRing I f e hcenter b c))) :=
  IsOpenImmersion.isoOfRangeEq_inv_fac _ _ _

theorem principalOverlapIso_inv_fst (b c : I) :
    (principalOverlapIso I f e hcenter hregular b c).inv ≫
        pullback.fst ((principalCoefficientCover I f e hcenter hregular).map b)
          ((principalCoefficientCover I f e hcenter hregular).map c) =
      Spec.map (CommRingCat.ofHom (principalOverlapLeft I f e hcenter b c)) := by
  apply (cancel_mono ((principalCoefficientCover I f e hcenter hregular).map b)).mp
  rw [Category.assoc, principalOverlapIso_inv_toSpec, principalOverlapLeft_toSpec]

theorem principalOverlapIso_inv_snd (b c : I) :
    (principalOverlapIso I f e hcenter hregular b c).inv ≫
        pullback.snd ((principalCoefficientCover I f e hcenter hregular).map b)
          ((principalCoefficientCover I f e hcenter hregular).map c) =
      Spec.map (CommRingCat.ofHom (principalOverlapRight I f e hcenter b c)) := by
  apply (cancel_mono ((principalCoefficientCover I f e hcenter hregular).map c)).mp
  rw [Category.assoc, ← pullback.condition, principalOverlapIso_inv_toSpec,
    principalOverlapRight_toSpec]

/-- The actual categorical pullback compatibility required by scheme gluing,
derived from the proved product-localization agreement. -/
theorem principalCoefficientLift_overlap (b c : I) :
    pullback.fst ((principalCoefficientCover I f e hcenter hregular).map b)
        ((principalCoefficientCover I f e hcenter hregular).map c) ≫
      principalCoefficientLift I f e hcenter hregular b =
    pullback.snd ((principalCoefficientCover I f e hcenter hregular).map b)
        ((principalCoefficientCover I f e hcenter hregular).map c) ≫
      principalCoefficientLift I f e hcenter hregular c := by
  apply (cancel_epi (principalOverlapIso I f e hcenter hregular b c).inv).mp
  rw [← Category.assoc, principalOverlapIso_inv_fst,
    ← Category.assoc, principalOverlapIso_inv_snd]
  exact principalCoefficientLift_product_overlap I f e hcenter hregular b c

/-- An actual global lift from an affine test scheme whose extended center
has an arbitrary principal nonzerodivisor equation. -/
def principalTargetLift : Spec (CommRingCat.of A) ⟶ scheme I :=
  (principalCoefficientCover I f e hcenter hregular).openCover.glueMorphisms
    (principalCoefficientLift I f e hcenter hregular)
    (principalCoefficientLift_overlap I f e hcenter hregular)

/-- The global lift restricts to the constructed local chart lift on each
member of the actual coefficient cover. -/
theorem principalTargetLift_restrict (b : I) :
    (principalCoefficientCover I f e hcenter hregular).map b ≫
      principalTargetLift I f e hcenter hregular =
        principalCoefficientLift I f e hcenter hregular b :=
  (principalCoefficientCover I f e hcenter hregular).openCover.ι_glueMorphisms _ _ b

/-- The glued morphism is over exactly the given affine test map. -/
@[simp]
theorem principalTargetLift_toSpec :
    principalTargetLift I f e hcenter hregular ≫ toSpec I =
      Spec.map (CommRingCat.ofHom f) := by
  apply (principalCoefficientCover I f e hcenter hregular).openCover.hom_ext
  intro b
  change (principalCoefficientCover I f e hcenter hregular).map b ≫
      (principalTargetLift I f e hcenter hregular ≫ toSpec I) =
    (principalCoefficientCover I f e hcenter hregular).map b ≫
      Spec.map (CommRingCat.ofHom f)
  rw [← Category.assoc, principalTargetLift_restrict, principalCoefficientLift_toSpec]

include e hcenter hregular in
/-- Existence of an actual lift for an arbitrary principal regular target
equation. The equation need not lie in the image of a chosen center element. -/
theorem exists_lift_of_principal_regular :
    ∃ j : Spec (CommRingCat.of A) ⟶ scheme I,
      j ≫ toSpec I = Spec.map (CommRingCat.ofHom f) :=
  ⟨principalTargetLift I f e hcenter hregular,
    principalTargetLift_toSpec I f e hcenter hregular⟩

end Scheme

end KltDP.Geometry.AffineBlowup
