import KltDP.Geometry.AffineBlowupLift
import KltDP.Geometry.AffineBlowupChartCenter

/-!
# Actual Rees chart transport under coordinate isomorphisms

An actual ring isomorphism carrying the center ideal and selected generator
to another center and generator induces an isomorphism of the actual Rees
chart rings. Both maps are constructed by the existing chart universal
property; the same uniqueness theorem proves their inverse identities.
-/

noncomputable section

namespace KltDP.Geometry.AffineBlowup

variable {R S : Type*} [CommRing R] [CommRing S]
    (I : Ideal R) (J : Ideal S) (a : I) (b : J)
    (e : R ≃+* S) (hI : Ideal.map e.toRingHom I = J)
    (ha : e (a : R) = (b : S))

include ha in
/-- The transported selected equation is regular in the target Rees chart. -/
theorem chartCoordinate_regular :
    ((chartBaseMap J b).comp e.toRingHom) (a : R) ∈
      nonZeroDivisors (chartRing J b) := by
  change chartBaseMap J b (e (a : R)) ∈ nonZeroDivisors (chartRing J b)
  rw [ha]
  exact chartBaseMap_equation_mem_nonZeroDivisors J b

include hI ha in
/-- The actual transported center is generated by the selected equation. -/
theorem chartCoordinate_center :
    Ideal.map ((chartBaseMap J b).comp e.toRingHom) I ≤
      Ideal.span {((chartBaseMap J b).comp e.toRingHom) (a : R)} := by
  rw [← Ideal.map_map, hI]
  change Ideal.map (chartBaseMap J b) J ≤ Ideal.span {chartBaseMap J b (e (a : R))}
  rw [ha]
  exact (map_chartBaseMap_ideal J b).le

/-- The map on actual Rees chart rings is obtained from the proved universal property. -/
def chartCoordinateMap : chartRing I a →+* chartRing J b :=
  chartLift I a ((chartBaseMap J b).comp e.toRingHom)
    (chartCoordinate_regular I J a b e ha) (chartCoordinate_center I J a b e hI ha)

@[simp] theorem chartCoordinateMap_baseMap (r : R) :
    chartCoordinateMap I J a b e hI ha (chartBaseMap I a r) =
      chartBaseMap J b (e r) :=
  chartLift_baseMap I a _ _ _ r

include hI in
/-- The inverse coordinate isomorphism transports the actual ideal back. -/
theorem chartCoordinate_inverse_center : Ideal.map e.symm.toRingHom J = I := by
  rw [← hI, Ideal.map_map]
  have he : e.symm.toRingHom.comp e.toRingHom = RingHom.id R := by
    ext r
    exact e.symm_apply_apply r
  rw [he, Ideal.map_id]

include ha in
/-- The inverse coordinate map sends the chosen generator back as an actual element. -/
theorem chartCoordinate_inverse_generator : e.symm (b : S) = (a : R) := by
  rw [← ha, e.symm_apply_apply]

/-- The two constructed coordinate maps are inverse, by chart uniqueness. -/
theorem chartCoordinateMap_inverse_comp :
    (chartCoordinateMap J I b a e.symm
      (chartCoordinate_inverse_center I J e hI)
      (chartCoordinate_inverse_generator I J a b e ha)).comp
        (chartCoordinateMap I J a b e hI ha) = RingHom.id (chartRing I a) := by
  let f := chartCoordinateMap I J a b e hI ha
  let g := chartCoordinateMap J I b a e.symm
    (chartCoordinate_inverse_center I J e hI)
    (chartCoordinate_inverse_generator I J a b e ha)
  have hreg := chartBaseMap_equation_mem_nonZeroDivisors I a
  have hcenter := (map_chartBaseMap_ideal I a).le
  have hcomp : (g.comp f).comp (chartBaseMap I a) = chartBaseMap I a := by
    apply RingHom.ext
    intro r
    simp only [RingHom.comp_apply, f, g, chartCoordinateMap_baseMap, e.symm_apply_apply]
  exact (chartLift_unique I a (chartBaseMap I a) hreg hcenter (g.comp f) hcomp).trans
    (chartLift_unique I a (chartBaseMap I a) hreg hcenter
      (RingHom.id _) (RingHom.id_comp _)).symm

/-- The induced actual chart-ring isomorphism preserves the original base maps. -/
def chartCoordinateEquiv : chartRing I a ≃+* chartRing J b where
  __ := chartCoordinateMap I J a b e hI ha
  invFun := chartCoordinateMap J I b a e.symm
    (chartCoordinate_inverse_center I J e hI)
    (chartCoordinate_inverse_generator I J a b e ha)
  left_inv x := RingHom.congr_fun (chartCoordinateMap_inverse_comp I J a b e hI ha) x
  right_inv x := by
    have h := chartCoordinateMap_inverse_comp J I b a e.symm
      (chartCoordinate_inverse_center I J e hI)
      (chartCoordinate_inverse_generator I J a b e ha)
    exact RingHom.congr_fun h x

@[simp] theorem chartCoordinateEquiv_baseMap (r : R) :
    chartCoordinateEquiv I J a b e hI ha (chartBaseMap I a r) =
      chartBaseMap J b (e r) :=
  chartCoordinateMap_baseMap I J a b e hI ha r

end KltDP.Geometry.AffineBlowup
