import KltDP.Geometry.AffineBlowupRegularPairClosedPoint
import Mathlib.RingTheory.Localization.AtPrime

/-!
# The actual generic prime and parameter of a regular-pair exceptional chart

The original exceptional quotient is the polynomial ring over the
original center quotient. A prime center therefore gives an actual prime
chart ideal. Localizing at that exact ideal makes the original first
parameter generate the maximal ideal. Its nonzerodivisor property is
transported from the accepted original Rees-chart equation.
-/

noncomputable section

namespace KltDP.Geometry.AffineBlowupRegularPairChart

open AffineBlowup

universe u

variable {R : Type u} [CommRing R] (I : Ideal R) (a b : I)
variable (ha : (a : R) ∈ nonZeroDivisors R)
variable (hb : Ideal.Quotient.mk (Ideal.span {(a : R)}) (b : R) ∈
  nonZeroDivisors (R ⧸ Ideal.span {(a : R)}))
variable (hI : I = Ideal.span {(a : R), (b : R)}) [I.IsPrime]

include ha hb hI in
/-- The actual extended center is prime, because its original quotient
map has domain target `(R/I)[T]`. -/
theorem chartCenterIdeal_isPrime : (chartCenterIdeal I a).IsPrime := by
  rw [← exceptionalCoordinateMap_ker I a b ha hb hI]
  exact RingHom.ker_isPrime (exceptionalCoordinateMap I a b ha hb hI)

/-- The generic point of the actual exceptional chart, as its original
prime ideal in the actual Rees chart ring. -/
def exceptionalGenericPrime : PrimeSpectrum (chartRing I a) :=
  ⟨chartCenterIdeal I a, chartCenterIdeal_isPrime I a b ha hb hI⟩

/-- The actual localization at the exceptional generic prime. -/
abbrev exceptionalGenericLocalRing :=
  Localization.AtPrime (exceptionalGenericPrime I a b ha hb hI).asIdeal

/-- The original base parameter mapped through the original chart map
and then through the original prime-localization map. -/
def exceptionalGenericParameter : exceptionalGenericLocalRing I a b ha hb hI :=
  algebraMap (chartRing I a) (exceptionalGenericLocalRing I a b ha hb hI)
    (chartBaseMap I a (a : R))

/-- The maximal ideal at the actual exceptional generic point is
generated by the image of the original first parameter. -/
theorem maximalIdeal_eq_span_exceptionalGenericParameter :
    IsLocalRing.maximalIdeal (exceptionalGenericLocalRing I a b ha hb hI) =
      Ideal.span {exceptionalGenericParameter I a b ha hb hI} := by
  rw [← Localization.AtPrime.map_eq_maximalIdeal
    (I := (exceptionalGenericPrime I a b ha hb hI).asIdeal)]
  change Ideal.map
    (algebraMap (chartRing I a) (exceptionalGenericLocalRing I a b ha hb hI))
    (chartCenterIdeal I a) = _
  rw [chartCenterIdeal, map_chartBaseMap_ideal, Ideal.map_span, Set.image_singleton]
  rfl

/-- The same original parameter remains a nonzerodivisor after the
actual prime localization. -/
theorem exceptionalGenericParameter_mem_nonZeroDivisors :
    exceptionalGenericParameter I a b ha hb hI ∈
      nonZeroDivisors (exceptionalGenericLocalRing I a b ha hb hI) := by
  exact IsLocalization.nonZeroDivisors_le_comap
    (exceptionalGenericPrime I a b ha hb hI).asIdeal.primeCompl
    (exceptionalGenericLocalRing I a b ha hb hI)
    (chartBaseMap_equation_mem_nonZeroDivisors I a)

/-- The actual exceptional generic parameter is nonzero. -/
theorem exceptionalGenericParameter_ne_zero :
    exceptionalGenericParameter I a b ha hb hI ≠ 0 :=
  nonZeroDivisors.coe_ne_zero
    ⟨_, exceptionalGenericParameter_mem_nonZeroDivisors I a b ha hb hI⟩

end KltDP.Geometry.AffineBlowupRegularPairChart
