import KltDP.Geometry.AffineBlowupRegularPairClosedStalk

/-!
# The actual exceptional/residual node in a regular-pair chart

Evaluation at zero after the original exceptional coordinate map has
kernel `(x,t)`. This ideal is maximal over the original center residue
field. Thus every original chart prime containing the exceptional ideal
and residual fraction is this node, and its actual localization has
maximal ideal generated by the original exceptional and fraction germs.
-/

noncomputable section

namespace KltDP.Geometry.AffineBlowupRegularPairChart

open AffineBlowup Polynomial

universe u

variable {R : Type u} [CommRing R] (I : Ideal R) (a b : I)
variable (ha : (a : R) ∈ nonZeroDivisors R)
variable (hb : Ideal.Quotient.mk (Ideal.span {(a : R)}) (b : R) ∈
  nonZeroDivisors (R ⧸ Ideal.span {(a : R)}))
variable (hI : I = Ideal.span {(a : R), (b : R)})

/-- The original exceptional coordinate map evaluated at the residual node. -/
def nodeCharacter : chartRing I a →+* R ⧸ I :=
  (Polynomial.evalRingHom 0).comp (exceptionalCoordinateMap I a b ha hb hI)

theorem nodeCharacter_surjective : Function.Surjective (nodeCharacter I a b ha hb hI) :=
  (Polynomial.eval_surjective 0).comp (exceptionalCoordinateMap_surjective I a b ha hb hI)

theorem nodeCharacter_ker :
    RingHom.ker (nodeCharacter I a b ha hb hI) =
      Ideal.span {chartBaseMap I a (a : R), chartFraction I a b} := by
  let φ := exceptionalCoordinateMap I a b ha hb hI
  have hmap : Ideal.map φ (Ideal.span {chartFraction I a b}) = Ideal.span {X} := by
    rw [Ideal.map_span, Set.image_singleton]
    exact congrArg (fun z => Ideal.span {z})
      (exceptionalCoordinateMap_fraction I a b ha hb hI)
  calc
    _ = (Ideal.span {(X : Polynomial (R ⧸ I))}).comap φ := by
      rw [nodeCharacter, ← RingHom.comap_ker, Polynomial.ker_evalRingHom,
        Polynomial.C_0, sub_zero]
    _ = (Ideal.map φ (Ideal.span {chartFraction I a b})).comap φ :=
      congrArg (Ideal.comap φ) hmap.symm
    _ = Ideal.span {chartFraction I a b} ⊔ chartCenterIdeal I a := by
      rw [Ideal.comap_map_of_surjective' φ
        (exceptionalCoordinateMap_surjective I a b ha hb hI),
        exceptionalCoordinateMap_ker]
    _ = _ := by
      rw [chartCenterIdeal, map_chartBaseMap_ideal, Ideal.span_insert, sup_comm]

attribute [local instance] Ideal.Quotient.field

variable [I.IsMaximal]

include ha hb hI in
/-- The literal exceptional/residual node ideal is maximal over the
original center residue field. Algebraic closedness is not required. -/
theorem nodeIdeal_isMaximal :
    (Ideal.span {chartBaseMap I a (a : R), chartFraction I a b}).IsMaximal := by
  rw [← nodeCharacter_ker I a b ha hb hI]
  exact RingHom.ker_isMaximal_of_surjective _ (nodeCharacter_surjective I a b ha hb hI)

include ha hb hI in
/-- Any actual exceptional prime at which the residual fraction vanishes
is precisely the original node ideal. -/
theorem prime_at_fraction_zero (P : Ideal (chartRing I a)) [P.IsPrime]
    (hcenter : chartCenterIdeal I a ≤ P) (ht : chartFraction I a b ∈ P) :
    P = Ideal.span {chartBaseMap I a (a : R), chartFraction I a b} := by
  have hx : chartBaseMap I a (a : R) ∈ P := hcenter (by
    rw [chartCenterIdeal, map_chartBaseMap_ideal]
    exact Ideal.mem_span_singleton_self _)
  refine ((nodeIdeal_isMaximal I a b ha hb hI).eq_of_le
    (inferInstance : P.IsPrime).ne_top ?_).symm
  rw [Ideal.span_insert]
  exact sup_le ((Ideal.span_singleton_le_iff_mem P).mpr hx)
    ((Ideal.span_singleton_le_iff_mem P).mpr ht)

include ha hb hI in
/-- The original exceptional and residual germs generate the actual
maximal ideal at their node. -/
theorem fraction_node_stalk_span (P : Ideal (chartRing I a)) [P.IsPrime]
    (hcenter : chartCenterIdeal I a ≤ P) (ht : chartFraction I a b ∈ P) :
    Ideal.span {
      algebraMap (chartRing I a) (Localization.AtPrime P) (chartBaseMap I a (a : R)),
      algebraMap (chartRing I a) (Localization.AtPrime P) (chartFraction I a b)} =
      IsLocalRing.maximalIdeal (Localization.AtPrime P) := by
  have hP := prime_at_fraction_zero I a b ha hb hI P hcenter ht
  let ψ := algebraMap (chartRing I a) (Localization.AtPrime P)
  calc
    _ = Ideal.map ψ (Ideal.span {chartBaseMap I a (a : R), chartFraction I a b}) := by
      rw [Ideal.map_span, Set.image_pair]
    _ = Ideal.map ψ P := congrArg (Ideal.map ψ) hP.symm
    _ = _ := Localization.AtPrime.map_eq_maximalIdeal (I := P)

end KltDP.Geometry.AffineBlowupRegularPairChart
