import KltDP.Geometry.AffineBlowupLift

/-!
# Chart containment and agreement of actual affine blowup lifts

For an admissible test map `φ`, whose extended center is generated by the
regular equation `φ a`, any map into another Rees chart over `φ` has unit
ratio `a/b`. The actual Proj chart isomorphism then proves containment in
the chart at `a`. Its open-immersion lift is the previously constructed
unique affine chart lift. Consequently the resulting morphisms to the full
Rees Proj agree, even when presented in different charts.

This module does not assume the chart containment it proves. It establishes
agreement for actual affine chart presentations; constructing a covering by
such presentations for an arbitrary global test scheme remains a separate
gluing step. No reducedness, domain, field, or Noetherian hypothesis is used.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory

namespace KltDP.Geometry.AffineBlowup

universe u v

variable {R : Type u} [CommRing R] (I : Ideal R)

section Algebra

variable {S : Type v} [CommRing S] (a b : I) (φ : R →+* S)

/-- Under an admissible test map, the ratio from any chart to the chosen
principal equation is a unit. The alternative chart map is actual input;
its containment in the chosen chart is not assumed. -/
theorem chartFraction_isUnit_of_principal_regular
    (hreg : φ (a : R) ∈ nonZeroDivisors S)
    (hI : Ideal.map φ I ≤ Ideal.span {φ (a : R)})
    (ψ : chartRing I b →+* S) (hψ : ψ.comp (chartBaseMap I b) = φ) :
    IsUnit (ψ (chartFraction I b a)) := by
  have hb (r : R) : ψ (chartBaseMap I b r) = φ r := RingHom.congr_fun hψ r
  have hmem : φ (b : R) ∈ Ideal.span {φ (a : R)} :=
    hI (Ideal.mem_map_of_mem φ b.property)
  obtain ⟨s, hs⟩ := Ideal.mem_span_singleton.mp hmem
  have h := congrArg ψ (chartBaseMap_mul_chartFraction I b a)
  simp only [map_mul, hb] at h
  have hinv : s * ψ (chartFraction I b a) = 1 := by
    apply (mul_cancel_left_mem_nonZeroDivisors hreg).mp
    calc
      φ (a : R) * (s * ψ (chartFraction I b a)) =
          φ (b : R) * ψ (chartFraction I b a) := by rw [← mul_assoc, ← hs]
      _ = φ (a : R) := h
      _ = φ (a : R) * 1 := (mul_one _).symm
  exact isUnit_iff_exists_inv'.mpr ⟨s, hinv⟩

end Algebra

/-- The pinned Proj chart morphism is the same locally ringed-space map used
by its homogeneous-fraction membership theorem. This is the equality already
proved inside Mathlib's `Proj.basicOpenIsoSpec` construction. -/
private theorem chartIso_hom_toLRSHom (b : I) :
    (chartIso I b).hom.toLRSHom =
      ProjectiveSpectrum.Proj.toSpec (ReesGrading.component I) (degreeOne I b) := by
  change (Proj.basicOpenToSpec (ReesGrading.component I) (degreeOne I b)).toLRSHom = _
  refine Eq.trans ?_ (ΓSpec.locallyRingedSpaceAdjunction.homEquiv_apply _ _ _).symm
  dsimp [Proj.basicOpenToSpec, Scheme.Opens.toSpecΓ]
  simp only [eqToHom_op, Category.assoc, ← Spec.map_comp]
  rfl

/-- Membership of the actual chart ratio in a prime is exactly membership
of its homogeneous numerator in the corresponding Proj point. -/
theorem chartFraction_mem_prime_iff (a b : I) (p : PrimeSpectrum (chartRing I b)) :
    chartFraction I b a ∈ p.asIdeal ↔
      degreeOne I a ∈ ((chartι I b).base p).asHomogeneousIdeal := by
  let x := (chartIso I b).inv.base p
  have he : (chartIso I b).hom.base x = p := by
    have h := congrArg
      (fun j : Spec (CommRingCat.of (chartRing I b)) ⟶
        Spec (CommRingCat.of (chartRing I b)) => j.base p)
      (chartIso I b).inv_hom_id
    simpa only [Scheme.comp_base_apply] using h
  have h : chartFraction I b a ∈
        ((ProjectiveSpectrum.Proj.toSpec (ReesGrading.component I) (degreeOne I b)).base x).asIdeal ↔
      degreeOne I a ∈ x.val.asHomogeneousIdeal := by
    unfold chartFraction chartMonomialFraction HomogeneousLocalization.Away.mk
    exact ProjectiveSpectrum.Proj.mk_mem_toSpec_base_apply (ReesGrading.component I) x _
  rw [← chartIso_hom_toLRSHom I b] at h
  change chartFraction I b a ∈ ((chartIso I b).hom.base x).asIdeal ↔
    degreeOne I a ∈ x.val.asHomogeneousIdeal at h
  rw [he] at h
  exact h

/-- Actual chart containment is detected by the chart ratio. -/
theorem chartι_mem_chartOpen_iff (a b : I) (p : PrimeSpectrum (chartRing I b)) :
    (chartι I b).base p ∈ chartOpen I a ↔ chartFraction I b a ∉ p.asIdeal := by
  change degreeOne I a ∉ ((chartι I b).base p).asHomogeneousIdeal ↔ _
  exact (chartFraction_mem_prime_iff I a b p).not.symm

/-- The range of the actual chart immersion is its prescribed Proj open. -/
theorem chartι_opensRange (a : I) : (chartι I a).opensRange = chartOpen I a :=
  Proj.opensRange_awayι (ReesGrading.component I) (degreeOne I a) (degreeOne_mem I a) (by decide)

section Scheme

variable {S : Type u} [CommRing S] (a : I) (φ : R →+* S)
    (hreg : φ (a : R) ∈ nonZeroDivisors S)
    (hI : Ideal.map φ I ≤ Ideal.span {φ (a : R)})

include hreg hI in
/-- Every actual affine map through another chart over an admissible test
map has image in the chosen chart. This is a proved containment, not an input. -/
theorem chartMap_range_subset (b : I) (ψ : chartRing I b →+* S)
    (hψ : ψ.comp (chartBaseMap I b) = φ) :
    Set.range (Spec.map (CommRingCat.ofHom ψ) ≫ chartι I b).base ⊆
      Set.range (chartι I a).base := by
  change Set.range (Spec.map (CommRingCat.ofHom ψ) ≫ chartι I b).base ⊆
    (chartι I a).opensRange
  rw [chartι_opensRange]
  rintro _ ⟨p, rfl⟩
  change (chartι I b).base (PrimeSpectrum.comap ψ p) ∈ chartOpen I a
  apply (chartι_mem_chartOpen_iff I a b (PrimeSpectrum.comap ψ p)).mpr
  change ψ (chartFraction I b a) ∉ p.asIdeal
  intro hmem
  exact p.isPrime.ne_top (p.asIdeal.eq_top_of_isUnit_mem hmem
    (chartFraction_isUnit_of_principal_regular I a b φ hreg hI ψ hψ))

/-- Any actual affine map through any Rees chart over this test map agrees
with the canonical lift as a morphism into the full Rees Proj. -/
theorem affineLift_eq_of_chartMap (b : I) (ψ : chartRing I b →+* S)
    (hψ : ψ.comp (chartBaseMap I b) = φ) :
    Spec.map (CommRingCat.ofHom ψ) ≫ chartι I b = affineLift I a φ hreg hI := by
  let j := Spec.map (CommRingCat.ofHom ψ) ≫ chartι I b
  let l := IsOpenImmersion.lift (chartι I a) j
    (chartMap_range_subset I a φ hreg hI b ψ hψ)
  have hl : l ≫ chartι I a = j := IsOpenImmersion.lift_fac _ _ _
  have hj : j ≫ toSpec I = Spec.map (CommRingCat.ofHom φ) := by
    dsimp only [j]
    rw [Category.assoc, chartι_toSpec, ← Spec.map_comp, ← CommRingCat.ofHom_comp]
    exact congrArg (fun f : R →+* S => Spec.map (CommRingCat.ofHom f)) hψ
  have hbase : l ≫ Spec.map (CommRingCat.ofHom (chartBaseMap I a)) =
      Spec.map (CommRingCat.ofHom φ) := by
    have hchart : chartι I a ≫ toSpec I =
        Spec.map (CommRingCat.ofHom (chartBaseMap I a)) := chartι_toSpec I a
    rw [← hchart, ← Category.assoc, hl, hj]
  have he := affineChartLift_unique I a φ hreg hI l hbase
  calc
    j = l ≫ chartι I a := hl.symm
    _ = affineLift I a φ hreg hI :=
      congrArg (fun f => f ≫ chartι I a) he

/-- Canonical lifts formed using two different actual regular generators
agree as morphisms to the Rees Proj. -/
theorem affineLift_independent_chart (b : I)
    (hbreg : φ (b : R) ∈ nonZeroDivisors S)
    (hbI : Ideal.map φ I ≤ Ideal.span {φ (b : R)}) :
    affineLift I b φ hbreg hbI = affineLift I a φ hreg hI :=
  affineLift_eq_of_chartMap I a φ hreg hI b (chartLift I b φ hbreg hbI)
    (chartLift_comp_baseMap I b φ hbreg hbI)

include a hreg hI in
/-- Two actual affine chart presentations over the same admissible test map
determine the same morphism to the full Proj. -/
theorem chartMap_hom_ext (b c : I)
    (ψ : chartRing I b →+* S) (χ : chartRing I c →+* S)
    (hψ : ψ.comp (chartBaseMap I b) = φ)
    (hχ : χ.comp (chartBaseMap I c) = φ) :
    Spec.map (CommRingCat.ofHom ψ) ≫ chartι I b =
      Spec.map (CommRingCat.ofHom χ) ≫ chartι I c :=
  (affineLift_eq_of_chartMap I a φ hreg hI b ψ hψ).trans
    (affineLift_eq_of_chartMap I a φ hreg hI c χ hχ).symm

end Scheme

end KltDP.Geometry.AffineBlowup
