import KltDP.Geometry.Positivity
import KltDP.Geometry.SchemeStructureTensor
import KltDP.Geometry.CoherentModule

/-!
# Ampleness in Serre's original form, and its link to the queued positivity interfaces

`docs/GAPS.md` records ampleness as absent in every form, and names it the cheapest and most widely
shared of the three absences blocking the geometric core of the Hodge index theorem. Re-verified this
round: `IsAmple`/`isAmple`/`IsVeryAmple` are declared nowhere in the accepted tree, the queue or the
pinned Mathlib, and `AlgebraicGeometry/ProjectiveSpectrum/` contains only `Basic`, `Proper`, `Scheme`,
`StructureSheaf`, `Topology` — **no Serre twist `O(n)`**.

**Which definition, and why this one.** Three presentations were available and two are refused:

* *very ample* (`i : X ↪ P^n` with `i^*O(1) ≅ L`) is **unstatable** — every witness routes through
  `O(1)`, which the pin does not have;
* the *Nakai–Moishezon* and *Serre cohomological vanishing* characterisations are **criteria**, and
  adopting a criterion as the definition is the substitution this lane declined twice already
  (E16's completed-stalk node, E22's Nakai–Moishezon). They would make `IsAmple` provable-looking by
  changing what it means.

What is left is **Serre's own definition**, which is not a criterion: `L` is ample when every
coherent sheaf, twisted by a high enough power of `L`, is generated by its global sections. That is
stated here over the accepted coherence predicate and the queued `IsGloballyGenerated`.

* `isGloballyGenerated_of_iso` — global generation transfers along an isomorphism. Absent everywhere
  (checked by name and by shape sweep); it is the step the link below needs.
* **`IsAmple`** — Serre's definition. The twist is written `M.obj ⊗ F` with the power sheaf on the
  left, because the accepted unitor `schemeStructureTensorRightIso` is stated on that side; this is a
  presentational choice, not a restriction. Powers are taken in the accepted Picard group and the
  representing sheaf is existentially quantified, exactly as the queued `IsSemiample` already does,
  since no sheaf is *chosen* to represent `L.toPic ^ n`.
* **`isSemiample_of_isAmple`** — the required connection to existing machinery: ample implies
  semi-ample, by instantiating the definition at the structure sheaf and cancelling the twist with
  the accepted `schemeStructureTensorRightIso`. Coherence of `O_X` is the accepted instance
  `unit_isCoherentModule`, whence the `[IsLocallyNoetherian X]` hypothesis.

**What would be false if the definition were different?** `isSemiample_of_isAmple` would fail: a
predicate not implying that *some positive power is globally generated* cannot be this one. The
implication is what keeps the definition from naming nothing.

**Honest limitation, stated rather than hidden.** Nothing in the accepted tree or the pin can yet
*witness* ampleness: producing one needs global sections of high powers, which needs `O(1)` or a
vanishing theorem, neither of which exists here. So this is a definition plus a consequence, not a
nonvacuity proof — `IsAmple` has no instance, and none is claimed.

**Import-closure cost, chosen deliberately.** `Positivity` is **queued, not accepted**, so this module
is queue-internal (group (h)) and certifies only after `Positivity` does. The alternative — an
accepted-only ampleness — would have had nothing to connect to, since every positivity interface in
this project is queued. A connected definition was preferred to an isolated one.

Nothing is admitted and no literature literal is used.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.MonoidalCategory

universe u

namespace KltDP.Geometry.AmpleSerre

attribute [local instance] Types.instFunLike Types.instConcreteCategory

local instance ampleSerreMonoidal (Y : Scheme.{u}) : MonoidalCategory Y.Modules :=
  Scheme.Modules.monoidalCategory Y

variable {X : Scheme.{u}}

/-- **Global generation transfers along an isomorphism**: if a free sheaf surjects onto `M` and
`M ≅ N`, the composite surjects onto `N`. -/
theorem isGloballyGenerated_of_iso {M N : X.Modules} (e : M ≅ N)
    (h : Positivity.IsGloballyGenerated M) : Positivity.IsGloballyGenerated N := by
  obtain ⟨I, φ, hφ⟩ := h
  haveI := hφ
  exact ⟨I, φ ≫ e.hom, inferInstance⟩

/-- **Ampleness, in Serre's original sense**: for every coherent `F` there is an `N` beyond which
every twist `L^n ⊗ F` is generated by its global sections.

The representing sheaf of `L.toPic ^ n` is existentially quantified because no sheaf is chosen for a
Picard power — the same device the queued `IsSemiample` uses. -/
def IsAmple (L : InvertibleSheaf X) : Prop :=
  ∀ F : X.Modules, IsCoherentModule F → ∃ N : ℕ, ∀ n : ℕ, N ≤ n →
    ∃ M : InvertibleSheaf X, M.toPic = L.toPic ^ n ∧
      Positivity.IsGloballyGenerated (M.obj ⊗ F)

/-- **Ample implies semi-ample.** Instantiate Serre's definition at the structure sheaf — coherent by
the accepted `unit_isCoherentModule` — and cancel the twist with the accepted unitor
`schemeStructureTensorRightIso`. This is the connection that keeps `IsAmple` from being isolated. -/
theorem isSemiample_of_isAmple [IsLocallyNoetherian X] (L : InvertibleSheaf X)
    (h : IsAmple L) : Positivity.IsSemiample L := by
  obtain ⟨N, hN⟩ := h (_root_.SheafOfModules.unit X.ringCatSheaf) inferInstance
  obtain ⟨M, hMclass, hMgg⟩ := hN (N + 1) (Nat.le_succ N)
  exact ⟨N + 1, Nat.succ_pos N, M, hMclass,
    isGloballyGenerated_of_iso (schemeStructureTensorRightIso M.obj) hMgg⟩

end KltDP.Geometry.AmpleSerre
