import KltDP.Geometry.EffectiveCartierSection

/-!
# The original Cartier divisor ideal and canonical-section image

For an original Cartier divisor D, define J_D independently of its
canonical section: it is the preimage of the actual O(-D) submodule under
the original O → K_X map. Thus it is O ∩ O(-D) before effectiveness is
known. Original restriction maps and existing Cartier-submodule locality
make it a genuine ideal subsheaf of O.

On any actual regular equation chart f=germ(d) for D, its ideal is (d).
When these original charts cover, their restrictions to intersections
and the genuine sheaf locality conditions identify this prescribed ideal
with the image of evaluation on the original canonical section. The
preceding integral-image theorem then gives invertibility with an actual
square-root isomorphism. No image equality is included in the data.

This does not yet construct IdealSheafData or a global closed subscheme,
identify that subscheme with a prescribed sum of prime curves, or prove
reducedness or a regular immersion. Generic quasicoherent-ideal localization
is a separate adapter. Reuse: existing actual fractional-module locality,
principal equations, submodule sheaves and canonical-section image theorem;
pinned ideal membership, actual germ injectivity and unit identities.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory MonoidalCategory Opposite TopologicalSpace

universe u

namespace KltDP.Geometry

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable (X : Scheme.{u}) [IsIntegral X]

/-- The prescribed divisor ideal, defined before any section image:
regular functions whose original rational image lies in O(-D). -/
def cartierSectionIdeal (D : CartierDivisor X) (W : X.Opens) : Ideal Γ(X, W) :=
  (cartierSectionSubmodule X (-D) W).comap
    ((structureToRationalFunctionModule X).val.app (op W)).hom

/-- The prescribed ideals respect the actual original ring restrictions. -/
theorem cartierSectionIdeal_restrict (D : CartierDivisor X) {V W : X.Opens}
    (i : V ⟶ W) (s : Γ(X, W)) (hs : s ∈ cartierSectionIdeal X D W) :
    X.presheaf.map i.op s ∈ cartierSectionIdeal X D V := by
  have h := (cartierDivisorPresheafSubmodule X (-D)).map_mem i.op hs
  change (rationalFunctionModule X).val.map i.op
    ((structureToRationalFunctionModule X).val.app (op W) s) ∈
      cartierSectionSubmodule X (-D) V at h
  rw [← _root_.PresheafOfModules.naturality_apply] at h
  exact h

/-- Membership in the prescribed ideal is local on the original open,
by locality of the independently constructed O(-D) subsheaf. -/
theorem cartierSectionIdeal_of_locally_mem (D : CartierDivisor X)
    (W : X.Opens) (s : Γ(X, W))
    (hs : ∀ x ∈ W, ∃ (V : X.Opens) (i : V ⟶ W),
      x ∈ V ∧ X.presheaf.map i.op s ∈ cartierSectionIdeal X D V) :
    s ∈ cartierSectionIdeal X D W := by
  apply (cartierDivisorSubmodule X (-D)).isSheaf
  intro x hx
  obtain ⟨V, i, hxV, hV⟩ := hs x hx
  refine ⟨V, i, ?_, hxV⟩
  change (rationalFunctionModule X).val.map i.op
      ((structureToRationalFunctionModule X).val.app (op W) s) ∈
    cartierSectionSubmodule X (-D) V
  rw [← _root_.PresheafOfModules.naturality_apply]
  exact hV

/-- The original divisor ideals as actual stable submodules of O. -/
def cartierIdealPresheafSubmodule (D : CartierDivisor X) :
    (_root_.SheafOfModules.unit X.ringCatSheaf).val.Submodule where
  obj W := cartierSectionIdeal X D W.unop
  map {V W} i := fun s hs => cartierSectionIdeal_restrict X D i.unop s hs

/-- The genuine prescribed ideal subsheaf of the original structure sheaf. -/
def cartierIdealSubmodule (D : CartierDivisor X) :
    (_root_.SheafOfModules.unit X.ringCatSheaf).Submodule where
  toSubmodule := cartierIdealPresheafSubmodule X D
  isSheaf {W} s hs := by
    apply cartierSectionIdeal_of_locally_mem X D W.unop s
    intro x hx
    obtain ⟨V, i, hV, hxV⟩ := hs x hx
    exact ⟨V, i, hxV, hV⟩

/-- Restrict an original regular equation chart along an original open
inclusion. Its coefficient is the actual ring restriction. -/
def RegularCartierEquationChart.restrict (D : CartierDivisor X)
    (c : RegularCartierEquationChart X D) (V : X.Opens) [Nonempty V]
    (h : V ≤ c.chart.openSet) : RegularCartierEquationChart X D where
  chart :=
    { openSet := V
      nonempty := inferInstance
      equation := c.chart.equation
      represents := cartierGlobalEquation_restrict X D (homOfLE h)
        c.chart.equation c.chart.represents }
  coefficient := X.presheaf.map (homOfLE h).op c.coefficient
  germ_eq := (X.presheaf.germ_res_apply (homOfLE h) (genericPoint X)
    (genericPoint_mem_nonempty_open X V) c.coefficient).trans c.germ_eq

/-- The independently defined original divisor ideal is generated by
its actual regular equation; the sign O(-D)=f O is derived. -/
theorem cartierSectionIdeal_eq_span (D : CartierDivisor X)
    (c : RegularCartierEquationChart X D) :
    cartierSectionIdeal X D c.chart.openSet =
      Ideal.span ({c.coefficient} : Set Γ(X, c.chart.openSet)) := by
  have hneg : cartierEquationClassHom X c.chart.openSet
      (Additive.ofMul c.chart.equation⁻¹) =
      (cartierDivisorSheaf X).val.map
        (homOfLE (le_top : c.chart.openSet ≤ ⊤)).op (-D) := by
    change cartierEquationClassHom X c.chart.openSet (-(Additive.ofMul c.chart.equation)) = _
    rw [map_neg, c.chart.represents, map_neg]
  apply SetLike.ext
  intro s
  change (structureToRationalFunctionModule X).val.app (op c.chart.openSet) s ∈
      cartierSectionSubmodule X (-D) c.chart.openSet ↔ _
  rw [mem_cartierSectionSubmodule_iff X (-D) c.chart.openSet c.chart.equation⁻¹ hneg,
    rationalFunctionModuleSectionsEquiv_structure]
  change X.germToFunctionField c.chart.openSet s ∈
    principalEquationSubmodule X c.chart.openSet c.chart.equation⁻¹ ↔ _
  rw [mem_principalEquationSubmodule_iff, Ideal.mem_span_singleton]
  constructor
  · rintro ⟨a, ha⟩
    refine ⟨a, ?_⟩
    apply X.germToFunctionField_injective c.chart.openSet
    rw [map_mul, c.germ_eq, ha]
    exact (Units.mul_inv_cancel_left c.chart.equation _).symm
  · rintro ⟨a, rfl⟩
    refine ⟨a, ?_⟩
    rw [map_mul, c.germ_eq]
    exact (Units.inv_mul_cancel_left c.chart.equation _).symm

local instance cartierIdealMonoidal : MonoidalCategory X.Modules :=
  Scheme.Modules.monoidalCategory X

/-- The original prescribed ideal equals the genuine canonical-section
image on every original open, using proved locality of both actual ideals. -/
theorem cartierSectionIdeal_eq_imageIdeal [X.IsSeparated] (D : CartierDivisor X)
    (hD : HasRegularCartierEquations X D) (L : InvertibleSheaf X)
    (e : L.obj ⊗ L.obj ≅ cartierDivisorModule X D) (W : X.Opens) :
    cartierSectionIdeal X D W =
      sectionImageIdeal X (cartierDivisorModule X D) (effectiveCartierSection X D hD) W := by
  apply le_antisymm
  · intro s hs
    apply sectionImageIdeal_of_locally_mem
    intro x hx
    obtain ⟨c, hxc⟩ := hD x
    let V : X.Opens := W ⊓ c.chart.openSet
    letI : Nonempty V := ⟨⟨x, hx, hxc⟩⟩
    let d := RegularCartierEquationChart.restrict X D c V
      (show V ≤ c.chart.openSet from inf_le_right)
    have hm := cartierSectionIdeal_restrict X D (homOfLE (show V ≤ W from inf_le_left)) s hs
    have hlocal : cartierSectionIdeal X D V =
        sectionImageIdeal X (cartierDivisorModule X D)
          (effectiveCartierSection X D hD) V :=
      (cartierSectionIdeal_eq_span X D d).trans
        (effectiveCartierSection_imageIdeal X D hD L e d).symm
    refine ⟨V, homOfLE inf_le_left, ⟨hx, hxc⟩, ?_⟩
    exact hlocal.le hm
  · intro s hs
    apply cartierSectionIdeal_of_locally_mem
    intro x hx
    obtain ⟨c, hxc⟩ := hD x
    let V : X.Opens := W ⊓ c.chart.openSet
    letI : Nonempty V := ⟨⟨x, hx, hxc⟩⟩
    let d := RegularCartierEquationChart.restrict X D c V
      (show V ≤ c.chart.openSet from inf_le_right)
    have hm := sectionImageIdeal_restrict X (cartierDivisorModule X D)
      (effectiveCartierSection X D hD) (homOfLE (show V ≤ W from inf_le_left)) s hs
    have hlocal : cartierSectionIdeal X D V =
        sectionImageIdeal X (cartierDivisorModule X D)
          (effectiveCartierSection X D hD) V :=
      (cartierSectionIdeal_eq_span X D d).trans
        (effectiveCartierSection_imageIdeal X D hD L e d).symm
    refine ⟨V, homOfLE inf_le_left, ⟨hx, hxc⟩, ?_⟩
    exact hlocal.ge hm

/-- Equality of the genuine ideal subsheaves, retaining the original O. -/
theorem cartierIdealSubmodule_eq_imageSubmodule [X.IsSeparated] (D : CartierDivisor X)
    (hD : HasRegularCartierEquations X D) (L : InvertibleSheaf X)
    (e : L.obj ⊗ L.obj ≅ cartierDivisorModule X D) :
    cartierIdealSubmodule X D =
      sectionImageSubmodule X (cartierDivisorModule X D) (effectiveCartierSection X D hD) := by
  apply _root_.SheafOfModules.Submodule.ext
  apply _root_.PresheafOfModules.Submodule.ext
  intro W
  exact cartierSectionIdeal_eq_imageIdeal X D hD L e W.unop

/-- The actual prescribed ideal is invertible, via the derived equality
with the genuine nonzero canonical-section image. -/
theorem cartierIdealSubmodule_isInvertible [X.IsSeparated] (D : CartierDivisor X)
    (hD : HasRegularCartierEquations X D) (L : InvertibleSheaf X)
    (e : L.obj ⊗ L.obj ≅ cartierDivisorModule X D) :
    KltDP.SheafOfModules.IsInvertible (R := X.ringCatSheaf)
      (cartierIdealSubmodule X D).toSheafOfModules := by
  rw [cartierIdealSubmodule_eq_imageSubmodule X D hD L e]
  exact InvertibleQuadraticAtlas.sectionImageSubmodule_isInvertible_of_nonzero X
    (cartierDivisorModule X D) (effectiveCartierSection X D hD) L e
    (effectiveCartierSection_ne_zero X D hD)

end KltDP.Geometry
