import KltDP.Geometry.CartierDivisorPullbackIdeal
import KltDP.Geometry.GluedIdealInvertible

/-!
# Compatible affine charts for the pullback of an effective Cartier divisor

First module of the general Cartier comparison `π^* I_D ≅ I_{π^*D}`, for a generic-point-preserving
morphism `π : X ⟶ Y` of integral schemes and an effective Cartier divisor `D` on `Y` with regular
equations.  It contains only **chart data**: no module-level construction, nothing that can time out.

For a regular chart `(U, f, d)` of `D`, a nonempty affine `V ≤ U` of `Y` and a nonempty affine
`W ≤ π ⁻¹ᵁ V` of `X`:

* `I_D` is generated on `V` by the restricted coefficient, a nonzerodivisor (`chartIdeal_eq_span`,
  `chartCoefficient_regular`), so the accepted `gluedAffineKernelIso` trivialises `I_D` over `V`;
* `I_{π^*D}` is generated on `W` by `π.appLE U W d`, also a nonzerodivisor
  (`pullbackIdeal_eq_span`, `pullbackCoefficient_regular`), so the same trivialisation applies over `W`;
* **the two generators correspond**: `π.appLE V W (d|_V) = π.appLE U W d`
  (`appLE_restrict_eq`, from the pinned `Scheme.Hom.map_appLE`), which is what makes the two frames
  comparable and hence the comparison an isomorphism of ideal *modules*, not merely of supports.

`exists_compatible_charts` produces such a pair around every point of `X`, so these charts cover `X`.

**Why the reduced/closed-range shortcut does not apply here.** `ker_eq_of_closure_range_eq` pins a
kernel down only up to the reduced structure (it identifies `f.ker` with the vanishing ideal of the
closure of the range).  A pulled-back divisor is characteristically *non-reduced*: the accepted
`f29_tower_fiber_relation` reads `π^*F₀ = F̃ + Σ_j (j+1)·C_j + (N+1)·P`.  Using the shortcut here would
prove the statement for the reduction of `π^*D`, which is strictly weaker.  It applies only when
`π^*D` is reduced — essentially the case already covered by
`SchemeKernelBaseChangeIsoLocus.baseChangeKernelIso`.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Opposite TopologicalSpace

universe u

namespace KltDP.Geometry.CartierPullbackFrameCharts

open KltDP.Geometry KltDP.Geometry.CartierDivisorPullbackIdeal

variable {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y] (π : X ⟶ Y)
  [GenericPointPreserving π] (D : CartierDivisor Y) (hD : HasRegularCartierEquations Y D)

/-! ## The `Y`-side chart -/

/-- The coefficient of a regular chart of `D`, restricted to an affine open inside it. -/
def chartCoefficient (c : RegularCartierEquationChart Y D) (V : Y.affineOpens)
    (hV : V.1 ≤ c.chart.openSet) : Γ(Y, V.1) :=
  Y.presheaf.map (homOfLE hV).op c.coefficient

include hD in
/-- On that affine open the ideal of `D` is generated by the restricted coefficient. -/
theorem chartIdeal_eq_span (c : RegularCartierEquationChart Y D) (V : Y.affineOpens)
    [Nonempty V.1] (hV : V.1 ≤ c.chart.openSet) :
    (effectiveCartierIdealDataOfRegularEquations Y D hD).ideal V =
      Ideal.span {chartCoefficient D c V hV} :=
  effectiveCartierIdealDataOfRegularEquations_ideal_chart Y D hD
    (RegularCartierEquationChart.restrict Y D c V.1 hV) V.2

/-- The restricted coefficient is a nonzerodivisor. -/
theorem chartCoefficient_regular (c : RegularCartierEquationChart Y D) (V : Y.affineOpens)
    [Nonempty V.1] (hV : V.1 ≤ c.chart.openSet) :
    chartCoefficient D c V hV ∈ nonZeroDivisors Γ(Y, V.1) :=
  mem_nonZeroDivisors_of_ne_zero
    (RegularCartierEquationChart.coefficient_ne_zero Y D
      (RegularCartierEquationChart.restrict Y D c V.1 hV))

/-! ## The two generators correspond -/

/-- **Restricting on `Y` and then pulling back is pulling back directly** (pinned
`Scheme.Hom.map_appLE`). -/
theorem appLE_restrict_eq (c : RegularCartierEquationChart Y D) (V : Y.affineOpens)
    (hV : V.1 ≤ c.chart.openSet) (W : X.affineOpens) (hW : W.1 ≤ π ⁻¹ᵁ V.1)
    (hWc : W.1 ≤ π ⁻¹ᵁ c.chart.openSet) :
    π.appLE V.1 W.1 hW (chartCoefficient D c V hV) =
      π.appLE c.chart.openSet W.1 hWc c.coefficient := by
  have h := Scheme.Hom.map_appLE π hW (homOfLE hV).op
  change (Y.presheaf.map (homOfLE hV).op ≫ π.appLE V.1 W.1 hW) c.coefficient =
    π.appLE c.chart.openSet W.1 hWc c.coefficient
  rw [h]

/-! ## The `X`-side chart -/

include hD in
/-- On an affine open of `X` inside the preimage, the ideal of the pulled-back divisor is generated by
the pulled-back coefficient. -/
theorem pullbackIdeal_eq_span (c : RegularCartierEquationChart Y D) (W : X.affineOpens)
    [Nonempty W.1] (hWc : W.1 ≤ π ⁻¹ᵁ c.chart.openSet) :
    (pullbackIdealData π D hD).ideal W =
      Ideal.span {π.appLE c.chart.openSet W.1 hWc c.coefficient} :=
  pullbackIdealData_ideal π D hD c W hWc

/-- The pulled-back coefficient is a nonzerodivisor. -/
theorem pullbackCoefficient_regular (c : RegularCartierEquationChart Y D) (W : X.affineOpens)
    [Nonempty W.1] (hWc : W.1 ≤ π ⁻¹ᵁ c.chart.openSet) :
    π.appLE c.chart.openSet W.1 hWc c.coefficient ∈ nonZeroDivisors Γ(X, W.1) :=
  mem_nonZeroDivisors_of_ne_zero (pulledCoefficient_restrict_ne_zero π D c W hWc)

/-! ## The charts cover `X` -/

include hD in
/-- Around every point of `X` there is a compatible pair: a regular chart of `D`, a nonempty affine
`V` inside it, and a nonempty affine `W ⊆ π ⁻¹ᵁ V` containing the point. -/
theorem exists_compatible_charts (x : X) :
    ∃ (c : RegularCartierEquationChart Y D) (V : Y.affineOpens) (W : X.affineOpens),
      V.1 ≤ c.chart.openSet ∧ x ∈ W.1 ∧ W.1 ≤ π ⁻¹ᵁ V.1 := by
  obtain ⟨c, hc⟩ := hD (π.base x)
  obtain ⟨_, ⟨V, hV, rfl⟩, hxV, hVle⟩ :=
    (isBasis_affine_open Y).exists_subset_of_mem_open hc c.chart.openSet.2
  obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ :=
    (isBasis_affine_open X).exists_subset_of_mem_open (show x ∈ π ⁻¹ᵁ V from hxV)
      (π ⁻¹ᵁ V).2
  exact ⟨c, ⟨V, hV⟩, ⟨W, hW⟩, hVle, hxW, hWle⟩

end KltDP.Geometry.CartierPullbackFrameCharts
