import KltDP.Geometry.CartierDivisorPullback
import KltDP.Geometry.EffectiveCartierOfInvertibleIdeal
import KltDP.Geometry.SchemeKernelIdealIsoTransport

/-!
# The ideal sheaf of a pulled-back Cartier divisor, and the reduction of the Picard compatibility

For a generic-point-preserving morphism `π : X ⟶ Y` of integral schemes and an effective Cartier
divisor `D` on `Y` with regular equations, the accepted `pullbackDivisor π D hD` has the accepted
ideal-sheaf data `pullbackIdealData π D hD`, generated on every affine open `W ≤ π ⁻¹ᵁ U` inside the
preimage of a regular chart `(U, f, c)` by `π.appLE U W c` (accepted `pullbackIdealData_ideal`).

This module proves that this ideal sheaf is **locally principal with regular generators**
(`pullbackIdealData_locallyPrincipalRegular`; the pulled-back coefficient is a nonzerodivisor because
its germ at the generic point is the unit `pulledEquation` of the function field, accepted
`functionFieldMap_germ_appLE`), so that the accepted theory of
`EffectiveCartierOfInvertibleIdeal` applies to it: the pulled-back divisor **is** the divisor of its
ideal (`pullbackDivisor_eq_cartierDivisorOfIdeal`) and therefore

  `cartierPicardHom X (pullbackDivisor π D hD) = −[I_{π^*D}]`   (`cartierPicardHom_pullbackDivisor`),
  `cartierPicardHom Y E = −[I_E]` for every `E` with regular equations
                                               (`cartierPicardHom_eq_neg_gluedKernelLine`).

Consequently the missing Picard compatibility of the Cartier pullback

  `cartierPicardHom X (pullbackDivisor π D hD) = schemePicardPullbackHom π (cartierPicardHom Y D)`

is **exactly equivalent** to the comparison of ideal modules `π^* I_D ≅ I_{π^*D}`: this is
`cartierPicardHom_pullbackDivisor_eq_picardPullback`, which takes that isomorphism as its only
input and is stated with no other hypothesis.

**Not proved here: the isomorphism `π^* I_D ≅ I_{π^*D}` itself.** For an open immersion it is the
accepted `KltDP.Geometry.OpenImmersionRational.schemePicardPullbackHom_cartierPicardClass`, and for a
morphism which is an isomorphism over an open containing the divisor it is the queued
`SchemeKernelBaseChangeIsoLocus.baseChangeKernelIso`. For a general generic-point-preserving `π` it
has to be glued from affine frames: on an affine `W ≤ π ⁻¹ᵁ V` with `V` an affine open of `Y` on
which `I_D` is generated by a regular `d`, both `W.ι^* π^* I_D` and `W.ι^* I_{π^*D}` are framed by
multiplication by `π.appLE V W d` — the first by the accepted `schemeKernelFrameOnSquare` applied to
the accepted affine trivialization `gluedAffineKernelIso` of `I_D` on `V`, the second by
`gluedAffineKernelIso` of `I_{π^*D}` on `W` (`pullbackIdealData_ideal` supplies its hypothesis) —
so the two frames differ by an isomorphism compatible with the inclusions into the structure sheaf,
and `schemeModuleMonicFactorIsoOnOpenCover` glues them over the affine cover produced here by
`exists_affine_le_preimage`.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Opposite TopologicalSpace

universe u

namespace KltDP.Geometry.CartierDivisorPullbackIdeal

open KltDP.Geometry KltDP.Geometry.SchemeKernelIdealIsoTransport

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable {X Y : Scheme.{u}} [IsIntegral X] [IsIntegral Y] (π : X ⟶ Y)
  [GenericPointPreserving π] (D : CartierDivisor Y) (hD : HasRegularCartierEquations Y D)

/-! ## The affine cover of `X` adapted to the regular charts of `D` -/

include hD in
/-- Every point of `X` has an affine neighbourhood inside the preimage of a regular chart of `D`. -/
theorem exists_affine_le_preimage (x : X) :
    ∃ (c : RegularCartierEquationChart Y D) (W : X.affineOpens),
      x ∈ W.1 ∧ W.1 ≤ π ⁻¹ᵁ c.chart.openSet := by
  obtain ⟨c, hc⟩ := hD (π.base x)
  obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ :=
    (isBasis_affine_open X).exists_subset_of_mem_open
      (show x ∈ π ⁻¹ᵁ c.chart.openSet from hc) (π ⁻¹ᵁ c.chart.openSet).2
  exact ⟨c, ⟨W, hW⟩, hxW, hWle⟩

/-! ## The pulled-back generators are regular -/

/-- The pulled-back coefficient of a regular chart is nonzero on every nonempty affine open of the
preimage: its germ at the generic point is the unit `pulledEquation`. -/
theorem pulledCoefficient_restrict_ne_zero (c : RegularCartierEquationChart Y D)
    (W : X.affineOpens) [Nonempty W.1] (hW : W.1 ≤ π ⁻¹ᵁ c.chart.openSet) :
    π.appLE c.chart.openSet W.1 hW c.coefficient ≠ 0 := by
  haveI : Nonempty c.chart.openSet :=
    ⟨⟨π.base (Classical.arbitrary W.1).1, hW (Classical.arbitrary W.1).2⟩⟩
  intro h
  have hne : X.germToFunctionField W.1 (π.appLE c.chart.openSet W.1 hW c.coefficient) ≠ 0 := by
    rw [← functionFieldMap_germ_appLE π c.chart.openSet W.1 hW c.coefficient, c.germ_eq,
      ← pulledEquation_val π D c]
    exact Units.ne_zero (pulledEquation π D c)
  rw [h, map_zero] at hne
  exact hne rfl

include hD in
/-- **The ideal sheaf of the pulled-back divisor is locally principal with regular generators.** -/
theorem pullbackIdealData_locallyPrincipalRegular :
    IdealLocallyPrincipalRegular (pullbackIdealData π D hD) := by
  intro x
  obtain ⟨c, W, hxW, hWle⟩ := exists_affine_le_preimage π D hD x
  haveI : Nonempty W.1 := ⟨⟨x, hxW⟩⟩
  exact ⟨W, hxW, π.appLE c.chart.openSet W.1 hWle c.coefficient,
    pullbackIdealData_ideal π D hD c W hWle,
    mem_nonZeroDivisors_of_ne_zero (pulledCoefficient_restrict_ne_zero π D c W hWle)⟩

/-! ## The pulled-back divisor is the divisor of its ideal -/

include hD in
/-- **The pullback of `D` is the effective Cartier divisor of its own ideal sheaf.** -/
theorem pullbackDivisor_eq_cartierDivisorOfIdeal :
    pullbackDivisor π D hD =
      cartierDivisorOfIdeal X (pullbackIdealData π D hD)
        (pullbackIdealData_locallyPrincipalRegular π D hD) :=
  eq_cartierDivisorOfIdeal X (pullbackIdealData π D hD)
    (pullbackIdealData_locallyPrincipalRegular π D hD) (pullbackDivisor π D hD)
    (pullbackDivisor_hasRegularEquations π D hD) rfl

include hD in
/-- **The Picard class of the pulled-back divisor is the class of its ideal line.** -/
theorem cartierPicardHom_pullbackDivisor :
    cartierPicardHom X (pullbackDivisor π D hD) =
      -Additive.ofMul (gluedKernelLine (pullbackIdealData π D hD)
        (pullbackIdealData_locallyPrincipalRegular π D hD)).toPic := by
  rw [pullbackDivisor_eq_cartierDivisorOfIdeal π D hD, cartierDivisorOfIdeal_picard]

/-- The Picard class of any effective divisor with regular equations is the class of its ideal
line (ideal-sheaf sign convention). -/
theorem cartierPicardHom_eq_neg_gluedKernelLine (E : CartierDivisor Y)
    (hE : HasRegularCartierEquations Y E) :
    cartierPicardHom Y E =
      -Additive.ofMul (gluedKernelLine (effectiveCartierIdealDataOfRegularEquations Y E hE)
        (effectiveCartierIdealDataOfRegularEquations_regular Y E hE)).toPic := by
  have h := cartierDivisorOfIdeal_picard Y (effectiveCartierIdealDataOfRegularEquations Y E hE)
    (effectiveCartierIdealDataOfRegularEquations_regular Y E hE)
  rwa [← eq_cartierDivisorOfIdeal Y (effectiveCartierIdealDataOfRegularEquations Y E hE)
    (effectiveCartierIdealDataOfRegularEquations_regular Y E hE) E hE rfl] at h

/-! ## The reduction of the Picard compatibility -/

include hD in
/-- **The missing Picard compatibility of the Cartier pullback, reduced to the comparison of ideal
modules**: given an isomorphism `π^* I_D ≅ I_{π^*D}` of ideal modules, the Picard class of the
pulled-back divisor is the Picard pullback of the class of `D`. No other hypothesis is used;
in particular `π` is not assumed flat, open or an isomorphism. -/
theorem cartierPicardHom_pullbackDivisor_eq_picardPullback
    (e : (schemeModulePullback π).obj
        (schemeKernelIdeal (effectiveCartierIdealDataOfRegularEquations Y D hD).gluedTo) ≅
      schemeKernelIdeal (pullbackIdealData π D hD).gluedTo) :
    cartierPicardHom X (pullbackDivisor π D hD) =
      (schemePicardPullbackHom π).toAdditive (cartierPicardHom Y D) := by
  rw [cartierPicardHom_pullbackDivisor π D hD, cartierPicardHom_eq_neg_gluedKernelLine D hD,
    map_neg, toPic_eq_pullback_of_iso π
      (gluedKernelLine (effectiveCartierIdealDataOfRegularEquations Y D hD)
        (effectiveCartierIdealDataOfRegularEquations_regular Y D hD))
      (gluedKernelLine (pullbackIdealData π D hD)
        (pullbackIdealData_locallyPrincipalRegular π D hD)) e.symm]
  rfl

end KltDP.Geometry.CartierDivisorPullbackIdeal
