import KltDP.Geometry.CartierSectionIdeal
import KltDP.Geometry.QuasicoherentIdealSheafData
import KltDP.Compatibility.InvertibleQuasicoherent

/-!
# Scheme ideal data for the original effective Cartier divisor

The independently defined ideal O ∩ O(-D) is the original canonical
section image and is invertible under the stated square-root data.
Its derived quasicoherence supplies scheme ideal data. Every affine
component is the prescribed original ideal; on an original regular
equation chart it is generated by that equation.

This construction does not identify the resulting closed subscheme with
a prescribed reduced union of curves. That geometric comparison and
reducedness remain separate statements.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory MonoidalCategory Opposite

universe u

namespace KltDP.Geometry

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable (X : Scheme.{u}) [IsIntegral X] [X.IsSeparated]

local instance : MonoidalCategory X.Modules := Scheme.Modules.monoidalCategory X

variable (D : CartierDivisor X) (hD : HasRegularCartierEquations X D)
  (L : InvertibleSheaf X) (e : L.obj ⊗ L.obj ≅ cartierDivisorModule X D)

/-- Scheme ideal data constructed from the original prescribed divisor ideal. -/
def effectiveCartierIdealData : X.IdealSheafData := by
  letI := cartierIdealSubmodule_isInvertible X D hD L e
  exact QuasicoherentImageIdeal.ofSubmodule (cartierIdealSubmodule X D)

/-- The affine components are exactly the original O ∩ O(-D) ideals. -/
@[simp]
theorem effectiveCartierIdealData_ideal (U : X.affineOpens) :
    (effectiveCartierIdealData X D hD L e).ideal U = cartierSectionIdeal X D U.1 := by
  letI := cartierIdealSubmodule_isInvertible X D hD L e
  exact QuasicoherentImageIdeal.ofSubmodule_ideal (cartierIdealSubmodule X D) U

/-- On an original affine regular-equation chart, the original coefficient
generates the scheme ideal. -/
theorem effectiveCartierIdealData_ideal_chart (c : RegularCartierEquationChart X D)
    (hc : IsAffineOpen c.chart.openSet) :
    (effectiveCartierIdealData X D hD L e).ideal ⟨c.chart.openSet, hc⟩ =
      Ideal.span ({c.coefficient} : Set Γ(X, c.chart.openSet)) := by
  rw [effectiveCartierIdealData_ideal]
  exact cartierSectionIdeal_eq_span X D c

/-- The same scheme ideal data also retains the actual canonical-section image. -/
theorem effectiveCartierIdealData_ideal_image (U : X.affineOpens) :
    (effectiveCartierIdealData X D hD L e).ideal U =
      sectionImageIdeal X (cartierDivisorModule X D)
        (effectiveCartierSection X D hD) U.1 := by
  rw [effectiveCartierIdealData_ideal]
  exact cartierSectionIdeal_eq_imageIdeal X D hD L e U.1

end KltDP.Geometry
