import KltDP.Geometry.ExceptionalKernelInfiniteOrder
import KltDP.Geometry.ActualContractionMorphismDescent
import KltDP.Geometry.SchemePointBlowupSequenceRestriction
import KltDP.Geometry.PrimeCurveCartierVanishingIdeal

/-!
# The integral Picard splitting of the original contraction

The original contracted prime fills the original center fiber. The actual
isomorphism away from that fiber, together with extension of Cartier classes
across the original smooth target point, gives a retraction of the actual
Picard pullback. Its kernel is generated by the actual exceptional class.
The supplied ordinary minus-one-curve proof makes that generator infinite
order. The inverse splitting retains both the actual pullback and generator.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace

universe u v

namespace KltDP.Geometry

namespace PrimeCurveComplementKernel

/-- The existing kernel splitting has the original generator, with coefficient one. -/
theorem picardEquivProdInt_symm_apply
    {k : Type u} [Field k] [IsAlgClosed k] {S : NormalProjectiveSurface k}
    [∀ s : S.toScheme, UniqueFactorizationMonoid (S.stalk s)]
    {V : S.toScheme.Opens} [Nonempty V.toScheme]
    {H : Type v} [CommGroup H] (E : S.PrimeCurve)
    (hV : ∀ C : S.PrimeCurve, C.genericPoint ∈ V ↔ C ≠ E)
    (hinf : InfiniteOrder (primeCurveClass E))
    (s : H →* S.toScheme.Pic) (ρ : S.toScheme.Pic →* H)
    (hρ : ∀ a, ρ (s a) = a)
    (hker : ρ.ker = (schemePicardPullbackHom V.ι).ker)
    (a : H) (n : ℤ) :
    (picardEquivProdInt E hV hinf s ρ hρ hker).symm (a, Multiplicative.ofAdd n) =
      s a * primeCurveClass E ^ n := rfl

end PrimeCurveComplementKernel

open PrimeCurveComplementKernel NormalProjectiveSurface

/-- A contraction of an actual minus-one curve splits the integral Picard
group. The inverse sends `(a,n)` to the original pullback times `O(E)^n`.
No general point-blowup exceptional-line literal is required. -/
theorem IsContraction.exists_picardDecomposition
    {k : Type u} [Field k] [IsAlgClosed k]
    {S T : NormalProjectiveSurface k} {b : S.toScheme ⟶ T.toScheme}
    {E : S.PrimeCurve} (hb : IsContraction S T b E)
    (hS : ∀ s : S.Point, RegularPoint S.toScheme s)
    (hminus : IsMinusOneCurve hS E) :
    ∃ e : S.toScheme.Pic ≃* T.toScheme.Pic × Multiplicative ℤ,
      ∀ (a : T.toScheme.Pic) (n : ℤ),
        e.symm (a, Multiplicative.ofAdd n) = schemePicardPullbackHom b a *
          cartierPicardClass S.toScheme (S.primeCurveCartier hS E) ^ n := by
  classical
  letI := S.stalks_uniqueFactorizationMonoid_of_regular hS
  letI := T.stalks_uniqueFactorizationMonoid_of_regular hb.regular
  obtain ⟨z, hz, hfiber, hbl⟩ := hb.centerFiber_eq_curve
  let U : T.toScheme.Opens := ⟨({z} : Set T.toScheme)ᶜ, hz.isOpen_compl⟩
  let V : S.toScheme.Opens := b ⁻¹ᵁ U
  have hVeq : V = complementOpen E := by
    apply Opens.ext
    ext x
    change b.base x ∉ ({z} : Set T.toScheme) ↔ x ∉ (E : Set S.toScheme)
    change x ∉ b.base ⁻¹' ({z} : Set T.toScheme) ↔ x ∉ (E : Set S.toScheme)
    rw [hfiber]
  letI : Nonempty V.toScheme := by rw [hVeq]; infer_instance
  letI : IsIso (b ∣_ U) := hbl.toSchemeIsAt.isIso_restrict U (by simp [U])
  let er : T.toScheme.Pic ≃* U.toScheme.Pic :=
    MulEquiv.ofBijective (schemePicardPullbackHom U.ι)
      (CartierExtension.compl_schemePicardPullbackHom_bijective z hz)
  let ep : U.toScheme.Pic ≃* V.toScheme.Pic :=
    PointBlowupPicard.pullbackEquivOfIso (asIso (b ∣_ U))
  let ρ : S.toScheme.Pic →* T.toScheme.Pic :=
    er.symm.toMonoidHom.comp
      (ep.symm.toMonoidHom.comp (schemePicardPullbackHom V.ι))
  have hres (a : T.toScheme.Pic) :
      schemePicardPullbackHom V.ι (schemePicardPullbackHom b a) = ep (er a) := by
    change schemePicardPullbackHom (b ⁻¹ᵁ U).ι
        (schemePicardPullbackHom b a) =
      schemePicardPullbackHom (b ∣_ U) (schemePicardPullbackHom U.ι a)
    rw [← MonoidHom.comp_apply, ← schemePicardPullbackHom_comp,
      ← morphismRestrict_ι, schemePicardPullbackHom_comp, MonoidHom.comp_apply]
  have hρ (a : T.toScheme.Pic) : ρ (schemePicardPullbackHom b a) = a := by
    change er.symm (ep.symm
      (schemePicardPullbackHom V.ι (schemePicardPullbackHom b a))) = a
    rw [hres, ep.symm_apply_apply, er.symm_apply_apply]
  have hker : ρ.ker = (schemePicardPullbackHom V.ι).ker := by
    ext c
    change er.symm (ep.symm (schemePicardPullbackHom V.ι c)) = 1 ↔
      schemePicardPullbackHom V.ι c = 1
    constructor
    · intro hc
      apply ep.symm.injective
      apply er.symm.injective
      simpa only [map_one] using hc
    · intro hc
      rw [hc, map_one, map_one]
  have hV (C : S.PrimeCurve) : C.genericPoint ∈ V ↔ C ≠ E := by
    rw [hVeq]
    exact genericPoint_mem_complementOpen_iff E C
  have hinf : InfiniteOrder (primeCurveClass E) :=
    infiniteOrder_of_intersectionNumber_neg_one E hminus.selfIntersection
  have hclass : primeCurveClass E =
      cartierPicardClass S.toScheme (S.primeCurveCartier hS E) :=
    S.weilClassPicardEquiv_representative (Finsupp.single E 1)
  refine ⟨picardEquivProdInt E hV hinf (schemePicardPullbackHom b) ρ hρ hker, ?_⟩
  intro a n
  rw [picardEquivProdInt_symm_apply, hclass]

namespace IsContraction

variable {k : Type u} [Field k] [IsAlgClosed k]
    {S T : NormalProjectiveSurface k} {b : S.toScheme ⟶ T.toScheme}
    {E : S.PrimeCurve} (hb : IsContraction S T b E)
    (hS : ∀ s : S.Point, RegularPoint S.toScheme s)
    (hminus : IsMinusOneCurve hS E)

/-- The splitting is chosen together with its original pullback and generator formula. -/
def picardDecomposition : S.toScheme.Pic ≃* T.toScheme.Pic × Multiplicative ℤ :=
  (hb.exists_picardDecomposition hS hminus).choose

/-- The exact integral normalization used by intersection-form transport. -/
theorem picardDecomposition_symm_apply (a : T.toScheme.Pic) (n : ℤ) :
    (hb.picardDecomposition hS hminus).symm (a, Multiplicative.ofAdd n) =
      schemePicardPullbackHom b a *
        cartierPicardClass S.toScheme (S.primeCurveCartier hS E) ^ n :=
  (hb.exists_picardDecomposition hS hminus).choose_spec a n

/-- Actual pulled-back classes have zero exceptional coordinate. -/
theorem picardDecomposition_pullback (a : T.toScheme.Pic) :
    hb.picardDecomposition hS hminus (schemePicardPullbackHom b a) = (a, 1) := by
  apply (hb.picardDecomposition hS hminus).symm.injective
  simpa only [MulEquiv.symm_apply_apply, zpow_zero, mul_one] using
    (hb.picardDecomposition_symm_apply hS hminus a 0).symm

/-- The original exceptional divisor has coefficient one, with positive sign. -/
theorem picardDecomposition_exceptional :
    hb.picardDecomposition hS hminus
      (cartierPicardClass S.toScheme (S.primeCurveCartier hS E)) =
        (1, Multiplicative.ofAdd (1 : ℤ)) := by
  apply (hb.picardDecomposition hS hminus).symm.injective
  simpa only [MulEquiv.symm_apply_apply, map_one, zpow_one, one_mul] using
    (hb.picardDecomposition_symm_apply hS hminus 1 1).symm

end IsContraction

end KltDP.Geometry

#print axioms KltDP.Geometry.IsContraction.exists_picardDecomposition
#print axioms KltDP.Geometry.IsContraction.picardDecomposition_symm_apply
