import KltDP.Geometry.NumericalIntersectionPairing
import KltDP.Geometry.DisjointNegativeCurvesRank
import KltDP.Geometry.NefNullCurveNegativeSquare
import Mathlib.Analysis.Convex.Cone.Pointed
import Mathlib.Analysis.Normed.Module.FiniteDimension
import Mathlib.Topology.Algebra.Module.FiniteDimension

/-!
# The real numerical space and the closed cone of curves of a regular surface

For an actual regular projective surface `S` over a field, with `N¹(S)_ℚ = S.NumericalClassGroup`
finite dimensional, we fix the Euclidean model `V S := Fin ρ → ℝ` of `N¹(S)_ℝ` through the
coordinates of `Module.finBasis ℚ N¹(S)_ℚ` (`toReal`). The pairing with a numerical class
`d` extends to the real linear functional `pairReal d`. The cone of curves `NE(S)` is the
`ℝ≥0`-span of the classes of actual prime curves, `NE(S)‾ = closedCurveCone` is its closure in
the Euclidean topology (this is the closed cone `NE(X/Spec k)` of Tanaka, *Minimal model
program for excellent surfaces*, AIF 68 (2018), §2.3, for `X = S`, `S = B = Spec k`, with
`N₁(S)_ℝ` identified with `N¹(S)_ℝ` through the perfect intersection pairing), and
`IsExtremalRay` is the usual notion (Kollár–Mori, Definition 1.16): a ray `R = ℝ≥0·v ⊆ NE‾`
such that `x, y ∈ NE‾` and `x + y ∈ R` force `x, y ∈ R`.

Only definitions and immediate facts live here; the positivity/compactness/extremal-ray
theorems are in `KltDP.Geometry.CurveConeExtremal`.
-/

set_option autoImplicit false

noncomputable section

open AlgebraicGeometry KltDP.Geometry.NormalProjectiveSurface

universe u

namespace KltDP.Geometry.CurveCone

variable {k : Type u} [Field k] [IsAlgClosed k] (S : NormalProjectiveSurface k)

/-- The Euclidean model of `N¹(S)_ℝ`: coordinates with respect to a fixed `ℚ`-basis. -/
abbrev V : Type := Fin (Module.finrank ℚ S.NumericalClassGroup) → ℝ

variable [FiniteDimensional ℚ S.NumericalClassGroup]

/-- The fixed `ℚ`-basis of `N¹(S)_ℚ`. -/
def basis : Basis (Fin (Module.finrank ℚ S.NumericalClassGroup)) ℚ S.NumericalClassGroup :=
  Module.finBasis ℚ S.NumericalClassGroup

/-- The coordinate map `N¹(S)_ℚ → N¹(S)_ℝ` (a `ℚ`-linear map into the real coordinate space). -/
def toReal : S.NumericalClassGroup →ₗ[ℚ] V S where
  toFun v i := ((basis S).repr v i : ℝ)
  map_add' v w := by funext i; simp
  map_smul' c v := by funext i; simp [Rat.smul_def]

theorem toReal_apply (v : S.NumericalClassGroup) (i : Fin (Module.finrank ℚ S.NumericalClassGroup)) :
    toReal S v i = ((basis S).repr v i : ℝ) := rfl

theorem toReal_injective : Function.Injective (toReal S) := by
  intro v w h
  apply (basis S).repr.injective
  ext i
  have := congrFun h i
  simp only [toReal_apply] at this
  exact_mod_cast this

variable (hreg : ∀ x : S.Point, RegularPoint S.toScheme x)

include hreg in
/-- The real extension of the intersection pairing with a fixed numerical class `d`:
`pairReal d (toReal v) = d · v`. -/
def pairReal (d : S.NumericalClassGroup) : V S →ₗ[ℝ] ℝ where
  toFun x := ∑ i, x i * (S.numericalIntersectionBilinForm hreg d ((basis S) i) : ℝ)
  map_add' x y := by simp [add_mul, Finset.sum_add_distrib]
  map_smul' c x := by simp [Finset.mul_sum, mul_assoc]

theorem pairReal_toReal (d v : S.NumericalClassGroup) :
    pairReal S hreg d (toReal S v) = (S.numericalIntersectionBilinForm hreg d v : ℝ) := by
  classical
  simp only [pairReal, LinearMap.coe_mk, AddHom.coe_mk, toReal_apply]
  have hv : v = ∑ i, (basis S).repr v i • (basis S) i := ((basis S).sum_repr v).symm
  conv_rhs => rw [hv]
  rw [map_sum]
  push_cast
  refine Finset.sum_congr rfl fun i _ => ?_
  rw [map_smul, smul_eq_mul]
  push_cast
  ring

include hreg in
/-- The real class of an actual prime curve. -/
def curveClassReal (C : S.PrimeCurve) : V S :=
  toReal S (DisjointNegativeCurvesRank.curveClass S hreg C)

include hreg in
/-- The cone of curves `NE(S)`: the pointed cone (`ℝ≥0`-span) generated by all actual prime
curve classes. -/
def effectiveCone : PointedCone ℝ (V S) :=
  Submodule.span {c : ℝ // 0 ≤ c} (Set.range (curveClassReal S hreg))

include hreg in
/-- The closed cone of curves `NE(S)‾`. -/
def closedCurveCone : Set (V S) := closure (effectiveCone S hreg : Set (V S))

theorem curveClassReal_mem_closedCurveCone (C : S.PrimeCurve) :
    curveClassReal S hreg C ∈ closedCurveCone S hreg :=
  subset_closure (Submodule.subset_span (Set.mem_range_self C))

theorem isClosed_closedCurveCone : IsClosed (closedCurveCone S hreg) := isClosed_closure

/-- The ray `ℝ≥0 · v`. -/
def ray (v : V S) : Set (V S) := {x | ∃ t : ℝ, 0 ≤ t ∧ x = t • v}

/-- `v` spans an extremal ray of the closed cone `K` (Kollár–Mori, Definition 1.16). -/
def IsExtremalRay (K : Set (V S)) (v : V S) : Prop :=
  v ≠ 0 ∧ v ∈ K ∧ ∀ x y : V S, x ∈ K → y ∈ K → x + y ∈ ray S v → x ∈ ray S v ∧ y ∈ ray S v

include hreg in
/-- A numerical class is negative on the ray of `v`. -/
def NegativeOn (d : S.NumericalClassGroup) (v : V S) : Prop := pairReal S hreg d v < 0

end KltDP.Geometry.CurveCone
