import KltDP.Geometry.CartierDivisorOfEquations
import KltDP.Geometry.EffectiveCartierIdeal

/-!
# Effective Cartier divisors from locally principal regular ideal sheaves

On an integral scheme `X`, an ideal sheaf `I` which is locally principal with regular generators
(the accepted `IdealLocallyPrincipalRegular I`, the premise of the accepted invertibility criterion
`gluedKernel_isInvertible`) is the ideal sheaf of an effective Cartier divisor of the project's API:

* `PrincipalRegularChart X I`: a nonempty affine open on which `I` is generated by a regular section;
  its `equation` is the generator's germ, a unit of the function field. Two charts have equal
  equation classes on their intersection (`equation_compat`: on every affine open inside it the two
  generators differ by a unit, and equality of equation classes is local,
  `cartierEquationClassHom_eq_of_locally`).
* `cartierDivisorOfIdeal I hI : CartierDivisor X`, glued from these equations by BRIEF8's
  `cartierDivisorOfEquations`; every chart is a regular equation chart, so it has
  `HasRegularCartierEquations`; its restriction to any nonempty affine open on which `I` is
  principal with a regular generator `d` is the class of `d` (`cartierDivisorOfIdeal_restrict_affine`),
  and it vanishes on affine opens where `I` is the unit ideal.
* Its zero scheme is the glued closed subscheme of `I`: the accepted ideal-sheaf data
  `effectiveCartierIdealDataOfRegularEquations` of the divisor *is* `I`
  (`cartierDivisorOfIdeal_idealData`, by the locality of ideal-sheaf data proved here,
  `IdealSheafData.ext_of_affine_cover`), hence `O(−D) ≅ I` as modules
  (`cartierDivisorOfIdeal_kernelIso`) and `cartierPicardHom D = −[I]` in the ideal-line sign
  convention (`cartierDivisorOfIdeal_picard`).
* Products ↔ sums: the affine-wise product `idealSheafDataMul I J` of two such ideal sheaves is again
  locally principal regular and `D(I·J) = D(I) + D(J)`; `D(⊤) = 0`; `D(Iⁿ) = n • D(I)`.
* Uniqueness: an effective divisor with regular equations whose ideal-sheaf data is `I` equals
  `cartierDivisorOfIdeal I` (`eq_cartierDivisorOfIdeal`), so two effective divisors with regular
  equations and the same ideal-sheaf data are equal (`cartierDivisor_eq_of_idealData`).

Not proved here: the passage from the *abstract* invertibility `IsInvertible (schemeKernelIdeal
I.gluedTo)` back to `IdealLocallyPrincipalRegular I`; the hypothesis used throughout is the concrete
one (regular local generators on an affine cover).
-/

noncomputable section

open AlgebraicGeometry CategoryTheory Opposite TopologicalSpace

universe u

namespace KltDP.Geometry

/-! ## Ideal-sheaf data is determined on an affine cover -/

section Locality

/-- Restricting `f.app U s` to the preimage of a smaller open is `f.app` of the restricted section. -/
theorem Scheme.Hom.app_map_restrict {X Y : Scheme.{u}} (f : X ⟶ Y) {U W : Y.Opens} (h : W ≤ U)
    (s : Γ(Y, U)) :
    X.presheaf.map (homOfLE (show f ⁻¹ᵁ W ≤ f ⁻¹ᵁ U from fun _ hx => h hx)).op (f.app U s) =
      f.app W (Y.presheaf.map (homOfLE h).op s) := by
  have hmor : f.app U ≫
      X.presheaf.map (homOfLE (show f ⁻¹ᵁ W ≤ f ⁻¹ᵁ U from fun _ hx => h hx)).op =
        Y.presheaf.map (homOfLE h).op ≫ f.app W := by
    rw [Scheme.Hom.app_eq_appLE, Scheme.Hom.app_eq_appLE, Scheme.Hom.appLE_map,
      Scheme.Hom.map_appLE]
  exact ConcreteCategory.congr_hom hmor s

variable {X : Scheme.{u}}

/-- Membership in an ideal of ideal-sheaf data is tested on the affine opens of a covering family:
a section of an affine open `U` lies in `I.ideal U` iff its restrictions to the affine opens of `U`
lying in a member of the family lie in the corresponding ideals (sheaf property of the glued closed
subscheme, through the accepted `ker_gluedTo_app`). -/
theorem IdealSheafData.mem_ideal_iff_of_affine_cover (I : X.IdealSheafData) {ι : Type*}
    (V : ι → X.Opens) (hV : ∀ x : X, ∃ i, x ∈ V i) (U : X.affineOpens) (s : Γ(X, U.1)) :
    s ∈ I.ideal U ↔
      ∀ (W : X.affineOpens) (hWU : W.1 ≤ U.1), (∃ i, W.1 ≤ V i) →
        X.presheaf.map (homOfLE hWU).op s ∈ I.ideal W := by
  have key : ∀ (W : X.affineOpens) (t : Γ(X, W.1)), t ∈ I.ideal W ↔ I.gluedTo.app W.1 t = 0 := by
    intro W t
    rw [← I.ker_gluedTo_app W, RingHom.mem_ker]
  rw [key]
  constructor
  · intro h W hWU _
    rw [key, ← Scheme.Hom.app_map_restrict I.gluedTo hWU s, h, map_zero]
  · intro h
    refine I.glueData.glued.sheaf.eq_of_locally_eq'
      (fun W : {W : X.affineOpens // W.1 ≤ U.1 ∧ ∃ i, W.1 ≤ V i} => I.gluedTo ⁻¹ᵁ W.1.1)
      (I.gluedTo ⁻¹ᵁ U.1) (fun W => homOfLE (fun _ hx => W.2.1 hx)) ?_ (I.gluedTo.app U.1 s) 0 ?_
    · intro x hx
      obtain ⟨i, hi⟩ := hV (I.gluedTo.base x)
      obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ := (isBasis_affine_open X).exists_subset_of_mem_open
        (show I.gluedTo.base x ∈ (U.1 ⊓ V i : X.Opens) from ⟨hx, hi⟩) (U.1 ⊓ V i).2
      exact Opens.mem_iSup.mpr
        ⟨⟨⟨W, hW⟩, fun _ hy => (hWle hy).1, i, fun _ hy => (hWle hy).2⟩, hxW⟩
    · intro W
      have hW := (key W.1 _).mp (h W.1 W.2.1 W.2.2)
      change I.glueData.glued.presheaf.map (homOfLE _).op (I.gluedTo.app U.1 s) =
        I.glueData.glued.presheaf.map (homOfLE _).op 0
      rw [map_zero, Scheme.Hom.app_map_restrict I.gluedTo W.2.1 s]
      exact hW

/-- Two ideal-sheaf data agreeing on every affine open contained in a member of a covering family
are equal. -/
theorem IdealSheafData.ext_of_affine_cover (I J : X.IdealSheafData) {ι : Type*} (V : ι → X.Opens)
    (hV : ∀ x : X, ∃ i, x ∈ V i)
    (H : ∀ (i : ι) (W : X.affineOpens), W.1 ≤ V i → I.ideal W = J.ideal W) : I = J := by
  apply Scheme.IdealSheafData.ext
  funext U
  ext s
  rw [IdealSheafData.mem_ideal_iff_of_affine_cover I V hV U s,
    IdealSheafData.mem_ideal_iff_of_affine_cover J V hV U s]
  constructor
  · intro h W hWU hWV
    obtain ⟨i, hi⟩ := hWV
    rw [← H i W hi]
    exact h W hWU ⟨i, hi⟩
  · intro h W hWU hWV
    obtain ⟨i, hi⟩ := hWV
    rw [H i W hi]
    exact h W hWU ⟨i, hi⟩

end Locality

/-! ## Equality of equation classes is local -/

section ClassLocality

variable (X : Scheme.{u}) [IsIntegral X]

/-- Equality of the Cartier classes of two rational equations on `W` can be checked on nonempty
opens covering `W`. -/
theorem cartierEquationClassHom_eq_of_locally (W : X.Opens) [Nonempty W] (f g : X.functionFieldˣ)
    (h : ∀ x ∈ W, ∃ V : X.Opens, x ∈ V ∧ ∃ _ : V ≤ W, ∃ _ : Nonempty V,
      cartierEquationClassHom X V (Additive.ofMul f) =
        cartierEquationClassHom X V (Additive.ofMul g)) :
    cartierEquationClassHom X W (Additive.ofMul f) =
      cartierEquationClassHom X W (Additive.ofMul g) := by
  choose V hxV hVW hne heq using h
  refine (cartierDivisorSheaf X).eq_of_locally_eq' (fun x : W => V x.1 x.2) W
    (fun x => homOfLE (hVW x.1 x.2)) ?_ _ _ ?_
  · intro x hx
    exact Opens.mem_iSup.mpr ⟨⟨x, hx⟩, hxV x hx⟩
  · intro x
    haveI := hne x.1 x.2
    change (cartierDivisorSheaf X).val.map (homOfLE (hVW x.1 x.2)).op
        (cartierEquationClassHom X W (Additive.ofMul f)) =
      (cartierDivisorSheaf X).val.map (homOfLE (hVW x.1 x.2)).op
        (cartierEquationClassHom X W (Additive.ofMul g))
    rw [cartierEquationClassHom_restrict, cartierEquationClassHom_restrict]
    exact heq x.1 x.2

end ClassLocality

/-! ## Principal regular charts of an ideal sheaf -/

variable (X : Scheme.{u}) [IsIntegral X] (I : X.IdealSheafData)

/-- A nonempty affine open on which the ideal sheaf is principal with a regular generator. -/
structure PrincipalRegularChart where
  /-- The affine open. -/
  openSet : X.affineOpens
  /-- It is nonempty. -/
  nonempty : Nonempty openSet.1
  /-- The generator. -/
  generator : Γ(X, openSet.1)
  /-- It generates the ideal. -/
  span_eq : I.ideal openSet = Ideal.span {generator}
  /-- It is a nonzerodivisor. -/
  regular : generator ∈ nonZeroDivisors Γ(X, openSet.1)

namespace PrincipalRegularChart

variable {X I}

instance nonempty_openSet (c : PrincipalRegularChart X I) : Nonempty c.openSet.1 := c.nonempty

omit [IsIntegral X] in
theorem generator_ne_zero (c : PrincipalRegularChart X I) : c.generator ≠ 0 :=
  nonZeroDivisors.ne_zero c.regular

theorem germ_ne_zero (c : PrincipalRegularChart X I) :
    X.germToFunctionField c.openSet.1 c.generator ≠ 0 := by
  intro h
  apply c.generator_ne_zero
  apply X.germToFunctionField_injective c.openSet.1
  rw [h, map_zero]

/-- The local equation of the chart: the generator's germ, as a unit of the function field. -/
def equation (c : PrincipalRegularChart X I) : X.functionFieldˣ :=
  Units.mk0 _ c.germ_ne_zero

@[simp] theorem val_equation (c : PrincipalRegularChart X I) :
    (c.equation : X.functionField) = X.germToFunctionField c.openSet.1 c.generator := rfl

omit [IsIntegral X] in
/-- The restricted generator generates the ideal on a smaller affine open. -/
theorem restrict_span_eq (c : PrincipalRegularChart X I) (W : X.affineOpens)
    (h : W.1 ≤ c.openSet.1) :
    I.ideal W = Ideal.span {X.presheaf.map (homOfLE h).op c.generator} := by
  rw [← I.map_ideal (U := W) (V := c.openSet) h, c.span_eq, Ideal.map_span, Set.image_singleton]
  rfl

/-- The germ of the restricted generator is the germ of the generator. -/
theorem germ_restrict (c : PrincipalRegularChart X I) (W : X.affineOpens) [Nonempty W.1]
    (h : W.1 ≤ c.openSet.1) :
    X.germToFunctionField W.1 (X.presheaf.map (homOfLE h).op c.generator) =
      X.germToFunctionField c.openSet.1 c.generator :=
  X.presheaf.germ_res_apply (homOfLE h) (genericPoint X)
    (genericPoint_mem_nonempty_open X W.1) c.generator

theorem restrict_ne_zero (c : PrincipalRegularChart X I) (W : X.affineOpens) [Nonempty W.1]
    (h : W.1 ≤ c.openSet.1) : X.presheaf.map (homOfLE h).op c.generator ≠ 0 := by
  intro h0
  apply c.germ_ne_zero
  rw [← c.germ_restrict W h, h0, map_zero]

/-- Restricting a chart to a nonempty affine open inside it. -/
def restrict (c : PrincipalRegularChart X I) (W : X.affineOpens) [hW : Nonempty W.1]
    (h : W.1 ≤ c.openSet.1) : PrincipalRegularChart X I where
  openSet := W
  nonempty := hW
  generator := X.presheaf.map (homOfLE h).op c.generator
  span_eq := c.restrict_span_eq W h
  regular := mem_nonZeroDivisors_of_ne_zero (c.restrict_ne_zero W h)

theorem restrict_equation (c : PrincipalRegularChart X I) (W : X.affineOpens) [Nonempty W.1]
    (h : W.1 ≤ c.openSet.1) : (c.restrict W h).equation = c.equation :=
  Units.ext (c.germ_restrict W h)

/-- On a common nonempty affine open the two generators differ by a unit, so the equation classes
agree. -/
theorem equation_compat_affine (c d : PrincipalRegularChart X I) (W : X.affineOpens)
    [Nonempty W.1] (hc : W.1 ≤ c.openSet.1) (hd : W.1 ≤ d.openSet.1) :
    cartierEquationClassHom X W.1 (Additive.ofMul c.equation) =
      cartierEquationClassHom X W.1 (Additive.ofMul d.equation) := by
  rw [cartierEquationClassHom_eq_iff]
  have h1 : X.presheaf.map (homOfLE hc).op c.generator ∈
      Ideal.span {X.presheaf.map (homOfLE hd).op d.generator} := by
    rw [← d.restrict_span_eq W hd, c.restrict_span_eq W hc]
    exact Ideal.subset_span (Set.mem_singleton _)
  have h2 : X.presheaf.map (homOfLE hd).op d.generator ∈
      Ideal.span {X.presheaf.map (homOfLE hc).op c.generator} := by
    rw [← c.restrict_span_eq W hc, d.restrict_span_eq W hd]
    exact Ideal.subset_span (Set.mem_singleton _)
  obtain ⟨a, ha⟩ := Ideal.mem_span_singleton'.mp h1
  obtain ⟨b, hb⟩ := Ideal.mem_span_singleton'.mp h2
  have hab : a * b = 1 := by
    have hmul : (a * b) * X.presheaf.map (homOfLE hc).op c.generator =
        1 * X.presheaf.map (homOfLE hc).op c.generator := by
      rw [one_mul, mul_assoc, hb, ha]
    exact mul_right_cancel₀ (c.restrict_ne_zero W hc) hmul
  refine ⟨Units.mkOfMulEqOne a b hab, ?_⟩
  rw [eq_div_iff_mul_eq']
  apply Units.ext
  change X.germToFunctionField W.1 a * X.germToFunctionField d.openSet.1 d.generator =
    X.germToFunctionField c.openSet.1 c.generator
  rw [← c.germ_restrict W hc, ← d.germ_restrict W hd, ← map_mul, ha]

/-- The equation classes of two charts agree on their intersection. -/
theorem equation_compat (c d : PrincipalRegularChart X I) :
    cartierEquationClassHom X (c.openSet.1 ⊓ d.openSet.1) (Additive.ofMul c.equation) =
      cartierEquationClassHom X (c.openSet.1 ⊓ d.openSet.1) (Additive.ofMul d.equation) := by
  apply cartierEquationClassHom_eq_of_locally
  intro x hx
  obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ := (isBasis_affine_open X).exists_subset_of_mem_open hx
    (c.openSet.1 ⊓ d.openSet.1).2
  haveI : Nonempty W := ⟨⟨x, hxW⟩⟩
  exact ⟨W, hxW, hWle, inferInstance, equation_compat_affine c d ⟨W, hW⟩
    (fun _ hy => (hWle hy).1) (fun _ hy => (hWle hy).2)⟩

omit [IsIntegral X] in
/-- The charts cover `X` when `I` is locally principal with regular generators. -/
theorem cover (hI : IdealLocallyPrincipalRegular I) :
    (⊤ : X.Opens) ≤ ⨆ c : PrincipalRegularChart X I, c.openSet.1 := by
  intro x _
  obtain ⟨U, hx, d, hEq, hreg⟩ := hI x
  exact Opens.mem_iSup.mpr ⟨⟨U, ⟨⟨x, hx⟩⟩, d, hEq, hreg⟩, hx⟩

end PrincipalRegularChart

/-! ## The effective Cartier divisor of a locally principal regular ideal sheaf -/

variable (hI : IdealLocallyPrincipalRegular I)

/-- The effective Cartier divisor of a locally principal regular ideal sheaf, glued from the
generators' germs on the principal regular charts. -/
def cartierDivisorOfIdeal : CartierDivisor X :=
  cartierDivisorOfEquations X (fun c : PrincipalRegularChart X I => c.openSet.1)
    (PrincipalRegularChart.cover hI) (fun c => c.equation)
    (fun c d => PrincipalRegularChart.equation_compat c d)

/-- On every principal regular chart the divisor has the chart's equation. -/
theorem cartierDivisorOfIdeal_restrict (c : PrincipalRegularChart X I) :
    (cartierDivisorSheaf X).val.map (homOfLE (show c.openSet.1 ≤ ⊤ from le_top)).op
        (cartierDivisorOfIdeal X I hI) =
      cartierEquationClassHom X c.openSet.1 (Additive.ofMul c.equation) :=
  cartierDivisorOfEquations_restrict X (fun c : PrincipalRegularChart X I => c.openSet.1)
    (PrincipalRegularChart.cover hI) (fun c => c.equation)
    (fun c d => PrincipalRegularChart.equation_compat c d) c

/-- On any nonempty affine open where `I` is generated by a regular section `d`, the divisor is the
class of the germ of `d`. -/
theorem cartierDivisorOfIdeal_restrict_affine (W : X.affineOpens) [hW : Nonempty W.1]
    (d : Γ(X, W.1)) (hd : I.ideal W = Ideal.span {d}) (hreg : d ∈ nonZeroDivisors Γ(X, W.1)) :
    (cartierDivisorSheaf X).val.map (homOfLE (show W.1 ≤ ⊤ from le_top)).op
        (cartierDivisorOfIdeal X I hI) =
      cartierEquationClassHom X W.1
        (Additive.ofMul (PrincipalRegularChart.equation (X := X) (I := I) ⟨W, hW, d, hd, hreg⟩)) :=
  cartierDivisorOfIdeal_restrict X I hI ⟨W, hW, d, hd, hreg⟩

/-- On a nonempty affine open where `I` is the unit ideal the divisor vanishes. -/
theorem cartierDivisorOfIdeal_restrict_top (W : X.affineOpens) [hW : Nonempty W.1]
    (hWI : I.ideal W = ⊤) :
    (cartierDivisorSheaf X).val.map (homOfLE (show W.1 ≤ ⊤ from le_top)).op
        (cartierDivisorOfIdeal X I hI) = 0 := by
  have hd : I.ideal W = Ideal.span {(1 : Γ(X, W.1))} := by
    rw [hWI, Ideal.span_singleton_one]
  rw [cartierDivisorOfIdeal_restrict_affine X I hI W 1 hd (Submonoid.one_mem _)]
  have h1 : PrincipalRegularChart.equation (I := I) ⟨W, hW, 1, hd, Submonoid.one_mem _⟩ = 1 :=
    Units.ext (map_one (X.germToFunctionField W.1).hom)
  rw [h1, ofMul_one, map_zero]

/-- Every principal regular chart is a regular equation chart of the divisor. -/
def cartierDivisorOfIdeal_regularChart (c : PrincipalRegularChart X I) :
    RegularCartierEquationChart X (cartierDivisorOfIdeal X I hI) :=
  cartierDivisorOfEquations_regularChart X (fun c : PrincipalRegularChart X I => c.openSet.1)
    (PrincipalRegularChart.cover hI) (fun c => c.equation)
    (fun c d => PrincipalRegularChart.equation_compat c d) (fun c => c.generator) (fun _ => rfl) c

@[simp] theorem cartierDivisorOfIdeal_regularChart_openSet (c : PrincipalRegularChart X I) :
    (cartierDivisorOfIdeal_regularChart X I hI c).chart.openSet = c.openSet.1 := rfl

@[simp] theorem cartierDivisorOfIdeal_regularChart_coefficient (c : PrincipalRegularChart X I) :
    (cartierDivisorOfIdeal_regularChart X I hI c).coefficient = c.generator := rfl

/-- The divisor is effective with regular equations. -/
theorem cartierDivisorOfIdeal_hasRegularEquations :
    HasRegularCartierEquations X (cartierDivisorOfIdeal X I hI) :=
  cartierDivisorOfEquations_hasRegularEquations X
    (fun c : PrincipalRegularChart X I => c.openSet.1) (PrincipalRegularChart.cover hI)
    (fun c => c.equation) (fun c d => PrincipalRegularChart.equation_compat c d)
    (fun c => c.generator) (fun _ => rfl)

/-- The ideal-sheaf data of the divisor is `I`: its zero scheme is the glued closed subscheme of `I`. -/
theorem cartierDivisorOfIdeal_idealData :
    effectiveCartierIdealDataOfRegularEquations X (cartierDivisorOfIdeal X I hI)
      (cartierDivisorOfIdeal_hasRegularEquations X I hI) = I := by
  apply IdealSheafData.ext_of_affine_cover _ _ (fun c : PrincipalRegularChart X I => c.openSet.1)
  · intro x
    exact Opens.mem_iSup.mp
      (PrincipalRegularChart.cover hI (show x ∈ (⊤ : X.Opens) from trivial))
  · intro c W hW
    have hchart : (effectiveCartierIdealDataOfRegularEquations X (cartierDivisorOfIdeal X I hI)
        (cartierDivisorOfIdeal_hasRegularEquations X I hI)).ideal c.openSet =
          Ideal.span {c.generator} :=
      effectiveCartierIdealDataOfRegularEquations_ideal_chart X _ _
        (cartierDivisorOfIdeal_regularChart X I hI c) c.openSet.2
    rw [← Scheme.IdealSheafData.map_ideal _ (U := W) (V := c.openSet) hW,
      ← Scheme.IdealSheafData.map_ideal _ (U := W) (V := c.openSet) hW, hchart, c.span_eq]

/-- The zero scheme of the divisor is the glued closed subscheme of `I`, over `X`. -/
theorem cartierDivisorOfIdeal_zeroScheme :
    ∃ f : (effectiveCartierIdealDataOfRegularEquations X (cartierDivisorOfIdeal X I hI)
        (cartierDivisorOfIdeal_hasRegularEquations X I hI)).glueData.glued ≅ I.glueData.glued,
      f.hom ≫ I.gluedTo = (effectiveCartierIdealDataOfRegularEquations X
        (cartierDivisorOfIdeal X I hI) (cartierDivisorOfIdeal_hasRegularEquations X I hI)).gluedTo := by
  have h := cartierDivisorOfIdeal_idealData X I hI
  revert h
  generalize effectiveCartierIdealDataOfRegularEquations X (cartierDivisorOfIdeal X I hI)
    (cartierDivisorOfIdeal_hasRegularEquations X I hI) = J
  rintro rfl
  exact ⟨Iso.refl _, Category.id_comp _⟩

/-- `O(−D) ≅ I`, the kernel module of the glued closed subscheme of `I`. -/
def cartierDivisorOfIdeal_kernelIso :
    cartierDivisorModule X (-cartierDivisorOfIdeal X I hI) ≅ schemeKernelIdeal I.gluedTo :=
  effectiveCartierKernelIso X _ (cartierDivisorOfIdeal_hasRegularEquations X I hI) ≪≫
    eqToIso (congrArg (fun J : X.IdealSheafData => schemeKernelIdeal J.gluedTo)
      (cartierDivisorOfIdeal_idealData X I hI))

/-- The Picard class of the ideal line of `I` is the class of `−D`. -/
theorem gluedKernelLine_toPic :
    (gluedKernelLine I hI).toPic = cartierPicardClass X (-cartierDivisorOfIdeal X I hI) := by
  letI := Scheme.Modules.monoidalCategory X
  apply Units.ext
  rw [InvertibleSheaf.toPic_val, cartierPicardClass_val]
  exact Quotient.sound ⟨(cartierDivisorOfIdeal_kernelIso X I hI).symm⟩

/-- `cartierPicardHom D = −[I]` (ideal-line sign convention). -/
theorem cartierDivisorOfIdeal_picard :
    cartierPicardHom X (cartierDivisorOfIdeal X I hI) =
      -Additive.ofMul (gluedKernelLine I hI).toPic := by
  have hdef : cartierPicardHom X (cartierDivisorOfIdeal X I hI) =
      Additive.ofMul (cartierPicardClass X (cartierDivisorOfIdeal X I hI)) := rfl
  rw [gluedKernelLine_toPic, cartierPicardClass_neg, ofMul_inv, neg_neg, hdef]

/-! ## Uniqueness -/

/-- On a nonempty affine open inside a regular chart `c'` of `E` and inside a principal regular
chart `c` of the ideal-sheaf data `I` of `E`, the equation classes of `c'` and of `c` agree. -/
theorem class_eq_of_idealData (E : CartierDivisor X) (hE : HasRegularCartierEquations X E)
    (hEI : effectiveCartierIdealDataOfRegularEquations X E hE = I) (c : PrincipalRegularChart X I)
    (c' : RegularCartierEquationChart X E) (W : X.affineOpens) [hW : Nonempty W.1]
    (hWc : W.1 ≤ c.openSet.1) (hWc' : W.1 ≤ c'.chart.openSet) :
    cartierEquationClassHom X W.1 (Additive.ofMul c'.chart.equation) =
      cartierEquationClassHom X W.1 (Additive.ofMul c.equation) := by
  have hspan : I.ideal W =
      Ideal.span {(RegularCartierEquationChart.restrict X E c' W.1 hWc').coefficient} := by
    rw [← hEI]
    exact effectiveCartierIdealDataOfRegularEquations_ideal_chart X E hE
      (RegularCartierEquationChart.restrict X E c' W.1 hWc') W.2
  have hreg : (RegularCartierEquationChart.restrict X E c' W.1 hWc').coefficient ∈
      nonZeroDivisors Γ(X, W.1) :=
    mem_nonZeroDivisors_of_ne_zero (RegularCartierEquationChart.coefficient_ne_zero X E _)
  have hd : PrincipalRegularChart.equation (X := X) (I := I) ⟨W, hW, _, hspan, hreg⟩ =
      c'.chart.equation :=
    Units.ext (RegularCartierEquationChart.restrict X E c' W.1 hWc').germ_eq
  rw [← hd]
  exact PrincipalRegularChart.equation_compat_affine ⟨W, hW, _, hspan, hreg⟩ c W le_rfl hWc

/-- An effective divisor with regular equations whose ideal-sheaf data is `I` restricts, on every
principal regular chart of `I`, to the chart's equation. -/
theorem restrict_eq_of_idealData (E : CartierDivisor X) (hE : HasRegularCartierEquations X E)
    (hEI : effectiveCartierIdealDataOfRegularEquations X E hE = I) (c : PrincipalRegularChart X I) :
    (cartierDivisorSheaf X).val.map (homOfLE (show c.openSet.1 ≤ ⊤ from le_top)).op E =
      cartierEquationClassHom X c.openSet.1 (Additive.ofMul c.equation) := by
  have hloc : ∀ x ∈ c.openSet.1, ∃ W : X.affineOpens, x ∈ W.1 ∧ W.1 ≤ c.openSet.1 ∧
      ∃ c' : RegularCartierEquationChart X E, W.1 ≤ c'.chart.openSet := by
    intro x hx
    obtain ⟨c', hxc'⟩ := hE x
    obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ := (isBasis_affine_open X).exists_subset_of_mem_open
      (show x ∈ (c.openSet.1 ⊓ c'.chart.openSet : X.Opens) from ⟨hx, hxc'⟩)
      (c.openSet.1 ⊓ c'.chart.openSet).2
    exact ⟨⟨W, hW⟩, hxW, fun _ hy => (hWle hy).1, c', fun _ hy => (hWle hy).2⟩
  choose W hxW hWc c' hWc' using hloc
  refine (cartierDivisorSheaf X).eq_of_locally_eq' (fun x : c.openSet.1 => (W x.1 x.2).1)
    c.openSet.1 (fun x => homOfLE (hWc x.1 x.2)) ?_ _ _ ?_
  · intro x hx
    exact Opens.mem_iSup.mpr ⟨⟨x, hx⟩, hxW x hx⟩
  · intro x
    haveI : Nonempty (W x.1 x.2).1 := ⟨⟨x.1, hxW x.1 x.2⟩⟩
    have hcomp : (homOfLE (show c.openSet.1 ≤ ⊤ from le_top)).op ≫ (homOfLE (hWc x.1 x.2)).op =
        (homOfLE (show (W x.1 x.2).1 ≤ ⊤ from le_top)).op := Subsingleton.elim _ _
    change (cartierDivisorSheaf X).val.map (homOfLE (hWc x.1 x.2)).op
        ((cartierDivisorSheaf X).val.map (homOfLE (show c.openSet.1 ≤ ⊤ from le_top)).op E) =
      (cartierDivisorSheaf X).val.map (homOfLE (hWc x.1 x.2)).op
        (cartierEquationClassHom X c.openSet.1 (Additive.ofMul c.equation))
    rw [cartierEquationClassHom_restrict, ← class_eq_of_idealData X I E hE hEI c (c' x.1 x.2)
      (W x.1 x.2) (hWc x.1 x.2) (hWc' x.1 x.2),
      cartierGlobalEquation_restrict X E (homOfLE (hWc' x.1 x.2)) (c' x.1 x.2).chart.equation
        (c' x.1 x.2).chart.represents,
      ← ConcreteCategory.comp_apply, ← Functor.map_comp, hcomp]

/-- An effective divisor with regular equations whose ideal-sheaf data is `I` is the divisor of `I`. -/
theorem eq_cartierDivisorOfIdeal (E : CartierDivisor X) (hE : HasRegularCartierEquations X E)
    (hEI : effectiveCartierIdealDataOfRegularEquations X E hE = I) :
    E = cartierDivisorOfIdeal X I hI :=
  cartierDivisor_eq_of_local_equations X (fun c : PrincipalRegularChart X I => c.openSet.1)
    (PrincipalRegularChart.cover hI) (fun c => c.equation)
    (fun c d => PrincipalRegularChart.equation_compat c d) E
    (fun c => restrict_eq_of_idealData X I E hE hEI c)

/-- Two effective divisors with regular equations and the same ideal-sheaf data are equal. -/
theorem cartierDivisor_eq_of_idealData (E E' : CartierDivisor X)
    (hE : HasRegularCartierEquations X E) (hE' : HasRegularCartierEquations X E')
    (h : effectiveCartierIdealDataOfRegularEquations X E hE =
      effectiveCartierIdealDataOfRegularEquations X E' hE') : E = E' := by
  rw [eq_cartierDivisorOfIdeal X _ (effectiveCartierIdealDataOfRegularEquations_regular X E' hE')
    E hE h]
  exact (eq_cartierDivisorOfIdeal X _ (effectiveCartierIdealDataOfRegularEquations_regular X E' hE')
    E' hE' rfl).symm

/-- The divisor depends only on the ideal-sheaf data. -/
theorem cartierDivisorOfIdeal_congr {J : X.IdealSheafData} (h : I = J)
    (hJ : IdealLocallyPrincipalRegular J) :
    cartierDivisorOfIdeal X I hI = cartierDivisorOfIdeal X J hJ := by
  subst h
  rfl

/-! ## Products of ideal sheaves and sums of divisors -/

section Products

variable {X I}

/-- The affine-wise product of two ideal-sheaf data. -/
def idealSheafDataMul (J K : X.IdealSheafData) : X.IdealSheafData where
  ideal U := J.ideal U * K.ideal U
  map_ideal_basicOpen U f := by
    rw [Ideal.map_mul, J.map_ideal_basicOpen U f, K.map_ideal_basicOpen U f]

omit [IsIntegral X] in
@[simp] theorem idealSheafDataMul_ideal (J K : X.IdealSheafData) (U : X.affineOpens) :
    (idealSheafDataMul J K).ideal U = J.ideal U * K.ideal U := rfl

/-- The `n`-th affine-wise power of an ideal-sheaf data (`J⁰ = ⊤`). -/
def idealSheafDataPow (J : X.IdealSheafData) : ℕ → X.IdealSheafData
  | 0 => ⊤
  | n + 1 => idealSheafDataMul (idealSheafDataPow J n) J

omit [IsIntegral X] in
@[simp] theorem idealSheafDataPow_zero (J : X.IdealSheafData) : idealSheafDataPow J 0 = ⊤ := rfl

omit [IsIntegral X] in
@[simp] theorem idealSheafDataPow_succ (J : X.IdealSheafData) (n : ℕ) :
    idealSheafDataPow J (n + 1) = idealSheafDataMul (idealSheafDataPow J n) J := rfl

omit [IsIntegral X] in
theorem idealSheafDataPow_ideal (J : X.IdealSheafData) (n : ℕ) (U : X.affineOpens) :
    (idealSheafDataPow J n).ideal U = J.ideal U ^ n := by
  induction n with
  | zero =>
    change (⊤ : Ideal Γ(X, U.1)) = J.ideal U ^ 0
    rw [pow_zero, Ideal.one_eq_top]
  | succ n ih => rw [idealSheafDataPow_succ, idealSheafDataMul_ideal, ih, pow_succ]

variable (X) in
omit [IsIntegral X] in
/-- The unit ideal sheaf is locally principal regular (generator `1`). -/
theorem top_locallyPrincipalRegular : IdealLocallyPrincipalRegular (⊤ : X.IdealSheafData) := by
  intro x
  obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ := (isBasis_affine_open X).exists_subset_of_mem_open
    (show x ∈ (⊤ : X.Opens) from trivial) (⊤ : X.Opens).2
  refine ⟨⟨U, hU⟩, hxU, 1, ?_, Submonoid.one_mem _⟩
  change (⊤ : Ideal Γ(X, U)) = Ideal.span {1}
  rw [Ideal.span_singleton_one]

/-- Two locally principal regular ideal sheaves have common principal regular affine opens through
every point. -/
theorem exists_common_chart {J : X.IdealSheafData} (hI : IdealLocallyPrincipalRegular I)
    (hJ : IdealLocallyPrincipalRegular J) (x : X) :
    ∃ (W : X.affineOpens) (_ : x ∈ W.1) (d e : Γ(X, W.1)),
      I.ideal W = Ideal.span {d} ∧ d ∈ nonZeroDivisors Γ(X, W.1) ∧
        J.ideal W = Ideal.span {e} ∧ e ∈ nonZeroDivisors Γ(X, W.1) := by
  obtain ⟨U, hxU, d, hd, hdr⟩ := hI x
  obtain ⟨U', hxU', e, he, her⟩ := hJ x
  obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ := (isBasis_affine_open X).exists_subset_of_mem_open
    (show x ∈ (U.1 ⊓ U'.1 : X.Opens) from ⟨hxU, hxU'⟩) (U.1 ⊓ U'.1).2
  haveI : Nonempty W := ⟨⟨x, hxW⟩⟩
  let c : PrincipalRegularChart X I := ⟨U, ⟨⟨x, hxU⟩⟩, d, hd, hdr⟩
  let c' : PrincipalRegularChart X J := ⟨U', ⟨⟨x, hxU'⟩⟩, e, he, her⟩
  have hWU : W ≤ U.1 := fun _ hy => (hWle hy).1
  have hWU' : W ≤ U'.1 := fun _ hy => (hWle hy).2
  exact ⟨⟨W, hW⟩, hxW, (c.restrict ⟨W, hW⟩ hWU).generator, (c'.restrict ⟨W, hW⟩ hWU').generator,
    (c.restrict ⟨W, hW⟩ hWU).span_eq, (c.restrict ⟨W, hW⟩ hWU).regular,
    (c'.restrict ⟨W, hW⟩ hWU').span_eq, (c'.restrict ⟨W, hW⟩ hWU').regular⟩

/-- The product of two locally principal regular ideal sheaves is locally principal regular. -/
theorem idealSheafDataMul_locallyPrincipalRegular {J : X.IdealSheafData}
    (hI : IdealLocallyPrincipalRegular I) (hJ : IdealLocallyPrincipalRegular J) :
    IdealLocallyPrincipalRegular (idealSheafDataMul I J) := by
  intro x
  obtain ⟨W, hxW, d, e, hd, hdr, he, her⟩ := exists_common_chart hI hJ x
  refine ⟨W, hxW, d * e, ?_, Submonoid.mul_mem _ hdr her⟩
  rw [idealSheafDataMul_ideal, hd, he, Ideal.span_singleton_mul_span_singleton]

theorem idealSheafDataPow_locallyPrincipalRegular (hI : IdealLocallyPrincipalRegular I) :
    ∀ n : ℕ, IdealLocallyPrincipalRegular (idealSheafDataPow I n)
  | 0 => top_locallyPrincipalRegular X
  | n + 1 => idealSheafDataMul_locallyPrincipalRegular
      (idealSheafDataPow_locallyPrincipalRegular hI n) hI

variable (X I)

/-- The divisor of the unit ideal sheaf is zero. -/
theorem cartierDivisorOfIdeal_top :
    cartierDivisorOfIdeal X ⊤ (top_locallyPrincipalRegular X) = 0 := by
  apply cartierDivisor_eq_of_restrict_eq X
    (fun W : {W : X.affineOpens // Nonempty W.1} => W.1.1)
  · intro x _
    obtain ⟨_, ⟨U, hU, rfl⟩, hxU, -⟩ := (isBasis_affine_open X).exists_subset_of_mem_open
      (show x ∈ (⊤ : X.Opens) from trivial) (⊤ : X.Opens).2
    exact Opens.mem_iSup.mpr ⟨⟨⟨U, hU⟩, ⟨⟨x, hxU⟩⟩⟩, hxU⟩
  · intro W
    haveI := W.2
    rw [map_zero]
    exact cartierDivisorOfIdeal_restrict_top X ⊤ (top_locallyPrincipalRegular X) W.1 rfl

/-- **Products ↔ sums**: the divisor of a product is the sum of the divisors. -/
theorem cartierDivisorOfIdeal_mul {J : X.IdealSheafData} (hJ : IdealLocallyPrincipalRegular J) :
    cartierDivisorOfIdeal X (idealSheafDataMul I J)
        (idealSheafDataMul_locallyPrincipalRegular hI hJ) =
      cartierDivisorOfIdeal X I hI + cartierDivisorOfIdeal X J hJ := by
  choose W hxW d e hd hdr he her using exists_common_chart hI hJ
  apply cartierDivisor_eq_of_restrict_eq X (fun x : X => (W x).1)
  · intro x _
    exact Opens.mem_iSup.mpr ⟨x, hxW x⟩
  · intro x
    haveI : Nonempty (W x).1 := ⟨⟨x, hxW x⟩⟩
    have hde : (idealSheafDataMul I J).ideal (W x) = Ideal.span {d x * e x} := by
      rw [idealSheafDataMul_ideal, hd x, he x, Ideal.span_singleton_mul_span_singleton]
    rw [map_add, cartierDivisorOfIdeal_restrict_affine X I hI (W x) (d x) (hd x) (hdr x),
      cartierDivisorOfIdeal_restrict_affine X J hJ (W x) (e x) (he x) (her x),
      cartierDivisorOfIdeal_restrict_affine X _ _ (W x) (d x * e x) hde
        (Submonoid.mul_mem _ (hdr x) (her x)),
      ← map_add, ← ofMul_mul]
    congr 1
    apply congrArg Additive.ofMul
    apply Units.ext
    exact map_mul (X.germToFunctionField (W x).1).hom (d x) (e x)

/-- The divisor of a power is the multiple of the divisor. -/
theorem cartierDivisorOfIdeal_pow (n : ℕ) :
    cartierDivisorOfIdeal X (idealSheafDataPow I n)
        (idealSheafDataPow_locallyPrincipalRegular hI n) =
      n • cartierDivisorOfIdeal X I hI := by
  induction n with
  | zero =>
    rw [zero_nsmul, cartierDivisorOfIdeal_congr X (idealSheafDataPow I 0)
      (idealSheafDataPow_locallyPrincipalRegular hI 0) (idealSheafDataPow_zero I)
      (top_locallyPrincipalRegular X)]
    exact cartierDivisorOfIdeal_top X
  | succ n ih =>
    rw [succ_nsmul, ← ih]
    exact cartierDivisorOfIdeal_mul X _ (idealSheafDataPow_locallyPrincipalRegular hI n) hI

end Products

/-! ## Finite products and the tower-shaped relation -/

section Tower

variable {X I}

/-- The product `J 0 ⋯ J (q-1)` of the first `q` members of a sequence of ideal-sheaf data. -/
def idealSheafDataFinProd (J : ℕ → X.IdealSheafData) : ℕ → X.IdealSheafData
  | 0 => ⊤
  | q + 1 => idealSheafDataMul (idealSheafDataFinProd J q) (J q)

theorem idealSheafDataFinProd_locallyPrincipalRegular (J : ℕ → X.IdealSheafData)
    (hJ : ∀ j, IdealLocallyPrincipalRegular (J j)) :
    ∀ q : ℕ, IdealLocallyPrincipalRegular (idealSheafDataFinProd J q)
  | 0 => top_locallyPrincipalRegular X
  | q + 1 => idealSheafDataMul_locallyPrincipalRegular
      (idealSheafDataFinProd_locallyPrincipalRegular J hJ q) (hJ q)

variable (X)

/-- The divisor of a finite product is the sum of the divisors. -/
theorem cartierDivisorOfIdeal_finProd (J : ℕ → X.IdealSheafData)
    (hJ : ∀ j, IdealLocallyPrincipalRegular (J j)) (q : ℕ) :
    cartierDivisorOfIdeal X (idealSheafDataFinProd J q)
        (idealSheafDataFinProd_locallyPrincipalRegular J hJ q) =
      ∑ j : Fin q, cartierDivisorOfIdeal X (J j.val) (hJ j.val) := by
  induction q with
  | zero =>
    rw [Fin.sum_univ_zero, cartierDivisorOfIdeal_congr X (idealSheafDataFinProd J 0)
      (idealSheafDataFinProd_locallyPrincipalRegular J hJ 0) rfl (top_locallyPrincipalRegular X)]
    exact cartierDivisorOfIdeal_top X
  | succ q ih =>
    rw [Fin.sum_univ_castSucc]
    change cartierDivisorOfIdeal X (idealSheafDataMul (idealSheafDataFinProd J q) (J q))
      (idealSheafDataMul_locallyPrincipalRegular
        (idealSheafDataFinProd_locallyPrincipalRegular J hJ q) (hJ q)) = _
    rw [cartierDivisorOfIdeal_mul X _ (idealSheafDataFinProd_locallyPrincipalRegular J hJ q) (hJ q),
      ih]
    rfl

/-- **The tower-shaped relation**: if `I₀ = F · Π_{j<q} C_j^{j+1} · P^p` as ideal sheaves, all
locally principal regular, then `D(I₀) = D(F) + Σ_{j<q} (j+1)•D(C_j) + p•D(P)` as Cartier divisors. -/
theorem cartierDivisorOfIdeal_tower (I₀ F P : X.IdealSheafData) (C : ℕ → X.IdealSheafData)
    (q p : ℕ) (hI₀ : IdealLocallyPrincipalRegular I₀) (hF : IdealLocallyPrincipalRegular F)
    (hP : IdealLocallyPrincipalRegular P) (hC : ∀ j, IdealLocallyPrincipalRegular (C j))
    (h : I₀ = idealSheafDataMul (idealSheafDataMul F
      (idealSheafDataFinProd (fun j => idealSheafDataPow (C j) (j + 1)) q))
      (idealSheafDataPow P p)) :
    cartierDivisorOfIdeal X I₀ hI₀ =
      cartierDivisorOfIdeal X F hF +
        ∑ j : Fin q, (j.val + 1) • cartierDivisorOfIdeal X (C j.val) (hC j.val) +
          p • cartierDivisorOfIdeal X P hP := by
  rw [cartierDivisorOfIdeal_congr X I₀ hI₀ h
    (idealSheafDataMul_locallyPrincipalRegular (idealSheafDataMul_locallyPrincipalRegular hF
      (idealSheafDataFinProd_locallyPrincipalRegular _
        (fun j => idealSheafDataPow_locallyPrincipalRegular (hC j) (j + 1)) q))
      (idealSheafDataPow_locallyPrincipalRegular hP p)),
    cartierDivisorOfIdeal_mul, cartierDivisorOfIdeal_mul, cartierDivisorOfIdeal_pow,
    cartierDivisorOfIdeal_finProd X (fun j => idealSheafDataPow (C j) (j + 1))
      (fun j => idealSheafDataPow_locallyPrincipalRegular (hC j) (j + 1)) q]
  congr 2
  exact Finset.sum_congr rfl
    (fun j _ => cartierDivisorOfIdeal_pow X (C j.val) (hC j.val) (j.val + 1))

/-- The Picard form of the tower-shaped relation, through the accepted `cartierPicardHom`. -/
theorem cartierDivisorOfIdeal_tower_picard (I₀ F P : X.IdealSheafData) (C : ℕ → X.IdealSheafData)
    (q p : ℕ) (hI₀ : IdealLocallyPrincipalRegular I₀) (hF : IdealLocallyPrincipalRegular F)
    (hP : IdealLocallyPrincipalRegular P) (hC : ∀ j, IdealLocallyPrincipalRegular (C j))
    (h : I₀ = idealSheafDataMul (idealSheafDataMul F
      (idealSheafDataFinProd (fun j => idealSheafDataPow (C j) (j + 1)) q))
      (idealSheafDataPow P p)) :
    cartierPicardHom X (cartierDivisorOfIdeal X I₀ hI₀) =
      cartierPicardHom X (cartierDivisorOfIdeal X F hF) +
        ∑ j : Fin q, (j.val + 1) • cartierPicardHom X (cartierDivisorOfIdeal X (C j.val) (hC j.val)) +
          p • cartierPicardHom X (cartierDivisorOfIdeal X P hP) :=
  cartierPicardHom_fiber_relation X _ _ _
    (fun j : Fin q => cartierDivisorOfIdeal X (C j.val) (hC j.val)) p
    (cartierDivisorOfIdeal_tower X I₀ F P C q p hI₀ hF hP hC h)

/-- The tower-shaped relation for the classes of the ideal lines, in the ideal-sheaf sign
convention (`−[I]` is the class of the curve). -/
theorem gluedKernelLine_tower_relation (I₀ F P : X.IdealSheafData) (C : ℕ → X.IdealSheafData)
    (q p : ℕ) (hI₀ : IdealLocallyPrincipalRegular I₀) (hF : IdealLocallyPrincipalRegular F)
    (hP : IdealLocallyPrincipalRegular P) (hC : ∀ j, IdealLocallyPrincipalRegular (C j))
    (h : I₀ = idealSheafDataMul (idealSheafDataMul F
      (idealSheafDataFinProd (fun j => idealSheafDataPow (C j) (j + 1)) q))
      (idealSheafDataPow P p)) :
    -Additive.ofMul (gluedKernelLine I₀ hI₀).toPic =
      -Additive.ofMul (gluedKernelLine F hF).toPic +
        ∑ j : Fin q, (j.val + 1) • (-Additive.ofMul (gluedKernelLine (C j.val) (hC j.val)).toPic) +
          p • (-Additive.ofMul (gluedKernelLine P hP).toPic) := by
  simp only [← cartierDivisorOfIdeal_picard]
  exact cartierDivisorOfIdeal_tower_picard X I₀ F P C q p hI₀ hF hP hC h

end Tower

end KltDP.Geometry
