import KltDP.Geometry.CartierRationalPointRestriction
import KltDP.Geometry.GlobalGenerationShortExact

/-! The original degree-one Cartier point line is globally generated when H1(O)=0.
The two outer terms are generated by the original unit and the original
closed-immersion structural map; no generation or point frame is assumed. -/

noncomputable section

open AlgebraicGeometry CategoryTheory

universe u

namespace KltDP.Geometry.CartierRationalPoint

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable {k : Type u} [Field k] {X : Scheme.{u}} [IsIntegral X]
  (E : CartierDivisor X) (hE : HasRegularCartierEquations X E)
  (i : Spec (CommRingCat.of k) ⟶ X) [hiClosed : IsClosedImmersion i]
  (hker : i.ker = effectiveCartierIdealDataOfRegularEquations X E hE)

include hiClosed hker in
/-- Actual H1 vanishing makes the original positive Cartier point line globally generated. -/
theorem isGloballyGenerated
    (hH1 : Subsingleton (ModuleCohomology.H
      (_root_.SheafOfModules.unit X.ringCatSheaf) 1)) :
    Positivity.IsGloballyGenerated (cartierDivisorModule X E) := by
  let S := EffectiveCartierPositive.sequence X E hE
  let e₁ := EffectiveCartierPositive.firstIsoUnit X E hE
  let e₂ := EffectiveCartierPositive.middleIso X E hE
  let e₃ := quotientIsoPoint E hE i hker
  let u := _root_.SheafOfModules.freeUniqueIsoUnit
    (R := X.ringCatSheaf) PUnit.{u + 1}
  letI := hH1
  letI : Subsingleton (ModuleCohomology.H S.X₁ 1) :=
    ((ModuleCohomology.zariskiFunctor X 1).mapIso e₁).addCommGroupIsoToAddEquiv.toEquiv.subsingleton_congr.mpr
      inferInstance
  letI : Epi (structureToPushforwardUnit i) :=
    structureToPushforwardUnit_epi_of_isClosedImmersion i
  have h₁ : Positivity.IsGloballyGenerated S.X₁ :=
    ⟨PUnit.{u + 1}, u.hom ≫ e₁.inv, inferInstance⟩
  have h₃ : Positivity.IsGloballyGenerated S.X₃ :=
    ⟨PUnit.{u + 1}, u.hom ≫ structureToPushforwardUnit i ≫ e₃.inv, inferInstance⟩
  obtain ⟨I, π, hπ⟩ := GlobalGenerationShortExact.isGloballyGenerated S
    (EffectiveCartierPositive.shortExact X E hE) h₁ h₃ inferInstance
  letI := hπ
  exact ⟨I, π ≫ e₂.hom, inferInstance⟩

#print axioms isGloballyGenerated

end KltDP.Geometry.CartierRationalPoint
