import KltDP.Geometry.PrimeCurveLocalLength
import KltDP.Geometry.GluedIdealSheafKernel

/-!
# Stalks of a glued closed subscheme

For an ideal sheaf `I` on `Y` with glued closed subscheme `ι : Z → Y`, the stalk map
`O_{Y,ι z} → O_{Z,z}` is surjective (closed immersions are preimmersions). Its kernel
consists of the germs of sections lying in `I` on some affine neighbourhood: this uses
the accepted `ker_gluedTo_app` (`ker (ι.app U) = I(U)` on affine `U`), the germ
description of stalks, naturality of `ι.app`, and the fact that opens of `Z` are
preimages of opens of `Y`. When `I` is generated near `ι z` by one section `d`
(compatibly on all smaller affine opens), the kernel is the principal ideal of the germ
of `d`, so `O_{Z,z} ≃+* O_{Y,ι z} ⧸ (germ d)`.

This applies to the closed subscheme of an effective Cartier divisor on a regular
equation chart, and to the intersection subscheme `C ∩ D` of a prime curve with the
restricted equation `d|_C`: `O_{C∩D,z} ≃+* O_{C,y} ⧸ (d|_C)_y`, whose length over
`O_{C,y}` is `localLength C y (germ d|_C)`.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite

universe u

namespace AlgebraicGeometry.Scheme.IdealSheafData

variable {Y : Scheme.{u}} (I : Y.IdealSheafData)

/-- If `I` is generated by `d` on every affine open of `U` containing `ι z`, the kernel of
the stalk map of the glued closed subscheme at `z` is the principal ideal of the germ of
`d`. -/
theorem stalkMap_gluedTo_ker_eq_span {z : I.glueData.glued} (U : Y.affineOpens)
    (hy : I.gluedTo.base z ∈ U.1) (d : Γ(Y, U)) (hdU : d ∈ I.ideal U)
    (hd : ∀ (V : Y.affineOpens) (hVU : V.1 ≤ U.1), I.gluedTo.base z ∈ V.1 →
      I.ideal V = Ideal.span {Y.presheaf.map (homOfLE hVU).op d}) :
    RingHom.ker (I.gluedTo.stalkMap z).hom =
      Ideal.span {Y.presheaf.germ U.1 (I.gluedTo.base z) hy d} := by
  apply le_antisymm
  · intro a ha
    obtain ⟨W, hzW, s, rfl⟩ := Y.presheaf.germ_exist (I.gluedTo.base z) a
    have ha' : I.gluedTo.stalkMap z (Y.presheaf.germ W (I.gluedTo.base z) hzW s) = 0 := ha
    rw [Scheme.stalkMap_germ_apply] at ha'
    have h0 : I.glueData.glued.presheaf.germ (I.gluedTo ⁻¹ᵁ W) z hzW (I.gluedTo.app W s) =
        I.glueData.glued.presheaf.germ ⊤ z trivial 0 := by
      rw [ha', map_zero]
    obtain ⟨W', hzW', iU, iV, hW'⟩ :=
      TopCat.Presheaf.germ_eq (V := ⊤) I.glueData.glued.presheaf z hzW trivial _ _ h0
    obtain ⟨V', hV'open, hV'⟩ :=
      (IsClosedImmersion.base_closed (f := I.gluedTo)).toIsEmbedding.toIsInducing.isOpen_iff.mp W'.isOpen
    let V'op : Y.Opens := ⟨V', hV'open⟩
    have hyV' : I.gluedTo.base z ∈ V'op := by
      have : z ∈ I.gluedTo.base ⁻¹' V' := by rw [hV']; exact hzW'
      exact this
    have hyU' : I.gluedTo.base z ∈ ((U.1 ⊓ W ⊓ V'op : Y.Opens) : Set Y) := ⟨⟨hy, hzW⟩, hyV'⟩
    obtain ⟨_, ⟨V, hVaff, rfl⟩, hyV, hVle⟩ :=
      (isBasis_affine_open Y).exists_subset_of_mem_open hyU' (U.1 ⊓ W ⊓ V'op).2
    have hVU : V ≤ U.1 := fun x hx => (hVle hx).1.1
    have hVW : V ≤ W := fun x hx => (hVle hx).1.2
    have hVV' : V ≤ V'op := fun x hx => (hVle hx).2
    have hj₁ : I.gluedTo ⁻¹ᵁ V ≤ W' := by
      intro w hw
      have : w ∈ I.gluedTo.base ⁻¹' V' := hVV' hw
      show w ∈ (W' : Set I.glueData.glued)
      rw [← hV']
      exact this
    have hmem : Y.presheaf.map (homOfLE hVW).op s ∈ RingHom.ker (I.gluedTo.app V).hom := by
      rw [RingHom.mem_ker]
      have hnat : I.gluedTo.app V (Y.presheaf.map (homOfLE hVW).op s) =
          I.glueData.glued.presheaf.map ((Opens.map I.gluedTo.base).map (homOfLE hVW)).op
            (I.gluedTo.app W s) :=
        ConcreteCategory.congr_hom (I.gluedTo.naturality ((homOfLE hVW).op : op W ⟶ op V)) s
      have hfac : (Opens.map I.gluedTo.base).map (homOfLE hVW) =
          (homOfLE hj₁ : I.gluedTo ⁻¹ᵁ V ⟶ W') ≫ iU := Subsingleton.elim _ _
      change I.gluedTo.app V (Y.presheaf.map (homOfLE hVW).op s) = 0
      rw [hnat, hfac, op_comp, Functor.map_comp]
      erw [CommRingCat.comp_apply]
      rw [hW', map_zero, map_zero]
    have hker := I.ker_gluedTo_app ⟨V, hVaff⟩
    change RingHom.ker (I.gluedTo.app V).hom = I.ideal ⟨V, hVaff⟩ at hker
    rw [hker, hd ⟨V, hVaff⟩ hVU hyV, Ideal.mem_span_singleton] at hmem
    obtain ⟨c, hc⟩ := hmem
    rw [Ideal.mem_span_singleton]
    refine ⟨Y.presheaf.germ V (I.gluedTo.base z) hyV c, ?_⟩
    rw [← Y.presheaf.germ_res_apply (homOfLE hVW) (I.gluedTo.base z) hyV s, hc, map_mul,
      Y.presheaf.germ_res_apply]
  · refine Ideal.span_le.mpr (Set.singleton_subset_iff.mpr ?_)
    have happ : I.gluedTo.app U.1 d = 0 := by
      have h := I.ker_gluedTo_app U
      have : d ∈ RingHom.ker (I.gluedTo.app U.1).hom := by rw [h]; exact hdU
      exact this
    show I.gluedTo.stalkMap z (Y.presheaf.germ U.1 (I.gluedTo.base z) hy d) = 0
    rw [Scheme.stalkMap_germ_apply, happ, map_zero]

/-- The stalk of the glued closed subscheme is the quotient of the ambient stalk by the germ
of a local generator of `I`. -/
def stalkQuotientEquiv {z : I.glueData.glued} (U : Y.affineOpens)
    (hy : I.gluedTo.base z ∈ U.1) (d : Γ(Y, U)) (hdU : d ∈ I.ideal U)
    (hd : ∀ (V : Y.affineOpens) (hVU : V.1 ≤ U.1), I.gluedTo.base z ∈ V.1 →
      I.ideal V = Ideal.span {Y.presheaf.map (homOfLE hVU).op d}) :
    (Y.presheaf.stalk (I.gluedTo.base z) ⧸
        Ideal.span {Y.presheaf.germ U.1 (I.gluedTo.base z) hy d}) ≃+*
      I.glueData.glued.presheaf.stalk z :=
  (Ideal.quotEquivOfEq (I.stalkMap_gluedTo_ker_eq_span U hy d hdU hd).symm).trans
    (RingHom.quotientKerEquivOfSurjective (I.gluedTo.stalkMap_surjective z))

end AlgebraicGeometry.Scheme.IdealSheafData

namespace KltDP.Geometry

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable (X : Scheme.{u}) [IsIntegral X] (E : CartierDivisor X)
  (hE : HasRegularCartierEquations X E)

/-- On an affine regular equation chart, the kernel of the stalk map of the closed subscheme
of an effective Cartier divisor is generated by the germ of the local equation. -/
theorem effectiveCartierInclusion_stalkMap_ker (c : RegularCartierEquationChart X E)
    (hU : IsAffineOpen c.chart.openSet) (z : effectiveCartierScheme X E hE)
    (hz : (effectiveCartierInclusion X E hE).base z ∈ c.chart.openSet) :
    RingHom.ker ((effectiveCartierInclusion X E hE).stalkMap z).hom =
      Ideal.span {X.presheaf.germ c.chart.openSet _ hz c.coefficient} := by
  refine (effectiveCartierIdealDataOfRegularEquations X E hE).stalkMap_gluedTo_ker_eq_span
    ⟨c.chart.openSet, hU⟩ hz c.coefficient ?_ ?_
  · rw [effectiveCartierIdealDataOfRegularEquations_ideal_chart X E hE c hU]
    exact Ideal.mem_span_singleton_self _
  · intro V hVU hyV
    haveI : Nonempty V.1 := ⟨⟨_, hyV⟩⟩
    rw [effectiveCartierIdealDataOfRegularEquations_ideal X E hE V]
    exact cartierSectionIdeal_eq_span X E (RegularCartierEquationChart.restrict X E c V.1 hVU)

/-- `O_{D,z} ≃+* O_{X,z} ⧸ (d)` for the closed subscheme of an effective Cartier divisor with
affine local equation chart `(U, d)`. -/
def effectiveCartierStalkQuotientEquiv (c : RegularCartierEquationChart X E)
    (hU : IsAffineOpen c.chart.openSet) (z : effectiveCartierScheme X E hE)
    (hz : (effectiveCartierInclusion X E hE).base z ∈ c.chart.openSet) :
    (X.presheaf.stalk ((effectiveCartierInclusion X E hE).base z) ⧸
        Ideal.span {X.presheaf.germ c.chart.openSet _ hz c.coefficient}) ≃+*
      (effectiveCartierScheme X E hE).presheaf.stalk z :=
  (Ideal.quotEquivOfEq (effectiveCartierInclusion_stalkMap_ker X E hE c hU z hz).symm).trans
    (RingHom.quotientKerEquivOfSurjective
      ((effectiveCartierInclusion X E hE).stalkMap_surjective z))

end KltDP.Geometry

namespace KltDP.Geometry.NormalProjectiveSurface.PrimeCurve

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable {k : Type u} [Field k] {X : NormalProjectiveSurface k} (C : X.PrimeCurve)
  (D : CartierDivisor X.toScheme) (hD : HasRegularCartierEquations X.toScheme D)
  (hC : C.NotInSupport D hD)

/-- Stalks of the integral curve scheme are domains. -/
local instance gluedSubschemeStalk_stalkIsDomain (y : C.toScheme) :
    IsDomain (C.toScheme.presheaf.stalk y) :=
  integralSchemeStalk_isDomain C.toScheme y

/-- `O_{C∩D,z} ≃+* O_{C,y} ⧸ (d|_C)_y` on an affine restricted chart containing `y = i z`. -/
def intersectionStalkQuotientEquiv (c : C.GenericChart D)
    (hU : IsAffineOpen (C.chartPreimage D c.1)) (z : C.intersectionScheme D hD hC)
    (hz : (C.intersectionInclusion D hD hC).base z ∈ C.chartPreimage D c.1) :
    (C.toScheme.presheaf.stalk ((C.intersectionInclusion D hD hC).base z) ⧸
        Ideal.span {C.toScheme.presheaf.germ (C.chartPreimage D c.1) _ hz
          (C.restrictedCoefficient D c.1)}) ≃+*
      (C.intersectionScheme D hD hC).presheaf.stalk z :=
  effectiveCartierStalkQuotientEquiv C.toScheme (C.restrictCartier D hD hC)
    (C.restrictCartier_hasRegularEquations D hD hC) (C.restrictedChart D hD hC c) hU z hz

/-- The length of the local ring of `C ∩ D` at `z` over `O_{C,y}` is the local length of the
restricted equation. -/
theorem length_intersectionStalk (c : C.GenericChart D) (z : C.intersectionScheme D hD hC)
    (hz : (C.intersectionInclusion D hD hC).base z ∈ C.chartPreimage D c.1)
    [IsDiscreteValuationRing
      (C.toScheme.presheaf.stalk ((C.intersectionInclusion D hD hC).base z))] :
    Module.length (C.toScheme.presheaf.stalk ((C.intersectionInclusion D hD hC).base z))
        (C.toScheme.presheaf.stalk ((C.intersectionInclusion D hD hC).base z) ⧸
          Ideal.span {C.toScheme.presheaf.germ (C.chartPreimage D c.1) _ hz
            (C.restrictedCoefficient D c.1)}) =
      C.localLength ((C.intersectionInclusion D hD hC).base z)
        (C.toScheme.presheaf.germ (C.chartPreimage D c.1) _ hz (C.restrictedCoefficient D c.1)) := by
  unfold localLength
  rw [ENat.coe_toNat]
  exact C.localLength_length_ne_top _ _ (C.germ_restrictedCoefficient_ne_zero _ D hD hC c hz)

end KltDP.Geometry.NormalProjectiveSurface.PrimeCurve
