import KltDP.Geometry.PointBlowupExceptionalIdeal
import KltDP.Geometry.PointBlowupIntegral
import KltDP.Geometry.EffectiveCartierOfInvertibleIdeal
import KltDP.Geometry.GluedSubschemeStalkKernel
import KltDP.Geometry.AffineBlowupExceptional

/-!
# The exceptional divisor of a point blowup, in Cartier form

BRIEF50 task 1. `docs/GAPS.md` records that there is no general exceptional Cartier divisor; only
Frobenius-family-specific ones exist. This module supplies it for the accepted glued point blowup
`KltDP.Geometry.PointBlowupGluing.scheme`.

## The gap that had to be closed, and why it was real

The accepted `globalCenterFiberIdeal_isInvertible` proves the exceptional kernel sheaf is invertible
**abstractly** (`KltDP.SheafOfModules.IsInvertible`), while the accepted
`cartierDivisorOfIdeal` consumes the **concrete** hypothesis `IdealLocallyPrincipalRegular` — a
regular generator on an *affine* open around every point. `EffectiveCartierOfInvertibleIdeal`'s own
docstring names precisely this as unproved:

> "Not proved here: the passage from the *abstract* invertibility `IsInvertible (schemeKernelIdeal
> I.gluedTo)` back to `IdealLocallyPrincipalRegular I`."

So the missing link was `exceptionalKer_locallyPrincipalRegular` below, and it is genuinely missing
rather than hidden under another name: no lane and no accepted module proves
`IdealLocallyPrincipalRegular` for this ideal.

## The two pieces

`pieces_cover` splits every point of the glued blowup.

* **On the affine blowup piece** the accepted `AffineBlowup.exceptionalIdeal_locallyPrincipalRegular`
  supplies a regular generator `d` on an affine `U`, and `globalCenterFiber_ideal_affine` transports
  its ideal across `(affineBlowupι).appIso U`; the generator becomes `e d` on the image open, still
  regular because `e` is a ring equivalence. This is the derivation already performed inside the
  accepted invertibility proof, here exposed as the data the Cartier API needs.
* **On the unchanged complement** the centre fibre does not meet the open at all, so the ideal is the
  unit ideal. The abstract proof could use an arbitrary open here; the concrete predicate demands an
  **affine** one, which is the whole of the extra work: shrink with
  `isBasis_affine_open …exists_subset_of_mem_open`, then apply the accepted generic
  `ker_ideal_eq_top_of_disjoint`, whose hypothesis is the *pointwise* `∀ z, f.base z ∉ W` and follows
  from `range_globalCenterFiberι` — the range of the centre fibre is `σ⁻¹{j.base q}`, which the
  complement misses by definition.

## Hypotheses, and what is deliberately absent from them

`exceptionalKer_locallyPrincipalRegular` carries **no** literal, **no** regularity of the base, and
**no** integrality: it holds for the blowup of any scheme at any closed point of an affine chart with
maximal centre. Only the passage to `CartierDivisor` needs `[IsIntegral (scheme j q hclosed)]`, since
that instance appears in the *type*; it is taken as an instance-implicit section variable and is
discharged by the accepted `PointBlowupGluing.scheme_isIntegral j q hclosed hq` under
`hq : q.asIdeal ≠ ⊥`. It is not a `local instance` here because an instance carrying an explicit
non-instance hypothesis such as `hq` can never be found by synthesis.

## What this does not claim

Nothing about multiplicity, and nothing of the form `σ^*C = C̃ + m·E`. The exceptional curve as a
*prime curve* already exists (lane A1's queued `PointBlowupPicardSplitting.exceptionalCurve`, from
Stacks 0AGQ); what was missing, and is supplied here, is its **Cartier** form, which needs no literal
at all.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace

universe u

namespace KltDP.Geometry.PointBlowupExceptionalCartier

open KltDP.Geometry.PointBlowupGluing

variable {R : Type u} [CommRing R] {X : Scheme.{u}}
    (j : Spec (CommRingCat.of R) ⟶ X) [IsOpenImmersion j]
    (q : PrimeSpectrum R) [q.asIdeal.IsMaximal]
    (hclosed : IsClosed ({j.base q} : Set X))

/-! ## The exceptional ideal is locally principal with regular generators -/

/-- **The concrete local form of the exceptional ideal of a point blowup.** Every point has an affine
neighbourhood on which the centre-fibre kernel is generated by a single regular section. This is the
`abstract → concrete` step that `EffectiveCartierOfInvertibleIdeal` records as unproved, here proved
for this ideal; it needs no integrality, no regularity and no literal. -/
theorem exceptionalKer_locallyPrincipalRegular :
    IdealLocallyPrincipalRegular ((globalCenterFiberι j q hclosed).ker) := by
  intro x
  rcases pieces_cover j q hclosed x with ⟨a, rfl⟩ | ⟨b, rfl⟩
  · obtain ⟨U, ha, d, hd, hr⟩ :=
      AffineBlowup.exceptionalIdeal_locallyPrincipalRegular q.asIdeal a
    let V : (scheme j q hclosed).affineOpens :=
      ⟨affineBlowupι j q hclosed ''ᵁ U, U.2.image_of_isOpenImmersion _⟩
    let e := ((affineBlowupι j q hclosed).appIso U).symm.commRingCatIsoToRingEquiv
    have he : (globalCenterFiberι j q hclosed).ker.ideal V = Ideal.span {e d} := by
      have h := globalCenterFiber_ideal_affine j q hclosed U
      change (AffineBlowup.exceptionalIdeal q.asIdeal).ideal U = Ideal.span {d} at hd
      rw [hd] at h
      change Ideal.span {d} =
        ((globalCenterFiberι j q hclosed).ker.ideal V).comap e.toRingHom at h
      calc
        _ = (((globalCenterFiberι j q hclosed).ker.ideal V).comap e.toRingHom).map
            e.toRingHom := (Ideal.map_comap_of_surjective e.toRingHom e.surjective _).symm
        _ = (Ideal.span {d}).map e.toRingHom := by rw [← h]
        _ = _ := by
          rw [Ideal.map_span, Set.image_singleton]
          rfl
    have hreg : e d ∈ nonZeroDivisors Γ(scheme j q hclosed, V.1) := by
      apply mem_nonZeroDivisors_of_injective (f := e.symm) e.symm.injective
      simpa only [e.symm_apply_apply] using hr
    exact ⟨V, ⟨a, ha, rfl⟩, e d, he, hreg⟩
  · have hx : (complementι j q hclosed).base b ∈ exceptionalComplementOpen j q hclosed := by
      change (complementι j q hclosed ≫ projection j q hclosed).base b ∈ puncture j q hclosed
      rw [complementι_projection]
      exact b.property
    obtain ⟨_, ⟨W, hW, rfl⟩, hxW, hWle⟩ :=
      (isBasis_affine_open (scheme j q hclosed)).exists_subset_of_mem_open hx
        (exceptionalComplementOpen j q hclosed).2
    have hdisj : ∀ z, (globalCenterFiberι j q hclosed).base z ∉ W := by
      intro z hz
      have hmem : (globalCenterFiberι j q hclosed).base z ∈
          exceptionalComplementOpen j q hclosed := hWle hz
      have hne : (projection j q hclosed).base
          ((globalCenterFiberι j q hclosed).base z) ≠ j.base q := hmem
      apply hne
      have hr : (globalCenterFiberι j q hclosed).base z ∈
          Set.range (globalCenterFiberι j q hclosed).base := ⟨z, rfl⟩
      rw [range_globalCenterFiberι] at hr
      exact hr
    exact ⟨⟨W, hW⟩, hxW, 1,
      (ker_ideal_eq_top_of_disjoint _ ⟨W, hW⟩ hdisj).trans Ideal.span_singleton_one.symm,
      Submonoid.one_mem _⟩

/-! ## The exceptional Cartier divisor

`CartierDivisor` carries `[IsIntegral]` in its *type*, so the instance is a section variable here
rather than a `letI`; discharge it with `PointBlowupGluing.scheme_isIntegral j q hclosed hq`. -/

section Divisor

variable [IsIntegral (scheme j q hclosed)]

/-- **The exceptional divisor of a point blowup, in Cartier form.** -/
def exceptionalCartierDivisor : CartierDivisor (scheme j q hclosed) :=
  cartierDivisorOfIdeal (scheme j q hclosed) ((globalCenterFiberι j q hclosed).ker)
    (exceptionalKer_locallyPrincipalRegular j q hclosed)

/-- It has regular local equations, so the whole effective-divisor API applies to it. -/
theorem exceptionalCartierDivisor_hasRegularEquations :
    HasRegularCartierEquations (scheme j q hclosed)
      (exceptionalCartierDivisor j q hclosed) :=
  cartierDivisorOfIdeal_hasRegularEquations _ _ _

/-- **Its zero scheme is exactly the centre fibre**: the divisor's ideal-sheaf data is the kernel of
the centre-fibre inclusion. This is what makes it *the* exceptional divisor rather than some divisor
supported there. -/
theorem exceptionalCartierDivisor_idealData :
    effectiveCartierIdealDataOfRegularEquations (scheme j q hclosed)
        (exceptionalCartierDivisor j q hclosed)
        (exceptionalCartierDivisor_hasRegularEquations j q hclosed) =
      (globalCenterFiberι j q hclosed).ker :=
  cartierDivisorOfIdeal_idealData _ _ _

end Divisor

end KltDP.Geometry.PointBlowupExceptionalCartier
