import KltDP.Geometry.QuotientChartKernelIdeal
import KltDP.Geometry.PointBlowupExceptionalCartier
import KltDP.Geometry.PointBlowupChartStalkAtCenter

/-!
# The original exceptional equation on an original point-blowup chart

The quotient chart of the original Rees construction is cartesian over
the original whole centre fibre. Its literal denominator therefore
generates the actual exceptional Cartier ideal in the original chart
coordinates. The regular equation below is a chart of that same divisor.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits TopologicalSpace

universe u

namespace KltDP.Geometry.PointBlowupExceptionalCartier

open PointBlowupGluing PointBlowupChartStalk AffineBlowup

variable {R : Type u} [CommRing R] {X : Scheme.{u}}
    (j : Spec (CommRingCat.of R) ⟶ X) [IsOpenImmersion j]
    (q : PrimeSpectrum R) [q.asIdeal.IsMaximal]
    (hclosed : IsClosed ({j.base q} : Set X))

/-- The original affine centre fibre is cartesian over the whole fibre. -/
theorem affineCenterFiber_overBlowup_isPullback :
    IsPullback (centerFiberι q.asIdeal) (affineCenterFiberIso j q hclosed).hom
      (affineBlowupι j q hclosed) (globalCenterFiberι j q hclosed) := by
  refine IsPullback.of_isLimit (PullbackCone.IsLimit.mk
    (affineCenterFiberIso_hom_ι j q hclosed).symm
    (fun s => s.snd ≫ (affineCenterFiberIso j q hclosed).inv)
    (fun s => ?_) (fun s => ?_) (fun s m _ hm => ?_))
  · apply (cancel_mono (affineBlowupι j q hclosed)).mp
    simp only [Category.assoc]
    rw [← affineCenterFiberIso_hom_ι, Iso.inv_hom_id_assoc]
    exact s.condition.symm
  · simp only [Category.assoc, Iso.inv_hom_id, Category.comp_id]
  · apply (cancel_mono (affineCenterFiberIso j q hclosed).hom).mp
    rw [hm, Category.assoc, Iso.inv_hom_id, Category.comp_id]

/-- The literal quotient chart is the restriction of the original whole fibre. -/
theorem exceptionalChart_overGlobalFiber_isPullback (a : q.asIdeal) :
    IsPullback (exceptionalChartInclusion q.asIdeal a)
      (exceptionalChartToFiber q.asIdeal a ≫ (affineCenterFiberIso j q hclosed).hom)
      (chartInclusion j q hclosed a) (globalCenterFiberι j q hclosed) :=
  (exceptionalChartToFiber_isPullback q.asIdeal a).paste_vert
    (affineCenterFiber_overBlowup_isPullback j q hclosed)

/-- The original chart coordinates identify the actual fibre ideal with
the ideal generated by the original denominator. -/
theorem exceptionalKer_chartSectionsEquiv (a : q.asIdeal) :
    ((globalCenterFiberι j q hclosed).ker.ideal
      ⟨chartInclusion j q hclosed a ''ᵁ ⊤,
        chart_image_top_isAffineOpen (chartInclusion j q hclosed a)⟩).map
      (KltDP.Geometry.chartSectionsEquiv (chartInclusion j q hclosed a)) =
        chartCenterIdeal q.asIdeal a :=
  ker_ideal_chartSectionsEquiv_of_quotient_pullback _ _ _ _
    (exceptionalChart_overGlobalFiber_isPullback j q hclosed a)

variable [IsIntegral (PointBlowupGluing.scheme j q hclosed)]

/-- A concrete regular chart of the actual exceptional ideal. -/
def exceptionalPrincipalChart (a : q.asIdeal) (P : PrimeSpectrum (chartRing q.asIdeal a)) :
    PrincipalRegularChart (PointBlowupGluing.scheme j q hclosed)
      (globalCenterFiberι j q hclosed).ker where
  openSet := ⟨chartInclusion j q hclosed a ''ᵁ ⊤,
    chart_image_top_isAffineOpen (chartInclusion j q hclosed a)⟩
  nonempty := ⟨⟨(chartInclusion j q hclosed a).base P,
    mem_chart_image_top (chartInclusion j q hclosed a) P⟩⟩
  generator := (KltDP.Geometry.chartSectionsEquiv
    (chartInclusion j q hclosed a)).symm (chartCenterEquation q.asIdeal a)
  span_eq := eq_span_symm_of_map_eq _
    ((exceptionalKer_chartSectionsEquiv j q hclosed a).trans
      (span_chartCenterEquation q.asIdeal a).symm)
  regular := by
    apply mem_nonZeroDivisors_of_injective
      (f := KltDP.Geometry.chartSectionsEquiv (chartInclusion j q hclosed a))
      (KltDP.Geometry.chartSectionsEquiv (chartInclusion j q hclosed a)).injective
    simpa only [RingEquiv.apply_symm_apply] using chartCenterEquation_regular q.asIdeal a

/-- The same principal chart is a regular equation chart of the original
exceptional Cartier divisor, rather than a newly chosen divisor. -/
def exceptionalEquationChart (a : q.asIdeal) (P : PrimeSpectrum (chartRing q.asIdeal a)) :
    RegularCartierEquationChart (PointBlowupGluing.scheme j q hclosed)
      (exceptionalCartierDivisor j q hclosed) :=
  cartierDivisorOfIdeal_regularChart _ _ _ (exceptionalPrincipalChart j q hclosed a P)

end KltDP.Geometry.PointBlowupExceptionalCartier

#check @KltDP.Geometry.PointBlowupExceptionalCartier.exceptionalEquationChart
#print axioms KltDP.Geometry.PointBlowupExceptionalCartier.exceptionalEquationChart
