import KltDP.Geometry.PrimeCurveOfClosedImmersion
import KltDP.Geometry.PrimeCurveCartierRestriction
import KltDP.Geometry.NormalStalkDVR
import Mathlib.RingTheory.DiscreteValuationRing.Basic

/-!
# The original prime-curve kernel at its generic point

The curve's generic stalk is its actual function field. Its original
surjective inclusion-stalk map therefore has the ambient maximal ideal
as kernel. The proved dimension-one normal surface stalk is a DVR, so
that same kernel is generated by an actual regular parameter.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing

universe u

namespace KltDP.Geometry.NormalProjectiveSurface.PrimeCurve

open KltDP.Geometry

variable {k : Type u} [Field k] {X : NormalProjectiveSurface k} (C : X.PrimeCurve)

/-- The actual generic point of the prime-curve scheme maps to the
original generic point of its support. -/
theorem inclusion_genericPoint_eq :
    C.inclusion.base (_root_.genericPoint C.toScheme) = C.genericPoint := by
  have h : IsGenericPoint (C.inclusion.base (_root_.genericPoint C.toScheme))
      (C : Set X.toScheme) :=
    (PrimeCurveOfClosedImmersion.range_eq_closure_genericPoint X C.inclusion).symm.trans
      C.range_inclusion
  exact h.eq (C.isIrreducible.isGenericPoint_genericPoint C.isClosed)

/-- The generic-point clause for the original curve equation. Smoothness
of the curve and algebraic closedness are unnecessary for this clause. -/
theorem exists_generic_stalk_parameter :
    let y := _root_.genericPoint C.toScheme
    ∃ f : X.toScheme.presheaf.stalk (C.inclusion.base y),
      Ideal.span {f} = maximalIdeal (X.toScheme.presheaf.stalk (C.inclusion.base y)) ∧
      RingHom.ker (C.inclusion.stalkMap y).hom = Ideal.span {f} ∧
      f ∉ (maximalIdeal (X.toScheme.presheaf.stalk (C.inclusion.base y))) ^ 2 := by
  let y := _root_.genericPoint C.toScheme
  letI : Field (C.toScheme.presheaf.stalk y) :=
    inferInstanceAs (Field C.toScheme.functionField)
  letI : IsDiscreteValuationRing (X.toScheme.presheaf.stalk (C.inclusion.base y)) := by
    change IsDiscreteValuationRing
      (X.toScheme.presheaf.stalk (C.inclusion.base (_root_.genericPoint C.toScheme)))
    rw [inclusion_genericPoint_eq]
    exact C.genericPoint_isDiscreteValuationRing
  have hker := IsLocalRing.ker_eq_maximalIdeal (C.inclusion.stalkMap y).hom
    (C.inclusion.stalkMap_surjective y)
  obtain ⟨f, hf⟩ := IsDiscreteValuationRing.exists_irreducible
    (X.toScheme.presheaf.stalk (C.inclusion.base y))
  refine ⟨f, hf.maximalIdeal_eq.symm, hker.trans hf.maximalIdeal_eq, ?_⟩
  intro hsq
  have hdiv : f ^ 2 ∣ f ^ 1 := by
    have hm : maximalIdeal (X.toScheme.presheaf.stalk (C.inclusion.base y)) =
        Ideal.span {f} := hf.maximalIdeal_eq
    rw [hm, Ideal.span_singleton_pow, Ideal.mem_span_singleton] at hsq
    simpa only [pow_one] using hsq
  have hbad : (2 : ℕ) ≤ 1 := (pow_dvd_pow_iff hf.ne_zero hf.not_unit).mp hdiv
  exact (by decide : ¬ (2 : ℕ) ≤ 1) hbad

end KltDP.Geometry.NormalProjectiveSurface.PrimeCurve
