import KltDP.Geometry.PrimeCurveTransversalPoint
import KltDP.Geometry.PrimeCurveIntersectionLocalLengthPoints
import KltDP.Geometry.GluedSubschemeStalkKernel
import KltDP.Geometry.RationalTreePicardStalkTransport
import KltDP.Geometry.RegularLocalParameterQuotient

/-!
# Canonical Cartier coefficients at a crossing of the original curve ideals

The actual vanishing ideal of a prime curve at a stalk is generated by the
germ of every regular equation of its canonical Cartier divisor. If the two
original curve ideals generate the ambient maximal ideal, the restricted
coefficient generates the maximal ideal of the first curve's actual stalk.
For a smooth curve at a closed point the accepted DVR theorem then proves
irreducibility. The crossing input is an equality of the actual stalk ideals;
no uniformizer, local multiplicity, or intersection-number premise is used.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace IsLocalRing

universe u

namespace KltDP.Geometry.PrimeCurveCrossingCoefficient

open KltDP.Geometry.NormalProjectiveSurface
  KltDP.Geometry.NormalProjectiveSurface.PrimeCurve

variable {k : Type u} [Field k] [IsAlgClosed k] (X : NormalProjectiveSurface k)
  (hregular : ∀ x : X.Point, RegularPoint X.toScheme x)

/-- Every actual canonical Cartier coefficient generates the original vanishing ideal at the stalk. -/
theorem vanishingIdeal_map_germ_eq_span_coefficient (D : X.PrimeCurve)
    (U : X.toScheme.affineOpens) (x : X.toScheme) (hxU : x ∈ U.1)
    (c : RegularCartierEquationChart X.toScheme (X.primeCurveCartier hregular D))
    (hxc : x ∈ c.chart.openSet) :
    (D.vanishingIdeal.ideal U).map (X.toScheme.presheaf.germ U.1 x hxU).hom =
      Ideal.span {X.toScheme.presheaf.germ c.chart.openSet x hxc c.coefficient} := by
  obtain ⟨_, ⟨V, hVaff, rfl⟩, hxV, hVc⟩ :=
    (isBasis_affine_open X.toScheme).exists_subset_of_mem_open hxc c.chart.openSet.isOpen
  letI : Nonempty V := ⟨⟨x, hxV⟩⟩
  let d := RegularCartierEquationChart.restrict X.toScheme (X.primeCurveCartier hregular D) c V hVc
  calc
    (D.vanishingIdeal.ideal U).map (X.toScheme.presheaf.germ U.1 x hxU).hom =
        (D.vanishingIdeal.ideal ⟨V, hVaff⟩).map (X.toScheme.presheaf.germ V x hxV).hom :=
      RationalTreePicard.ideal_map_germ_eq D.vanishingIdeal x hxU hxV
    _ = Ideal.span {X.toScheme.presheaf.germ V x hxV
        (X.toScheme.presheaf.map (homOfLE hVc).op c.coefficient)} := by
      have hd := effectiveCartierIdealDataOfRegularEquations_ideal_chart X.toScheme
        (X.primeCurveCartier hregular D) (X.primeCurveCartier_hasRegularEquations hregular D)
        d (show IsAffineOpen d.chart.openSet from hVaff)
      change (effectiveCartierIdealDataOfRegularEquations X.toScheme
          (X.primeCurveCartier hregular D)
          (X.primeCurveCartier_hasRegularEquations hregular D)).ideal ⟨V, hVaff⟩ =
        Ideal.span {X.toScheme.presheaf.map (homOfLE hVc).op c.coefficient} at hd
      rw [← X.primeCurveCartier_idealData_eq_vanishingIdeal hregular D,
        hd, Ideal.map_span, Set.image_singleton]
    _ = _ := congrArg (fun t => Ideal.span ({t} : Set (X.toScheme.presheaf.stalk x)))
      (X.toScheme.presheaf.germ_res_apply (homOfLE hVc) x hxV c.coefficient)

variable (C D : X.PrimeCurve) (y : C.toScheme) (U : X.toScheme.affineOpens)
  (hyU : C.inclusion.base y ∈ U.1)
  (hcross :
    (C.vanishingIdeal.ideal U).map (X.toScheme.presheaf.germ U.1 (C.inclusion.base y) hyU).hom ⊔
      (D.vanishingIdeal.ideal U).map (X.toScheme.presheaf.germ U.1 (C.inclusion.base y) hyU).hom =
      maximalIdeal (X.toScheme.presheaf.stalk (C.inclusion.base y)))

include hcross in
/-- The actual Cartier coefficient restricted to the first curve generates its maximal ideal. -/
theorem restrictedCoefficient_span_eq_maximalIdeal
    (c : RegularCartierEquationChart X.toScheme (X.primeCurveCartier hregular D))
    (hyc : y ∈ C.chartPreimage (X.primeCurveCartier hregular D) c) :
    maximalIdeal (C.toScheme.presheaf.stalk y) =
      Ideal.span {C.toScheme.presheaf.germ (C.chartPreimage (X.primeCurveCartier hregular D) c)
        y hyc (C.restrictedCoefficient (X.primeCurveCartier hregular D) c)} := by
  have hker : RingHom.ker (C.inclusion.stalkMap y).hom =
      (C.vanishingIdeal.ideal U).map
        (X.toScheme.presheaf.germ U.1 (C.inclusion.base y) hyU).hom :=
    C.vanishingIdeal.stalkMap_gluedTo_ker_eq_map U hyU
  have hzero : ((C.vanishingIdeal.ideal U).map
      (X.toScheme.presheaf.germ U.1 (C.inclusion.base y) hyU).hom).map
        (C.inclusion.stalkMap y).hom = ⊥ :=
    (Ideal.map_eq_bot_iff_le_ker (C.inclusion.stalkMap y).hom).mpr hker.symm.le
  have h := congrArg (Ideal.map (C.inclusion.stalkMap y).hom) hcross
  rw [Ideal.map_sup, hzero, bot_sup_eq,
    vanishingIdeal_map_germ_eq_span_coefficient X hregular D U (C.inclusion.base y) hyU c hyc,
    Ideal.map_span, Set.image_singleton,
    RegularLocalParameterQuotient.map_maximalIdeal_eq (C.inclusion.stalkMap y).hom
      (C.inclusion.stalkMap_surjective y)] at h
  exact h.symm.trans (congrArg
    (fun t => Ideal.span ({t} : Set (C.toScheme.presheaf.stalk y)))
    (Scheme.stalkMap_germ_apply C.inclusion c.chart.openSet y hyc c.coefficient))

local instance crossingCoefficient_stalkIsDomain : IsDomain (C.toScheme.presheaf.stalk y) :=
  integralSchemeStalk_isDomain C.toScheme y

include hcross in
/-- At a closed point of a smooth original curve, the actual restricted coefficient is irreducible. -/
theorem restrictedCoefficient_irreducible_of_isSmooth [IsSmooth C.toSpec]
    (hy : IsClosed ({y} : Set C.toScheme))
    (c : RegularCartierEquationChart X.toScheme (X.primeCurveCartier hregular D))
    (hyc : y ∈ C.chartPreimage (X.primeCurveCartier hregular D) c) :
    Irreducible (C.toScheme.presheaf.germ (C.chartPreimage (X.primeCurveCartier hregular D) c)
      y hyc (C.restrictedCoefficient (X.primeCurveCartier hregular D) c)) := by
  haveI := C.stalk_isDiscreteValuationRing_of_isSmooth y hy
  exact (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr
    (restrictedCoefficient_span_eq_maximalIdeal X hregular C D y U hyU hcross c hyc)

end KltDP.Geometry.PrimeCurveCrossingCoefficient
