import KltDP.Geometry.GluedSubschemeStalk
import KltDP.Geometry.PrimeCurveIntersectionFinite
import KltDP.Geometry.PrimeCurveResidueFinrank

/-!
# The sum formula `intersectionDegree = Σ_z localLength z`

At a point `z` of the intersection subscheme `C ∩ D` (open singleton, since the
subscheme is finite with closed points), the sections over `{z}` are the stalk
`O_{C∩D,z}`, which is `O_{C,y} ⧸ (d|_C)_y` by the stalk identification of the glued
subscheme. The base-field action on `Γ(C ∩ D, {z})` through the structure morphism of
`C ∩ D` corresponds under this identification to the action on `O_{C,y}` through the
structure morphism of `C` (`stalkBaseMap`): both are the germ of the pulled-back
constant, by naturality of the stalk map. Hence the `k`-dimension of `Γ(C ∩ D, {z})`
is `localLength C y (germ d|_C)` at a closed DVR point over an algebraically closed
field, and summing over the points,

`intersectionDegree = Σ_{z ∈ C ∩ D} (cartierOrderAt C (D|_C) y_z).toNat = Σ_z localLength`.

Hypotheses: `k` algebraically closed, `C ⊄ Supp D`, and the curve regular (DVR stalks)
at every point.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory CategoryTheory.Limits TopologicalSpace Opposite

universe u

namespace KltDP.Geometry

variable (Z : Scheme.{u})

/-- The stalk-to-singleton-sections isomorphism sends the germ of a section to its
restriction to the singleton. -/
theorem stalkIsoSingletonSections_hom_germ (z : Z) (hz : IsOpen ({z} : Set Z)) (W : Z.Opens)
    (hzW : z ∈ W) (t : Γ(Z, W)) :
    (stalkIsoSingletonSections Z z hz).hom (Z.presheaf.germ W z hzW t) =
      Z.presheaf.map (homOfLE (Set.singleton_subset_iff.mpr hzW :
        (⟨{z}, hz⟩ : Z.Opens) ≤ W)).op t := by
  change (colimit.ι ((OpenNhds.inclusion z).op ⋙ Z.presheaf) (op ⟨W, hzW⟩) ≫
    (stalkIsoSingletonSections Z z hz).hom) t = _
  unfold stalkIsoSingletonSections
  rw [colimit.isoColimitCocone_ι_hom]
  rfl

end KltDP.Geometry

namespace KltDP.Geometry.NormalProjectiveSurface.PrimeCurve

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable {k : Type u} [Field k] {X : NormalProjectiveSurface k} (C : X.PrimeCurve)
  (D : CartierDivisor X.toScheme) (hD : HasRegularCartierEquations X.toScheme D)
  (hC : C.NotInSupport D hD)

/-- Stalks of the integral curve scheme are domains. -/
local instance primeCurveIntersectionLocalLength_stalkIsDomain (y : C.toScheme) :
    IsDomain (C.toScheme.presheaf.stalk y) :=
  integralSchemeStalk_isDomain C.toScheme y

/-- The kernel of the stalk map of `C ∩ D → C` at `z`, using any affine open `V` of the
restricted chart containing `y = i z`: it is generated by the germ of `d|_C`. -/
theorem intersectionInclusion_stalkMap_ker (c : C.GenericChart D)
    (V : C.toScheme.affineOpens) (hVU : V.1 ≤ C.chartPreimage D c.1)
    (z : C.intersectionScheme D hD hC) (hzV : (C.intersectionInclusion D hD hC).base z ∈ V.1) :
    RingHom.ker ((C.intersectionInclusion D hD hC).stalkMap z).hom =
      Ideal.span {C.toScheme.presheaf.germ (C.chartPreimage D c.1) _ (hVU hzV)
        (C.restrictedCoefficient D c.1)} := by
  haveI : Nonempty V.1 := ⟨⟨_, hzV⟩⟩
  have h := effectiveCartierInclusion_stalkMap_ker C.toScheme (C.restrictCartier D hD hC)
    (C.restrictCartier_hasRegularEquations D hD hC)
    (RegularCartierEquationChart.restrict C.toScheme (C.restrictCartier D hD hC)
      (C.restrictedChart D hD hC c) V.1 hVU) V.2 z hzV
  exact h.trans (congrArg (fun a => Ideal.span {a})
    (C.toScheme.presheaf.germ_res_apply (homOfLE hVU) _ hzV (C.restrictedCoefficient D c.1)))

/-- `O_{C∩D,z} ≃+* O_{C,y} ⧸ (d|_C)_y`, for any affine open of the restricted chart
containing `y`. -/
def intersectionStalkQuotientEquiv' (c : C.GenericChart D)
    (V : C.toScheme.affineOpens) (hVU : V.1 ≤ C.chartPreimage D c.1)
    (z : C.intersectionScheme D hD hC) (hzV : (C.intersectionInclusion D hD hC).base z ∈ V.1) :
    (C.toScheme.presheaf.stalk ((C.intersectionInclusion D hD hC).base z) ⧸
        Ideal.span {C.toScheme.presheaf.germ (C.chartPreimage D c.1) _ (hVU hzV)
          (C.restrictedCoefficient D c.1)}) ≃+*
      (C.intersectionScheme D hD hC).presheaf.stalk z :=
  (Ideal.quotEquivOfEq (C.intersectionInclusion_stalkMap_ker D hD hC c V hVU z hzV).symm).trans
    (RingHom.quotientKerEquivOfSurjective
      ((C.intersectionInclusion D hD hC).stalkMap_surjective z))

/-- The base action on `Γ(C ∩ D, {z})` through the structure morphism of `C ∩ D` is the
image of the base action on `O_{C,y}` through the structure morphism of `C`. -/
theorem baseSection_singleton_eq (z : C.intersectionScheme D hD hC)
    (hz : IsOpen ({z} : Set (C.intersectionScheme D hD hC))) (r : k) :
    (C.intersectionScheme D hD hC).presheaf.map
        (homOfLE (le_top : (⟨{z}, hz⟩ : (C.intersectionScheme D hD hC).Opens) ≤ ⊤)).op
        (baseFieldToGlobalSections (C.intersectionToSpec D hD hC) r) =
      (stalkIsoSingletonSections (C.intersectionScheme D hD hC) z hz).hom
        ((C.intersectionInclusion D hD hC).stalkMap z
          (C.stalkBaseMap ((C.intersectionInclusion D hD hC).base z) r)) := by
  change _ = (stalkIsoSingletonSections (C.intersectionScheme D hD hC) z hz).hom
    ((C.intersectionInclusion D hD hC).stalkMap z
      (C.toScheme.presheaf.germ ⊤ _ trivial (baseFieldToGlobalSections C.toSpec r)))
  rw [Scheme.stalkMap_germ_apply, stalkIsoSingletonSections_hom_germ]
  rfl

/-- `dim_k Γ(C ∩ D, {z}) = localLength C y (germ d|_C)` at a point `z` of the (discrete)
intersection subscheme, over an algebraically closed field, when the curve is regular at
`y = i z`. -/
theorem finrank_singleton_eq_localLength [IsAlgClosed k]
    [DiscreteTopology (C.intersectionScheme D hD hC)] (z : C.intersectionScheme D hD hC)
    [IsDiscreteValuationRing
      (C.toScheme.presheaf.stalk ((C.intersectionInclusion D hD hC).base z))]
    (c : C.GenericChart D) (V : C.toScheme.affineOpens) (hVU : V.1 ≤ C.chartPreimage D c.1)
    (hzV : (C.intersectionInclusion D hD hC).base z ∈ V.1) :
    letI := sectionsBaseModule (C.intersectionScheme D hD hC)
      (baseFieldToGlobalSections (C.intersectionToSpec D hD hC))
      (singletonOpen (C.intersectionScheme D hD hC) z)
    Module.finrank k Γ(C.intersectionScheme D hD hC, singletonOpen (C.intersectionScheme D hD hC) z) =
      C.localLength ((C.intersectionInclusion D hD hC).base z)
        (C.toScheme.presheaf.germ (C.chartPreimage D c.1) _ (hVU hzV)
          (C.restrictedCoefficient D c.1)) := by
  letI := (C.stalkBaseMap ((C.intersectionInclusion D hD hC).base z)).toAlgebra
  letI : Algebra k Γ(C.intersectionScheme D hD hC, singletonOpen (C.intersectionScheme D hD hC) z) :=
    (((C.intersectionScheme D hD hC).presheaf.map
      (homOfLE (le_top : singletonOpen (C.intersectionScheme D hD hC) z ≤ ⊤)).op).hom.comp
        (baseFieldToGlobalSections (C.intersectionToSpec D hD hC))).toAlgebra
  let q : (C.toScheme.presheaf.stalk ((C.intersectionInclusion D hD hC).base z) ⧸
      Ideal.span {C.toScheme.presheaf.germ (C.chartPreimage D c.1) _ (hVU hzV)
        (C.restrictedCoefficient D c.1)}) ≃+*
      Γ(C.intersectionScheme D hD hC, singletonOpen (C.intersectionScheme D hD hC) z) :=
    (C.intersectionStalkQuotientEquiv' D hD hC c V hVU z hzV).trans
      (stalkIsoSingletonSections (C.intersectionScheme D hD hC) z
        (isOpen_discrete _)).commRingCatIsoToRingEquiv
  have hq : ∀ r : k, q (algebraMap k _ r) =
      algebraMap k Γ(C.intersectionScheme D hD hC, singletonOpen (C.intersectionScheme D hD hC) z) r :=
    fun r =>
      (show q (algebraMap k _ r) =
          (stalkIsoSingletonSections (C.intersectionScheme D hD hC) z (isOpen_discrete _)).hom
            ((C.intersectionInclusion D hD hC).stalkMap z
              (C.stalkBaseMap ((C.intersectionInclusion D hD hC).base z) r)) from rfl).trans
        (C.baseSection_singleton_eq D hD hC z (isOpen_discrete _) r).symm
  have hfr := (AlgEquiv.ofRingEquiv hq).toLinearEquiv.finrank_eq
  have hd0 := C.germ_restrictedCoefficient_ne_zero _ D hD hC c (hVU hzV)
  have hcl : IsClosed ({(C.intersectionInclusion D hD hC).base z} : Set C.toScheme) := by
    rw [← Set.image_singleton]
    exact (IsClosedImmersion.base_closed (f := C.intersectionInclusion D hD hC)).isClosedMap _
      (C.intersectionScheme_isClosed_singleton' D hD hC z)
  exact hfr.symm.trans (C.finrank_quotient_span_eq_localLength _ _ hd0 hcl)

/-- **The sum formula.** For an algebraically closed field and a prime curve `C ⊄ Supp D`
that is regular at every point,
`intersectionDegree = Σ_{z ∈ C ∩ D} (cartierOrderAt C (D|_C) (i z)).toNat`, where each
term is `localLength C (i z) (germ d|_C)` (`cartierOrderAt_restrictCartier_eq_localLength`). -/
theorem intersectionDegree_eq_sum_cartierOrderAt [IsAlgClosed k]
    (hDVR : ∀ y : C.toScheme, IsDiscreteValuationRing (C.toScheme.presheaf.stalk y)) :
    letI : Fintype (C.intersectionScheme D hD hC) :=
      haveI := C.intersectionScheme_finite' D hD hC
      Fintype.ofFinite _
    C.intersectionDegree D hD hC = ∑ z : C.intersectionScheme D hD hC,
      (cartierOrderAt C.toScheme (C.restrictCartier D hD hC)
        ((C.intersectionInclusion D hD hC).base z)).toNat := by
  letI : Fintype (C.intersectionScheme D hD hC) :=
    haveI := C.intersectionScheme_finite' D hD hC
    Fintype.ofFinite _
  letI : DiscreteTopology (C.intersectionScheme D hD hC) :=
    DiscreteTopology.of_finite_of_isClosed_singleton
      (C.intersectionScheme_isClosed_singleton' D hD hC)
  refine (C.intersectionDegree_eq_sum_points'' D hD hC).trans ?_
  refine Finset.sum_congr rfl fun z _ => ?_
  obtain ⟨c, hzc⟩ := C.exists_genericChart D hD ((C.intersectionInclusion D hD hC).base z)
  obtain ⟨_, ⟨V, hVaff, rfl⟩, hzV, hVle⟩ :=
    (isBasis_affine_open C.toScheme).exists_subset_of_mem_open hzc (C.chartPreimage D c.1).2
  haveI := hDVR ((C.intersectionInclusion D hD hC).base z)
  refine (C.finrank_singleton_eq_localLength D hD hC z c ⟨V, hVaff⟩ hVle hzV).trans ?_
  rw [C.cartierOrderAt_restrictCartier_eq_localLength _ D hD hC c (hVle hzV), Int.toNat_natCast]

end KltDP.Geometry.NormalProjectiveSurface.PrimeCurve
