import KltDP.Geometry.PrimeCurveCartierRestriction
import KltDP.Geometry.GluedIdealSheafLift
import KltDP.Geometry.GluedIdealSheafKernel
import KltDP.Geometry.ClosedImmersionKerDegree
import KltDP.Geometry.CartierIntersectionScheme

/-!
# The kernel of `C ∩ D → X` is `vanishingIdeal C ⊔ I(D)`

For a prime curve `C ⊂ X` with inclusion `i` and an effective Cartier divisor `D` (regular local
equations, `C ⊄ Supp D`), the scheme-theoretic intersection `C ∩ D` (task 4) is the zero scheme of
`D|_C` on `C`, and `C ∩ D → C → X` is a closed immersion. Its kernel ideal sheaf is identified here:

* `⊇`: the vanishing ideal of `C` is the kernel of `i` (`Scheme.Hom.le_ker_comp`), and a section of
  `I(D)` pulls back into the ideal of `D|_C` (`inclusion_app_mem_cartierSectionIdeal_restrictCartier`:
  locally on `C`, `D` has a chart equation `f`, `D|_C` the equation `i^*f`, and `s = a f` pulls back to
  `i^*a · i^*f`), which is killed by the structure map of `Z(D|_C)`
  (`gluedTo_app_eq_zero_of_mem_cartierSectionIdeal`: vanishing is local and on affine opens the kernel
  of `K.gluedTo.app` is `K.ideal`).
* `⊆`: `K := vanishingIdeal C ⊔ I(D)` contains the kernel of `i`, so `K.gluedTo` lifts through `C`
  (`GluedIdealSheafLift.liftGlued`, lane F); the lift `ℓ` kills the ideal of `D|_C`
  (`app_eq_zero_of_mem_cartierSectionIdeal_restrictCartier`: locally `t = b · i^*f` and
  `ℓ (i^*f) = K.gluedTo f = 0`), so it lifts again through `Z(D|_C)`, and `Scheme.Hom.le_ker_comp`
  bounds the kernel of `C ∩ D → X` by `K.gluedTo.ker = K`.

Consequently (`intersectionDegree_eq_idealSheafDataDegree`, through the degree transport
`cohomologyDimension_unit_eq_of_ker_eq` of task 15) `C·D` is the degree of the closed subscheme
`Z(vanishingIdeal C ⊔ I(D))` of the surface — a symmetric expression once `vanishingIdeal C = I(D_C)`.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory TopologicalSpace Opposite
open KltDP.Geometry.ModuleCohomology

universe u

namespace KltDP.Geometry

attribute [local instance] Types.instFunLike Types.instConcreteCategory

section KilledByGluedTo

variable (Y : Scheme.{u}) [IsIntegral Y] (E : CartierDivisor Y) (hE : HasRegularCartierEquations Y E)

/-- A section of the divisor ideal of `E` over any open is killed by `K.gluedTo` for every ideal sheaf
datum `K ≥ I(E)`: vanishing is local on affine opens, where the kernel of `K.gluedTo.app` is `K.ideal`. -/
theorem gluedTo_app_eq_zero_of_mem_cartierSectionIdeal (K : Y.IdealSheafData)
    (hK : effectiveCartierIdealDataOfRegularEquations Y E hE ≤ K) (W : Y.Opens) (x : Γ(Y, W))
    (hx : x ∈ cartierSectionIdeal Y E W) : K.gluedTo.app W x = 0 := by
  rw [app_eq_zero_iff_forall_affine]
  intro A hA hAW
  have hK' := Scheme.IdealSheafData.le_def.mp hK
  have hmem : Y.presheaf.map (homOfLE hAW).op x ∈ K.ideal ⟨A, hA⟩ := by
    apply hK' ⟨A, hA⟩
    rw [effectiveCartierIdealDataOfRegularEquations_ideal]
    exact cartierSectionIdeal_restrict Y E (homOfLE hAW) x hx
  rw [← K.ker_gluedTo_app ⟨A, hA⟩] at hmem
  exact RingHom.mem_ker.mp hmem

end KilledByGluedTo

namespace NormalProjectiveSurface.PrimeCurve

variable {k : Type u} [Field k] {X : NormalProjectiveSurface k} (C : X.PrimeCurve)
  (D : CartierDivisor X.toScheme) (hD : HasRegularCartierEquations X.toScheme D)
  (hC : C.NotInSupport D hD)

/-- On an open `V` inside a generic chart preimage, the ideal of `D|_C` is generated by the restricted
coefficient. -/
theorem cartierSectionIdeal_restrictCartier_eq_span (c : C.GenericChart D) (V : C.toScheme.Opens)
    [Nonempty V] (hV : V ≤ C.chartPreimage D c.1) :
    cartierSectionIdeal C.toScheme (C.restrictCartier D hD hC) V =
      Ideal.span ({C.toScheme.presheaf.map (homOfLE hV).op (C.restrictedCoefficient D c.1)} :
        Set Γ(C.toScheme, V)) :=
  cartierSectionIdeal_eq_span C.toScheme (C.restrictCartier D hD hC)
    (RegularCartierEquationChart.restrict C.toScheme (C.restrictCartier D hD hC)
      (C.restrictedChart D hD hC c) V hV)

/-- `i^*` maps sections of the ideal of `D` into the ideal of `D|_C` (locality on `C`). -/
theorem inclusion_app_mem_cartierSectionIdeal_restrictCartier (U : X.toScheme.Opens)
    (s : Γ(X.toScheme, U)) (hs : s ∈ cartierSectionIdeal X.toScheme D U) :
    C.inclusion.app U s ∈
      cartierSectionIdeal C.toScheme (C.restrictCartier D hD hC) (C.inclusion ⁻¹ᵁ U) := by
  apply cartierSectionIdeal_of_locally_mem
  intro y hy
  obtain ⟨c, hyc⟩ := C.exists_genericChart D hD y
  have hyU : C.inclusion.base y ∈ U := hy
  have hyW : C.inclusion.base y ∈ c.1.chart.openSet := hyc
  haveI : Nonempty ((U ⊓ c.1.chart.openSet : X.toScheme.Opens)) :=
    ⟨⟨C.inclusion.base y, Opens.mem_inf.mpr ⟨hyU, hyW⟩⟩⟩
  haveI : Nonempty ((C.inclusion ⁻¹ᵁ (U ⊓ c.1.chart.openSet) : C.toScheme.Opens)) :=
    ⟨⟨y, Opens.mem_inf.mpr ⟨hyU, hyW⟩⟩⟩
  have hVle : C.inclusion ⁻¹ᵁ (U ⊓ c.1.chart.openSet) ≤ C.chartPreimage D c.1 :=
    leOfHom ((Opens.map C.inclusion.base).map (homOfLE inf_le_right))
  refine ⟨C.inclusion ⁻¹ᵁ (U ⊓ c.1.chart.openSet),
    (Opens.map C.inclusion.base).map (homOfLE inf_le_left), Opens.mem_inf.mpr ⟨hyU, hyW⟩, ?_⟩
  have hspan : cartierSectionIdeal X.toScheme D (U ⊓ c.1.chart.openSet) =
      Ideal.span ({X.toScheme.presheaf.map
        (homOfLE (inf_le_right : U ⊓ c.1.chart.openSet ≤ c.1.chart.openSet)).op c.1.coefficient} :
        Set Γ(X.toScheme, U ⊓ c.1.chart.openSet)) :=
    cartierSectionIdeal_eq_span X.toScheme D
      (RegularCartierEquationChart.restrict X.toScheme D c.1 (U ⊓ c.1.chart.openSet) inf_le_right)
  have hs' : X.toScheme.presheaf.map (homOfLE (inf_le_left : U ⊓ c.1.chart.openSet ≤ U)).op s ∈
      cartierSectionIdeal X.toScheme D (U ⊓ c.1.chart.openSet) :=
    cartierSectionIdeal_restrict X.toScheme D (homOfLE inf_le_left) s hs
  rw [hspan, Ideal.mem_span_singleton'] at hs'
  obtain ⟨a, ha⟩ := hs'
  rw [C.cartierSectionIdeal_restrictCartier_eq_span D hD hC c _ hVle, Ideal.mem_span_singleton']
  refine ⟨C.inclusion.app (U ⊓ c.1.chart.openSet) a, ?_⟩
  have h1 : C.inclusion.app (U ⊓ c.1.chart.openSet)
      (X.toScheme.presheaf.map
        (homOfLE (inf_le_right : U ⊓ c.1.chart.openSet ≤ c.1.chart.openSet)).op c.1.coefficient) =
      C.toScheme.presheaf.map (homOfLE hVle).op (C.restrictedCoefficient D c.1) :=
    ConcreteCategory.congr_hom (C.inclusion.naturality (homOfLE inf_le_right).op) c.1.coefficient
  have h2 : C.inclusion.app (U ⊓ c.1.chart.openSet)
      (X.toScheme.presheaf.map (homOfLE (inf_le_left : U ⊓ c.1.chart.openSet ≤ U)).op s) =
      C.toScheme.presheaf.map ((Opens.map C.inclusion.base).map (homOfLE inf_le_left)).op
        (C.inclusion.app U s) :=
    ConcreteCategory.congr_hom (C.inclusion.naturality (homOfLE inf_le_left).op) s
  rw [← h1, ← h2, ← ha, map_mul]

/-- Sections of the ideal of `D|_C` are killed by every `ℓ : Z(K) ⟶ C` with `ℓ ≫ i = K.gluedTo`,
`K ≥ I(D)`: locally `t = b · i^*f` for a chart equation `f` of `D`, and `ℓ (i^*f) = K.gluedTo f = 0`. -/
theorem app_eq_zero_of_mem_cartierSectionIdeal_restrictCartier (K : X.toScheme.IdealSheafData)
    (ℓ : K.glueData.glued ⟶ C.toScheme)
    (hK : effectiveCartierIdealDataOfRegularEquations X.toScheme D hD ≤ K)
    (hℓ : ℓ ≫ C.inclusion = K.gluedTo) (V : C.toScheme.Opens) (t : Γ(C.toScheme, V))
    (ht : t ∈ cartierSectionIdeal C.toScheme (C.restrictCartier D hD hC) V) : ℓ.app V t = 0 := by
  have hcoef : ∀ c : C.GenericChart D,
      ℓ.app (C.chartPreimage D c.1) (C.restrictedCoefficient D c.1) = 0 := by
    intro c
    have hmem : c.1.coefficient ∈ cartierSectionIdeal X.toScheme D c.1.chart.openSet := by
      rw [cartierSectionIdeal_eq_span X.toScheme D c.1]
      exact Ideal.mem_span_singleton_self _
    have h0 := gluedTo_app_eq_zero_of_mem_cartierSectionIdeal X.toScheme D hD K hK
      c.1.chart.openSet c.1.coefficient hmem
    rw [← hℓ, Scheme.comp_app, CommRingCat.comp_apply] at h0
    exact h0
  have hchart : ∀ w : (ℓ ⁻¹ᵁ V : K.glueData.glued.Opens),
      ∃ c : C.GenericChart D, ℓ.base w ∈ C.chartPreimage D c.1 :=
    fun w => C.exists_genericChart D hD (ℓ.base w)
  choose c hc using hchart
  refine K.glueData.glued.sheaf.eq_of_locally_eq'
    (fun w : (ℓ ⁻¹ᵁ V : K.glueData.glued.Opens) => ℓ ⁻¹ᵁ (V ⊓ C.chartPreimage D (c w).1))
    (ℓ ⁻¹ᵁ V)
    (fun w => (Opens.map ℓ.base).map (homOfLE inf_le_left)) ?_ (ℓ.app V t) 0 ?_
  · intro z hz
    exact Opens.mem_iSup.mpr ⟨⟨z, hz⟩, Opens.mem_inf.mpr ⟨hz, hc ⟨z, hz⟩⟩⟩
  · intro w
    rw [map_zero]
    have hnat : ℓ.app (V ⊓ C.chartPreimage D (c w).1)
        (C.toScheme.presheaf.map
          (homOfLE (inf_le_left : V ⊓ C.chartPreimage D (c w).1 ≤ V)).op t) =
        K.glueData.glued.presheaf.map ((Opens.map ℓ.base).map (homOfLE inf_le_left)).op
          (ℓ.app V t) :=
      ConcreteCategory.congr_hom (ℓ.naturality (homOfLE inf_le_left).op) t
    refine hnat.symm.trans ?_
    haveI : Nonempty ((V ⊓ C.chartPreimage D (c w).1 : C.toScheme.Opens)) :=
      ⟨⟨ℓ.base w, Opens.mem_inf.mpr ⟨w.2, hc w⟩⟩⟩
    have ht' : C.toScheme.presheaf.map
        (homOfLE (inf_le_left : V ⊓ C.chartPreimage D (c w).1 ≤ V)).op t ∈
        cartierSectionIdeal C.toScheme (C.restrictCartier D hD hC)
          (V ⊓ C.chartPreimage D (c w).1) :=
      cartierSectionIdeal_restrict C.toScheme (C.restrictCartier D hD hC) (homOfLE inf_le_left) t ht
    rw [C.cartierSectionIdeal_restrictCartier_eq_span D hD hC (c w) _ inf_le_right,
      Ideal.mem_span_singleton'] at ht'
    obtain ⟨b, hb⟩ := ht'
    rw [← hb, map_mul]
    have hres : ℓ.app (V ⊓ C.chartPreimage D (c w).1)
        (C.toScheme.presheaf.map
          (homOfLE (inf_le_right : V ⊓ C.chartPreimage D (c w).1 ≤ C.chartPreimage D (c w).1)).op
          (C.restrictedCoefficient D (c w).1)) =
        K.glueData.glued.presheaf.map ((Opens.map ℓ.base).map (homOfLE inf_le_right)).op
          (ℓ.app (C.chartPreimage D (c w).1) (C.restrictedCoefficient D (c w).1)) :=
      ConcreteCategory.congr_hom (ℓ.naturality (homOfLE inf_le_right).op) _
    rw [hres, hcoef (c w), map_zero, mul_zero]

/-- The closed immersion `C ∩ D → C` is the glued inclusion of the ideal sheaf of `D|_C`. -/
theorem intersectionInclusion_eq_gluedTo :
    C.intersectionInclusion D hD hC =
      (effectiveCartierIdealDataOfRegularEquations C.toScheme (C.restrictCartier D hD hC)
        (C.restrictCartier_hasRegularEquations D hD hC)).gluedTo := rfl

/-- `i : C → X` is the glued inclusion of the vanishing ideal of `C`. -/
theorem inclusion_eq_gluedTo : C.inclusion = C.vanishingIdeal.gluedTo := rfl

/-- The kernel of `i : C → X` is the vanishing ideal of `C`. -/
theorem inclusion_ker : C.inclusion.ker = C.vanishingIdeal := C.vanishingIdeal.ker_gluedTo

/-- `⊇`: `vanishingIdeal C ⊔ I(D)` is contained in the kernel of `C ∩ D → X`. -/
theorem sup_le_ker_intersectionToSurface :
    C.vanishingIdeal ⊔ effectiveCartierIdealDataOfRegularEquations X.toScheme D hD ≤
      (C.intersectionToSurface D hD hC).ker := by
  refine sup_le ?_ ?_
  · have h := Scheme.Hom.le_ker_comp (C.intersectionInclusion D hD hC) C.inclusion
    rw [C.inclusion_ker] at h
    exact h
  · refine Scheme.IdealSheafData.le_ofIdeals_iff.mpr ?_
    intro U s hs
    rw [effectiveCartierIdealDataOfRegularEquations_ideal] at hs
    rw [RingHom.mem_ker]
    change (C.intersectionInclusion D hD hC ≫ C.inclusion).app U.1 s = 0
    rw [Scheme.comp_app, CommRingCat.comp_apply]
    exact gluedTo_app_eq_zero_of_mem_cartierSectionIdeal C.toScheme (C.restrictCartier D hD hC)
      (C.restrictCartier_hasRegularEquations D hD hC) _ le_rfl _ _
      (C.inclusion_app_mem_cartierSectionIdeal_restrictCartier D hD hC U.1 s hs)

/-- A morphism into `C ∩ D` over `K.gluedTo` bounds the kernel of `C ∩ D → X` by `K`. -/
theorem ker_intersectionToSurface_le_of_factor (K : X.toScheme.IdealSheafData)
    (n : K.glueData.glued ⟶ C.intersectionScheme D hD hC)
    (hn : n ≫ C.intersectionToSurface D hD hC = K.gluedTo) :
    (C.intersectionToSurface D hD hC).ker ≤ K := by
  have h := Scheme.Hom.le_ker_comp n (C.intersectionToSurface D hD hC)
  rw [hn, Scheme.IdealSheafData.ker_gluedTo] at h
  exact h

/-- The ideal of `D|_C` is contained in the kernel of every `ℓ : Z(K) ⟶ C` with `ℓ ≫ i = K.gluedTo`,
`K ≥ I(D)`. -/
theorem restrictedIdealData_le_ker (K : X.toScheme.IdealSheafData)
    (hK : effectiveCartierIdealDataOfRegularEquations X.toScheme D hD ≤ K)
    (ℓ : K.glueData.glued ⟶ C.toScheme) (hℓ : ℓ ≫ C.inclusion = K.gluedTo) :
    effectiveCartierIdealDataOfRegularEquations C.toScheme (C.restrictCartier D hD hC)
      (C.restrictCartier_hasRegularEquations D hD hC) ≤ ℓ.ker := by
  refine Scheme.IdealSheafData.le_ofIdeals_iff.mpr ?_
  intro V t ht
  rw [effectiveCartierIdealDataOfRegularEquations_ideal] at ht
  rw [RingHom.mem_ker]
  exact C.app_eq_zero_of_mem_cartierSectionIdeal_restrictCartier D hD hC K ℓ hK hℓ V.1 t ht

/-- `⊆`: the kernel of `C ∩ D → X` is contained in `vanishingIdeal C ⊔ I(D)`, through the two lifts. -/
theorem ker_intersectionToSurface_le_sup :
    (C.intersectionToSurface D hD hC).ker ≤
      C.vanishingIdeal ⊔ effectiveCartierIdealDataOfRegularEquations X.toScheme D hD := by
  have hK1 : C.vanishingIdeal ≤
      (C.vanishingIdeal ⊔ effectiveCartierIdealDataOfRegularEquations X.toScheme D hD).gluedTo.ker := by
    rw [Scheme.IdealSheafData.ker_gluedTo]
    exact le_sup_left
  have hJ := C.restrictedIdealData_le_ker D hD hC
    (C.vanishingIdeal ⊔ effectiveCartierIdealDataOfRegularEquations X.toScheme D hD) le_sup_right
    (GluedIdealSheafLift.liftGlued C.vanishingIdeal _ hK1)
    (GluedIdealSheafLift.liftGlued_gluedTo C.vanishingIdeal _ hK1)
  refine C.ker_intersectionToSurface_le_of_factor D hD hC _
    (GluedIdealSheafLift.liftGlued _ (GluedIdealSheafLift.liftGlued C.vanishingIdeal _ hK1) hJ) ?_
  show _ ≫ (C.intersectionInclusion D hD hC ≫ C.inclusion) = _
  rw [← Category.assoc, C.intersectionInclusion_eq_gluedTo D hD hC,
    GluedIdealSheafLift.liftGlued_gluedTo, C.inclusion_eq_gluedTo,
    GluedIdealSheafLift.liftGlued_gluedTo]

/-- **Kernel identification**: `ker (C ∩ D → X) = vanishingIdeal C ⊔ I(D)`. -/
theorem intersectionToSurface_ker :
    (C.intersectionToSurface D hD hC).ker =
      C.vanishingIdeal ⊔ effectiveCartierIdealDataOfRegularEquations X.toScheme D hD :=
  le_antisymm (C.ker_intersectionToSurface_le_sup D hD hC)
    (C.sup_le_ker_intersectionToSurface D hD hC)

/-- **`C·D` is the degree of the closed subscheme `Z(vanishingIdeal C ⊔ I(D))` of the surface.** -/
theorem intersectionDegree_eq_idealSheafDataDegree :
    C.intersectionDegree D hD hC =
      idealSheafDataDegree X.toScheme
        (C.vanishingIdeal ⊔ effectiveCartierIdealDataOfRegularEquations X.toScheme D hD)
        X.structureMorphism := by
  have h1 : C.intersectionDegree D hD hC =
      cohomologyDimension (C.intersectionToSurface D hD hC ≫ X.structureMorphism)
        (_root_.SheafOfModules.unit (C.intersectionScheme D hD hC).ringCatSheaf) 0 :=
    congrArg (fun φ => cohomologyDimension φ
      (_root_.SheafOfModules.unit (C.intersectionScheme D hD hC).ringCatSheaf) 0)
      (Category.assoc (C.intersectionInclusion D hD hC) C.inclusion X.structureMorphism).symm
  rw [h1]
  exact cohomologyDimension_unit_eq_of_ker_eq (C.intersectionToSurface D hD hC)
    (C.vanishingIdeal ⊔ effectiveCartierIdealDataOfRegularEquations X.toScheme D hD).gluedTo
    (by rw [C.intersectionToSurface_ker D hD hC, Scheme.IdealSheafData.ker_gluedTo])
    X.structureMorphism

end NormalProjectiveSurface.PrimeCurve

end KltDP.Geometry
