import KltDP.Geometry.ReesChartLocalization
import KltDP.Geometry.AffineBlowupCover

/-!
# The actual Rees blowup of a principal regular ideal

For an actual ideal generated by `a`, its single degree-one Rees chart covers
the existing Proj. The chart's base-ring map is surjective by the proved
homogeneous-fraction description. If `a` is a nonzerodivisor, localization
also proves injectivity. Consequently the actual structure morphism `toSpec`
is an isomorphism, with no isomorphism or universal property supplied as data.

The nonzerodivisor hypothesis is the precise effective-Cartier condition for
this chosen global principal equation. No domain, Noetherian, field, or
nonemptiness hypothesis is imposed. This proves the affine principal-center
case, not the global blowup universal property or surface intersection formulas.

Reuse: pinned Mathlib localization injectivity, principal-ideal powers,
open-immersion isomorphisms, and `IsIso.of_isIso_fac_left`. The newer/external
source review is recorded in `docs/REES_BLOWUP_NEXT_OBLIGATIONS.md`.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory

namespace KltDP.Geometry.AffineBlowup

variable {R : Type*} [CommRing R] (I : Ideal R) (a : I)

/-- Principal generation makes the actual chart base map surjective, even
without a nonzerodivisor assumption. -/
theorem chartBaseMap_surjective_of_span_singleton
    (hI : Ideal.span {(a : R)} = I) : Function.Surjective (chartBaseMap I a) := by
  intro x
  obtain ⟨n, r, rfl⟩ := exists_chartMonomialFraction I a x
  have hr : (r : R) ∈ Ideal.span {(a : R) ^ n} :=
    (Ideal.span_singleton_pow (a : R) n).le
      ((congrArg (fun J : Ideal R => J ^ n) hI).ge r.property)
  obtain ⟨s, hs⟩ := Ideal.mem_span_singleton.mp hr
  refine ⟨s, chartToLocalization_injective I a ?_⟩
  rw [chartToLocalization_baseMap, chartToLocalization_monomialFraction,
    hs, map_mul, map_pow]
  have hcancel :
      algebraMap R (Localization.Away (a : R)) (a : R) ^ n *
        IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^ n = 1 := by
    rw [← mul_pow, IsLocalization.Away.mul_invSelf, one_pow]
  calc
    _ = algebraMap R (Localization.Away (a : R)) s *
        (algebraMap R (Localization.Away (a : R)) (a : R) ^ n *
          IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^ n) := by
      rw [hcancel, mul_one]
    _ = _ := by ring

/-- A nonzerodivisor equation makes the actual chart base map injective. -/
theorem chartBaseMap_injective_of_mem_nonZeroDivisors
    (ha : (a : R) ∈ nonZeroDivisors R) : Function.Injective (chartBaseMap I a) := by
  have hloc : Function.Injective (algebraMap R (Localization.Away (a : R))) :=
    IsLocalization.injective (Localization.Away (a : R)) (Submonoid.powers_le.mpr ha)
  intro r s hrs
  apply hloc
  have h := congrArg (chartToLocalization I a) hrs
  simpa only [chartToLocalization_baseMap] using h

/-- The actual base-ring map of the unique chart is bijective for a principal
nonzerodivisor ideal. -/
theorem chartBaseMap_bijective_of_principal_regular
    (hI : Ideal.span {(a : R)} = I) (ha : (a : R) ∈ nonZeroDivisors R) :
    Function.Bijective (chartBaseMap I a) :=
  ⟨chartBaseMap_injective_of_mem_nonZeroDivisors I a ha,
    chartBaseMap_surjective_of_span_singleton I a hI⟩

/-- Principal generation proves that this single chart is all of the actual Proj. -/
theorem chartOpen_eq_top_of_span_singleton (hI : Ideal.span {(a : R)} = I) :
    chartOpen I a = ⊤ := by
  have hspan : Ideal.span (Set.range (fun _ : Unit => (a : R))) = I := by
    simpa only [Set.range_const] using hI
  simpa only [iSup_const] using
    (iSup_chartOpen_generators I (fun _ : Unit => a) hspan)

/-- The unique covering chart's actual open immersion is an isomorphism. -/
theorem chartι_isIso_of_span_singleton (hI : Ideal.span {(a : R)} = I) :
    IsIso (chartι I a) := by
  apply isIso_of_isOpenImmersion_of_opensRange_eq_top
  change (Proj.awayι (ReesGrading.component I) (degreeOne I a)
    (degreeOne_mem I a) (by decide)).opensRange = ⊤
  rw [Proj.opensRange_awayι]
  exact chartOpen_eq_top_of_span_singleton I a hI

/-- The canonical Rees-Proj structure morphism is an isomorphism when its
center is generated by a nonzerodivisor. -/
theorem toSpec_isIso_of_principal_regular
    (hI : Ideal.span {(a : R)} = I) (ha : (a : R) ∈ nonZeroDivisors R) :
    IsIso (toSpec I) := by
  letI : IsIso (chartι I a) := chartι_isIso_of_span_singleton I a hI
  letI : IsIso (CommRingCat.ofHom (chartBaseMap I a)) :=
    (RingEquiv.ofBijective (chartBaseMap I a)
      (chartBaseMap_bijective_of_principal_regular I a hI ha)).toCommRingCatIso.isIso_hom
  exact IsIso.of_isIso_fac_left
    (show chartι I a ≫ toSpec I = Spec.map (CommRingCat.ofHom (chartBaseMap I a)) from
      chartι_toSpec I a)

/-- The actual blowup isomorphism over the original affine scheme. Its forward
map is exactly the already constructed `toSpec I`. -/
def principalCenterIso (hI : Ideal.span {(a : R)} = I)
    (ha : (a : R) ∈ nonZeroDivisors R) : scheme I ≅ Spec (CommRingCat.of R) := by
  letI : IsIso (toSpec I) := toSpec_isIso_of_principal_regular I a hI ha
  exact asIso (toSpec I)

@[simp]
theorem principalCenterIso_hom (hI : Ideal.span {(a : R)} = I)
    (ha : (a : R) ∈ nonZeroDivisors R) :
    (principalCenterIso I a hI ha).hom = toSpec I := rfl

@[simp]
theorem principalCenterIso_inv_toSpec (hI : Ideal.span {(a : R)} = I)
    (ha : (a : R) ∈ nonZeroDivisors R) :
    (principalCenterIso I a hI ha).inv ≫ toSpec I = 𝟙 (Spec (CommRingCat.of R)) :=
  (principalCenterIso I a hI ha).inv_hom_id

@[simp]
theorem toSpec_principalCenterIso_inv (hI : Ideal.span {(a : R)} = I)
    (ha : (a : R) ∈ nonZeroDivisors R) :
    toSpec I ≫ (principalCenterIso I a hI ha).inv = 𝟙 (scheme I) :=
  (principalCenterIso I a hI ha).hom_inv_id

end KltDP.Geometry.AffineBlowup
