import KltDP.Geometry.ProjectiveLineDegreeOneGlobalGeneration
import KltDP.Geometry.GloballyGeneratedPullback
import KltDP.Geometry.AmpleNefUnconditional

/-!
# Actual nef coordinate pullbacks along original surface-to-line morphisms

The original degree-one line bundle has its two proved global generators.
Their actual scheme pullbacks are globally generating; the accepted
unconditional surface positivity theorem gives nefness for every original
surface-to-projective-line morphism, including original fibration maps.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory

universe u

namespace KltDP.Geometry.ProjectiveLineDegreeOnePullbackNef

open RationalTreePicard

variable {k : Type u} [Field k] (X : NormalProjectiveSurface k)
  (f : X.toScheme ⟶ projectiveSpace k 1)

/-- The actual coordinate pullback is globally generated by the transported
original two-section family. -/
theorem pullback_isGloballyGenerated :
    Positivity.IsGloballyGenerated (pullbackInvertibleSheaf f (monomialLineBundle k 1)).obj :=
  GloballyGeneratedPullback.isGloballyGenerated f (monomialLineBundle k 1).obj
    (ProjectiveLineDegreeOneGlobalGeneration.degreeOne_isGloballyGenerated k)

/-- The original pullback of the degree-one line bundle is nef on the
original normal projective surface, for every actual morphism to P¹. -/
theorem pullback_isNef :
    Positivity.IsNef X.structureMorphism (pullbackInvertibleSheaf f (monomialLineBundle k 1)) := by
  apply AmpleNefUnconditional.isNef_of_isSemiample X
  refine ⟨1, Nat.one_pos, pullbackInvertibleSheaf f (monomialLineBundle k 1), ?_,
    pullback_isGloballyGenerated X f⟩
  exact (pow_one _).symm

end KltDP.Geometry.ProjectiveLineDegreeOnePullbackNef
