import KltDP.Geometry.ProjectiveSpaceDegreeOneSheaf
import KltDP.Geometry.FramedGlobalGeneration

/-! # The original n+1 homogeneous coordinates generate the original degree-one sheaf -/

noncomputable section

open AlgebraicGeometry CategoryTheory Opposite TopologicalSpace

universe u

namespace KltDP.Geometry.ProjectiveSpaceDegreeOneSheaf

attribute [local instance] Types.instFunLike Types.instConcreteCategory

open TransitionUnitGluing ProjectiveCoordinateSectionBasicOpen ProjectiveCoordinateSectionRelations

variable (k : Type u) [Field k] (n : ℕ)

/-- The original homogeneous coordinate frame on an original standard chart. -/
def coordinateFrame (i : ULift.{u} (Fin (n + 1))) :
    (degreeOne k n).obj.over (chart k n i) ≅
      _root_.SheafOfModules.unit ((projectiveSpace k n).ringCatSheaf.over (chart k n i)) :=
  chartIsoOn (projectiveSpace k n) (chart k n) (overlapUnit k n)
    (overlapUnit_isCocycle k n) i le_rfl

/-- The matching original homogeneous coordinate has coefficient one
in the actual original chart frame. -/
theorem homogeneousSection_coefficient (i : ULift.{u} (Fin (n + 1))) :
    (coordinateFrame k n i).hom.val.app (op (Over.mk (𝟙 (chart k n i))))
      ((homogeneousSection k n i.down).val (op (chart k n i))) =
        (1 : Γ(projectiveSpace k n, chart k n i)) := by
  have h := chartIsoOn_hom_app_apply (projectiveSpace k n) (chart k n) (overlapUnit k n)
    (overlapUnit_isCocycle k n) i (le_refl (chart k n i))
    (op (Over.mk (𝟙 (chart k n i))))
    ((homogeneousSection k n i.down).val (op (chart k n i)))
  have ht := trivialization_globalSectionOfCoordinates (projectiveSpace k n) (chart k n)
    (overlapUnit k n) (fun j => coordinateSection k n j.down i.down)
    (fun j l => coordinateSection_relation_mul k n j.down l.down i.down)
    (overlapUnit_isCocycle k n) i (le_refl (chart k n i))
  refine h.trans (ht.trans ?_)
  rw [coordinateSection_self, map_one]

/-- The original n+1 homogeneous-coordinate sections give an actual
free-sheaf epimorphism onto the original degree-one sheaf. -/
theorem homogeneousSections_epi :
    Epi ((degreeOne k n).obj.freeHomEquiv.symm
      (fun i : ULift.{u} (Fin (n + 1)) => homogeneousSection k n i.down)) := by
  apply FramedGlobalGeneration.epi_of_unit_coefficients (degreeOne k n).obj
    (chart k n) (chart_cover k n).ge (coordinateFrame k n)
    (fun i : ULift.{u} (Fin (n + 1)) => homogeneousSection k n i.down)
  intro i
  exact ⟨i, homogeneousSection_coefficient k n i⟩

/-- The literal finite family of the original homogeneous-coordinate generators. -/
def homogeneousGenerators : (degreeOne k n).obj.GeneratingSections where
  I := ULift.{u} (Fin (n + 1))
  s i := homogeneousSection k n i.down
  epi := homogeneousSections_epi k n

theorem homogeneousGenerators_finite : Finite (homogeneousGenerators k n).I :=
  inferInstanceAs (Finite (ULift.{u} (Fin (n + 1))))

/-- The original projective degree-one sheaf is globally generated by
its constructed homogeneous coordinates. -/
theorem degreeOne_isGloballyGenerated : Positivity.IsGloballyGenerated (degreeOne k n).obj :=
  ⟨ULift.{u} (Fin (n + 1)), (degreeOne k n).obj.freeHomEquiv.symm
    (fun i : ULift.{u} (Fin (n + 1)) => homogeneousSection k n i.down),
    homogeneousSections_epi k n⟩

end KltDP.Geometry.ProjectiveSpaceDegreeOneSheaf
