import KltDP.Geometry.ProjectiveCoordinateSectionBasicOpen
import KltDP.Geometry.ProjectiveSpaceChartFunctionsGeneral
import KltDP.Geometry.ClosedImmersionStructureEpi
import Mathlib.AlgebraicGeometry.FunctionField

/-!
# Polynomial fractions on the actual affine chart of a projective image

The chart ring maps to the original sections of the inverse-image open.
For a closed immersion that map is surjective. If the source is integral
and the chosen chart is nonempty, its actual function field is therefore
generated by quotients of polynomials in the pulled coordinate fractions.

The coefficient map is recorded as the actual composite from the original
field through the original projective chart and the generic-point germ.
Its comparison with the global structure-map scalar homomorphism is a
separate adapter. No birationality or global section-ratio premise is used.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory

universe u

namespace KltDP.Geometry.ProjectiveImageChartFieldGeneration

attribute [local instance] Types.instFunLike Types.instConcreteCategory
attribute [local instance] MvPolynomial.gradedAlgebra

open ProjectiveChart ProjectiveCoordinateSectionBasicOpen

variable {k : Type u} [Field k] {n : ℕ} {Y : Scheme.{u}}
  (e : Y ⟶ projectiveSpace k n) (j : Fin (n + 1))

/-- The original homogeneous chart ring maps to the actual inverse-image
open by the original scheme morphism's section map. -/
def chartSectionMap : coordinateChartRing k n j →+*
    Γ(Y, e ⁻¹ᵁ standardOpen k n j) :=
  (e.app (standardOpen k n j)).hom.comp
    (Proj.awayToSection (grading k n) (MvPolynomial.X j)).hom

/-- Constants pulled from the original projective chart. -/
def sectionConstants : k →+* Γ(Y, e ⁻¹ᵁ standardOpen k n j) :=
  (chartSectionMap e j).comp (coordinateChartConstants k n j)

/-- The original chart-coordinate section pulled to the inverse image. -/
def sectionCoordinate (i : Fin (n + 1)) :
    Γ(Y, e ⁻¹ᵁ standardOpen k n j) :=
  chartSectionMap e j (chartFraction k n j i)

theorem sectionCoordinate_eq_app (i : Fin (n + 1)) :
    sectionCoordinate e j i =
      e.app (standardOpen k n j) (coordinateSection k n j i) := rfl

/-- The actual affine chart of a closed subscheme is a quotient of the
original homogeneous chart ring. -/
theorem chartSectionMap_surjective [IsClosedImmersion e] :
    Function.Surjective (chartSectionMap e j) := by
  have haway : Function.Surjective
      (Proj.basicOpenIsoAway (grading k n) (MvPolynomial.X j)
        (coordinate_mem k n j) Nat.one_pos).hom :=
    (ConcreteCategory.bijective_of_isIso _).2
  exact (app_surjective_of_isAffineOpen e (standardOpen k n j)
    (Proj.isAffineOpen_basicOpen (grading k n) (MvPolynomial.X j)
      (coordinate_mem k n j) Nat.one_pos)).comp haway

/-- Every actual section on the image chart is a polynomial in the
actual pulled coordinate fractions, with the original chart constants. -/
theorem exists_polynomial_section [IsClosedImmersion e]
    (s : Γ(Y, e ⁻¹ᵁ standardOpen k n j)) :
    ∃ p : homogeneousRing k n,
      MvPolynomial.eval₂ (sectionConstants e j) (sectionCoordinate e j) p = s := by
  obtain ⟨a, ha⟩ := chartSectionMap_surjective e j s
  obtain ⟨p, hp⟩ := exists_eval_chartFraction k n j a
  refine ⟨p, ?_⟩
  rw [hp, MvPolynomial.eval₂_comp_left] at ha
  exact ha

section FunctionField

variable [IsIntegral Y] [Nonempty (e ⁻¹ᵁ standardOpen k n j)]

/-- The coefficient map into the actual original function field. -/
def fieldConstants : k →+* Y.functionField :=
  (Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j)).hom.comp
    (sectionConstants e j)

/-- The actual generic-point germ of a pulled coordinate fraction. -/
def fieldCoordinate (i : Fin (n + 1)) : Y.functionField :=
  Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j) (sectionCoordinate e j i)

theorem polynomial_germ (p : homogeneousRing k n) :
    Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j)
        (MvPolynomial.eval₂ (sectionConstants e j) (sectionCoordinate e j) p) =
      MvPolynomial.eval₂ (fieldConstants e j) (fieldCoordinate e j) p :=
  MvPolynomial.eval₂_comp_left
    (Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j)).hom
    (sectionConstants e j) (sectionCoordinate e j) p

/-- Every element of the actual function field is a quotient of
polynomials in the actual image-chart coordinates, with nonzero
denominator in that same function field. -/
theorem exists_polynomial_quotient [IsClosedImmersion e] (z : Y.functionField) :
    ∃ p q : homogeneousRing k n,
      MvPolynomial.eval₂ (fieldConstants e j) (fieldCoordinate e j) q ≠ 0 ∧
      MvPolynomial.eval₂ (fieldConstants e j) (fieldCoordinate e j) p /
        MvPolynomial.eval₂ (fieldConstants e j) (fieldCoordinate e j) q = z := by
  letI := functionField_isFractionRing_of_isAffineOpen Y
    (e ⁻¹ᵁ standardOpen k n j)
    ((Proj.isAffineOpen_basicOpen (grading k n) (MvPolynomial.X j)
      (coordinate_mem k n j) Nat.one_pos).preimage e)
  obtain ⟨a, b, hb, hz⟩ :=
    IsFractionRing.div_surjective (A := Γ(Y, e ⁻¹ᵁ standardOpen k n j)) z
  obtain ⟨p, hp⟩ := exists_polynomial_section e j a
  obtain ⟨q, hq⟩ := exists_polynomial_section e j b
  have hp' : MvPolynomial.eval₂ (fieldConstants e j) (fieldCoordinate e j) p =
      algebraMap Γ(Y, e ⁻¹ᵁ standardOpen k n j) Y.functionField a := by
    calc
      _ = Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j)
          (MvPolynomial.eval₂ (sectionConstants e j) (sectionCoordinate e j) p) :=
        (polynomial_germ e j p).symm
      _ = _ := congrArg (Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j)) hp
  have hq' : MvPolynomial.eval₂ (fieldConstants e j) (fieldCoordinate e j) q =
      algebraMap Γ(Y, e ⁻¹ᵁ standardOpen k n j) Y.functionField b := by
    calc
      _ = Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j)
          (MvPolynomial.eval₂ (sectionConstants e j) (sectionCoordinate e j) q) :=
        (polynomial_germ e j q).symm
      _ = _ := congrArg (Y.germToFunctionField (e ⁻¹ᵁ standardOpen k n j)) hq
  refine ⟨p, q, ?_, ?_⟩
  · rw [hq']
    exact IsFractionRing.to_map_ne_zero_of_mem_nonZeroDivisors hb
  · rwa [hp', hq']

end FunctionField

end KltDP.Geometry.ProjectiveImageChartFieldGeneration
