import KltDP.Geometry.InvertibleQuadraticAtlas
import KltDP.Geometry.QuadraticRamificationCharts
import Mathlib.LinearAlgebra.Dual.Defs

/-!
# The actual section-evaluation ideal on quadratic branch charts

For an original module sheaf N and global section b, define an ideal on
each open W as the image of evaluation at the actual restriction of b.
The map is the original dual evaluation
`Hom(N(W), O(W)) → O(W)`, sending a functional to its value on b|W.
The ideal is defined before any trivialization or branch coefficient.

The existing square-root isomorphism and existing matching-coordinate
trivializations identify the original section module with O(W) on each
affine refinement chart. Naturality of the original sheaf morphisms shows
that b|W has precisely the existing quadratic atlas coefficient. The
evaluation ideal is therefore its principal ideal. The equality induces
an actual quotient-ring equivalence and Spec isomorphism to the existing
branchScheme, preserving the original quotient and affine base maps.

This is the local dual-evaluation prerequisite. It does not assert that
these ideals have already been assembled into a global coherent ideal
sheaf, nor that this local zero scheme is the manuscript's Cartier divisor.
No reducedness, regularity, nonzero section, normality, integral base or
characteristic condition is assumed.

Reuse: pinned Module.Dual.eval, actual sheaf-module evaluation/naturality,
Ideal.quotEquivOfEq and the existing original square-root atlas. Newer
official Mathlib a4d9f2fdd2f64b55969042eef459606961dc63a2 retains the dual
evaluation API (Apache-2.0); no newer source port is needed.
-/

noncomputable section

open AlgebraicGeometry CategoryTheory MonoidalCategory Opposite

universe u v

namespace KltDP.Geometry

/-- The range of actual dual evaluation is the ideal generated by the
coordinate in any actual rank-one trivialization. -/
theorem dual_evaluation_range_eq_span
    {R : Type u} [CommRing R] {M : Type v} [AddCommGroup M] [Module R M]
    (e : M ≃ₗ[R] R) (m : M) :
    LinearMap.range (Module.Dual.eval R M m) = Ideal.span ({e m} : Set R) := by
  apply le_antisymm
  · rintro _ ⟨f, rfl⟩
    apply Ideal.mem_span_singleton.mpr
    refine ⟨f (e.symm 1), ?_⟩
    change f m = e m * f (e.symm 1)
    have hm : (e m) • e.symm 1 = m := by
      apply e.injective
      simp only [map_smul, LinearEquiv.apply_symm_apply, smul_eq_mul, mul_one]
    calc
      f m = f ((e m) • e.symm 1) := congrArg f hm.symm
      _ = e m * f (e.symm 1) := f.map_smul _ _
  · apply Ideal.span_le.mpr
    intro x hx
    rw [Set.mem_singleton_iff] at hx
    subst x
    exact ⟨e.toLinearMap, rfl⟩

attribute [local instance] Types.instFunLike Types.instConcreteCategory

variable (X : Scheme.{u})

/-- The ideal is the image of evaluation on the original restricted
global section, independent of any supplied local frame or generator. -/
def sectionEvaluationIdeal (N : X.Modules)
    (b : N.val.obj (op (⊤ : X.Opens))) (W : X.Opens) : Ideal Γ(X, W) :=
  LinearMap.range (Module.Dual.eval Γ(X, W) (N.val.obj (op W))
    (N.val.map (homOfLE (le_top : W ≤ ⊤)).op b))

namespace InvertibleQuadraticAtlas

open TransitionUnitGluing TransitionUnitExtraction QuadraticCover

local instance evaluationIdealMonoidal : MonoidalCategory X.Modules :=
  Scheme.Modules.monoidalCategory X

variable (L : InvertibleSheaf X) (N : X.Modules) (e : L.obj ⊗ L.obj ≅ N)

/-- The actual square-root and tensor-coordinate isomorphisms, evaluated
on an original affine refinement chart and followed by its original frame. -/
def squareRootCoordinateEquiv
    (i : AffineOpenRefinement.Index X L.localTrivializations.X) :
    N.val.obj (op (AffineOpenRefinement.opens X L.localTrivializations.X i)) ≃ₗ[
      Γ(X, AffineOpenRefinement.opens X L.localTrivializations.X i)]
      Γ(X, AffineOpenRefinement.opens X L.localTrivializations.X i) :=
  (((_root_.SheafOfModules.evaluation X.ringCatSheaf
      (op (AffineOpenRefinement.opens X L.localTrivializations.X i))).mapIso
      (e.symm ≪≫ squareCoordinatesIso X L)).toLinearEquiv) ≪≫ₗ
    (trivialization X L.localTrivializations.X
      (productUnits X L.localTrivializations.X (invertibleSheafUnits X L)
        (invertibleSheafUnits X L))
      (productUnits_isCocycle X L.localTrivializations.X
        (invertibleSheafUnits X L) (invertibleSheafUnits X L)
        (invertibleSheafUnits_isCocycle X L) (invertibleSheafUnits_isCocycle X L))
      (AffineOpenRefinement.original X L.localTrivializations.X i)
      (AffineOpenRefinement.subordinate X L.localTrivializations.X i))

variable [X.IsSeparated]

set_option maxHeartbeats 800000 in
/-- The original restricted section has exactly the coefficient used by
the existing quadratic atlas, by actual sheaf-morphism naturality. -/
theorem squareRootCoordinateEquiv_restrictedSection
    (b : N.val.obj (op (⊤ : X.Opens)))
    (i : AffineOpenRefinement.Index X L.localTrivializations.X) :
    squareRootCoordinateEquiv X L N e i
      (N.val.map (homOfLE (le_top :
        AffineOpenRefinement.opens X L.localTrivializations.X i ≤ ⊤)).op b) =
      (fromSquareRoot X L N e b).sections i := by
  let U := L.localTrivializations.X
  let g := invertibleSheafUnits X L
  let V := AffineOpenRefinement.opens X U i
  let j := AffineOpenRefinement.original X U i
  let hc := productUnits_isCocycle X U g g
    (invertibleSheafUnits_isCocycle X L) (invertibleSheafUnits_isCocycle X L)
  let f := e.symm ≪≫ squareCoordinatesIso X L
  change trivialization X U (productUnits X U g g) hc j
      (AffineOpenRefinement.subordinate X U i)
      (f.hom.val.app (op V) (N.val.map (homOfLE (le_top : V ≤ ⊤)).op b)) =
    refinedCoefficient X U g (squareCoordinates X L (e.inv.val.app (op ⊤) b)) i
  rw [_root_.PresheafOfModules.naturality_apply f.hom.val
    (homOfLE (le_top : V ≤ ⊤)).op b]
  change trivialization X U (productUnits X U g g) hc j
      (AffineOpenRefinement.subordinate X U i)
      (restrict X U (productUnits X U g g) (le_top : V ≤ ⊤)
        (squareCoordinates X L (e.inv.val.app (op ⊤) b))) = _
  simpa only [trivialization_apply, restrict_val, refinedCoefficient] using
    (res_res X (le_inf le_rfl (AffineOpenRefinement.subordinate X U i))
      (inf_le_inf_right (U j) (le_top : V ≤ ⊤))
      ((squareCoordinates X L (e.inv.val.app (op ⊤) b)).val j))

/-- The local zero ideal is derived from actual dual evaluation of the
original section; its generator is the original quadratic coefficient. -/
theorem sectionEvaluationIdeal_eq_branchIdeal
    (b : N.val.obj (op (⊤ : X.Opens)))
    (i : AffineOpenRefinement.Index X L.localTrivializations.X) :
    sectionEvaluationIdeal X N b (AffineOpenRefinement.opens X L.localTrivializations.X i) =
      branchIdeal ((fromSquareRoot X L N e b).sections i) := by
  change LinearMap.range (Module.Dual.eval _ _ _) = Ideal.span {_}
  rw [dual_evaluation_range_eq_span (squareRootCoordinateEquiv X L N e i),
    squareRootCoordinateEquiv_restrictedSection]

/-- The actual dual-evaluation quotient and the branch quotient are
canonically equivalent because their original ideals have been proved equal. -/
def sectionEvaluationQuotientEquiv
    (b : N.val.obj (op (⊤ : X.Opens)))
    (i : AffineOpenRefinement.Index X L.localTrivializations.X) :
    (Γ(X, AffineOpenRefinement.opens X L.localTrivializations.X i) ⧸
      sectionEvaluationIdeal X N b (AffineOpenRefinement.opens X L.localTrivializations.X i)) ≃+*
      (Γ(X, AffineOpenRefinement.opens X L.localTrivializations.X i) ⧸
        branchIdeal ((fromSquareRoot X L N e b).sections i)) :=
  Ideal.quotEquivOfEq (sectionEvaluationIdeal_eq_branchIdeal X L N e b i)

/-- The quotient equivalence retains the actual original quotient maps. -/
@[simp]
theorem sectionEvaluationQuotientEquiv_mk
    (b : N.val.obj (op (⊤ : X.Opens)))
    (i : AffineOpenRefinement.Index X L.localTrivializations.X)
    (r : Γ(X, AffineOpenRefinement.opens X L.localTrivializations.X i)) :
    sectionEvaluationQuotientEquiv X L N e b i (Ideal.Quotient.mk
        (sectionEvaluationIdeal X N b
          (AffineOpenRefinement.opens X L.localTrivializations.X i)) r) =
      Ideal.Quotient.mk (branchIdeal ((fromSquareRoot X L N e b).sections i)) r :=
  Ideal.quotEquivOfEq_mk _ r

/-- The actual local dual-evaluation zero scheme is the existing branch
chart, via the derived quotient equivalence. -/
def sectionZeroChartIsoBranch
    (b : N.val.obj (op (⊤ : X.Opens)))
    (i : AffineOpenRefinement.Index X L.localTrivializations.X) :
    Spec (.of (Γ(X, AffineOpenRefinement.opens X L.localTrivializations.X i) ⧸
      sectionEvaluationIdeal X N b
        (AffineOpenRefinement.opens X L.localTrivializations.X i))) ≅
      branchScheme ((fromSquareRoot X L N e b).sections i) :=
  Scheme.Spec.mapIso
    (sectionEvaluationQuotientEquiv X L N e b i).symm.toCommRingCatIso.op

-- Check the same quotient triangle with abstract ideals before substituting
-- the concrete section module, atlas coefficient and quotient constructions.
private theorem spec_quotEquivOfEq_hom_mk
    {R : Type u} [CommRing R] {I J : Ideal R} (h : I = J) :
    (Scheme.Spec.mapIso ((Ideal.quotEquivOfEq h).symm.toCommRingCatIso.op)).hom ≫
        Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk J)) =
      Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk I)) := by
  change Spec.map _ ≫ Spec.map _ = Spec.map _
  rw [← Spec.map_comp]
  apply congrArg (fun f : R →+* (R ⧸ I) => Spec.map (CommRingCat.ofHom f))
  apply RingHom.ext
  intro r
  change (Ideal.quotEquivOfEq h).symm (Ideal.Quotient.mk _ r) = Ideal.Quotient.mk _ r
  rw [Ideal.quotEquivOfEq_symm, Ideal.quotEquivOfEq_mk]

/-- The derived local zero-scheme identification is over the original
affine base, with its original quotient inclusion. -/
@[reassoc]
theorem sectionZeroChartIsoBranch_hom_toSpec
    (b : N.val.obj (op (⊤ : X.Opens)))
    (i : AffineOpenRefinement.Index X L.localTrivializations.X) :
    (sectionZeroChartIsoBranch X L N e b i).hom ≫
        branchι ((fromSquareRoot X L N e b).sections i) =
      Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk
        (sectionEvaluationIdeal X N b
          (AffineOpenRefinement.opens X L.localTrivializations.X i)))) := by
  exact spec_quotEquivOfEq_hom_mk
    (sectionEvaluationIdeal_eq_branchIdeal X L N e b i)

/-- Postcomposition retains the original affine chart map into X. -/
@[reassoc]
theorem sectionZeroChartIsoBranch_hom_toBase
    (b : N.val.obj (op (⊤ : X.Opens)))
    (i : AffineOpenRefinement.Index X L.localTrivializations.X) :
    (sectionZeroChartIsoBranch X L N e b i).hom ≫
        branchι ((fromSquareRoot X L N e b).sections i) ≫
          ((fromSquareRoot X L N e b).affine i).fromSpec =
      Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk
        (sectionEvaluationIdeal X N b
          (AffineOpenRefinement.opens X L.localTrivializations.X i)))) ≫
            ((fromSquareRoot X L N e b).affine i).fromSpec := by
  rw [← Category.assoc, sectionZeroChartIsoBranch_hom_toSpec]

end InvertibleQuadraticAtlas

end KltDP.Geometry
