import KltDP.Geometry.QuadraticBranchDifferentialCoordinates
import KltDP.Geometry.QuadraticAbsoluteDifferentialFactor

/-!
# The actual branch-normalized differential basis of a quadratic cover

If the original base differentials have a basis (ds, eta), the actual
absolute differentials of R[t]/(t²-s) have the basis (dt, image(eta)).
The proof constructs dual coordinates and proves generation by the
original universal derivation. No smoothness, differential injectivity,
cover basis, or determinant-factorization hypothesis is used.
-/

noncomputable section

universe u

namespace KltDP.Geometry.QuadraticCover

variable (k R : Type u) [CommRing k] [CommRing R] [Algebra k R] [Nontrivial R]

/-- The two specified forms in the actual cover differential module. -/
def branchDifferentialVectors (s : R)
    (b : Basis (Fin 2) R (KaehlerDifferential k R)) :
    Fin 2 → KaehlerDifferential k (CoverAlgebra s) :=
  ![KaehlerDifferential.D k (CoverAlgebra s) (root s),
    KaehlerDifferential.map k k R (CoverAlgebra s) (b 1)]

/-- The constructed actual dual coordinates prove linear independence. -/
theorem branchDifferentialVectors_linearIndependent (s : R)
    (b : Basis (Fin 2) R (KaehlerDifferential k R))
    (hb : b 0 = KaehlerDifferential.D k R s) :
    LinearIndependent (CoverAlgebra s) (branchDifferentialVectors k R s b) := by
  apply LinearIndependent.of_comp (branchDifferentialCoordinates k R s b hb)
  have heq : branchDifferentialCoordinates k R s b hb ∘
      branchDifferentialVectors k R s b = Basis.finTwoProd (CoverAlgebra s) := by
    funext i
    fin_cases i <;> simp [branchDifferentialVectors]
  rw [heq]
  exact (Basis.finTwoProd (CoverAlgebra s)).linearIndependent

/-- Every original differential is generated by dt and the image of
the second base vector. -/
theorem branchDifferentialVectors_span (s : R)
    (b : Basis (Fin 2) R (KaehlerDifferential k R))
    (hb : b 0 = KaehlerDifferential.D k R s) :
    Submodule.span (CoverAlgebra s) (Set.range (branchDifferentialVectors k R s b)) = ⊤ := by
  let P := Submodule.span (CoverAlgebra s) (Set.range (branchDifferentialVectors k R s b))
  have ht : KaehlerDifferential.D k (CoverAlgebra s) (root s) ∈ P :=
    Submodule.subset_span ⟨0, rfl⟩
  have heta : KaehlerDifferential.map k k R (CoverAlgebra s) (b 1) ∈ P :=
    Submodule.subset_span ⟨1, rfl⟩
  have hds : KaehlerDifferential.map k k R (CoverAlgebra s)
      (KaehlerDifferential.D k R s) =
      (2 * root s) • KaehlerDifferential.D k (CoverAlgebra s) (root s) := by
    rw [KaehlerDifferential.map_D]
    exact absoluteDifferential_branch k R s
  have hmap : ∀ omega : KaehlerDifferential k R,
      KaehlerDifferential.map k k R (CoverAlgebra s) omega ∈ P := by
    intro omega
    have hw := b.sum_repr omega
    rw [Fin.sum_univ_two, hb] at hw
    rw [← hw, map_add, map_smul, map_smul, hds]
    exact P.add_mem
      ((P.restrictScalars R).smul_mem _ (P.smul_mem _ ht))
      ((P.restrictScalars R).smul_mem _ heta)
  have hD : ∀ x : CoverAlgebra s, KaehlerDifferential.D k (CoverAlgebra s) x ∈ P := by
    intro x
    obtain ⟨a, c, rfl⟩ : ∃ a c, ofCoeffs s a c = x :=
      ⟨constantCoeff s x, rootCoeff s x, ofCoeffs_coefficients s x⟩
    rw [ofCoeffs, map_add, Derivation.leibniz,
      ← KaehlerDifferential.map_D k k R (CoverAlgebra s) a,
      ← KaehlerDifferential.map_D k k R (CoverAlgebra s) c]
    exact P.add_mem (hmap _) (P.add_mem (P.smul_mem _ ht) (P.smul_mem _ (hmap _)))
  apply top_unique
  rw [← KaehlerDifferential.span_range_derivation k (CoverAlgebra s)]
  apply Submodule.span_le.mpr
  rintro _ ⟨x, rfl⟩
  exact hD x

/-- The actual absolute basis is constructed, rather than included as
an extra assumption on the original cover. -/
def branchDifferentialBasis (s : R)
    (b : Basis (Fin 2) R (KaehlerDifferential k R))
    (hb : b 0 = KaehlerDifferential.D k R s) :
    Basis (Fin 2) (CoverAlgebra s) (KaehlerDifferential k (CoverAlgebra s)) :=
  Basis.mk (branchDifferentialVectors_linearIndependent k R s b hb)
    (by rw [branchDifferentialVectors_span k R s b hb])

theorem branchDifferentialBasis_apply (s : R)
    (b : Basis (Fin 2) R (KaehlerDifferential k R))
    (hb : b 0 = KaehlerDifferential.D k R s) (i : Fin 2) :
    branchDifferentialBasis k R s b hb i = branchDifferentialVectors k R s b i := by
  simp only [branchDifferentialBasis, Basis.coe_mk]

@[simp]
theorem branchDifferentialBasis_zero (s : R)
    (b : Basis (Fin 2) R (KaehlerDifferential k R))
    (hb : b 0 = KaehlerDifferential.D k R s) :
    branchDifferentialBasis k R s b hb 0 =
      KaehlerDifferential.D k (CoverAlgebra s) (root s) := by
  rw [branchDifferentialBasis_apply]
  rfl

@[simp]
theorem branchDifferentialBasis_one (s : R)
    (b : Basis (Fin 2) R (KaehlerDifferential k R))
    (hb : b 0 = KaehlerDifferential.D k R s) :
    branchDifferentialBasis k R s b hb 1 =
      KaehlerDifferential.map k k R (CoverAlgebra s) (b 1) := by
  rw [branchDifferentialBasis_apply]
  rfl

end KltDP.Geometry.QuadraticCover

#check @KltDP.Geometry.QuadraticCover.branchDifferentialBasis
#print axioms KltDP.Geometry.QuadraticCover.branchDifferentialBasis
