import KltDP.Geometry.QuadraticCoverAlgebra
import Mathlib.RingTheory.Ideal.Quotient.Operations

/-!
# Killing the actual quadratic root

The quotient of `R[t]/(t²-s)` by the ideal generated by `t` is the actual
base quotient `R/(s)`. The forward map evaluates the root at zero. The
inverse is induced by the original base-algebra map, since `t²=s` forces
`s` to vanish in the root quotient. The two universal maps are proved
inverse using the quotient and adjoined-root extensionality lemmas.

Reuse: pinned `Ideal.Quotient.liftₐ`, `Ideal.Quotient.algHom_ext`,
`AdjoinRoot.liftHom`, and `AdjoinRoot.algHom_ext` provide the construction.
The pinned `Polynomial.quotientSpanCXSubCAlgEquiv` is the related
polynomial evaluation quotient theorem. These APIs and the corresponding
AdjoinRoot quotient constructions were also inspected in official Mathlib
revision `80cbd0498ab39e21d24d6730b3f932cec672a702`,
`Mathlib/RingTheory/Polynomial/Quotient.lean` and
`Mathlib/RingTheory/AdjoinRoot.lean` (Apache 2.0, Lean 4.34.0-rc2).
No newer API is ported: the adapter below proves the required quadratic
relation directly with pinned universal maps.

There is no assumption of monicity, invertibility of two, nontriviality,
or nonvanishing of the branch coefficient.
-/

noncomputable section

open Polynomial

namespace KltDP.Geometry.QuadraticCover

variable {R : Type*} [CommRing R]

/-- The actual principal ideal of the branch coefficient in the base ring. -/
def branchIdeal (s : R) : Ideal R := Ideal.span {s}

/-- The actual principal ideal of the generator in the quadratic quotient. -/
def rootIdeal (s : R) : Ideal (CoverAlgebra s) := Ideal.span {root s}

@[simp]
theorem branchQuotient_mk_self (s : R) : Ideal.Quotient.mk (branchIdeal s) s = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Set.mem_singleton s)

@[simp]
theorem rootQuotient_mk_root (s : R) : Ideal.Quotient.mk (rootIdeal s) (root s) = 0 := by
  apply Ideal.Quotient.eq_zero_iff_mem.mpr
  exact Ideal.subset_span (Set.mem_singleton (root s))

/-- The original branch scalar vanishes after killing the actual root. -/
theorem rootQuotient_algebraMap_self (s : R) :
    algebraMap R (CoverAlgebra s ⧸ rootIdeal s) s = 0 := by
  change Ideal.Quotient.mk (rootIdeal s) (algebraMap R (CoverAlgebra s) s) = 0
  rw [← root_sq, map_pow, rootQuotient_mk_root, zero_pow (by decide : (2 : ℕ) ≠ 0)]

/-- Evaluation at zero in the actual quotient by the branch coefficient. -/
def rootToBranchHom (s : R) : CoverAlgebra s →ₐ[R] (R ⧸ branchIdeal s) :=
  AdjoinRoot.liftHom (polynomial s) 0 (by
    simp only [polynomial, map_sub, map_pow, aeval_X, aeval_C,
      Ideal.Quotient.algebraMap_eq, branchQuotient_mk_self,
      zero_pow (by decide : (2 : ℕ) ≠ 0), sub_self])

@[simp]
theorem rootToBranchHom_root (s : R) : rootToBranchHom s (root s) = 0 := by
  simp only [rootToBranchHom, root, AdjoinRoot.liftHom_root]

/-- The forward map descends through the actual root ideal. -/
def rootQuotientHom (s : R) :
    (CoverAlgebra s ⧸ rootIdeal s) →ₐ[R] (R ⧸ branchIdeal s) :=
  Ideal.Quotient.liftₐ (rootIdeal s) (rootToBranchHom s) (by
    intro x hx
    obtain ⟨y, rfl⟩ := Ideal.mem_span_singleton.mp hx
    rw [map_mul, rootToBranchHom_root, zero_mul])

@[simp]
theorem rootQuotientHom_mk (s : R) (x : CoverAlgebra s) :
    rootQuotientHom s (Ideal.Quotient.mk (rootIdeal s) x) = rootToBranchHom s x := rfl

/-- The inverse is induced by the original scalar map into the root quotient. -/
def branchQuotientHom (s : R) :
    (R ⧸ branchIdeal s) →ₐ[R] (CoverAlgebra s ⧸ rootIdeal s) :=
  Ideal.Quotient.liftₐ (branchIdeal s)
    (Algebra.ofId R (CoverAlgebra s ⧸ rootIdeal s)) (by
      intro a ha
      obtain ⟨b, rfl⟩ := Ideal.mem_span_singleton.mp ha
      simp only [Algebra.ofId_apply, map_mul, rootQuotient_algebraMap_self, zero_mul])

@[simp]
theorem branchQuotientHom_mk (s a : R) :
    branchQuotientHom s (Ideal.Quotient.mk (branchIdeal s) a) =
      Ideal.Quotient.mk (rootIdeal s) (algebraMap R (CoverAlgebra s) a) := rfl

theorem rootQuotientHom_comp_branchQuotientHom (s : R) :
    (rootQuotientHom s).comp (branchQuotientHom s) = AlgHom.id R (R ⧸ branchIdeal s) := by
  apply Ideal.Quotient.algHom_ext R
  exact Subsingleton.elim _ _

theorem branchQuotientHom_comp_rootQuotientHom (s : R) :
    (branchQuotientHom s).comp (rootQuotientHom s) =
      AlgHom.id R (CoverAlgebra s ⧸ rootIdeal s) := by
  apply Ideal.Quotient.algHom_ext R
  apply AdjoinRoot.algHom_ext
  change branchQuotientHom s (rootQuotientHom s
    (Ideal.Quotient.mk (rootIdeal s) (root s))) =
      Ideal.Quotient.mk (rootIdeal s) (root s)
  rw [rootQuotientHom_mk, rootToBranchHom_root, map_zero, rootQuotient_mk_root]

/-- Killing the root of the actual quadratic quotient gives exactly the branch quotient. -/
def rootQuotientEquiv (s : R) :
    (CoverAlgebra s ⧸ rootIdeal s) ≃ₐ[R] (R ⧸ branchIdeal s) :=
  AlgEquiv.ofAlgHom (rootQuotientHom s) (branchQuotientHom s)
    (rootQuotientHom_comp_branchQuotientHom s) (branchQuotientHom_comp_rootQuotientHom s)

@[simp]
theorem rootQuotientEquiv_mk (s : R) (x : CoverAlgebra s) :
    rootQuotientEquiv s (Ideal.Quotient.mk (rootIdeal s) x) = rootToBranchHom s x := rfl

/-- The equivalence preserves the original base scalar quotient map. -/
@[simp]
theorem rootQuotientEquiv_mk_algebraMap (s a : R) :
    rootQuotientEquiv s
      (Ideal.Quotient.mk (rootIdeal s) (algebraMap R (CoverAlgebra s) a)) =
        Ideal.Quotient.mk (branchIdeal s) a := by
  rw [rootQuotientEquiv_mk]
  exact (rootToBranchHom s).commutes a

/-- The inverse sends a base class to its original scalar class in the root quotient. -/
@[simp]
theorem rootQuotientEquiv_symm_mk (s a : R) :
    (rootQuotientEquiv s).symm (Ideal.Quotient.mk (branchIdeal s) a) =
      Ideal.Quotient.mk (rootIdeal s) (algebraMap R (CoverAlgebra s) a) := rfl

/-- On a polynomial representative the equivalence is literal evaluation at zero. -/
theorem rootQuotientEquiv_mk_polynomial (s : R) (p : Polynomial R) :
    rootQuotientEquiv s
      (Ideal.Quotient.mk (rootIdeal s) (AdjoinRoot.mk (polynomial s) p)) =
        Polynomial.aeval (0 : R ⧸ branchIdeal s) p := by
  rw [rootQuotientEquiv_mk]
  simp only [rootToBranchHom, AdjoinRoot.liftHom_mk]

end KltDP.Geometry.QuadraticCover
