import KltDP.Geometry.AffineBlowup
import Mathlib.Algebra.Polynomial.Eval.Defs

/-!
# Actual Rees charts inside an ordinary localization

The chart at `aT` of the existing polynomial Rees algebra maps canonically
to `R[1/a]`: evaluate at `T = 1`, extend across the ordinary localization,
and restrict to its homogeneous degree-zero part. The map is injective;
its image is the subalgebra generated by the actual fractions `b/a`, `b ∈ I`.

All constructions use the existing `AffineBlowup.chartRing`. No domain or
nonzerodivisor hypothesis on `R` or `a` is imposed. In particular, the proof
does not assert that evaluation is injective on the entire Rees algebra.
The chart's nilpotent-denominator case is covered by the pinned homogeneous
fraction and localization APIs.

Reuse: Mathlib c44e0c8ee63ca166450922a373c7409c5d26b00b,
`Polynomial.eval₂RingHom`, `Localization.awayLift`, homogeneous fraction
representatives, and localization's zero criterion. No external source
theorem or literature axiom is introduced.
-/

noncomputable section

open Polynomial

namespace KltDP.Geometry.AffineBlowup

variable {R : Type*} [CommRing R] (I : Ideal R) (a : I)

/-- The actual base-ring map used by the Rees chart's structure morphism. -/
def chartBaseMap : R →+* chartRing I a :=
  (HomogeneousLocalization.fromZeroRingHom (ReesGrading.component I)
    (Submonoid.powers (degreeOne I a))).comp
      (algebraMap R (ReesGrading.component I 0))

/-- The canonical `R`-algebra structure on the actual Rees chart. -/
instance chartAlgebra : Algebra R (chartRing I a) :=
  (chartBaseMap I a).toAlgebra

@[simp]
theorem chartAlgebra_algebraMap :
    algebraMap R (chartRing I a) = chartBaseMap I a := rfl

/-- Evaluation of the polynomial Rees carrier at one, with values in `R[1/a]`. -/
def reesEvaluation : reesAlgebra I →+* Localization.Away (a : R) :=
  (Polynomial.eval₂RingHom (algebraMap R (Localization.Away (a : R))) 1).comp
    (reesAlgebra I).val.toRingHom

@[simp]
theorem reesEvaluation_single (n : ℕ) (r : ↥(I ^ n)) :
    reesEvaluation I a (ReesGrading.single I n r) =
      algebraMap R (Localization.Away (a : R)) (r : R) := by
  change (monomial n (r : R)).eval₂
    (algebraMap R (Localization.Away (a : R))) 1 = _
  simp only [Polynomial.eval₂_monomial, one_pow, mul_one]

@[simp]
theorem reesEvaluation_degreeOne :
    reesEvaluation I a (degreeOne I a) =
      algebraMap R (Localization.Away (a : R)) (a : R) :=
  reesEvaluation_single I a 1 _

@[simp]
theorem reesEvaluation_algebraMap (r : R) :
    reesEvaluation I a (algebraMap R (reesAlgebra I) r) =
      algebraMap R (Localization.Away (a : R)) r := by
  change (Polynomial.C r).eval₂
    (algebraMap R (Localization.Away (a : R))) 1 = _
  exact Polynomial.eval₂_C _ _

private theorem reesEvaluation_mul_invSelf :
    reesEvaluation I a (degreeOne I a) *
      IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) = 1 := by
  rw [reesEvaluation_degreeOne]
  exact IsLocalization.Away.mul_invSelf (a : R)

/-- Extension of evaluation to the ordinary localization of the Rees ring at `aT`. -/
def localizedReesEvaluation :
    Localization.Away (degreeOne I a) →+* Localization.Away (a : R) :=
  Localization.awayLift (reesEvaluation I a) (degreeOne I a)
    (isUnit_iff_exists_inv.mpr
      ⟨IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R),
        reesEvaluation_mul_invSelf I a⟩)

/-- The canonical ring map from the degree-zero chart to `R[1/a]`. -/
def chartToLocalization : chartRing I a →+* Localization.Away (a : R) :=
  (localizedReesEvaluation I a).comp
    (algebraMap (chartRing I a) (Localization.Away (degreeOne I a)))

@[simp]
theorem chartToLocalization_baseMap (r : R) :
    chartToLocalization I a (chartBaseMap I a r) =
      algebraMap R (Localization.Away (a : R)) r := by
  change localizedReesEvaluation I a
    (algebraMap (reesAlgebra I) (Localization.Away (degreeOne I a))
      (algebraMap R (reesAlgebra I) r)) = _
  rw [localizedReesEvaluation, IsLocalization.Away.lift_eq,
    reesEvaluation_algebraMap]

/-- The same canonical map with its proved base-ring compatibility. -/
def chartToLocalizationAlgHom :
    chartRing I a →ₐ[R] Localization.Away (a : R) where
  toRingHom := chartToLocalization I a
  commutes' := chartToLocalization_baseMap I a

@[simp]
theorem chartToLocalizationAlgHom_apply (x : chartRing I a) :
    chartToLocalizationAlgHom I a x = chartToLocalization I a x := rfl

/-- The homogeneous fraction `(rT^n)/(aT)^n`, with its actual numerator in `I^n`. -/
def chartMonomialFraction (n : ℕ) (r : ↥(I ^ n)) : chartRing I a :=
  HomogeneousLocalization.Away.mk (ReesGrading.component I) (degreeOne_mem I a)
    n (ReesGrading.single I n r) (by
      simpa using ReesGrading.single_mem_component I n r)

/-- Every actual chart element has a homogeneous monomial-fraction representative. -/
theorem exists_chartMonomialFraction (x : chartRing I a) :
    ∃ (n : ℕ) (r : ↥(I ^ n)), chartMonomialFraction I a n r = x := by
  obtain ⟨n, s, hs, hx⟩ := HomogeneousLocalization.Away.mk_surjective
    (ReesGrading.component I) (degreeOne_mem I a) x
  have hs' : s ∈ ReesGrading.component I n := by simpa using hs
  obtain ⟨r, hr⟩ := hs'
  refine ⟨n, r, ?_⟩
  simpa only [chartMonomialFraction, hr] using hx

/-- Evaluation sends the actual homogeneous fraction to `r/a^n`. -/
@[simp]
theorem chartToLocalization_monomialFraction (n : ℕ) (r : ↥(I ^ n)) :
    chartToLocalization I a (chartMonomialFraction I a n r) =
      algebraMap R (Localization.Away (a : R)) (r : R) *
        IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^ n := by
  change localizedReesEvaluation I a
    (Localization.mk (ReesGrading.single I n r) ⟨degreeOne I a ^ n, n, rfl⟩) = _
  have h := Localization.awayLift_mk
    (R := reesAlgebra I) (A := Localization.Away (a : R))
    (reesEvaluation I a) (degreeOne I a) (ReesGrading.single I n r)
    (IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R))
    (reesEvaluation_mul_invSelf I a) n
  simpa only [localizedReesEvaluation, reesEvaluation_single] using h

/-- The actual degree-one fraction `b/a` in the Rees chart. -/
def chartFraction (b : I) : chartRing I a :=
  chartMonomialFraction I a 1 ⟨(b : R), by simpa using b.property⟩

@[simp]
theorem chartToLocalization_fraction (b : I) :
    chartToLocalization I a (chartFraction I a b) =
      algebraMap R (Localization.Away (a : R)) (b : R) *
        IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) := by
  simp only [chartFraction, chartToLocalization_monomialFraction, pow_one]

/-- The precise image as homogeneous fractions with numerators in ideal powers. -/
theorem mem_range_chartToLocalization_iff (z : Localization.Away (a : R)) :
    z ∈ Set.range (chartToLocalization I a) ↔
      ∃ (n : ℕ) (r : ↥(I ^ n)),
        algebraMap R (Localization.Away (a : R)) (r : R) *
          IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^ n = z := by
  constructor
  · rintro ⟨x, rfl⟩
    obtain ⟨n, r, rfl⟩ := exists_chartMonomialFraction I a x
    exact ⟨n, r, (chartToLocalization_monomialFraction I a n r).symm⟩
  · rintro ⟨n, r, hr⟩
    exact ⟨chartMonomialFraction I a n r,
      (chartToLocalization_monomialFraction I a n r).trans hr⟩

/-- Only the degree-zero localized chart is asserted to embed into `R[1/a]`. -/
theorem chartToLocalization_injective : Function.Injective (chartToLocalization I a) := by
  apply (injective_iff_map_eq_zero (chartToLocalization I a)).mpr
  intro x hx
  obtain ⟨n, r, rfl⟩ := exists_chartMonomialFraction I a x
  rw [chartToLocalization_monomialFraction] at hx
  have hcancel :
      IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^ n *
        algebraMap R (Localization.Away (a : R)) (a : R) ^ n = 1 := by
    rw [← mul_pow, mul_comm, IsLocalization.Away.mul_invSelf, one_pow]
  have hrzero : algebraMap R (Localization.Away (a : R)) (r : R) = 0 := by
    calc
      _ = (algebraMap R (Localization.Away (a : R)) (r : R) *
          IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^ n) *
            algebraMap R (Localization.Away (a : R)) (a : R) ^ n := by
        rw [mul_assoc, hcancel, mul_one]
      _ = 0 := by rw [hx, zero_mul]
  obtain ⟨⟨_, m, rfl⟩, hm⟩ :=
    (IsLocalization.map_eq_zero_iff (Submonoid.powers (a : R))
      (Localization.Away (a : R)) (r : R)).mp hrzero
  have hmul : degreeOne I a ^ m * ReesGrading.single I n r = 0 := by
    apply Subtype.ext
    change (monomial 1 (a : R)) ^ m * monomial n (r : R) = 0
    rw [Polynomial.monomial_pow, Polynomial.monomial_mul_monomial, hm]
    exact map_zero (monomial _)
  apply HomogeneousLocalization.val_injective (x := Submonoid.powers (degreeOne I a))
  simp only [chartMonomialFraction, HomogeneousLocalization.Away.val_mk,
    HomogeneousLocalization.val_zero, Localization.mk_eq_mk']
  exact (IsLocalization.mk'_eq_zero_iff
    (M := Submonoid.powers (degreeOne I a))
    (S := Localization.Away (degreeOne I a)) _ _).mpr
      ⟨⟨degreeOne I a ^ m, m, rfl⟩, hmul⟩

/-- The chart fractions satisfy the actual equation `a * (b/a) = b`. -/
theorem chartBaseMap_mul_chartFraction (b : I) :
    chartBaseMap I a (a : R) * chartFraction I a b = chartBaseMap I a (b : R) := by
  apply chartToLocalization_injective I a
  rw [map_mul, chartToLocalization_baseMap, chartToLocalization_fraction,
    chartToLocalization_baseMap]
  calc
    _ = algebraMap R (Localization.Away (a : R)) (b : R) *
        (algebraMap R (Localization.Away (a : R)) (a : R) *
          IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R)) := by ring
    _ = _ := by rw [IsLocalization.Away.mul_invSelf, mul_one]

@[simp]
theorem chartFraction_self : chartFraction I a a = 1 := by
  apply chartToLocalization_injective I a
  rw [chartToLocalization_fraction, map_one, IsLocalization.Away.mul_invSelf]

/-- The actual affine blowup algebra as a subalgebra of `R[1/a]`. -/
def affineBlowupSubalgebra : Subalgebra R (Localization.Away (a : R)) :=
  Algebra.adjoin R (Set.range fun b : I =>
    algebraMap R (Localization.Away (a : R)) (b : R) *
      IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R))

/-- Numerators in `I^n` give elements of the subalgebra generated by `I/a`. -/
theorem idealPowerFraction_mem_affineBlowupSubalgebra (n : ℕ) {r : R} (hr : r ∈ I ^ n) :
    algebraMap R (Localization.Away (a : R)) r *
      IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^ n ∈
        affineBlowupSubalgebra I a := by
  induction n generalizing r with
  | zero =>
      simpa only [pow_zero, mul_one] using
        (affineBlowupSubalgebra I a).algebraMap_mem r
  | succ n ih =>
      rw [pow_succ'] at hr
      apply Submodule.smul_induction_on
        (p := fun r => algebraMap R (Localization.Away (a : R)) r *
          IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ^
            (n + 1) ∈ affineBlowupSubalgebra I a) hr
      · intro b hb c hc
        have hb' : algebraMap R (Localization.Away (a : R)) b *
            IsLocalization.Away.invSelf (S := Localization.Away (a : R)) (a : R) ∈
              affineBlowupSubalgebra I a :=
          Algebra.subset_adjoin (R := R) ⟨⟨b, hb⟩, rfl⟩
        convert (affineBlowupSubalgebra I a).mul_mem hb' (ih hc) using 1 <;>
          simp only [smul_eq_mul, map_mul, pow_succ] <;> ring
      · intro b c hb hc
        simpa only [map_add, add_mul] using
          (affineBlowupSubalgebra I a).add_mem hb hc

/-- The map's image is exactly the subalgebra generated by the actual `b/a` fractions. -/
theorem range_chartToLocalizationAlgHom :
    (chartToLocalizationAlgHom I a).range = affineBlowupSubalgebra I a := by
  apply le_antisymm
  · rintro z ⟨x, rfl⟩
    obtain ⟨n, r, rfl⟩ := exists_chartMonomialFraction I a x
    change chartToLocalization I a (chartMonomialFraction I a n r) ∈
      affineBlowupSubalgebra I a
    rw [chartToLocalization_monomialFraction]
    exact idealPowerFraction_mem_affineBlowupSubalgebra I a n r.property
  · apply Algebra.adjoin_le (R := R) (A := Localization.Away (a : R))
      (S := (chartToLocalizationAlgHom I a).range)
    rintro z ⟨b, rfl⟩
    exact ⟨chartFraction I a b, chartToLocalization_fraction I a b⟩

/-- Each element of the actual affine blowup subalgebra has a chart preimage. -/
theorem exists_chartToLocalization_eq (z : affineBlowupSubalgebra I a) :
    ∃ x : chartRing I a, chartToLocalization I a x = (z : Localization.Away (a : R)) := by
  have hz : (z : Localization.Away (a : R)) ∈ (chartToLocalizationAlgHom I a).range :=
    (range_chartToLocalizationAlgHom I a).ge z.property
  exact hz

/-- Restriction of the canonical map to its proved image, the actual algebra `R[I/a]`. -/
def chartToAffineBlowupSubalgebra : chartRing I a →ₐ[R] affineBlowupSubalgebra I a :=
  (chartToLocalizationAlgHom I a).codRestrict (affineBlowupSubalgebra I a) (fun x => by
    rw [← range_chartToLocalizationAlgHom I a]
    exact (chartToLocalizationAlgHom I a).mem_range_self x)

@[simp]
theorem chartToAffineBlowupSubalgebra_coe (x : chartRing I a) :
    (chartToAffineBlowupSubalgebra I a x : Localization.Away (a : R)) =
      chartToLocalization I a x := rfl

/-- Bijectivity is proved from the canonical map and its image description. -/
theorem chartToAffineBlowupSubalgebra_bijective :
    Function.Bijective (chartToAffineBlowupSubalgebra I a) := by
  constructor
  · intro x y h
    apply chartToLocalization_injective I a
    exact congrArg Subtype.val h
  · intro z
    obtain ⟨x, hx⟩ := exists_chartToLocalization_eq I a z
    exact ⟨x, Subtype.ext hx⟩

/-- The actual Rees chart is canonically isomorphic, over `R`, to `R[I/a]`. -/
def chartAffineBlowupAlgEquiv : chartRing I a ≃ₐ[R] affineBlowupSubalgebra I a :=
  AlgEquiv.ofBijective (chartToAffineBlowupSubalgebra I a)
    (chartToAffineBlowupSubalgebra_bijective I a)

@[simp]
theorem chartAffineBlowupAlgEquiv_coe (x : chartRing I a) :
    (chartAffineBlowupAlgEquiv I a x : Localization.Away (a : R)) =
      chartToLocalization I a x := rfl

end KltDP.Geometry.AffineBlowup
