import KltDP.Geometry.AffineBlowupLift
import KltDP.Geometry.AffineBlowupChartCenter

/-!
# Unit rescaling of the original Rees chart

The original chart universal property constructs both maps between charts at
unit-associated generators. Chart uniqueness proves that they are inverse.
The resulting equivalence fixes the original base map and has explicit
formulas on the original homogeneous fractions in both directions.
-/

noncomputable section

namespace KltDP.Geometry.AffineBlowup

variable {R : Type*} [CommRing R]

/-- A unit-associated chart equation is regular in the original target chart. -/
theorem chartUnitMultiple_regular (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) :
    chartBaseMap I b (a : R) ∈ nonZeroDivisors (chartRing I b) := by
  have hreg := chartBaseMap_equation_mem_nonZeroDivisors I b
  rw [h, map_mul] at hreg
  exact (mul_mem_nonZeroDivisors.mp hreg).2

/-- The original target center is generated by the unit-associated equation. -/
theorem chartUnitMultiple_center (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) :
    Ideal.map (chartBaseMap I b) I ≤ Ideal.span {chartBaseMap I b (a : R)} := by
  rw [map_chartBaseMap_ideal]
  apply (Ideal.span_singleton_le_iff_mem _).mpr
  apply Ideal.mem_span_singleton.mpr
  refine ⟨chartBaseMap I b (u : R), ?_⟩
  rw [h, map_mul, mul_comm]

/-- The actual Rees-chart map obtained from the existing chart lift. -/
def chartUnitMultipleMap (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) : chartRing I a →+* chartRing I b :=
  chartLift I a (chartBaseMap I b)
    (chartUnitMultiple_regular I a b u h) (chartUnitMultiple_center I a b u h)

@[simp] theorem chartUnitMultipleMap_baseMap (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) (r : R) :
    chartUnitMultipleMap I a b u h (chartBaseMap I a r) = chartBaseMap I b r :=
  chartLift_baseMap I a (chartBaseMap I b)
    (chartUnitMultiple_regular I a b u h) (chartUnitMultiple_center I a b u h) r

private theorem chartBaseMap_endomorphism_eq_id (I : Ideal R) (a : I)
    (F : chartRing I a →+* chartRing I a)
    (hF : F.comp (chartBaseMap I a) = chartBaseMap I a) :
    F = RingHom.id (chartRing I a) :=
  (chartLift_unique I a (chartBaseMap I a)
    (chartBaseMap_equation_mem_nonZeroDivisors I a) (map_chartBaseMap_ideal I a).le
    F hF).trans
  (chartLift_unique I a (chartBaseMap I a)
    (chartBaseMap_equation_mem_nonZeroDivisors I a) (map_chartBaseMap_ideal I a).le
    (RingHom.id _) (RingHom.id_comp _)).symm

/-- Canonical equivalence of the original charts at unit-associated elements. -/
def chartUnitMultipleEquiv (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) : chartRing I a ≃+* chartRing I b :=
  let hinv : (a : R) = (↑u⁻¹ : R) * (b : R) := by
    rw [h, Units.inv_mul_cancel_left]
  let f := chartUnitMultipleMap I a b u h
  let g := chartUnitMultipleMap I b a u⁻¹ hinv
  { __ := f
    invFun := g
    left_inv x := by
      have hc : (g.comp f).comp (chartBaseMap I a) = chartBaseMap I a := by
        ext r
        simp only [RingHom.comp_apply, f, g, chartUnitMultipleMap_baseMap]
      exact RingHom.congr_fun (chartBaseMap_endomorphism_eq_id I a (g.comp f) hc) x
    right_inv x := by
      have hc : (f.comp g).comp (chartBaseMap I b) = chartBaseMap I b := by
        ext r
        simp only [RingHom.comp_apply, f, g, chartUnitMultipleMap_baseMap]
      exact RingHom.congr_fun (chartBaseMap_endomorphism_eq_id I b (f.comp g) hc) x }

@[simp] theorem chartUnitMultipleEquiv_baseMap (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) (r : R) :
    chartUnitMultipleEquiv I a b u h (chartBaseMap I a r) = chartBaseMap I b r :=
  chartUnitMultipleMap_baseMap I a b u h r

@[simp] theorem chartUnitMultipleEquiv_symm_baseMap
    (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) (r : R) :
    (chartUnitMultipleEquiv I a b u h).symm (chartBaseMap I b r) =
      chartBaseMap I a r := by
  apply (chartUnitMultipleEquiv I a b u h).injective
  rw [RingEquiv.apply_symm_apply, chartUnitMultipleEquiv_baseMap]

/-- In the forward direction the original fraction is multiplied by the unit. -/
theorem chartUnitMultipleEquiv_fraction (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) (c : I) :
    chartUnitMultipleEquiv I a b u h (chartFraction I a c) =
      chartBaseMap I b (u : R) * chartFraction I b c := by
  apply (mul_cancel_left_mem_nonZeroDivisors (chartUnitMultiple_regular I a b u h)).mp
  have hc := congrArg (chartUnitMultipleEquiv I a b u h)
    (chartBaseMap_mul_chartFraction I a c)
  simp only [map_mul, chartUnitMultipleEquiv_baseMap] at hc
  calc
    chartBaseMap I b (a : R) *
        chartUnitMultipleEquiv I a b u h (chartFraction I a c) =
        chartBaseMap I b (c : R) := hc
    _ = chartBaseMap I b (a : R) *
        (chartBaseMap I b (u : R) * chartFraction I b c) := by
      rw [← mul_assoc, ← map_mul, mul_comm (a : R) (u : R), ← h,
        chartBaseMap_mul_chartFraction]

/-- The inverse sends the original rescaled fraction to the inverse-unit multiple. -/
theorem chartUnitMultipleEquiv_symm_fraction (I : Ideal R) (a b : I) (u : Rˣ)
    (h : (b : R) = (u : R) * (a : R)) (c : I) :
    (chartUnitMultipleEquiv I a b u h).symm (chartFraction I b c) =
      chartBaseMap I a (↑u⁻¹ : R) * chartFraction I a c := by
  apply (chartUnitMultipleEquiv I a b u h).injective
  rw [RingEquiv.apply_symm_apply, map_mul, chartUnitMultipleEquiv_baseMap,
    chartUnitMultipleEquiv_fraction, ← mul_assoc, ← map_mul, Units.inv_mul,
    map_one, one_mul]

end KltDP.Geometry.AffineBlowup

#check @KltDP.Geometry.AffineBlowup.chartUnitMultipleEquiv
#check @KltDP.Geometry.AffineBlowup.chartUnitMultipleEquiv_fraction
#check @KltDP.Geometry.AffineBlowup.chartUnitMultipleEquiv_symm_fraction
#print axioms KltDP.Geometry.AffineBlowup.chartUnitMultipleEquiv
#print axioms KltDP.Geometry.AffineBlowup.chartUnitMultipleEquiv_fraction
#print axioms KltDP.Geometry.AffineBlowup.chartUnitMultipleEquiv_symm_fraction
