import KltDP.Geometry.PrincipalQuotientParameters
import KltDP.Geometry.RegularLocalFactorialSupport
import KltDP.Geometry.RegularLocalUFD
import Mathlib.LinearAlgebra.LinearIndependent.Lemmas

/-!
# The regular-pair conditions for actual surface parameters

Two generators of the maximal ideal in an actual regular local surface
ring have independent cotangent classes. The existing factoriality
theorem makes the first parameter prime, so the second is regular in
its actual principal quotient. No regular-sequence premise is added.
-/

noncomputable section

namespace KltDP.Geometry.RegularLocalTwoParameters

open IsLocalRing

universe u

variable {R : Type u} [CommRing R] [IsLocalRing R]

/-- The second member of the actual parameter pair does not belong to
the principal ideal generated by the first. -/
theorem second_not_mem_first (hR : RegularLocal R) (hdim : ringKrullDim R = 2)
    (f g : R) (hspan : Ideal.span {f, g} = maximalIdeal R) :
    g ∉ Ideal.span {f} := by
  have hf : f ∈ maximalIdeal R := by
    rw [← hspan]
    exact Ideal.subset_span (by simp)
  have hg : g ∈ maximalIdeal R := by
    rw [← hspan]
    exact Ideal.subset_span (by simp)
  let w : Fin 2 → maximalIdeal R := ![⟨g, hg⟩, ⟨f, hf⟩]
  have hind := RationalTreePicard.linearIndependent_toCotangent_of_span_pair_eq
    (RationalTreePicard.finrank_cotangentSpace_eq_two_of_regularLocal hR hdim) w
    (by
      change Ideal.span {g, f} = maximalIdeal R
      exact Ideal.span_pair_comm.trans hspan)
  intro hmem
  obtain ⟨r, hr⟩ := Ideal.mem_span_singleton'.mp hmem
  apply (linearIndependent_fin2.mp hind).2 (residue R r)
  change (algebraMap R (ResidueField R) r) •
      (maximalIdeal R).toCotangent (w 1) = (maximalIdeal R).toCotangent (w 0)
  rw [IsScalarTower.algebraMap_smul, ← (maximalIdeal R).toCotangent.map_smul]
  apply congrArg (maximalIdeal R).toCotangent
  exact Subtype.ext hr

/-- The original two-element maximal-ideal generating family on a
regular local surface satisfies precisely the two nonzerodivisor
conditions required by the proved original Rees-chart presentation. -/
theorem regular_pair (hR : RegularLocal R) (hdim : ringKrullDim R = 2)
    (f g : R) (hspan : Ideal.span {f, g} = maximalIdeal R) :
    f ∈ nonZeroDivisors R ∧
      Ideal.Quotient.mk (Ideal.span {f}) g ∈ nonZeroDivisors (R ⧸ Ideal.span {f}) := by
  obtain ⟨hDomain, hUFM⟩ := regularLocal_isDomain_and_uniqueFactorizationMonoid R hR
  letI : IsDomain R := hDomain
  letI : UniqueFactorizationMonoid R := hUFM
  have hf : f ∈ maximalIdeal R := by
    rw [← hspan]
    exact Ideal.subset_span (by simp)
  have hfsq := PrincipalQuotientParameters.first_not_mem_square hR hdim f g hspan
  have hprime : Prime f := UniqueFactorizationMonoid.irreducible_iff_prime.mp
    (RegularLocalFactorialSupport.irreducible_of_mem_maximal_not_mem_sq hf hfsq)
  letI : (Ideal.span {f}).IsPrime := (Ideal.span_singleton_prime hprime.ne_zero).mpr hprime
  refine ⟨mem_nonZeroDivisors_of_ne_zero hprime.ne_zero,
    mem_nonZeroDivisors_of_ne_zero ?_⟩
  intro hz
  exact second_not_mem_first hR hdim f g hspan (Ideal.Quotient.eq_zero_iff_mem.mp hz)

end KltDP.Geometry.RegularLocalTwoParameters
