/-
The cotangent-kernel argument is adapted from the proved helper portion of
UW auslander-buchsbaum, RegularLocalRing/Basic.lean (Nailin Guan, 2025),
released under the Apache 2.0 license. Exact source and changes are recorded
in docs/REGULAR_LOCAL_PARAMETER_QUOTIENT.md.
-/

import KltDP.Geometry.RegularLocalEquiv
import Mathlib.GroupTheory.QuotientGroup.Basic
import Mathlib.LinearAlgebra.Dimension.RankNullity
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.Tactic

/-!
# Cotangent dimension of a quotient by a parameter

The actual map between cotangent spaces is semilinear over the actual map on
residue fields. For a surjective local ring map with kernel generated by a
parameter, its cotangent kernel is the line generated by the parameter's
cotangent class. Rank-nullity therefore gives an exact drop of one in
cotangent dimension when that class is nonzero.

This isolates the linear-algebra part of the proved UW quotient-regularity
argument. It does not assert the missing lower bound on quotient Krull
dimension or assume that the parameter is prime. The final specialization
uses the project's actual `RegularLocal` predicate.
-/

noncomputable section

universe u

namespace KltDP.Geometry.RegularLocalParameterQuotient

open IsLocalRing

variable {R S : Type u} [CommRing R] [CommRing S]
variable [IsLocalRing R] [IsLocalRing S]

/-- A surjective local ring map carries the actual maximal ideal onto the
actual maximal ideal. -/
theorem map_maximalIdeal_eq (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) :
    (maximalIdeal R).map f = maximalIdeal S := by
  have hc : (maximalIdeal S).comap f = maximalIdeal R :=
    by
      ext r
      change ¬ IsUnit (f r) ↔ ¬ IsUnit r
      exact not_congr (isUnit_map_iff f r)
  rw [← hc, Ideal.map_comap_of_surjective f hf]

/-- The residue-field map of a surjective local ring map is bijective. -/
theorem residueField_map_bijective (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) : Function.Bijective (ResidueField.map f) := by
  refine ⟨(ResidueField.map f).injective, ?_⟩
  intro c
  obtain ⟨s, rfl⟩ := residue_surjective c
  obtain ⟨r, rfl⟩ := hf s
  exact ⟨residue R r, rfl⟩

/-- Scalar compatibility uses the original residue-field actions on both
cotangent spaces. -/
theorem localCotangentMap_residue_smul (f : R →+* S) [IsLocalHom f]
    (c : ResidueField R) (v : CotangentSpace R) :
    localCotangentMap f (c • v) = ResidueField.map f c • localCotangentMap f v := by
  obtain ⟨r, rfl⟩ := residue_surjective c
  rw [ResidueField.map_residue]
  change localCotangentMap f ((algebraMap R (ResidueField R) r) • v) =
    (algebraMap S (ResidueField S) (f r)) • localCotangentMap f v
  rw [IsScalarTower.algebraMap_smul, IsScalarTower.algebraMap_smul]
  exact localCotangentMap_smul f r v

/-- The actual cotangent map, bundled over the actual residue-field map. -/
def cotangentSemilinearMap (f : R →+* S) [IsLocalHom f] :
    CotangentSpace R →ₛₗ[ResidueField.map f] CotangentSpace S where
  toFun := localCotangentMap f
  map_add' := (localCotangentMap f).map_add
  map_smul' := localCotangentMap_residue_smul f

/-- Surjectivity of a local ring map gives surjectivity on actual cotangent
spaces by lifting maximal-ideal representatives. -/
theorem cotangentSemilinearMap_surjective (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) : Function.Surjective (cotangentSemilinearMap f) := by
  intro v
  obtain ⟨b, rfl⟩ := (maximalIdeal S).toCotangent_surjective v
  obtain ⟨a, ha⟩ := hf (b : S)
  have ham : a ∈ maximalIdeal R := by
    change ¬ IsUnit a
    rw [← isUnit_map_iff f a, ha]
    exact b.property
  refine ⟨(maximalIdeal R).toCotangent ⟨a, ham⟩, ?_⟩
  change (maximalIdeal S).toCotangent ⟨f a, _⟩ = (maximalIdeal S).toCotangent b
  congr 1
  exact Subtype.ext ha

/-- Before passing to the cotangent quotient, its actual kernel is the sum
of the maximal-ideal square and the ring-map kernel. -/
theorem cotangent_map_zero_iff (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) (a : maximalIdeal R) :
    cotangentSemilinearMap f ((maximalIdeal R).toCotangent a) = 0 ↔
      (a : R) ∈ (maximalIdeal R) ^ 2 ⊔ RingHom.ker f := by
  change (maximalIdeal S).toCotangent ⟨f a, _⟩ = 0 ↔ _
  rw [Ideal.toCotangent_eq_zero]
  change f (a : R) ∈ (maximalIdeal S) ^ 2 ↔ _
  rw [← map_maximalIdeal_eq f hf, ← Ideal.map_pow]
  change (a : R) ∈ (((maximalIdeal R) ^ 2).map f).comap f ↔ _
  rw [Ideal.comap_map_of_surjective' f hf]

/-- When the actual ring-map kernel is generated by `x`, the actual
cotangent kernel is exactly the line generated by the class of `x`. -/
theorem cotangent_ker_eq_span_parameter (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) {x : R} (hx : x ∈ maximalIdeal R)
    (hker : RingHom.ker f = Ideal.span {x}) :
    LinearMap.ker (cotangentSemilinearMap f) =
      Submodule.span (ResidueField R) {(maximalIdeal R).toCotangent ⟨x, hx⟩} := by
  apply Submodule.ext
  intro v
  obtain ⟨a, rfl⟩ := (maximalIdeal R).toCotangent_surjective v
  rw [LinearMap.mem_ker]
  constructor
  · intro hv
    have hmem := (cotangent_map_zero_iff f hf a).mp hv
    rw [hker] at hmem
    obtain ⟨b, hb, c, hc, hbc⟩ := Submodule.mem_sup.mp hmem
    obtain ⟨r, rfl⟩ := Ideal.mem_span_singleton'.mp hc
    apply Submodule.mem_span_singleton.mpr
    refine ⟨residue R r, ?_⟩
    change (algebraMap R (ResidueField R) r) •
        (maximalIdeal R).toCotangent ⟨x, hx⟩ = (maximalIdeal R).toCotangent a
    rw [IsScalarTower.algebraMap_smul, ← (maximalIdeal R).toCotangent.map_smul]
    apply ((maximalIdeal R).toCotangent_eq).mpr
    change r * x - (a : R) ∈ (maximalIdeal R) ^ 2
    have heq : r * x - (a : R) = -b := by rw [← hbc]; abel
    rw [heq]
    exact ((maximalIdeal R) ^ 2).neg_mem hb
  · intro hv
    obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hv
    rw [← hc]
    rw [map_smulₛₗ]
    have hfx : f x = 0 := by
      apply RingHom.mem_ker.mp
      rw [hker]
      exact Ideal.mem_span_singleton_self x
    have hzero : cotangentSemilinearMap f ((maximalIdeal R).toCotangent ⟨x, hx⟩) = 0 := by
      change (maximalIdeal S).toCotangent ⟨f x, _⟩ = 0
      rw [Ideal.toCotangent_eq_zero]
      change f x ∈ (maximalIdeal S) ^ 2
      rw [hfx]
      exact Ideal.zero_mem _
    rw [hzero, smul_zero]

/-- The first isomorphism theorem on the underlying additive groups. The
quotient retains its source residue-field action. -/
def cotangentQuotientAddEquiv (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) :
    (CotangentSpace R ⧸ LinearMap.ker (cotangentSemilinearMap f)) ≃+
      CotangentSpace S :=
  QuotientAddGroup.quotientKerEquivOfSurjective
    (cotangentSemilinearMap f).toAddMonoidHom (cotangentSemilinearMap_surjective f hf)

/-- Scalar compatibility of the induced quotient equivalence. -/
theorem cotangentQuotientAddEquiv_smul (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) (c : ResidueField R)
    (v : CotangentSpace R ⧸ LinearMap.ker (cotangentSemilinearMap f)) :
    cotangentQuotientAddEquiv f hf (c • v) =
      ResidueField.map f c • cotangentQuotientAddEquiv f hf v := by
  obtain ⟨v, rfl⟩ := Submodule.mkQ_surjective (LinearMap.ker (cotangentSemilinearMap f)) v
  change cotangentSemilinearMap f (c • v) =
    ResidueField.map f c • cotangentSemilinearMap f v
  exact (cotangentSemilinearMap f).map_smulₛₗ c v

/-- Dimension transport compares the two genuine residue fields, without
replacing either cotangent space's scalar action. -/
theorem cotangent_quotient_finrank_eq (f : R →+* S) [IsLocalHom f]
    (hf : Function.Surjective f) :
    Module.finrank (ResidueField R)
        (CotangentSpace R ⧸ LinearMap.ker (cotangentSemilinearMap f)) =
      Module.finrank (ResidueField S) (CotangentSpace S) := by
  simpa only [Module.finrank] using congrArg Cardinal.toNat
    (rank_eq_of_equiv_equiv (ResidueField.map f) (cotangentQuotientAddEquiv f hf)
      (residueField_map_bijective f hf) (cotangentQuotientAddEquiv_smul f hf))

/-- Quotienting by a parameter with nonzero cotangent class decreases the
actual cotangent dimension by exactly one. -/
theorem cotangent_finrank_add_one (f : R →+* S) [IsLocalHom f]
    [IsNoetherianRing R] (hf : Function.Surjective f)
    {x : R} (hx : x ∈ maximalIdeal R) (hxsq : x ∉ (maximalIdeal R) ^ 2)
    (hker : RingHom.ker f = Ideal.span {x}) :
    Module.finrank (ResidueField S) (CotangentSpace S) + 1 =
      Module.finrank (ResidueField R) (CotangentSpace R) := by
  have hdim : Module.finrank (ResidueField R)
      (LinearMap.ker (cotangentSemilinearMap f)) = 1 := by
    rw [cotangent_ker_eq_span_parameter f hf hx hker]
    apply finrank_span_singleton
    intro hzero
    exact hxsq (((maximalIdeal R).toCotangent_eq_zero ⟨x, hx⟩).mp hzero)
  have heq := Submodule.finrank_quotient_add_finrank (LinearMap.ker (cotangentSemilinearMap f))
  rw [cotangent_quotient_finrank_eq f hf, hdim] at heq
  exact heq

/-- The actual quotient by an element of the maximal ideal is a local ring.
Its nontriviality is derived from properness of the principal ideal. -/
theorem parameterQuotientLocalRing {x : R} (hx : x ∈ maximalIdeal R) :
    IsLocalRing (R ⧸ Ideal.span {x}) := by
  have hunit : ¬ IsUnit x := by
    simpa only [mem_maximalIdeal, mem_nonunits_iff] using hx
  letI : Nontrivial (R ⧸ Ideal.span {x}) :=
    Ideal.Quotient.nontrivial (Ideal.span_singleton_ne_top hunit)
  exact IsLocalRing.of_surjective' (Ideal.Quotient.mk (Ideal.span {x}))
    Ideal.Quotient.mk_surjective

/-- Exact cotangent rank drop for the actual principal quotient, with its
local-ring structure proved rather than supplied as an assumption. -/
theorem parameterQuotient_cotangent_finrank [IsNoetherianRing R] {x : R}
    (hx : x ∈ maximalIdeal R) (hxsq : x ∉ (maximalIdeal R) ^ 2) :
    letI : IsLocalRing (R ⧸ Ideal.span {x}) := parameterQuotientLocalRing hx
    Module.finrank (ResidueField (R ⧸ Ideal.span {x}))
        (CotangentSpace (R ⧸ Ideal.span {x})) + 1 =
      Module.finrank (ResidueField R) (CotangentSpace R) := by
  letI : IsLocalRing (R ⧸ Ideal.span {x}) := parameterQuotientLocalRing hx
  letI : IsLocalHom (Ideal.Quotient.mk (Ideal.span {x})) :=
    IsLocalHom.of_surjective _ Ideal.Quotient.mk_surjective
  exact cotangent_finrank_add_one (Ideal.Quotient.mk (Ideal.span {x}))
    Ideal.Quotient.mk_surjective hx hxsq Ideal.mk_ker

/-- For the project's actual regular-local predicate, the quotient's
embedding dimension plus one equals the original ring's Krull dimension.
No equality involving the quotient's Krull dimension is assumed or claimed. -/
theorem regularLocal_parameterQuotient_embedding_dimension (hR : RegularLocal R)
    {x : R} (hx : x ∈ maximalIdeal R) (hxsq : x ∉ (maximalIdeal R) ^ 2) :
    letI : IsLocalRing (R ⧸ Ideal.span {x}) := parameterQuotientLocalRing hx
    (Module.finrank (ResidueField (R ⧸ Ideal.span {x}))
        (CotangentSpace (R ⧸ Ideal.span {x})) : WithBot ℕ∞) + 1 = ringKrullDim R := by
  letI : IsLocalRing (R ⧸ Ideal.span {x}) := parameterQuotientLocalRing hx
  letI : IsNoetherianRing R := hR.1
  have h := parameterQuotient_cotangent_finrank hx hxsq
  rw [hR.2]
  exact_mod_cast h

end KltDP.Geometry.RegularLocalParameterQuotient
