import KltDP.Geometry.SmoothPointBlowupRightChartBasis
import KltDP.Geometry.AffineBlowupChartCenter

/-!
# Original complementary-chart maps and center ideals on principal refinements

The map is the actual Rees-chart base map followed by the actual localization.
The original product equation, the regular exceptional parameter, and the
original extended center ideal are all preserved on this refinement.
-/

noncomputable section

namespace KltDP.Geometry.SmoothPointBlowupRightLocalizedChart

open KltDP.Examples.FrobeniusBlowupContact KltDP.Examples.FrobeniusBlowupSmooth
open SmoothPointBlowupRightChartBasis AffineBlowupChartBaseChange

universe u

variable (k : Type u) [Field k]
variable {S : Type u} [CommRing S] [Algebra k S] (φ : planeRing k →ₐ[k] S)

/-- The original Rees projection respects the supplied original ground-field map. -/
def baseAlgHom : S →ₐ[k] chartRing k φ where
  __ := AffineBlowup.chartBaseMap _ _
  commutes' _ := rfl

/-- The actual source-to-refined-chart algebra map. -/
def localizedBaseMap (r : chartRing k φ) : S →ₐ[k] Localization.Away r :=
  (IsScalarTower.toAlgHom k (chartRing k φ) (Localization.Away r)).comp (baseAlgHom k φ)

theorem localizedBaseMap_apply (r : chartRing k φ) (s : S) :
    localizedBaseMap k φ r s =
      algebraMap (chartRing k φ) (Localization.Away r)
        (AffineBlowup.chartBaseMap _ _ s) := rfl

/-- The original homogeneous fraction, carried to the original principal refinement. -/
def localizedFraction (r : chartRing k φ) : Localization.Away r :=
  algebraMap (chartRing k φ) (Localization.Away r) (fractionCoordinate k φ)

/-- The relation remains the literal original Rees relation after localization. -/
theorem localized_relation (r : chartRing k φ) :
    localizedBaseMap k φ r (φ vCoord) * localizedFraction k φ r =
      localizedBaseMap k φ r (φ uCoord) := by
  have h := congrArg (algebraMap (chartRing k φ) (Localization.Away r))
    (AffineBlowup.chartBaseMap_mul_chartFraction (Ideal.map φ.toRingHom centerIdeal)
      (mappedElement centerIdeal φ.toRingHom centerV)
      (mappedElement centerIdeal φ.toRingHom centerU))
  simpa only [map_mul] using h

/-- The original exceptional parameter remains a nonzerodivisor on every refinement. -/
theorem localized_parameter_regular (r : chartRing k φ) :
    localizedBaseMap k φ r (φ vCoord) ∈ nonZeroDivisors (Localization.Away r) :=
  IsLocalization.nonZeroDivisors_le_comap (Submonoid.powers r) (Localization.Away r)
    (AffineBlowup.chartBaseMap_equation_mem_nonZeroDivisors
      (Ideal.map φ.toRingHom centerIdeal) (mappedElement centerIdeal φ.toRingHom centerV))

/-- The ideal is the original plane center pulled along both original maps. -/
def localizedCenterIdeal (r : chartRing k φ) : Ideal (Localization.Away r) :=
  Ideal.map (localizedBaseMap k φ r).toRingHom (Ideal.map φ.toRingHom centerIdeal)

/-- The actual pulled center, not a substitute ideal, is generated by the
same original parameter appearing in the differential formula. -/
theorem localizedCenterIdeal_span (r : chartRing k φ) :
    localizedCenterIdeal k φ r = Ideal.span {localizedBaseMap k φ r (φ vCoord)} := by
  change Ideal.map
    ((algebraMap (chartRing k φ) (Localization.Away r)).comp
      (AffineBlowup.chartBaseMap (Ideal.map φ.toRingHom centerIdeal)
        (mappedElement centerIdeal φ.toRingHom centerV)))
    (Ideal.map φ.toRingHom centerIdeal) = _
  rw [← Ideal.map_map, AffineBlowup.map_chartBaseMap_ideal,
    Ideal.map_span, Set.image_singleton] <;> rfl

end KltDP.Geometry.SmoothPointBlowupRightLocalizedChart
