import KltDP.Geometry.ClosedImmersionActualStalkKernel
import Mathlib.Algebra.Ring.Divisibility.Basic

/-!
# The original principal Spec quotient has its actual principal stalk kernel

Naturality of the canonical global-sections isomorphism identifies the
original quotient inclusion's kernel with the original equation, viewed
as a global section. The proved closed-immersion stalk-kernel comparison
then identifies the actual stalk kernel with its actual germ. That germ
is in the original maximal ideal because its image in the quotient stalk
is zero. This applies directly to the quadratic root-zero inclusion.
-/

noncomputable section
open AlgebraicGeometry CategoryTheory IsLocalRing
universe u

namespace KltDP.Geometry.SpecPrincipalQuotient

variable {R : Type u} [CommRing R]

def scheme (r : R) : Scheme.{u} := Spec (.of (R ⧸ Ideal.span {r}))

def inclusion (r : R) : scheme r ⟶ Spec (.of R) :=
  Spec.map (CommRingCat.ofHom (Ideal.Quotient.mk (Ideal.span {r})))

instance inclusion_isClosedImmersion (r : R) : IsClosedImmersion (inclusion r) :=
  IsClosedImmersion.spec_of_surjective
    (CommRingCat.ofHom (Ideal.Quotient.mk (Ideal.span {r}))) Ideal.Quotient.mk_surjective

def sectionOf (r : R) : Γ(Spec (.of R), ⊤) := (Scheme.ΓSpecIso (.of R)).inv r

/-- The original inclusion's affine kernel is generated by the original equation's section. -/
theorem ker_ideal_top (r : R) :
    (inclusion r).ker.ideal ⟨⊤, isAffineOpen_top (Spec (.of R))⟩ =
      Ideal.span {sectionOf r} := by
  rw [Scheme.Hom.ker_apply]
  change RingHom.ker (inclusion r).appTop.hom = Ideal.span {sectionOf r}
  let eR := (Scheme.ΓSpecIso (.of R)).commRingCatIsoToRingEquiv
  let eS := (Scheme.ΓSpecIso (.of (R ⧸ Ideal.span {r}))).commRingCatIsoToRingEquiv
  ext z
  change (inclusion r).appTop.hom z = 0 ↔ z ∈ Ideal.span {sectionOf r}
  have hnat := ConcreteCategory.congr_hom
    (Scheme.ΓSpecIso_naturality (CommRingCat.ofHom (Ideal.Quotient.mk (Ideal.span {r})))) z
  change eS ((inclusion r).appTop.hom z) = Ideal.Quotient.mk (Ideal.span {r}) (eR z) at hnat
  calc
    (inclusion r).appTop.hom z = 0 ↔ eS ((inclusion r).appTop.hom z) = 0 := by
      constructor
      · intro h
        rw [h, map_zero]
      · intro h
        exact eS.injective (h.trans (map_zero eS).symm)
    _ ↔ Ideal.Quotient.mk (Ideal.span {r}) (eR z) = 0 := by rw [hnat]
    _ ↔ r ∣ eR z := by rw [Ideal.Quotient.eq_zero_iff_mem, Ideal.mem_span_singleton]
    _ ↔ eR.symm r ∣ z := by
      simpa only [RingEquiv.apply_symm_apply] using
        (map_dvd_iff eR (a := eR.symm r) (b := z))
    _ ↔ z ∈ Ideal.span {sectionOf r} := by rw [Ideal.mem_span_singleton]; rfl

def equationGerm (r : R) (y : scheme r) :
    (Spec (.of R)).presheaf.stalk ((inclusion r).base y) :=
  (Spec (.of R)).presheaf.germ ⊤ ((inclusion r).base y) trivial (sectionOf r)

/-- The actual quotient stalk map has the actual principal equation germ as its kernel. -/
theorem stalkMap_ker (r : R) (y : scheme r) :
    RingHom.ker ((inclusion r).stalkMap y).hom = Ideal.span {equationGerm r y} := by
  have h := closedImmersion_stalkMap_ker_eq_map (inclusion r)
    (z := y) ⟨⊤, isAffineOpen_top (Spec (.of R))⟩ trivial
  rw [ker_ideal_top, Ideal.map_span, Set.image_singleton] at h
  exact h

/-- Its original defining germ belongs to the actual ambient maximal ideal. -/
theorem equationGerm_mem_maximalIdeal (r : R) (y : scheme r) :
    equationGerm r y ∈ maximalIdeal ((Spec (.of R)).presheaf.stalk ((inclusion r).base y)) := by
  have hzero : ((inclusion r).stalkMap y).hom (equationGerm r y) = 0 := by
    apply RingHom.mem_ker.mp
    rw [stalkMap_ker]
    exact Ideal.mem_span_singleton_self _
  change ¬IsUnit (equationGerm r y)
  intro hunit
  have h := hunit.map ((inclusion r).stalkMap y).hom
  rw [hzero] at h
  exact not_isUnit_zero h

end KltDP.Geometry.SpecPrincipalQuotient

#print axioms KltDP.Geometry.SpecPrincipalQuotient.stalkMap_ker
#print axioms KltDP.Geometry.SpecPrincipalQuotient.equationGerm_mem_maximalIdeal
