import KltDP.Geometry.AffinePrincipalSupport
import Mathlib.RingTheory.UniqueFactorizationDomain.Ideal
import Mathlib.RingTheory.Localization.NumDen

/-!
# Actual height-one divisor coordinates over a UFD

The base is a Noetherian unique factorization domain of arbitrary
dimension, with an actual fraction field. Height-one primes are the
existing actual prime ideals of height one, and orders are the existing
normalized DVR orders on their actual localizations.

Pinned Mathlib supplies prime elements in nonzero prime ideals,
minimal-prime uniqueness for a prime ideal, localization of the maximal
ideal, and the normalized uniformizer valuation. These prove that a
chosen actual prime generator has its Kronecker-delta divisor. Products
of their integer powers therefore realize every finite divisor.

Reuse: Mathlib c44e0c8ee63ca166450922a373c7409c5d26b00b,
`UniqueFactorizationDomain/Ideal.lean`, `Localization/AtPrime.lean`,
`DedekindDomain/AdicValuation.lean`, and `Localization/NumDen.lean`
(Apache-2.0). No Cartier–Weil comparison or principal-divisor
surjectivity is an input.
-/

noncomputable section

open IsDedekindDomain
open scoped Multiplicative

universe u v

namespace KltDP.RingTheory

variable (R : Type u) [CommRing R] [IsDomain R]
  [IsNoetherianRing R] [UniqueFactorizationMonoid R]

/-- A height-one prime is nonzero as an actual ideal. -/
theorem affineHeightOnePrime_ne_bot (p : AffineHeightOnePrime R) :
    p.1.asIdeal ≠ ⊥ := by
  letI : (⊥ : Ideal R).IsPrime := Ideal.bot_prime
  intro h
  have hp := p.2
  rw [h, Ideal.height_eq_primeHeight] at hp
  change Order.height (⊥ : PrimeSpectrum R) = 1 at hp
  simp only [Order.height_bot, zero_ne_one] at hp

/-- A height-one prime in a UFD is generated by an actual prime element.
The proof uses minimal primes, rather than a dimension-one base assumption. -/
theorem exists_prime_generator_heightOne (p : AffineHeightOnePrime R) :
    ∃ a : R, Prime a ∧ Ideal.span {a} = p.1.asIdeal := by
  obtain ⟨a, ha, hprime⟩ := p.1.isPrime.exists_mem_prime_of_ne_bot
    (affineHeightOnePrime_ne_bot R p)
  letI : (Ideal.span ({a} : Set R)).IsPrime :=
    (Ideal.span_singleton_prime hprime.ne_zero).mpr hprime
  have hmin := mem_minimalPrimes_span_singleton_of_height_one p.2 hprime.ne_zero ha
  have heq : p.1.asIdeal = Ideal.span {a} := by
    simpa only [Ideal.minimalPrimes_eq_subsingleton_self, Set.mem_singleton_iff] using hmin
  exact ⟨a, hprime, heq.symm⟩

/-- A selected prime generator of the actual height-one ideal. -/
def heightOnePrimeGenerator (p : AffineHeightOnePrime R) : R :=
  (exists_prime_generator_heightOne R p).choose

theorem heightOnePrimeGenerator_prime (p : AffineHeightOnePrime R) :
    Prime (heightOnePrimeGenerator R p) :=
  (exists_prime_generator_heightOne R p).choose_spec.1

theorem heightOnePrimeGenerator_span (p : AffineHeightOnePrime R) :
    Ideal.span {heightOnePrimeGenerator R p} = p.1.asIdeal :=
  (exists_prime_generator_heightOne R p).choose_spec.2

/-- An actual prime generator of one height-one ideal lies in another
height-one prime exactly when the two primes agree. -/
theorem heightOnePrimeGenerator_mem_iff (p q : AffineHeightOnePrime R) :
    heightOnePrimeGenerator R p ∈ q.1.asIdeal ↔ p = q := by
  constructor
  · intro h
    letI : (Ideal.span ({heightOnePrimeGenerator R p} : Set R)).IsPrime :=
      (Ideal.span_singleton_prime (heightOnePrimeGenerator_prime R p).ne_zero).mpr
        (heightOnePrimeGenerator_prime R p)
    have hmin := mem_minimalPrimes_span_singleton_of_height_one q.2
      (heightOnePrimeGenerator_prime R p).ne_zero h
    have heq : q.1.asIdeal = Ideal.span {heightOnePrimeGenerator R p} := by
      simpa only [Ideal.minimalPrimes_eq_subsingleton_self, Set.mem_singleton_iff] using hmin
    exact Subtype.ext (PrimeSpectrum.ext ((heightOnePrimeGenerator_span R p).symm.trans heq.symm))
  · rintro rfl
    rw [← heightOnePrimeGenerator_span R p]
    exact Ideal.subset_span (Set.mem_singleton _)

variable (K : Type v) [Field K] [Algebra R K] [IsFractionRing R K]

/-- The original prime element, embedded as a unit of the actual fraction field. -/
def heightOnePrimeGeneratorUnit (p : AffineHeightOnePrime R) : Kˣ :=
  fractionFieldUnit R K (heightOnePrimeGenerator R p)
    (heightOnePrimeGenerator_prime R p).ne_zero

@[simp]
theorem heightOnePrimeGeneratorUnit_val (p : AffineHeightOnePrime R) :
    (heightOnePrimeGeneratorUnit R K p : K) =
      algebraMap R K (heightOnePrimeGenerator R p) := rfl

/-- Multiplication of original fractions adds their actual local orders. -/
def affinePrincipalOrderHom (p : AffineHeightOnePrime R) : Additive Kˣ →+ ℤ :=
  let S := Localization.AtPrime p.1.asIdeal
  letI : IsDiscreteValuationRing S := heightOneLocalization_isDiscreteValuationRing R p
  letI : Algebra S K := heightOneFractionFieldAlgebra R K p
  letI : IsScalarTower R S K :=
    IsLocalization.localization_isScalarTower_of_submonoid_le S K
      p.1.asIdeal.primeCompl (nonZeroDivisors R) p.1.asIdeal.primeCompl_le_nonZeroDivisors
  letI : IsFractionRing S K :=
    IsFractionRing.isFractionRing_of_isDomain_of_isLocalization p.1.asIdeal.primeCompl S K
  divisorOrderHom S K

@[simp]
theorem affinePrincipalOrderHom_apply (p : AffineHeightOnePrime R) (f : Kˣ) :
    affinePrincipalOrderHom R K p (Additive.ofMul f) = affinePrincipalOrder R K p f := rfl

/-- Multiplication of original fractions adds their actual local orders. -/
theorem affinePrincipalOrder_mul (p : AffineHeightOnePrime R) (f g : Kˣ) :
    affinePrincipalOrder R K p (f * g) =
      affinePrincipalOrder R K p f + affinePrincipalOrder R K p g :=
  (affinePrincipalOrderHom R K p).map_add (Additive.ofMul f) (Additive.ofMul g)

@[simp]
theorem affinePrincipalOrder_one (p : AffineHeightOnePrime R) :
    affinePrincipalOrder R K p 1 = 0 :=
  (affinePrincipalOrderHom R K p).map_zero

@[simp]
theorem affinePrincipalOrder_inv (p : AffineHeightOnePrime R) (f : Kˣ) :
    affinePrincipalOrder R K p f⁻¹ = -affinePrincipalOrder R K p f :=
  (affinePrincipalOrderHom R K p).map_neg (Additive.ofMul f)

theorem affinePrincipalOrder_zpow (p : AffineHeightOnePrime R) (f : Kˣ) (n : ℤ) :
    affinePrincipalOrder R K p (f ^ n) = n * affinePrincipalOrder R K p f := by
  simpa only [affinePrincipalOrderHom_apply, zsmul_eq_mul] using
    (affinePrincipalOrderHom R K p).map_zsmul (Additive.ofMul f) n

theorem affinePrincipalOrder_prod {ι : Type*} (p : AffineHeightOnePrime R)
    (s : Finset ι) (f : ι → Kˣ) :
    affinePrincipalOrder R K p (∏ i ∈ s, f i) =
      ∑ i ∈ s, affinePrincipalOrder R K p (f i) := by
  classical
  induction s using Finset.induction_on with
  | empty => simp only [Finset.prod_empty, Finset.sum_empty, affinePrincipalOrder_one]
  | @insert i s hi ih =>
      rw [Finset.prod_insert hi, affinePrincipalOrder_mul, ih, Finset.sum_insert hi]

/-- The generator of a height-one prime becomes an actual uniformizer
of its actual prime localization, so its normalized order is one. -/
theorem affinePrincipalOrder_generator_self (p : AffineHeightOnePrime R) :
    affinePrincipalOrder R K p (heightOnePrimeGeneratorUnit R K p) = 1 := by
  let S := Localization.AtPrime p.1.asIdeal
  letI : IsDiscreteValuationRing S := heightOneLocalization_isDiscreteValuationRing R p
  letI : Algebra S K := heightOneFractionFieldAlgebra R K p
  letI : IsScalarTower R S K :=
    IsLocalization.localization_isScalarTower_of_submonoid_le S K
      p.1.asIdeal.primeCompl (nonZeroDivisors R) p.1.asIdeal.primeCompl_le_nonZeroDivisors
  letI : IsFractionRing S K :=
    IsFractionRing.isFractionRing_of_isDomain_of_isLocalization p.1.asIdeal.primeCompl S K
  have hmax : IsLocalRing.maximalIdeal S =
      Ideal.span {algebraMap R S (heightOnePrimeGenerator R p)} := by
    calc
      IsLocalRing.maximalIdeal S = Ideal.map (algebraMap R S) p.1.asIdeal :=
        (Localization.AtPrime.map_eq_maximalIdeal (I := p.1.asIdeal)).symm
      _ = Ideal.map (algebraMap R S) (Ideal.span {heightOnePrimeGenerator R p}) :=
        congrArg (Ideal.map (algebraMap R S)) (heightOnePrimeGenerator_span R p).symm
      _ = Ideal.span {algebraMap R S (heightOnePrimeGenerator R p)} := by
        rw [Ideal.map_span, Set.image_singleton]
  have hirr : Irreducible (algebraMap R S (heightOnePrimeGenerator R p)) :=
    (IsDiscreteValuationRing.irreducible_iff_uniformizer _).mpr hmax
  have hunit : fractionFieldUnit S K (algebraMap R S (heightOnePrimeGenerator R p))
      hirr.ne_zero = heightOnePrimeGeneratorUnit R K p := by
    apply Units.ext
    exact (IsScalarTower.algebraMap_apply R S K (heightOnePrimeGenerator R p)).symm
  change divisorOrder S K (heightOnePrimeGeneratorUnit R K p) = 1
  rw [← hunit]
  exact divisorOrder_uniformizer S K _ hirr

open scoped Classical in
/-- Each chosen actual prime generator has exactly its Kronecker-delta
order function on the full height-one-prime carrier. -/
theorem affinePrincipalOrder_generator (p q : AffineHeightOnePrime R) :
    affinePrincipalOrder R K q (heightOnePrimeGeneratorUnit R K p) =
      if p = q then 1 else 0 := by
  classical
  by_cases h : p = q
  · subst q
    rw [if_pos rfl, affinePrincipalOrder_generator_self]
  · rw [if_neg h]
    apply affinePrincipalOrder_eq_zero_of_fraction_notMem R K q
      (heightOnePrimeGeneratorUnit R K p) (heightOnePrimeGenerator R p) 1
    · simp only [heightOnePrimeGeneratorUnit_val, map_one, inv_one, mul_one]
    · exact fun hm => h ((heightOnePrimeGenerator_mem_iff R p q).mp hm)
    · exact (Ideal.ne_top_iff_one _).mp q.1.isPrime.ne_top

/-- The actual finite product of prime generators with specified integer
exponents; negative exponents use the inverse in the actual fraction field. -/
def fractionOfDivisorCoordinates (D : AffineHeightOnePrime R →₀ ℤ) : Kˣ :=
  ∏ p ∈ D.support, (heightOnePrimeGeneratorUnit R K p) ^ D p

/-- The constructed product realizes every specified divisor coefficient. -/
theorem affinePrincipalOrder_fractionOfDivisorCoordinates
    (D : AffineHeightOnePrime R →₀ ℤ) (q : AffineHeightOnePrime R) :
    affinePrincipalOrder R K q (fractionOfDivisorCoordinates R K D) = D q := by
  classical
  unfold fractionOfDivisorCoordinates
  rw [affinePrincipalOrder_prod]
  simp only [affinePrincipalOrder_zpow, affinePrincipalOrder_generator,
    mul_ite, mul_one, mul_zero]
  by_cases hq : q ∈ D.support
  · simp only [Finset.sum_ite_eq', hq, if_pos]
  · have hz : D q = 0 := Finsupp.not_mem_support_iff.mp hq
    simp only [Finset.sum_ite_eq', hq, if_neg, hz, ite_self]

/-- Every finite height-one divisor over the UFD is the actual principal
divisor of the explicitly constructed product. -/
theorem affinePrincipalDivisor_fractionOfDivisorCoordinates
    (D : AffineHeightOnePrime R →₀ ℤ) :
    affinePrincipalDivisor R K (fractionOfDivisorCoordinates R K D) = D := by
  ext q
  exact affinePrincipalOrder_fractionOfDivisorCoordinates R K D q

omit [IsNoetherianRing R] in
/-- The ideal of a prime element has actual height one in a UFD.
Every nonzero prime below it contains an associated prime element, so
there can be no intermediate nonzero prime. -/
theorem primeElement_span_height_eq_one (a : R) (ha : Prime a) :
    (Ideal.span ({a} : Set R)).height = 1 := by
  let P : PrimeSpectrum R := ⟨Ideal.span {a},
    (Ideal.span_singleton_prime ha.ne_zero).mpr ha⟩
  have hPbot : P ≠ ⊥ := by
    intro h
    have hI : Ideal.span ({a} : Set R) = ⊥ := congrArg PrimeSpectrum.asIdeal h
    exact ha.ne_zero (Ideal.span_singleton_eq_bot.mp hI)
  have hupper : Order.height P ≤ (1 : ℕ∞) := by
    apply (Order.height_le_coe_iff (n := 1)).mpr
    intro Q hQP
    have hQbot : Q = ⊥ := by
      by_contra hQ
      have hQne : Q.asIdeal ≠ ⊥ := fun h => hQ (PrimeSpectrum.ext h)
      obtain ⟨b, hbQ, hb⟩ := Q.isPrime.exists_mem_prime_of_ne_bot hQne
      have hab : a ∣ b := Ideal.mem_span_singleton.mp (hQP.le hbQ)
      have heq := Ideal.span_singleton_eq_span_singleton.mpr (ha.associated_of_dvd hb hab)
      have hPQ : P ≤ Q := by
        change Ideal.span ({a} : Set R) ≤ Q.asIdeal
        rw [heq]
        exact Ideal.span_le.mpr (Set.singleton_subset_iff.mpr hbQ)
      exact (not_le_of_gt hQP) hPQ
    rw [hQbot, Order.height_bot]
    norm_num
  have hlower : (1 : ℕ∞) ≤ Order.height P := by
    simpa only [Order.height_bot, zero_add] using
      Order.height_add_one_le (bot_lt_iff_ne_bot.mpr hPbot)
  letI : (Ideal.span ({a} : Set R)).IsPrime := P.isPrime
  rw [Ideal.height_eq_primeHeight]
  exact le_antisymm hupper hlower

/-- The actual height-one prime ideal generated by a specified prime element. -/
def primeElementHeightOnePrime (a : R) (ha : Prime a) : AffineHeightOnePrime R :=
  ⟨⟨Ideal.span {a}, (Ideal.span_singleton_prime ha.ne_zero).mpr ha⟩,
    primeElement_span_height_eq_one R a ha⟩

/-- A nonzero base-ring element has zero order at a height-one prime
exactly when that element is outside the prime. This uses the valuation
criterion only in the actual DVR localization. -/
theorem affinePrincipalOrder_algebraMap_eq_zero_iff (p : AffineHeightOnePrime R)
    (a : R) (ha : a ≠ 0) :
    affinePrincipalOrder R K p (fractionFieldUnit R K a ha) = 0 ↔ a ∉ p.1.asIdeal := by
  constructor
  · intro hzero hamem
    let S := Localization.AtPrime p.1.asIdeal
    letI : IsDiscreteValuationRing S := heightOneLocalization_isDiscreteValuationRing R p
    letI : Algebra S K := heightOneFractionFieldAlgebra R K p
    letI : IsScalarTower R S K :=
      IsLocalization.localization_isScalarTower_of_submonoid_le S K
        p.1.asIdeal.primeCompl (nonZeroDivisors R) p.1.asIdeal.primeCompl_le_nonZeroDivisors
    letI : IsFractionRing S K :=
      IsFractionRing.isFractionRing_of_isDomain_of_isLocalization p.1.asIdeal.primeCompl S K
    change divisorOrder S K (fractionFieldUnit R K a ha) = 0 at hzero
    have hval : fractionFieldValuation S K (algebraMap R K a) = 1 := by
      simpa only [fractionFieldUnit_val, neg_zero, ofAdd_zero,
        WithZero.coe_one] using (divisorOrder_eq_iff S K _ 0).mp hzero
    have hlt : fractionFieldValuation S K (algebraMap R K a) < 1 := by
      rw [IsScalarTower.algebraMap_apply R S K]
      change (dvrHeightOnePrime S).valuation K (algebraMap S K (algebraMap R S a)) < 1
      apply ((dvrHeightOnePrime S).valuation_lt_one_iff_dvd (algebraMap R S a)).mpr
      apply Ideal.dvd_span_singleton.mpr
      exact (IsLocalization.AtPrime.to_map_mem_maximal_iff S p.1.asIdeal a).mpr hamem
    exact (ne_of_lt hlt) hval
  · intro hnot
    apply affinePrincipalOrder_eq_zero_of_fraction_notMem R K p
      (fractionFieldUnit R K a ha) a 1
    · simp only [fractionFieldUnit_val, map_one, inv_one, mul_one]
    · exact hnot
    · exact (Ideal.ne_top_iff_one _).mp p.1.isPrime.ne_top

/-- An actual base-ring element whose height-one orders all vanish is
an actual base-ring unit, by unique factorization. -/
theorem isUnit_of_affinePrincipalOrder_algebraMap_eq_zero
    (a : R) (ha : a ≠ 0)
    (hzero : ∀ p : AffineHeightOnePrime R,
      affinePrincipalOrder R K p (fractionFieldUnit R K a ha) = 0) : IsUnit a := by
  by_contra hunit
  obtain ⟨b, hb, hba⟩ := WfDvdMonoid.exists_irreducible_factor hunit ha
  have hprime : Prime b := UniqueFactorizationMonoid.irreducible_iff_prime.mp hb
  let p := primeElementHeightOnePrime R b hprime
  have hmem : a ∈ p.1.asIdeal := Ideal.mem_span_singleton.mpr hba
  exact ((affinePrincipalOrder_algebraMap_eq_zero_iff R K p a ha).mp (hzero p)) hmem

/-- Actual units of the original base ring have zero height-one order. -/
theorem affinePrincipalOrder_map_base_unit (p : AffineHeightOnePrime R) (a : Rˣ) :
    affinePrincipalOrder R K p (Units.map (algebraMap R K) a) = 0 := by
  apply affinePrincipalOrder_eq_zero_of_fraction_notMem R K p
    (Units.map (algebraMap R K) a) (a : R) 1
  · simp only [Units.coe_map, MonoidHom.coe_coe, map_one, inv_one, mul_one]
  · intro hmem
    exact p.1.isPrime.ne_top (Ideal.eq_top_of_isUnit_mem _ hmem a.isUnit)
  · exact (Ideal.ne_top_iff_one _).mp p.1.isPrime.ne_top

/-- For a reduced nonzero fraction with zero divisor, its numerator and
denominator are actual base-ring units. Reducedness prevents cancellation
of the prime factor used in the height-one valuation test. -/
theorem isUnit_num_den_of_affinePrincipalOrder_eq_zero (f : Kˣ)
    (hzero : ∀ p : AffineHeightOnePrime R, affinePrincipalOrder R K p f = 0) :
    IsUnit (IsFractionRing.num R (f : K)) ∧
      IsUnit (IsFractionRing.den R (f : K) : R) := by
  let a := IsFractionRing.num R (f : K)
  let b : R := IsFractionRing.den R (f : K)
  have ha : a ≠ 0 := fun h => f.ne_zero (IsFractionRing.eq_zero_of_num_eq_zero h)
  have hb : b ≠ 0 := nonZeroDivisors.ne_zero (IsFractionRing.den R (f : K)).property
  have hrel : IsRelPrime a b := IsFractionRing.num_den_reduced R (f : K)
  have hfrac : fractionFieldUnit R K a ha * (fractionFieldUnit R K b hb)⁻¹ = f := by
    apply Units.ext
    change algebraMap R K a * (algebraMap R K b)⁻¹ = (f : K)
    exact (div_eq_mul_inv _ _).symm.trans (IsFractionRing.mk'_num_den' R (f : K))
  have horders (p : AffineHeightOnePrime R) :
      affinePrincipalOrder R K p (fractionFieldUnit R K a ha) =
        affinePrincipalOrder R K p (fractionFieldUnit R K b hb) := by
    have h := congrArg (affinePrincipalOrder R K p) hfrac
    rw [affinePrincipalOrder_mul, affinePrincipalOrder_inv, hzero p] at h
    exact sub_eq_zero.mp (by simpa only [sub_eq_add_neg] using h)
  have hau : IsUnit a := by
    by_contra hunit
    obtain ⟨c, hc, hca⟩ := WfDvdMonoid.exists_irreducible_factor hunit ha
    have hprime : Prime c := UniqueFactorizationMonoid.irreducible_iff_prime.mp hc
    let p := primeElementHeightOnePrime R c hprime
    have hmem : a ∈ p.1.asIdeal := Ideal.mem_span_singleton.mpr hca
    have hbnot : b ∉ p.1.asIdeal := by
      intro hbm
      exact hc.not_isUnit (hrel hca (Ideal.mem_span_singleton.mp hbm))
    have hbzero := (affinePrincipalOrder_algebraMap_eq_zero_iff R K p b hb).mpr hbnot
    exact ((affinePrincipalOrder_algebraMap_eq_zero_iff R K p a ha).mp
      ((horders p).trans hbzero)) hmem
  have hbu : IsUnit b := by
    apply isUnit_of_affinePrincipalOrder_algebraMap_eq_zero R K b hb
    intro p
    rw [← horders p]
    apply (affinePrincipalOrder_algebraMap_eq_zero_iff R K p a ha).mpr
    intro hmem
    exact p.1.isPrime.ne_top (Ideal.eq_top_of_isUnit_mem _ hmem hau)
  exact ⟨hau, hbu⟩

/-- A nonzero fraction has zero actual height-one divisor if and only if
it is the image of an actual unit of the original UFD. -/
theorem affinePrincipalDivisor_eq_zero_iff (f : Kˣ) :
    affinePrincipalDivisor R K f = 0 ↔
      ∃ a : Rˣ, Units.map (algebraMap R K) a = f := by
  constructor
  · intro hz
    have hzero (p : AffineHeightOnePrime R) : affinePrincipalOrder R K p f = 0 :=
      congrArg (fun D : AffineHeightOnePrime R →₀ ℤ => D p) hz
    obtain ⟨⟨a, ha⟩, ⟨b, hb⟩⟩ := isUnit_num_den_of_affinePrincipalOrder_eq_zero R K f hzero
    refine ⟨a * b⁻¹, ?_⟩
    apply Units.ext
    change algebraMap R K ((a : R) * ((b⁻¹ : Rˣ) : R)) = (f : K)
    rw [map_mul, map_units_inv, ha, hb]
    exact (div_eq_mul_inv _ _).symm.trans (IsFractionRing.mk'_num_den' R (f : K))
  · rintro ⟨a, rfl⟩
    ext p
    exact affinePrincipalOrder_map_base_unit R K p a

end KltDP.RingTheory
